### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by infinity0** [BurntSushi/ripgrep#1000]
Hi, please release a new version 0.8.2 of ripgrep.

We've packaged [all of the dependencies in Debian](https://qa.debian.org/developer.php?login=pkg-rust-maintainers@alioth-lists.debian.net) now and are ready to upload ripgrep. However the latest release 0.8.1 still uses old versions of some dependencies. I see git master has updated, so it would be nice to publish to crates.io so we can upload ripgrep to Debian so `apt-get install ripgrep` works.

**Comment by BurntSushi** [comment]
> so we can upload ripgrep to Debian so `apt-get install ripgrep` works.

Wow! That's awesome news! I'm super appreciative of all the hard work that must have gone into that. :-)

With that said, I don't think a 0.8.2 release is practical. Too much has changed from 0.8.1, including an increase in the minimum supported version of Rust from 1.20 to 1.23. Are you OK with a 0.9.0 release instead?

**Comment by kpcyrd** [comment]
A 0.9.0 release is fine, right now we have rustc 1.27 in sid, it's only the dependencies that need a bump. :)

**Comment by BurntSushi** [comment]
Sounds great. 1.27 is especially good news, because that means ripgrep will automatically get (some) SIMD optimizations. I will start the release process soon.

**Comment by BurntSushi** [comment]
Done: https://github.com/BurntSushi/ripgrep/releases/tag/0.9.0

**Comment by BurntSushi** [comment]
Ah right, all set!

**Comment by BurntSushi** [comment]
w00t! Thank you!
