### ISSUE TITLE
Is it possible to search file names and content at same time with same regex?

### ISSUE THREAD

**Issue by jessegrosjean** [BurntSushi/ripgrep#1002]
I'd like to search for a pattern in both file name and content. Ideally at the same time. Is this possible, if not is there a recommended workaround?

**Comment by jessegrosjean** [comment]
> If you want regexes, you need to use pipelines, e.g., `rg --files | rg 'foo\w+'`.

I'm using ripgrep to implement file search in my app. I want the search results to include files if name OR content matches the pattern.

I can use your suggestion to solve the problem, I just wanted to make sure I wasn't missing a more direct built in solution.

Thanks!

**Comment by zachliu** [comment]
@jessegrosjean @BurntSushi What if I want the search results to include files if name AND content matches the pattern?

**Comment by BurntSushi** [comment]
@zachliu `rg content-pattern | rg file-pattern` will get you pretty close.

**Comment by zachliu** [comment]
@BurntSushi many thanks :+1:
