### ISSUE TITLE
match ignored files with ignore crate

### ISSUE THREAD

**Issue by DD5HT** [BurntSushi/ripgrep#1004]
#### Describe your question, feature request, or bug.

Is there a way to reverse match the files with the **ignore crate** so it only returns all the files which are in my .ignore file?

Maybe even add a `.reverse()` method to the `WalkBuilder` ?

**Comment by BurntSushi** [comment]
No, there is no way to do this. `ignore` files are intended for specifying things to ignore, with the possibility of whitelisting things using `!`.

I'm not particularly inclined to add this feature either. The [semantics of how ignore patterns are handled are complex](https://docs.rs/ignore/0.4.3/ignore/struct.WalkBuilder.html#ignore-rules), and adding a "reverse" feature will require rethinking and testing all of those cases. It's a fairly big feature and will probably have a fairly significant maintenance burden as well.

What problem are you trying to solve with this?

**Comment by DD5HT** [comment]
I want to easily take all entries out of the ignore file and delete/modify these entries.

**Comment by BurntSushi** [comment]
Oh, well that's easy:

```
$ comm -2 <(rg --files) <(rg --files -u)
```
