### ISSUE TITLE
output string have garbled if fileencoding is not utf-8

### ISSUE THREAD

**Issue by fcying** [BurntSushi/ripgrep#1011]
#### What version of ripgrep are you using?
ripgrep 0.9.0 (rev 6afdf15d85)

#### How did you install ripgrep?
cargo build

#### What operating system are you using ripgrep on?

Debian

#### Describe your question, feature request, or bug.
I have a txt file, fileencoding is `CP936`, I search some string in this file, the output string have garbled, 
If I modify the fileencoding to `UTF-8`, it work fine.

#### If this is a bug, what are the steps to reproduce the behavior?

readme_cp936.txt, have garbled
fileencoding `cp936` in vim
```
file readme_cp936.txt 
readme_cp936.txt: ISO-8859 text, with CRLF line terminators

rg CONFIG_START readme_cp936.txt
1:	2¡¢ў¸Üproject.mk£ºʨ׃ǰʼµٖ·CONFIG_STARTºʹ𐠃ONFIG_SIZE¡£
2:	3iproject.mk£ºCONFIG_START
```

readme_utf8.txt, work fine.
fileencoding `utf-8` in vim,  work fine.
```
file readme_utf8.txt 
readme_utf8.txt: UTF-8 Unicode text, with CRLF line terminators

rg CONFIG_START readme_utf8.txt 
1:	2、修改\project.mk：设置起始地址CONFIG_START和大小CONFIG_SIZE。
2:	3iproject.mk：CONFIG_START
```
[readme_utf8.txt](https://github.com/BurntSushi/ripgrep/files/2280781/readme_utf8.txt)
[readme_cp936.txt](https://github.com/BurntSushi/ripgrep/files/2280782/readme_cp936.txt)

**Comment by okdana** [comment]
There's a bit in the [guide](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#file-encoding) about this

The [WHATWG encoding standard](https://encoding.spec.whatwg.org/#concept-encoding-get) doesn't mention CP936 specifically, but i think it's covered under 'GBK' — that seems to work for me, anyway:

```
rg -Egbk CONFIG_START readme_utf8.txt
1:	2、修改\project.mk：设置起始地址CONFIG_START和大小CONFIG_SIZE。
2:	3iproject.mk：CONFIG_START
```

**Comment by BurntSushi** [comment]
Yeah, I mean, I don't really understand what it is you want ripgrep to do here. How the text is shown to you is dependent on your terminal emulator. If you have your terminal emulator set to UTF-8 and you're searching non-UTF-8 contents without transcoding it, then you're going to have a bad time. There's nothing ripgrep can do about that.

**Comment by fcying** [comment]
@BurntSushi  
Can it recognize the file encoding and then automatically set encoding(ex, auto set `-Egbk`)?  Or it can set some file encoding  in ripgreprc for check?

**Comment by BurntSushi** [comment]
> Can it recognize the file encoding and then automatically set encoding(ex, auto set -Egbk)?

No.

> Or it can set some file encoding in ripgreprc for check?

You can set any flag, including `-E/--encoding`, in your config file. But it will impact all searches.

**Comment by fcying** [comment]
Now `-E` can only set one type of encoding, I try `-Egbk -Eutf8`, it only effect by last `-Eutf8`. 
This will still be garbled when searching many files with multi encoding. 
Can it support for set multi encoding? (ex `-E=utf-8,gbk,euc-jp`)

**Comment by BurntSushi** [comment]
No.
