### ISSUE TITLE
rg --version is misleading

### ISSUE THREAD

**Issue by vks** [BurntSushi/ripgrep#1013]
When running `rg --version` with the provided ripgrep-0.9.0-x86_64-unknown-linux-musl binary I'm getting the following output:

```
ripgrep 0.9.0 (rev 6799dcfc0e)
-SIMD -AVX
```

This suggests that `SIMD` and `AVX` are disabled. However, the binary is supposedly using runtime detection of the corresponding hardware support, so this is misleading.

To fix this, the corresponding output code should check for hardware support like the ripgrep code actually using the hardware instructions. Currently, the output code only considers the corresponding Cargo features, ignoring runtime detection.

**Comment by BurntSushi** [comment]
It looks like we'll need to include _both_ compile time and run time support unfortunately. Including only one will be misleading until all of ripgrep's dependencies move to runtime detection.
