### ISSUE TITLE
Doesn't find pattern occurrences in .env file

### ISSUE THREAD

**Issue by Boscop** [BurntSushi/ripgrep#1029]
#### What version of ripgrep are you using?
ripgrep 0.9.0

#### What operating system are you using ripgrep on?

arch

#### Describe your question, feature request, or bug.

It doesn't find occurrences in .env file.

#### If this is a bug, what are the steps to reproduce the behavior?

> $ rg --hidden DATABASE_URL

#### If this is a bug, what is the actual behavior?

Only finds results in other files.

#### If this is a bug, what is the expected behavior?

Should show the occurrence in the .env file `foo/bar/.env`:
> DATABASE_URL=...

**Comment by okdana** [comment]
You didn't include the `--debug` output like the issue template says, but given the purpose of `.env` files i suppose you've probably added it to your `.gitignore`, which `rg` respects by default

`rg -uu` will search hidden files without respecting `.gitignore`
