### ISSUE TITLE
Add filename-only option

### ISSUE THREAD

**Issue by ddrcoder** [BurntSushi/ripgrep#103]
I quite frequently use `grep -l` to simply identify files which contained any match of the given pattern.  Since only existence checking is required, you could terminate at the first match. The list of files can then be fed to `xargs` or the like. This would go hand-in-hand with the `-0, --null` option.

**Comment by BurntSushi** [comment]
This is already done. It's in `0.2.0`.

**Comment by Flaque** [comment]
To be clear for folks who stumbled upon this like I did, the way to only show filenames in `rg` is the same as in `grep`:

```
$ rg -l 
```

**Comment by watsoncj** [comment]
Here's the relevant help section from ripgrep 12.1.0:
```
    -l, --files-with-matches
            Only print the paths with at least one match.

            This overrides --files-without-match.
```

**Comment by iburunat** [comment]
Maybe helpful to know that adding the flag `-c/--counter` will show the number of lines matching the searched term. The flag `--count-matches` will count the number of matches instead (see [man page](https://www.mankier.com/1/rg#--count)).

**Comment by NetMage** [comment]
I think the help could be a little clearer - it doesn't clearly imply that the matches won't be printed.

**Comment by SoftwareApe** [comment]
I agree with @NetMage I looked through all the file related options in the help and this one didn't seem to apply.

>Only print the paths with at least one match.

To me this says that it will only print those files that have at least one match. Which sounds like the default behavior. It doesn't say that it *doesn't* print the match, which is what most people are likely looking for.

I think it would be more clear if the help read

>Only print the path to the files with matches, not the matches.

**Comment by NightMachinary** [comment]
> To be clear for folks who stumbled upon this like I did, the way to only show filenames in `rg` is the same as in `grep`:
> 
> ```
> $ rg -l 
> ```

`rg -l .`, to just list everything.

**Comment by RichardBronosky** [comment]
Thank you for this! I used it to make `vg`, the perfect companion to `rg`.

```sh
function vg() { $EDITOR $(rg -l "$@"); }
```
Then I can follow up "find all files containing *pattern*" with "edit them".
