### ISSUE TITLE
rg silently exits when greping certain patterns using -A/-B

### ISSUE THREAD

**Issue by HongxuChen** [BurntSushi/ripgrep#1030]
#### What version of ripgrep are you using?
ripgrep 0.9.0
-SIMD -AVX

#### How did you install ripgrep?
cargo install (nightly)

#### What operating system are you using ripgrep on?
x86_64 GNU/Linux Ubuntu 18.04

#### Describe your question, feature request, or bug.

When using options like `-A` or `-B`, rg may exit silently when matching some patterns.

#### If this is a bug, what are the steps to reproduce the behavior?
[hang-res.zip](https://github.com/BurntSushi/ripgrep/files/2328104/hang-res.zip)

![2018-08-28-205721_562x498_scrot](https://user-images.githubusercontent.com/843267/44724467-5986e900-ab05-11e8-8cd2-19192649083e.png)

#### If this is a bug, what is the actual behavior?
`-A` version should print matched lines and lines after.

What do you think ripgrep should have done?
N.A.

**Comment by BurntSushi** [comment]
Interesting! I don't know what's wrong here, but this bug is fixed on master, which includes a rewrite of the relevant code. I was able to reproduce this on the current release of ripgrep (0.9.0). Thanks for the great bug report!

**Comment by HongxuChen** [comment]
Confirmed that the issue no longer exists as of 8f978a3 :smile:
