### ISSUE TITLE
Feature Request: flag to search filenames in addition to contents

### ISSUE THREAD

**Issue by sweth** [BurntSushi/ripgrep#1034]
#### What version of ripgrep are you using?

ripgrep 0.9.0
-SIMD -AVX

#### How did you install ripgrep?

brew

#### What operating system are you using ripgrep on?

Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

#### Describe your question, feature request, or bug.

A flag (perhaps `--search-names-and-contents` or `--also-search-filenames` ?) that will allow searching both file contents and file names as part of the same invocation.  i.e. for the hypothetical

```
rg --search-names-and-contents pattern dir
```

the output would be the (interleaved) equivalent of

```
rg --files -g '*pattern*' dir
rg pattern dir
```

I know that rg isn't intended to be a `find` replacement, but I often am searching through very large dir structures for files that either contain a given string OR where their filename contains that string, and running rg twice (or rg once and fd once, which is what I currently do) on the same huge dir structure (hundreds of thousands of files) is very inefficient, and having the output not interleaved because it is generated by two commands also makes it harder to read.

**Comment by BurntSushi** [comment]
I don't think this is a good fit for ripgrep. I understand the use case, but ripgrep isn't a tool for searching file names. It's a tool for searching files. For example, there are several things that aren't considered in this feature request:

1. The match semantics of `-g '*pattern*'` are of globs, not regexes.
2. Emitting a file path without any of its contents seems weird to me. There is no way for that to happen today. Each matching file contains at least one line.
3. How is a regex applied to a file path? Is it only the base name? The entire path? Something else?
4. It seems like if this flag were added, it would be natural to ask for a flag that is "search only file names." In other words, it's a feature that begets more features, which doesn't excite me.

**Comment by BurntSushi** [comment]
I've thought about this more, and I'd like to keep ripgrep focused on searching files for now.

Needing to do two searches is somewhat unfortunate, but one of those searches only needs to look at file paths, which should be much quicker to execute.

**Comment by fregante** [comment]
For anyone arriving here from Google, use `fd` instead, to search files by filename: https://github.com/sharkdp/fd
It has similar improvements to `rg` (e.g. automatic .gitignore exclusions)

**Comment by BurntSushi** [comment]
@fregante I would have mentioned that, but note that this feature request is subtly different than just searching the contents of file names. The requested feature is to search _both_ file names _and_ file contents simultaneously for the same pattern.

**Comment by jeffr-spire** [comment]
I realize this is a very old and very closed ticket, and that I'm not submitting a patch or anything similarly helpful.  Still, on the off change you ever decide to revisit this, I offer this suggestion:  consider a directory to be a mostly ordinary file whose contents are the names of the files, one per line, in that directory (people who include newlines in filenames deserve what pain they get); and any file that is a directory is distinguished in output and processing by ending with a slash, as is the custom.  That point of view provides these answers to your questions:

> 1. The match semantics of `-g '*pattern*'` are of globs, not regexes.

Doesn't change, `-g pattern` would still glob against file names only.   A file name could be a directory.

> 2. Emitting a file path without any of its contents seems weird to me. There is no way for that to happen today. Each matching file contains at least one line.

The file path would be the containing directory; the contents is the regex-matched filename itself.

> 3. How is a regex applied to a file path? Is it only the base name? The entire path? Something else?

It would only match against the base name as it would be found in the contents of the containing directory, not the entire file path, which can already be matched by globs. 

> 4. It seems like if this flag were added, it would be natural to ask for a flag that is "search only file names." In other words, it's a feature that begets more features, which doesn't excite me.

Here I would argue that the most sensible thing is for this to _not_ be a flag, but to be default behavior.  Treating the directories as files to be searched means that they could be excluded by specifying `-g '!*/'`, and similarly searched only for by inverting the glob.  Likewise, if you are specifically searching for a directory you could anchor the regexp with a trailing / to find only directory names.

**Comment by BurntSushi** [comment]
Your conceptualization is not bad, but:

> Here I would argue that the most sensible thing is for this to not be a flag, but to be default behavior.

This definitely will never happen. I can say that with certainty. It is too different from grep and would be very unexpected.

**Comment by jeffr-spire** [comment]
Fair enough;  I may disagree about whether it's too different or unexpected, but you're the maintainer and get to make that call :smile: 
I think even supporting this model under a flag rather than by default would allow the other pieces, in particular the inclusion/exclusion behavior using the path glob to stand and not require more feature bloat.
