### ISSUE TITLE
Static binary for Arm

### ISSUE THREAD

**Issue by babam86** [BurntSushi/ripgrep#1037]
Please provide static binary for Arm.

I will use ripgrep on my Android (armv7). 

Thanks.

**Comment by BurntSushi** [comment]
There are already binaries for Arm: https://github.com/BurntSushi/ripgrep/releases/tag/0.9.0

I don't have any plans to add additional binaries because I don't have the bandwidth to maintain them. The existing arm binary is already sub-optimal in a couple respects.

**Comment by BurntSushi** [comment]
I didn't say I did.

**Comment by vovcacik** [comment]
You kinda [did](https://github.com/BurntSushi/ripgrep/commit/0ce82403d48a7283321474fbf60c966ab45f0a6b#diff-04c6e90faac2675aa89e2176d2eec7d8R93). Just saying as I got confused just like @babam86.
