### ISSUE TITLE
Logical AND between glob patterns

### ISSUE THREAD

**Issue by strindberg** [BurntSushi/ripgrep#1046]
#### What version of ripgrep are you using?
ripgrep 0.10.0

I might be missing something, but I can't figure out a way to make ripgrep treat multiple glob patterns with logical AND. The background is, I have a wrapper script combining input from the user to set up conditions for which files to search. This wrapper script today uses find and grep, and I was interested in trying to use ripgrep instead.

What I am trying to achieve is for example: "all files with the string 'warehouse' in its name AND the file ending 'properties' should be searched". Now, in this case I could express it as a single glob, but since there might be a lot more conditions, the combinatorics quickly become unwieldy.

As far as I can see, the invocation ripgrep --glob '*warehouse*' --glob '*properties' matches all files that match EITHER of the globs, and I would need away to specify that BOTH must match.

**Comment by BurntSushi** [comment]
I suspect this type of complicated filtering would be more appropriately done by `find`. I don't think it's reasonable to expect that ripgrep grow every filtering feature found in `find` as well. For example, GNU grep's recursive search doesn't have the feature you're requesting either, and instead just has basic disjunctive `--include` rules.

**Comment by strindberg** [comment]
Yes, you're probably right. Every tool should be an expert in its own field. However, I can see no easy way to combine ripgrep with find, i.e. use my existing find filters and feed it into ripgrep. I would like an option saying "use this list of files and don't recurse". Am I missing something and this is already possible?

**Comment by BurntSushi** [comment]
@strindberg Glad you figured it out! And yeah, I forgot to include the `-type f` condition, which you probably also want with `grep` as well, but grep does print a helpful error message.

**Comment by strindberg** [comment]
Yes. grep has a -dskip option which automatically drops directories, which is useful. The reason why it is harder than it sounds to weed out directories is that if you use the "-prune" option in find, it is a bit complex to make sure that the right directories are pruned, but the resulting (printed) files are only just files.
