### ISSUE TITLE
Feature Request: Adding a Type for *.impex files

### ISSUE THREAD

**Issue by SpikePy** [BurntSushi/ripgrep#1047]
Could you implement a type for *.impex files? They are used in hybris and it would be nice if I could just type `rg "pattern" -timpex` instead of `rg "pattern" -g "*.impex"`.

**Comment by BurntSushi** [comment]
I'm not sure ripgrep should be in the business of adding every file type extension used by every type of proprietary software. I could reverse course on that if there's a strong enough motivation, but you don't need the type to be in ripgrep core to make easy use of it. Have you  read the [guide's section on file types](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-file-types)? The section on [configuration files](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) is also probably useful.
