### ISSUE TITLE
Suggest -U when regex contains \n

### ISSUE THREAD

**Issue by dtolnay** [BurntSushi/ripgrep#1055]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

cargo install

#### Describe your question, feature request, or bug.

I tried this regex today: `rg '=> \{\n *break;'`. The output is:

```console
the literal '"\n"' is not allowed in a regex
```

I would expect this error to suggest passing `-U` to enable multiline mode, in which that pattern would be allowed.

**Comment by BurntSushi** [comment]
This seems like a good idea! We already do the same with the `-P` flag if look-around or backreferences are used.
