### ISSUE TITLE
Better globs for ocaml files

### ISSUE THREAD

**Issue by Wilfred** [BurntSushi/ripgrep#1062]
https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/types.rs#L212

```rust
("ml", &["*.ml"]),
```

It'd be really useful to add `*.mli` files, which are header files for ocaml code. I think it might also make sense to rename the language from "ml" to "ocaml".

**Comment by BurntSushi** [comment]
There is already an Ocaml type: https://github.com/BurntSushi/ripgrep/blob/f72c2dfd90f98cfbd678d3d957e3d104237ab15b/ignore/src/types.rs#L220

The ml type is for Standard ML.

**Comment by Wilfred** [comment]
Argh, I totally missed that. Thanks.

I'm currently just using a dumb 'first match' heuristic in my Emacs integration of ripgrep. I think I'd be better off using the match with the most extensions, as those are typically more widely used languages.
