### ISSUE TITLE
--max-results not working

### ISSUE THREAD

**Issue by FranzSkuffka** [BurntSushi/ripgrep#1066]
actual
```
❯ rg -l -m 3 'hi'  | wc -l
     541
```

expected
```
❯ rg -l -m 3 'hi'  | wc -l
     3
```
version
```                                                                                                                   
❯ rg --version            
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```
platform
```
OSX High Sierra 10.13.6
```
installed with `brew`

**Comment by BurntSushi** [comment]
There is no --max-results flag. The -m flag is short for --max-count. As the documentation started, it limits the *number of lines matched per file*. Therefore, it had no impact on the behavior of the -l flag.

**Comment by FranzSkuffka** [comment]
ah okey so that means if I want to truncate the number of results I will need `head`

**Comment by BurntSushi** [comment]
@FranzSkuffka Yes, but note that by default, the order of results on subsequent runs isn't necessarily stable. So the results that `head` shows can change from run to run. You can make results stable with `--sort path` at the expense of parallelism.

**Comment by FranzSkuffka** [comment]
That's fine :) I was using this to create an interactive file selection.

https://github.com/FranzSkuffka/dotfiles/blob/master/rgki.sh#L11

thanks.
