### ISSUE TITLE
Snap has no pcre2 support

### ISSUE THREAD

**Issue by nilsboy** [BurntSushi/ripgrep#1069]
#### What version of ripgrep are you using?

```
ripgrep.rg --version
ripgrep 0.10.0 (rev f72c2dfd90)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

snap install ripgrep

#### What operating system are you using ripgrep on?

Ubuntu 14.04

#### Describe your question, feature request, or bug.

The snap version of ripgrep has no pcre2 support
Please add it.

Thank you.

**Comment by BurntSushi** [comment]
I do not maintain the snap. Please files bug with the snap maintainer.
