### ISSUE TITLE
Feature Request: Output in HTML

### ISSUE THREAD

**Issue by zivcaspi** [BurntSushi/ripgrep#1076]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

Cargo

#### What operating system are you using ripgrep on?

Windows 10

#### Describe your question, feature request, or bug.

Feature request: Add support in the printer for outputting the text in a way which preserves colors in non-terminal environments. For example, to be able to pipe the output of the tool into the clipboard and then paste it into a document. Thanks

**Comment by BurntSushi** [comment]
Please see the documentation for the color flag. In particular, use `--color always`.

**Comment by zivcaspi** [comment]
Thanks, but the problem isn't that the text output isn't colored, it's that (at least on Windows) the colored console output is copied without the color attributes, so that if I want to send the output of ripgrep to somebody over email I have to do a screen capture to get the colors preserved -- If I use tools such as clip (or select + CTRL-C) the colors will be lost.

**Comment by BurntSushi** [comment]
That sounds like a feature request for whatever terminal you're using. There ain't nothing ripgrep can do AFAIK.

**Comment by zivcaspi** [comment]
The feature request for the terminal is to be able to copy the color attributes (I have already created it). The one on ripgrep is to be able to output HTML.

**Comment by BurntSushi** [comment]
OK... I will say that it is frustrating as a maintainer when feature requests don't include relevant details initially. Instead, I seem to be getting details in a show trickle. Are there any other relevant details you've omitted?

ripgrep is not going to grow an HTML output mode. If that's the only way to achieve colors when copying and pasting, then it sounds like the terminal itself should be improved to support things other than HTML. If that's not feasible, then write a tool that converts ANSI escape sequences (emitted by ripgrep) to HTML.

**Comment by zivcaspi** [comment]
Sorry, I thought the title of the request was a dead giveaway...

Cool, thanks.

**Comment by BurntSushi** [comment]
Ah, my bad. I initially read this via email and the subject line was cutoff and just had "Feature Request: Output in." Sorry about that!
