### ISSUE TITLE
ripgrep warns about a .gitignore pattern accepted by git

### ISSUE THREAD

**Issue by hferreiro** [BurntSushi/ripgrep#1082]
#### What version of ripgrep are you using?

0.8.1.

#### How did you install ripgrep?

Fedora repo package.

#### What operating system are you using ripgrep on?

Fedora 28.

#### Describe your question, feature request, or bug.

I'm getting the following warning:
```
.gitignore: line 7: error parsing glob '**.sw[po]': invalid use of **; must be one path component
```

By looking at the gitignore man page, I assume the correct way to write this would be `**/*.sw[po]`, but git seems to accept both versions.

**Comment by BurntSushi** [comment]
Yup. There are a number of issues for this, so closing as a duplicate.

**Comment by BurntSushi** [comment]
FYI, if your don't want to see error messages from parsing ignore files, you can use `--no-ignore-messages`.
