### ISSUE TITLE
How can I get the previous behavior?

### ISSUE THREAD

**Issue by Yggdroot** [BurntSushi/ripgrep#1085]
I update the `rg` recently, and find the behavior of `--files` has been changed.

Before:  ripgrep 0.5.2

output of `rg --files .` is :
```
aaa/test.txt
bbb/test2.txt
```
Now: ripgrep 0.10.0
output of `rg --files .` is :
```
./aaa/test.txt
./bbb/test2.txt
```
How can I get the previous behavior?

**Comment by BurntSushi** [comment]
By omitting the `.`.
