### ISSUE TITLE
Panic when searching binary file as utf-16le

### ISSUE THREAD

**Issue by comex** [BurntSushi/ripgrep#1089]
Seems similar to #1052, but I'm encountering this on current ripgrep trunk (acf226c39d).

With the following file: https://a.qoid.us/System.Collections.dll

Running `rg -E utf-16le a System.Collections.dll` produces:
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /Users/comex/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_rs-0.8.6/src/handles.rs:311:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by BurntSushi** [comment]
Thanks! This was indeed occurring on master. It looks like bumping to the latest release of `encoding_rs` fixes this.
