### ISSUE TITLE
Directory ignore command line

### ISSUE THREAD

**Issue by gsquire** [BurntSushi/ripgrep#109]
Do you think it would be valuable to add an option to skip traversing directories? I know I can use an `.rgignore` file but it's not convenient to copy it from repository to repository.

If so, I think I could try and implement it as well.

**Comment by lzybkr** [comment]
I was just looking for an option to not recurse, so yeah, that'd be useful.

**Comment by BurntSushi** [comment]
I think `rg -g '!*/' PAT` will do it.

**Comment by BurntSushi** [comment]
That's not to say we don't want, say, a `--depth` flag or something that sets a limit on the recursion depth. I think I'd be OK with that. (Certainly, `find` has it.) Maybe use the same flag name as `find`? `--maxdepth`. A depth of `0` could mean "only search current directory."

**Comment by gsquire** [comment]
Ah I missed the `-g` flag. I suppose I need to read the usage more carefully. I imagine max depth would be easy to add considering you use your `walkdir` crate too :)

**Comment by BurntSushi** [comment]
Yes indeedy! Let me know if you'd like to work on it and I won't touch it. :-)

(I think `maxdepth` should be relatively straight-forward. `mindepth` would not be. Thankfully, there's less of a use case for that I think.)

**Comment by gsquire** [comment]
I would be happy to try it tonight and I'll keep you updated in this thread. Thanks!

**Comment by BurntSushi** [comment]
Awesome, thank you. :-)
