### ISSUE TITLE
avx build requires uninutative build flags

### ISSUE THREAD

**Issue by valarauca** [BurntSushi/ripgrep#1096]
### What rustc version are you using?

```
rustc 1.31.0-nightly (d586d5d2f 2018-10-29)
```

### What cargo version are you using?

```
cargo 1.31.0-nightly (2d0863f65 2018-10-20)
```

### What operating system are you trying to build on

```
fedora 28
4.18.16-200.fc28.x86_64
```

#### What command did you run?

```shell
cargo build --features "avx-accel" --release
```

Other attempts include

```shell
cargo build --features "avx-accel simd-accel" --release
```

### What finally works is

```shell
RUSTFLAGS=-Ctarget-cpu=native cargo build --features "avx-accel" --release
```

which is rather extremely unintuitive, is there a work around to this?

**Comment by BurntSushi** [comment]
This is documented in the README: https://github.com/BurntSushi/ripgrep/blob/master/README.md#building

I don't know what you mean by "extremely unintuitive," but I don't know of any other way. Hopefully the dependencies that require compile time target features for optimizations will eventually move to runtime target detection.
