### ISSUE TITLE
No info on how `ripgrep` compares to `pcregrep` and `pcre2grep`

### ISSUE THREAD

**Issue by chojrak11** [BurntSushi/ripgrep#1107]
I've just come across this utility. For years I've been using `pcregrep` and then `pcre2grep` which are marvelous. In README there's a lot about comparing `ripgrep` to other tools, but no word on `pcre[2]grep`. Is it possible to fill this gap?

**Comment by BurntSushi** [comment]
What questions do you want answered? The primary comparison point with
other tools in the README is mostly performance oriented.

**Comment by chojrak11** [comment]
Sorry it was just an impulse feeling of missing a favorite tool in the table. I've read what `ripgrep` is about, I can see the difference, and perf-wise I don't care, so to answer your question: I'm not sure. I'm closing this.

**Comment by BurntSushi** [comment]
All righty. I personally haven't used `pcre2grep` much myself, however, I did use it as a baseline when adding the `-P/--pcre2` flag to ripgrep in terms of performance.

Quickly scanning `pcre2grep`'s man page, nothing jumps out at me as a feature that isn't in ripgrep, other than perhaps POSIX locale support. (ripgrep does support transcoding from a number of different encodings however, including UTF-16, which I don't think `pcre2grep` supports.)

At first glance, it looked like `pcre2grep` didn't have Unicode support, but you can enable it via the special `(*UCP)` directive in the pattern when combined with the `-u` flag (short for "UTF-8 mode"). e.g., `pcre2grep -u '(*UCP)Napol\won'` will match `Napoléon`, but if you remove _either_ of `-u` or `(*UCP)`, then `Napoléon` is not matched. So one place where ripgrep does well here is that it can use PCRE2 and its Unicode features even on input that is not valid UTF-8. For example:

```
$ echo $'\xFFNapoléon' | pcre2grep -u '(*UCP)Napol\won'
pcre2grep: pcre2_match() gave error -23 while matching this text:

Napoléon

$ echo $'\xFFNapoléon' | rg 'Napol\won'
Napoléon
```
