### ISSUE TITLE
.gitignore not respected at all.

### ISSUE THREAD

**Issue by Tim-at-AST** [BurntSushi/ripgrep#1109]
#### What version of ripgrep are you using?

````
$ rg --version
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
````

#### How did you install ripgrep?
macports

#### What operating system are you using ripgrep on?
mac osx 10.14.1 (mojave)

#### Describe your question, feature request, or bug.
here is my .gitignore file:

````
$ cat ~/.gitignore
**/*.pdf
*.pdf
````

I am trying to ignore pdf files in my rg search.

Here is a test directory:
````
$ cd /tmp/test
$ touch a.pdf b.txt
$ ls
a.pdf
b.txt

$ rg --files --debug
b.txt
a.pdf
````

The problem is that the file `a.pdf` should be ignored.

**Comment by BurntSushi** [comment]
Your `.gitignore` is in your home directory and you are searching outside your home directory. Therefore, what you're observing is expected behavior. Try using a standard git repository setup instead. See `man gitignore` for how to specify global gitignore rules.

**Comment by Tim-at-AST** [comment]
The example was badly chosen.  But the problem persists inside the home directory also.  Here is a better example:

````
$ cat ~/.gitignore
**/*.pdf
*.pdf
**/*.jpg
$ cd /Users/tim/documents/rg/test
$ touch a.pdf b.txt
$ ls
a.pdf
b.txt
$ rg --files --debug
DEBUG|rg::config|src/config.rs:37: /Users/tim/gdrive/tim/app-support/ripgreprc: arguments loaded from config file: ["--max-columns=150", "--smart-case"]
DEBUG|rg::args|src/args.rs:508: final argv: ["rg", "--max-columns=150", "--smart-case", "--files", "--debug"]
DEBUG|globset|globset/src/lib.rs:429: built glob set; 0 literals, 0 basenames, 2 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
b.txt
a.pdf

`````

**Comment by Tim-at-AST** [comment]
ok, I changed .gitignore to .rgignore and problem solved.  
The documentation seems to me to indicate that .gitignore was used by rg.

> After recursive search, ripgrep's most important feature is what it doesn't search. By default, when you search a directory, ripgrep will ignore all of the following:

> 1. Files and directories that match the rules in your .gitignore glob pattern.

**Comment by BurntSushi** [comment]
> The documentation seems to me to indicate that .gitignore was used by rg.

Right, _in a git repository_. I agree that the docs could be more precise on this point. In particular, I do not think ripgrep always behaved this way, but I can't find the corresponding bug report that prompted the change to require a git repository before respecting `.gitignore`.

**Comment by anntzer** [comment]
Note that currently, if rg follows a symlink that points to a subdirectory of a git repo, it will not detect that it is in a git repo, and thus won't respect a gitignore file in that subdirectory (even though that gitignore is indeed in a git repo), as shown by:
```
$ tree -a -L 3
.
├── a
│   └── subdir -> ../c/subdir
└── c
    ├── .git
    │   ├── branches
    │   ├── config
    │   ├── description
    │   ├── HEAD
    │   ├── hooks
    │   ├── info
    │   ├── objects
    │   └── refs
    └── subdir
        ├── .gitignore
        └── somefile
$ cat a/subdir/.gitignore
*
$ rg --follow --files
a/subdir/somedir  # oops, not ignored.
```

I would thus suggest revisiting the choice of not respecting gitignores outside of git repos -- the alternative being, I guess, to check for each *resolved* symlink whether it is in a git repo.

**Comment by BurntSushi** [comment]
@anntzer Yes, that's interesting, although it's definitely a distinct bug from this ticket. My guess is that I'd probably mark it as `wontfix`. I don't think I'm willing to start messing with the resolved paths of symlinks.

**Comment by anntzer** [comment]
That's why I listed checking the resolved paths as the alternative solution -- if you don't remember what change prompted you to ignore gitignores outside of git repositories, perhaps you can consider the above an argument in favor of always taking them into account?

**Comment by BurntSushi** [comment]
I'm not going to change that. It's semantically incorrect and leads to other types of bugs. I wrote "I don't remember" above because it's often inconvenient for me to spend the time to remember. Looking at revision history, I found this commit https://github.com/BurntSushi/ripgrep/commit/e65ca21a which fixed this bug https://github.com/BurntSushi/ripgrep/issues/934

**Comment by anntzer** [comment]
Sure, thanks for the reference.

**Comment by EndlessDex** [comment]
A note for future readers:  The ~/.ignore file DOES work for non-git repos. It is just the .gitignore file that does not work
