### ISSUE TITLE
how to search java file only 

### ISSUE THREAD

**Issue by northleafup** [BurntSushi/ripgrep#1115]
I use the latest version `ripgrep 0.10.0` 
if I run the command ,there is java and jsp file types 
```shell
➜  ~ rg --type-list | grep java
java: *.java, *.jsp
```
how to search java file only ?

thanks

**Comment by BurntSushi** [comment]
This should be answered in the documentation. Please consider reading it before filling issues. Specifically, see: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-file-types
