### ISSUE TITLE
ignore crate: Show matched FileTypeDef?

### ISSUE THREAD

**Issue by firesock** [BurntSushi/ripgrep#1116]
#### What version of ripgrep are you using?

ignore-0.4.4

#### How did you install ripgrep?

ignore crate via crates.io

#### What operating system are you using ripgrep on?

Linux

#### Describe your question, feature request, or bug.

Is it feasible to make ignore's `Walk` return `DirEntry`'s that are aware of the `FileTypeDef` they matched on, if any?

My use case is to use `Walk` to iterate and depending on the name registered with the matching `FileTypeDef` do some different logic.

As far as I can tell, this information isn't accessible easily right now. Even if I used `Types` and called `matched`, the `Glob` struct doesn't return the `FileTypeDef` and hence the name registered.

**Comment by firesock** [comment]
Okay thanks, is the intended goal to use `Types` and `matched` after a `DirEntry` is returned, and not expose it on `DirEntry` at all?

**Comment by BurntSushi** [comment]
If you can make that work, then I think that would be ideal. Exposing it through the directory iterator would require more API design work.
