### ISSUE TITLE
Please do not ignore file tracked by git, even it's in .gitignore

### ISSUE THREAD

**Issue by co-dh** [BurntSushi/ripgrep#1127]
#### What version of ripgrep are you using?

ripgrep 0.10.0 (rev 8a7db1a918)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

tar -xzvf ripgrep-0.10.0-x86_64-unknown-linux-musl.tar.gz

#### Describe your question, feature request, or bug.
More like a feature than bug.
I added a file that is tracked by git to .gitignore by accident.
rg will ignore the file, but git grep will not.
expecting rg do not ignore the file.

**Comment by co-dh** [comment]
why not just use git list-files?

**Comment by BurntSushi** [comment]
This is unfortunately a bug that is unlikely to be fixed. The work around is to either take the file out of your gitignore or specifically whitelist it in either your gitignore or a separate `.ignore` file.
