### ISSUE TITLE
Etymology of ripgrep

### ISSUE THREAD

**Issue by maxbla** [BurntSushi/ripgrep#1128]
#### What version of ripgrep are you using?
```
$ rg --version
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

pacman

#### What operating system are you using ripgrep on?

Arch

#### Describe your question, feature request, or bug.

Feature Request: add an entry to FAQ as to why the program is called ripgrep - is it as simple as a concatenation of RIP (rest in peace) and grep (the program with similar functionality)?

**Comment by BurntSushi** [comment]
This is an easy one to do! It's already done. :-) It's the last entry: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#intentcountsforsomething
