### ISSUE TITLE
ripgrep fails to match line with pipe pattern

### ISSUE THREAD

**Issue by mc10** [BurntSushi/ripgrep#1136]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

Probably from the repo.

#### What operating system are you using ripgrep on?

CentOS 7.5

#### Describe your question, feature request, or bug.

rg fails to match this line with a pipe (that `grep` matches).

#### If this is a bug, what are the steps to reproduce the behavior?

1. Create file.txt with `1|t|1234|asdf`
2. Run `rg '^[^|]*\|t\|(?:[^|]*\|)' file.txt`

#### If this is a bug, what is the actual behavior?

No results.

#### If this is a bug, what is the expected behavior?

Should have matched on the `1|t|1234|`.

`grep '^[^|]*\|t\|(?:[^|]*\|)' file.txt` works fine.

Oddly, the following work:
- `rg '^[^|]*\|t\|(?:[^|]*\|?)' file.txt`
- `rg '^[^|]*\|t\|(?:[^|]*)' file.txt`
- `rg '^[^|]*\|t\|[^|]*\|' file.txt`

But this does not:
- `rg '^[^|]*\|t\|(?:[^|]*\|+)' file.txt`

**Comment by okdana** [comment]
I think this is #1064 again, it's fixed in `master`

**Comment by BurntSushi** [comment]
Yup, confirmed that this is fixed in master.
