### ISSUE TITLE
asciidoc does not support python 3

### ISSUE THREAD

**Issue by Hello71** [BurntSushi/ripgrep#1137]
asciidoc is no longer maintained, and requires python 2 (as I am sure you know, EOL in 2020). AIUI, immediate remedy is to migrate to asciidoctor, but projects can also consider markdown, pandoc, docbook, whatever.

**Comment by BurntSushi** [comment]
We can address this when there is actual problem. As long as asciidoc is stiol available in distributions and serves its primary function, I'll probably continue to use it. With that said, I would love to move to a different tool. I've already tried pandoc and it doesn't work nearly as well as asciidoc for this purpose.
