### ISSUE TITLE
ignore: Please update crossbeam-channel dependencies to 0.3

### ISSUE THREAD

**Issue by sylvestre** [BurntSushi/ripgrep#1141]
ignore uses crossbeam-channel 0.2 currently ( https://github.com/BurntSushi/ripgrep/tree/master/ignore )
it would make the life of distro if it could use the most recent upstream release (0.3.2) instead.
Currently, ignore fails with this version with:

> 
> error[E0308]: mismatched types                                                                                                                                                   
>     --> src/walk.rs:1449:17                                                                                                                                                      
>      |                                                                                                                                                                           
> 1449 |                 Some(Message::Work(work)) => {                                                                                                                            
>      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `std::option::Option`                                                           
>      |                                                                                                                                                                           
>      = note: expected type `std::result::Result<walk::Message, channel::TryRecvError>`                                                                                           
>                 found type `std::option::Option<_>`                                                                                                                              
>                                                                                                                                                                                  
> error[E0308]: mismatched types                                                                                                                                                   
>     --> src/walk.rs:1454:17                                                                                                                                                      
>      |                                                                                                                                                                           
> 1454 |                 Some(Message::Quit) => {                                                                                                                                  
>      |                 ^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `std::option::Option`                                                                 
>      |                                                                                                                                                                           
>      = note: expected type `std::result::Result<walk::Message, channel::TryRecvError>`                                                                                           
>                 found type `std::option::Option<_>`                                                                                                                              
>                                                                                                                                                                                  
> error[E0308]: mismatched types                                                                                                                                                   
>     --> src/walk.rs:1485:17                                                                                                                                                      
>      |                                                                                                                                                                           
> 1485 |                 None => {                                                                                                                                                 
>      |                 ^^^^ expected enum `std::result::Result`, found enum `std::option::Option`                                                                                
>      |                                                                                                                                                                           
>      = note: expected type `std::result::Result<walk::Message, channel::TryRecvError>`                                                                                           
>                 found type `std::option::Option<_>`                                                                                                                              
>                                                                                                                                                                                  
> error: aborting due to 3 previous errors

**Comment by ignatenkobrain** [comment]
We need this for Fedora asap too :)

**Comment by BurntSushi** [comment]
Could someone help me understand why this is time sensitive? Getting this
fixed on master in a reasonable amount of time seems okay, but that doesn't
mean I'm going to also then put out a new release. Releases are a lot of
work, and I cannot be beholded to a release process whose schedule is
dictated by the new release of a dependency.

**Comment by ignatenkobrain** [comment]
Because we would like to avoid supporting multiple versions of dependencies.

Also I'm not asking for release -- I'll simply backport patch into Fedora.

**Comment by BurntSushi** [comment]
@sylvestre - Is that true for you as well? You don't need a release?

**Comment by sylvestre** [comment]
Correct, I already uploaded ignore with this pr

Le sam. 15 déc. 2018 à 14:08, Andrew Gallant <notifications@github.com> a
écrit :

**Comment by BurntSushi** [comment]
OK, this should be all set. I did the fix myself since this wasn't quite right and cleaned up a few other things. I've also put my changes to `ignore` on crates.io in `0.4.5`. Thanks!
