### ISSUE TITLE
ripgrep default `|` regexp metadata behavior not compitable with gnu grep

### ISSUE THREAD

**Issue by zw963** [BurntSushi/ripgrep#1147]
#### What version of ripgrep are you using?

ripgrep 0.10.0 (rev 8a7db1a918)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

download compiled version.

#### What operating system are you using ripgrep on?

Deepin linux

#### Describe your question, feature request, or bug.

When want to replace default grep with ripgrep, i found some not compatible behavior.

default grep:

```sh
 ╰─ $ 1  echo 'hello world' |grep 'hello\|world'
hello world       # => this is expected behavior for grep
```

ripgrep 

```sh
╰─ $ echo 'hello world' |rg 'hello\|world'  # => not output
 ╰─ $ echo 'hello world' |rg 'hello|world'
hello world       # => must replace  \| to |, to resolve this.
```

i guess ripgrep default behavior same with grep `-E`, but i think
this maybe not a good idea, anywhy,  we have `-P` to perl regex.

I don't know this is a bug or just expected behavior, Thanks

**Comment by BurntSushi** [comment]
This is expected behavior because ripgrep does not support BREs. Please see https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#posix4ever
