### ISSUE TITLE
How to pass rg matched filenames as " quoted string instead of literal?

### ISSUE THREAD

**Issue by stardiviner** [BurntSushi/ripgrep#1148]
I got problem on passing matched filenames (from option `--files-with-matches`) to command `xargs`. But when filename contains space, it report error.

Like command:
```
rg --files-with-matches --type org -e "Emacs" ~/Org | xargs rg --files-with-matches -e "Linux" | xargs rg --heading -e "Arch"
```

Here is the detailed link: https://github.com/dajva/rg.el/issues/49#issuecomment-449677077

**Comment by BurntSushi** [comment]
This is your shell, not ripgrep. Either don't create file paths with whitespace in them or ask ripgrep to print file paths delimited by NUL with the `-0/--null` flag. Once you do that, you need to tell xargs to read NUL delimited file paths with the `-0` flag.

**Comment by stardiviner** [comment]
Thanks. @BurntSushi
