### ISSUE TITLE
output kind PathWithMatch requires a file path

### ISSUE THREAD

**Issue by need47** [BurntSushi/ripgrep#1156]
#### What version of ripgrep are you using?

Replace this text with the output of `rg --version`.
ripgrep 0.10.0 (rev 8a7db1a918)
-SIMD -AVX (compiled)
+SIMD -AVX (runtime)

#### How did you install ripgrep?

use Github binary release

#### What operating system are you using ripgrep on?

x86_64 GNU/Linux

#### Bug

I have a file named 'list', which contains two lines:
abc
xyz

Then I tested with the command below to show only the filename with match.

$ rg -l abc list
list: output kind PathWithMatch requires a file path

I didn't expect to see 'output kind PathWithMatch requires a file path'

Then I tested with multiple files, it looks good.

$ rg -l abc list list
list
list

**Comment by BurntSushi** [comment]
This is a duplicate. I'm on mobile so I don't have a link, but it should
come up in a search.

**Comment by need47** [comment]
Got it. #1130.
