### ISSUE TITLE
Feature request: Make rg possible to change delimiter from colon

### ISSUE THREAD

**Issue by yantene** [BurntSushi/ripgrep#1169]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

I install ripgrep from the arch official repos.

#### What operating system are you using ripgrep on?

Arch Linux

#### Describe your question, feature request, or bug.

When I execute the following command, the file path, line number, contents are displayed in a colon delimiter.

```
$ rg --no-heading --line-number .
test.txt:1:hogehoge
test.txt:2:fugafuga
test.txt:3:piyopiyo
```

I'd like to change the delimiter to anything.

Replacing by `sed` will fail if the file path contains some colons.
So I want to specify an other delimiter character in ripgrep.

Thank you.

**Comment by BurntSushi** [comment]
> Replacing by sed will fail if the file path contains some colons.
So I want to specify an other delimiter character in ripgrep.

This is basically what the `-0/--null` flag is for, because the NUL byte is the only byte that is illegal in a file path on Unix.

Otherwise, if you need a more structured format for parsing, you might consider using `--json`.

**Comment by yantene** [comment]
`-0/--null` is exactly what I needed!
Thank you very much!
