### ISSUE TITLE
Add OPTION --output

### ISSUE THREAD

**Issue by matjaz9** [BurntSushi/ripgrep#1171]
#### What version of ripgrep are you using?

ripgrep 0.10.0 (rev 8a7db1a918)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

Archives of precompiled binaries for ripgrep are available for Windows, macOS and Linux

#### What operating system are you using ripgrep on?

Windows 10

#### Describe your question, feature request, or bug.

This is proposal to introduce new switch --output. 
This switch is implemented on ACK utility and allows  output of variables together with some text. This allows composing of command files for process automation, etc..

Example of usage switch --output on ACK utility:
>ack "some text (\d{15})\s+(\d{11})" my_file.log --output "Command: MSISDN=$2, IMSI=$1;"

Drawback of using ACK on Windows is that perl needs to be installed  as well. Not everyone has it installed. While rg is compiled executable file and switch --output would make it very competitive, especially for Windows users.

**Comment by BurntSushi** [comment]
This already exists. Please read the GUIDE and see the `-r/--replace` flag.
