### ISSUE TITLE
rg --type-add not working

### ISSUE THREAD

**Issue by Kerruba** [BurntSushi/ripgrep#118]
Even tried to copy your example (ie rg --type-add 'foo:*.{foo,foobar}'), not adding the type to type-list.

Mac - El Capitain 10.11.6

**Comment by BurntSushi** [comment]
Could you please provide the entire command you're running, its output and the output you expected? Thanks.

**Comment by Kerruba** [comment]
typing `rg --type-add 'vue:*.vue'` is returning `Invalid argument`

See picture attached
![image](https://cloud.githubusercontent.com/assets/2854782/18893745/02fce0a6-8507-11e6-9bd8-b0d121c26aef.png)

**Comment by BurntSushi** [comment]
That looks like expected behavior to me. Check out the docs for `--type-add`:

```
    --type-add ARG ...
        Add a new glob for a particular file type. Only one glob can be added
        at a time. Multiple type-add flags can be provided. Unless type-clear
        is used, globs are added to any existing globs inside of ripgrep. Note
        that this must be passed to every invocation of rg.

        Example: `--type-add html:*.html`
```

So you need to do `rg --type-add 'vue:*.{vue}' -tvue PATTERN`.

Perhaps we need more concrete examples. I think that's #76.

**Comment by Kerruba** [comment]
Sorry, but is not exactly what I understand from the "tour"

![image](https://cloud.githubusercontent.com/assets/2854782/18894308/11451d2e-850a-11e6-9343-2311bc53bbbf.png)

Reading that I would suppose that typing `rg --type-add 'foo:*.{foo,foobar}'` would return a message like "New type added" and that `rg --type-list` would list that.

**Comment by BurntSushi** [comment]
You're right. Thank you for catching that. The tour is sadly wrong. Fixing now.

**Comment by BurntSushi** [comment]
All set. Thanks!

**Comment by Kerruba** [comment]
I'm sorry, don't want to seem pedant, is what I described before as "expected behaviour" for `rg --type-add ...` actually the behaviour?

Because this is what I get following the new instructions:
![image](https://cloud.githubusercontent.com/assets/2854782/18894726/809343a2-850c-11e6-9b3d-2aca5af0737f.png) 
this is definitely not what I'm expecting from this setting

**Comment by BurntSushi** [comment]
I put this note in the `README`:

> `rg` won't persist your type settings

Let me be very clear: `--type-add` must always be present. `rg` has no config file, it does not persist any of the options. If you want to configure it, use an alias.

(We may grow a config file or something at some point.)

**Comment by Kerruba** [comment]
Ok so why should I write such a long line when I can do this?
`rg bar -g "*.{foo,foobar}"`

**Comment by BurntSushi** [comment]
`--type-add` is probably most useful in an alias.
