### ISSUE TITLE
Add .dtx and .ins for -type tex

### ISSUE THREAD

**Issue by steffenbanhardt** [BurntSushi/ripgrep#1181]
#### What version of ripgrep are you using?

ripgrep 0.10.0 (rev 8a7db1a918)

#### Describe your feature request

The --type tex should include documented LaTeX sources (.dtx) and their .ins files

diff for types.rs:

    @@ -283,7 +283,7 @@
         ]),
         ("taskpaper", &["*.taskpaper"]),
         ("tcl", &["*.tcl"]),
    -    ("tex", &["*.tex", "*.ltx", "*.cls", "*.sty", "*.bib"]),
    +    ("tex", &["*.tex", "*.ltx", "*.cls", "*.sty", "*.bib", "*.dtx", "*.ins"]),
         ("textile", &["*.textile"]),
         ("thrift", &["*.thrift"]),
         ("tf", &["*.tf"]),

**Comment by BurntSushi** [comment]
Thanks! I don't keep issues open tracking trivial changes to the file type list. Please just submit a PR instead. :-)
