### ISSUE TITLE
File filter/glob?

### ISSUE THREAD

**Issue by alexreg** [BurntSushi/ripgrep#1192]
#### What version of ripgrep are you using?

```
ripgrep 0.10.0 (rev 8a7db1a918)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

macOS Homebrew

#### What operating system are you using ripgrep on?

macOS 10.14.2

#### Describe your question, feature request, or bug.

Could we have a feature to search files that match a certain glob/pattern, so the expansion doesn't have to take place in the shell (which is slow, and sometimes too large)? E.g., similar to the `-name` option of find.

**Comment by BurntSushi** [comment]
[Please consult the documentation.](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs)
