### ISSUE TITLE
add CI test for a big-endian target

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#1193]
Given #1144, it seems prudent for ripgrep to get tested on a big-endian target.

I tried playing with this in #1152 and ran into errors. The `memchr` crate is an example with a big-endian target test that works: https://github.com/BurntSushi/rust-memchr/blob/974943c8bc840538e18d788b6682bbfcdccceb12/.travis.yml#L31-L35

**Comment by hlieberman-gov** [comment]
Though it's not really useful for "live" testing, we do get post-facto testing from Debian's build infra which has several big-endian targets that will at least tell us if we broke something horribly.

i.e., https://buildd.debian.org/status/package.php?p=rust-ripgrep.

**Comment by BurntSushi** [comment]
@hlieberman-gov Right, that's how #1144 was reported, AIUI. The point here is to catch problems before they get to the Debian folks. :-)

**Comment by BurntSushi** [comment]
This was done in da3431b4780a2654cdbb35613ff428cdef3fc8fe, which adds a `nightly-mips` builder which should cover big endian.
