### ISSUE TITLE
rg.exe still shows v0.10

### ISSUE THREAD

**Issue by leeoniya** [BurntSushi/ripgrep#1195]
`rg.exe` in the grep-searcher-0.1.3 release shows correct commit but incorrect version?

`ripgrep 0.10.0 (rev d6feeb7ff2)`

could be useful to add the build date in there as well to quickly grok how old the build is without git/github spelunking.

cheers!

**Comment by BurntSushi** [comment]
Those aren't releases. Windows CI is just over-eager.

I think a revision number is sufficient for now.

**Comment by leeoniya** [comment]
ok, thanks!
