### ISSUE TITLE
crlf tests fail on Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [BurntSushi/ripgrep#1199]
```
---- feature::f416_crlf_only_matching stdout ----
thread 'feature::f416_crlf_only_matching' panicked at '
printed outputs differ!
expected:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sherlock
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
got:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sherlock

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
', tests/feature.rs:455:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- json::crlf stdout ----
thread 'json::crlf' panicked at 'assertion failed: `(left == right)`
  left: `SubMatch { m: Text { text: "Sherlock\r" }, start: 56, end: 65 }`,
 right: `SubMatch { m: Text { text: "Sherlock" }, start: 56, end: 64 }`', tests/json.rs:298:5
failures:
    feature::f416_crlf_only_matching
    json::crlf
```

**Comment by BurntSushi** [comment]
The Debian folks ran into the same test failures. The issue is that a new version of the `grep-searcher` crate was released, which includes a CRLF related fix. But in order for it to work correctly with ripgrep on master, it also needs a corresponding fix in `grep-regex`, which I haven't released yet.

With that said, ripgrep 0.10.0, which is the latest release, should be working fine. Are you trying to use ripgrep master with only the latest releases of crates? I'm not sure that's always guaranteed to work.

**Comment by ignatenkobrain** [comment]
> With that said, ripgrep 0.10.0, which is the latest release, should be working fine. Are you trying to use ripgrep master with only the latest releases of crates? I'm not sure that's always guaranteed to work.

In Fedora we always use latest crates. Which means that it picked up latest grep-searcher.

**Comment by BurntSushi** [comment]
@ignatenkobrain I _think_ I can release a new version of `grep-regex` and it might fix it this time, but I don't know if I can provide that guarantee in all cases. Otherwise, it requires the pace of ripgrep releases to be on par with the pace of crate releases, and I'm just never going to do that.

**Comment by ignatenkobrain** [comment]
@BurntSushi but doesn't that mean when you changed handling of crlf in grep-searcher it should have been a breaking change? Since that changes semantics.

**Comment by BurntSushi** [comment]
No. It's a bug fix. It changes errant behavior, not semantics.

**Comment by ignatenkobrain** [comment]
Then I guess the best way forward would be to publish new version of grep-regex.

**Comment by BurntSushi** [comment]
`grep-regex 0.1.2` is now on crates.io.
