### ISSUE TITLE
Cannot build project: could not parse input as TOML

### ISSUE THREAD

**Issue by lava** [BurntSushi/ripgrep#12]
On a fresh checkout, on ubuntu xenial:

    ➜  ripgrep git:(master) ./compile              
    failed to parse manifest at `/usr/local/src/ripgrep/Cargo.toml`
    
    Caused by:
      could not parse input as TOML
    Cargo.toml:42:9 expected a key but found an empty string
    Cargo.toml:42:9-42:10 expected `.`, but found `'`

On a related note, since I don't know anything about rust, is there support for doing out-of-tree builds?

**Comment by BurntSushi** [comment]
What version of Rust do you have? Ripgrep needs 1.9 or newer. Just
guessing, but it looks like you have an older version.

Also, the README has the build instructions.

**Comment by lava** [comment]
You're correct, my version of rustc seems to be too old:

    ➜  ripgrep git:(master) apt-cache policy rustc
    rustc:
      Installed: 1.7.0+dfsg1-1
      Candidate: 1.7.0+dfsg1-1
      Version table:
     *** 1.7.0+dfsg1-1 500
            500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
            100 /var/lib/dpkg/status

That will make it quite...challenging to build a package for ubuntu ;p

I don't see out-of-tree builds being mentioned in the README.

**Comment by BurntSushi** [comment]
Could you say a bit more by what you need for "out-of-tree" builds? The standard way to build Rust code is with `cargo`.

**Comment by lava** [comment]
As I said, I don't really know a lot about rust, but my usual way of building an open-source project looks like this

    cd ~/build/ripgrep
    ~/src/ripgrep/configure --some-weird args
    make

or

    cd ~/build/ripgrep
    cmake ~/src/ripgrep/ -DWEIRD_OPTION=SOME_VALUE
    make

I believe this is more or less standard, as it avoids cluttering the source tree with build artifacts, and allows to build multiple configurations from the same source tree. The build instructions in the README seem to be for an in-tree build, so I was wondering if it is possible to do an out-of-tree build.
