### ISSUE TITLE
Add search by shannon entropy

### ISSUE THREAD

**Issue by xstevens** [BurntSushi/ripgrep#1200]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

Homebrew

#### What operating system are you using ripgrep on?

macOS

#### Describe your question, feature request, or bug.

I thought it would be really handy if ripgrep supported shannon entropy search. By that I mean adding an option, so as it's searching through text; if any given word has entropy above a threshold then display it as a match. I currently use other tools for this type of search, though I use ripgrep for regex and most other types of grep functionality. It would be handy and I suspect faster to have all of that in this tool.

**Comment by BurntSushi** [comment]
This doesn't sound like a good fit for ripgrep, sorry. If speed is important, you might consider reusing some of ripgrep's libraries for this. It shouldn't be too much code for such a specialized use case. High level documentation for ripgrep's libraries is still missing, but [this example](https://github.com/BurntSushi/ripgrep/blob/master/grep/examples/simplegrep.rs) should be a good starting point for now.

**Comment by xstevens** [comment]
I understand. Thanks for the example!
