### ISSUE TITLE
--sort path ignores case sensitivity of the file system

### ISSUE THREAD

**Issue by laggardkernel** [BurntSushi/ripgrep#1209]
#### What version of ripgrep are you using?

```bash
❯ rg --version
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

Installed on macOS 10.12.6 with homebrew.

#### Describe your question, feature request, or bug.

The sort option `--sort path` sort the result by their file path. But it doesn't respect the case sensitivity of the file system. The result is sorted case-sensitively.

**Comment by BurntSushi** [comment]
AFAIK, the correct way to implement this is to use an implementation of the [Unicode collation algorithm](https://www.unicode.org/reports/tr10/tr10-38.html). Such a thing does not exist in Rust yet. When it does, we can revisit this. Until then, I'm going to unfortunately mark this as `wontfix`. Sorry.
