### ISSUE TITLE
Speedup ripgrep using profile guided optimization

### ISSUE THREAD

**Issue by maklemenz** [BurntSushi/ripgrep#1225]
#### What version of ripgrep are you using?

compiled current master (09139721047b1cda6ad88dbf89dc5fa74c66a3a2)

#### How did you install ripgrep?

compiled current master (09139721047b1cda6ad88dbf89dc5fa74c66a3a2)

#### What operating system are you using ripgrep on?

Linux Mint 19.1 with kernel 4.18.0-16-lowlatency

#### Describe your question, feature request, or bug.

Profile guided optimization works by building the binary with profiling instrumentation first, then running the instrumented binary in a few test cases while saving runtime profiles and then using the profiles to optimize the code for example by reordering functions to improve cachability.

Using the very naive benchmark `time sudo target/release/rg --with-filename --word-regexp --line-buffered a /home > /dev/null` ripgrep needed `3.7s` on avg without profile guided optimization on my system and `3.3s` with pgo.

This is how I compiled rg with pgo:
````
# make sure we get a profile for each run, %p will be replaced with the pid
export LLVM_PROFILE_FILE=./target/pgo/pgo-%p.profraw

# compile instrumented binary
RUSTFLAGS="-Z pgo-gen=llvm-profile-file-env-variable-overrides-this" cargo +nightly build --release

# run a few test cases (these need to be improved to cover more rg features)
target/release/rg --help > /dev/null
target/release/rg a > /dev/null
target/release/rg B --line-buffered > /dev/null
target/release/rg c --word-regexp > /dev/null
target/release/rg D --vimgrep > /dev/null
target/release/rg e --with-filename > /dev/null
target/release/rg f --unrestricted > /dev/null
target/release/rg '[A-Z]+_SUSPEND' --with-filename --word-regexp --line-buffered > /dev/null
target/release/rg h --unrestricted --with-filename --vimgrep --word-regexp --line-buffered > /dev/null

# merge profiles
rustup run nightly llvm-profdata merge -o target/pgo/pgo.profdata target/pgo/pgo*.profraw

# compile with profile in mind
RUSTFLAGS="-Z pgo-use=target/pgo/pgo.profdata" cargo +nightly build --release
````

pgo could speed up ripgrep quite a bit when done correctly.

**Comment by BurntSushi** [comment]
Neat. Could you please document the build dependencies here more thoroughly? Whether this is done or not almost completely depends on how much of a hassle it would be to add to the release process.

**Comment by maklemenz** [comment]
I just checked this against alpine since it is used in .travis.yaml. The package llvm-dev would be required. The main problem is that `-Z` flags requires nightly rust, which is not available as an alpine package.

**Comment by BurntSushi** [comment]
Thanks for suggesting this. I just briefly tried this out, and while I could get it to work, I couldn't really see any noticeable performance improvement. Moreover, this would complicate and prolong the release process by quite a bit. Not only does ripgrep need to be built twice, but it needs to get some sizable corpus on which to search a number of times. Overall, I don't think it's worth it.

**Comment by ArniDagur** [comment]
As of [Rust 1.37](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#profile-guided-optimization), PGO is stable.

**Comment by BurntSushi** [comment]
@zamazan4ik See https://github.com/BurntSushi/ripgrep/commit/b6bac8484e5466d332640c4022951061bb865329

Basically, I'm still not convinced. I only tested LTO and not PGO, but PGO does not sound like something I'm keen on maintaining.

In any case, I've at least added a `release-lto` profile to ripgrep, but stopped short of using it in the actual release binaries.
