### ISSUE TITLE
aho-corasick 0.7

### ISSUE THREAD

**Issue by ignatenkobrain** [BurntSushi/ripgrep#1228]
Hi @BurntSushi, I'm pretty sure you are planning to update aho-corasick at some point. Just curious if anytime soon.

I would be happy if you just have patch (doesn't have to be new release).

Thanks in advance!

**Comment by BurntSushi** [comment]
The intent is to do it soonish, yes.

(One of the goals of the Aho-Corasick rewrite was to fix the slow performance of the `-f` flag when used with a large dictionary of literals.)
