### ISSUE TITLE
rg --files -z ( \0 line termination)

### ISSUE THREAD

**Issue by thisch** [BurntSushi/ripgrep#1233]
#### What operating system are you using ripgrep on?

GNU/Linux (ubuntu/fedora)

#### Describe your question, feature request, or bug.

I would like to use ripgrep as a backend in the emacs [projectile](https://github.com/bbatsov/projectile) package for opening files in a project. In the case of git repos projectile uses ``git ls-files -zco --exclude-standard`` by default, which returns `\0` separated list of files (From the man page: ``  -z:  \0 line termination on output and do not quote filenames.``. For generic projects ``find . -type f -print0`` is used.

WDYT about adding support for changing the output format of `rg --files`, in particular adding a flag for \0 line termination?

**Comment by BurntSushi** [comment]
Could you please explain why the `-0/--null` flag does not work for your purposes?

**Comment by thisch** [comment]
Sry I competely overlooked that this flag exists. (searching in the ripgrep github project didn't return me any satisfying results) 
I'll try to the ``-0/-null`` flag tomorrow. Let's close this ticket.

Thank you very much for developing ripgrep!!
