### ISSUE TITLE
Feature request: add a command-line option to force case-sensitive search

### ISSUE THREAD

**Issue by jeberger** [BurntSushi/ripgrep#124]
Rationale: I would prefer smart case to be the default. I can get that by creating an alias like `alias rg="rg -S"` but then I need some way to force case-sensitive search when I need it e.g. `rg --case-sensitive`, which given the alias would become `rg -S --case-sensitive`, the last given flag would then override previous flags.

**Comment by BurntSushi** [comment]
Should it also override the `-i` flag?

**Comment by kaushalmodi** [comment]
> Should it also override the `-i` flag?

Is it possible to have the last flag win? The idea is to allow a user to override whatever is in the alias.

- `rg -S --case-sensitive` ≈ `rg --case-sensitive`
- `rg --case-sensitive -S` ≈ `rg -S`
- `rg -S -i` ≈ `rg -i`
- `rg -i --case-sensitive` ≈ `rg --case-sensitive`
- and so on.. (you get the idea :))

**Comment by BurntSushi** [comment]
Sadly, no, although I agree that might be more intuitive. We'd probably have to switch arg parsing libraries. Docopt doesn't expose that kind of information.

**Comment by lespea** [comment]
Just a thought... most of the time this won't happen so if you detect both flags as being set you could just loop through argv and manually take the last one?  Not very clean but it would work without requiring a new library.

**Comment by BurntSushi** [comment]
Yeah, I don't really want to add that implementation complexity. We should either do it right (switch to a different arg parsing library, which I don't really want to do) or just specify a precedence.

Let's punt on "last flag wins for now" and decide on precedence. I feel like the precedence should be:

* `--case-sensitive`
* `--case-insensitive`
* `--smart-case`

where flags earlier in the list override flags later in the list.

**Comment by kaushalmodi** [comment]
That precedence will work for my use case too where I have `--smart-case` in the alias.

On a different note. Would you also please add `-s` as an alias to `--case-sensitive`?

**Comment by jeberger** [comment]
Since we can't have "last flag wins", that precedence would be fine. And +1 for the short alias for `--case-sensitive`.

**Comment by BurntSushi** [comment]
This is done and will be in the next release. I implemented the precedence rules discussed here and made `-s` alias `--case-sensitive`.

**Comment by gomesalexandre** [comment]
Thank you! Made case-insensitive my default `:Rg` binding, this is really helpful when having to case-sensitive search ❤️
