### ISSUE TITLE
Would you like to Add Chinese about the Doc 😊

### ISSUE THREAD

**Issue by chinanf-boy** [BurntSushi/ripgrep#1246]
#### What commit of ripgrep ?

`v0.10.0` [2019-04-14 commit](https://github.com/BurntSushi/ripgrep/tree/45d12abbc5f576d3b10ae13dc7410b14400a8d1e)

## Source

[chinese doc :GithubRepo](https://github.com/chinanf-boy/ripgrep-zh)

- readme.md [Chinese](https://github.com/chinanf-boy/ripgrep-zh#ripgrep-rg)

- GUIDE.md [Chinese](https://github.com/chinanf-boy/ripgrep-zh/blob/master/GUIDE.zh.md)

- FAQ.md [Chinese](https://github.com/chinanf-boy/ripgrep-zh/blob/master/FAQ.zh.md)

**Comment by BurntSushi** [comment]
Thanks for doing this translation! It looks like this would be really useful, and it also looks like it was a lot of work!

Unfortunately, I'm not quite sure what to do with it. I certainly can't maintain it myself, so it's likely to rot pretty quickly. And I'm not sure how I feel about pointing to outdated docs. With that said, I don't want to throw the baby out with the bath water; it might still be useful.

What kind of outcome are you hoping for here? Perhaps a link to your repo in the README with the caveat that they might be out of date?

**Comment by Lin-Buo-Ren** [comment]
I think that the best we can do is to mention which commit of the original version the translation is based on in the translated version and the link to the original version.

**Comment by chinanf-boy** [comment]
## yes, I had! BTW, I always did 😊 

https://github.com/chinanf-boy/ripgrep-zh#%E6%9B%B4%E6%96%B0-


## 更新 ✅





翻译的原文 | 与日期 | 最新更新 | 更多
---|---|---|---
[commit] | ⏰ 2019-04-14 | ![last] | [中文翻译][translate-list]

[last]: https://img.shields.io/github/last-commit/BurntSushi/ripgrep.svg
[commit]: https://github.com/BurntSushi/ripgrep/tree/45d12abbc5f576d3b10ae13dc7410b14400a8d1e
