### ISSUE TITLE
unresolved import app

### ISSUE THREAD

**Issue by luisbg** [BurntSushi/ripgrep#1251]
#### What version of ripgrep are you using?

git clone today right after the 11.0.1

#### How did you install ripgrep?

Building from source.

#### What operating system are you using ripgrep on?

Building on macOS. Strangely this doesn't happen when building in Ubuntu 18.10.

#### Describe your question, feature request, or bug.

When trying to build ripgrep I get the following error.

```
error[E0432]: unresolved import `app`
 --> build.rs:9:5
  |
9 | use app::{RGArg, RGArgKind};
  |     ^^^ Did you mean `self::app`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `ripgrep`.
```

#### If this is a bug, what are the steps to reproduce the behavior?

cargo build --release

#### If this is a bug, what is the expected behavior?

A clean build :)

**Comment by BurntSushi** [comment]
Please show the output of `rustc --version` and `cargo --version`.

**Comment by luisbg** [comment]
I should've thought of doing that. Sorry.

Problem happens with nightly, but not with stable.
```
$ rustc --version
rustc 1.31.0-nightly (b2d6ea98b 2018-10-07)

$ cargo --version
cargo 1.31.0-nightly (ad6e5c003 2018-09-28)
```

**Comment by BurntSushi** [comment]
As the [README says](https://github.com/BurntSushi/ripgrep#building), ripgrep's minimum supported Rust version is 1.34. So you'll need to upgrade.

**Comment by luisbg** [comment]
Updating nightly fixes the problem. False alarm.

```
$ rustc --version
rustc 1.35.0-nightly (2975a3c4b 2019-04-15)
```
