### ISSUE TITLE
Add `--directories-with-matches` flag

### ISSUE THREAD

**Issue by ad-si** [BurntSushi/ripgrep#1258]
#### Describe your feature request

`rg --files-with-matches` shows all files containing a match. E.g.:

```sh
$ rg --files-with-matches test
projectA/readme.md
projectA/main.hs
projectB/readme.md
```

It would be cool if there was a flag to show all directories which contain files with matches:

```sh
$ rg --directories-with-matches test
projectA
projectB
```

This could be  for example used to check which of the projects has a certain dependency:
```sh
rg --directories-with-matches --max-depth 1 jquery-v3.4.0
```

**Comment by BurntSushi** [comment]
I'm going to have to decline. Sorry. I suggest using a shell pipeline for this. For example:

```
$ rg foo -l -0 | xargs -0 dirname | sort -u
```

**Comment by ad-si** [comment]
😭That's much longer and definitely not user friendly
