### ISSUE TITLE
win10 crashes

### ISSUE THREAD

**Issue by habamax** [BurntSushi/ripgrep#126]
Downloaded  v0.2.1

ripgrep-0.2.1-x86_64-pc-windows-msvc.zip

It gives 
![rg_win10_crash](https://cloud.githubusercontent.com/assets/234774/18912069/40cfe2d4-8589-11e6-96f2-10b6f9f95e6d.png)

**Comment by BurntSushi** [comment]
Honestly, I have no idea how to debug this. I can download that same file and run it on my new Windows 10 laptop just fine.

Can you try the GNU version?

**Comment by BurntSushi** [comment]
Also, for the MSVC version, do you have the [Microsoft VC++ 2015 redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed?

**Comment by BurntSushi** [comment]
And finally, how are you running `rg.exe`?

**Comment by habamax** [comment]
GNU version works

**Comment by habamax** [comment]
cmd.exe

then

     rg

**Comment by habamax** [comment]
I guess not, I don't have MS redistributable files.

**Comment by BurntSushi** [comment]
All right, I'm going to close this. I've heard there's a way to bundle the VC++ redistributable, but I don't quite know how to do that.
