### ISSUE TITLE
Nerd out about ripgrep on The Changelog?!

### ISSUE THREAD

**Issue by jerodsanto** [BurntSushi/ripgrep#1260]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of software development since '09.)_

We'd love to have you on the show sometime soon, @BurntSushi. What do you think? 

💚

**Comment by BurntSushi** [comment]
@jerodsanto Hiya! Sounds awesome. Do you want to reach out via email with more details? :-) My email address is on my contact page: https://blog.burntsushi.net/about/

Thanks!
