### ISSUE TITLE
add --test flag for test replace

### ISSUE THREAD

**Issue by woodgear** [BurntSushi/ripgrep#1276]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
#### How did you install ripgrep?

cargo 
#### What operating system are you using ripgrep on?
windows

#### Describe your question, feature request, or bug.
 feature request
add ability to test replace.
i want to check the replace result and then replace it in real.
for example 
rg fast README.md -ort FAST
if you add flag -t which will not replace in real but for test

**Comment by BurntSushi** [comment]
ripgrep doesn't execute the replacement in files. Indeed, ripgrep will never write to any file. All it does is read and search.
