### ISSUE TITLE
can't search keyword in xml files with current dir

### ISSUE THREAD

**Issue by zhjunjun** [BurntSushi/ripgrep#1281]
#### What version of ripgrep are you using?

Replace this text with the output of `rg --version`.

#### How did you install ripgrep?

If you installed ripgrep with snap and are getting strange file permission or
file not found errors, then please do not file a bug. Instead, use one of the
Github binary releases.

#### What operating system are you using ripgrep on?

Replace this text with your operating system and version.

#### Describe your question, feature request, or bug.

If a question, please describe the problem you're trying to solve and give
as much context as possible.

If a feature request, please describe the behavior you want and the motivation.
Please also provide an example of how ripgrep would be used if your feature
request were added.

If a bug, please see below.

#### If this is a bug, what are the steps to reproduce the behavior?

If possible, please include both your search patterns and the corpus on which
you are searching. Unless the bug is very obvious, then it is unlikely that it
will be fixed if the ripgrep maintainers cannot reproduce it.

If the corpus is too big and you cannot decrease its size, file the bug anyway
and the ripgrep maintainers will help figure out next steps.

#### If this is a bug, what is the actual behavior?

Show the command you ran and the actual output. Include the `--debug` flag in
your invocation of ripgrep.

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### If this is a bug, what is the expected behavior?

What do you think ripgrep should have done?

**Comment by BurntSushi** [comment]
This bug report isn't actionable. Please consider following the template provided to you.
