### ISSUE TITLE
Provide a way to associate the match to the pattern

### ISSUE THREAD

**Issue by kewisch** [BurntSushi/ripgrep#1286]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### Describe your feature request

When running `rg -f patternfile` with multiple patterns, I'm wanting to find out which pattern triggered the match so I can group them in my results. Assuming a pattern file like

```
foo+
bar
```

##### A new option `--with-pattern`

Calling `rg -f patternfile --no-heading --with-pattern --with-filename --line-number` would show output like

```
foo:src/cli.js:      // get all your foooooooo here
bar:src/quality.js   // There is a high bar for quality
```
This might need to be displayed somewhat differently with multiple patterns per line or with different options.

##### Including pattern in JSON output
This is what I am most interested in. When calling with `--json`, regardless of the pattern option, matches should include the pattern data:

```json
{
   "type" : "match",
   "data" : {
      "absolute_offset" : 0, "line_number" : 1,
      "path" : { "text" : "src/cli.js" },
      "submatches" : [
        {
            "match" : { "text" : "foooooooo" },
            "pattern" : "foo+",
            "start" : 16, "end" : 25
         }
      ],
      
      "lines" : { "text" : "// get all your foooooooo here\n" }
   }
}
```

##### Alternatives
If this doesn't fit in well, what about exposing the named capture groups in the JSON output? This way I could modify the pattern to `(?P<identifier>foo+)` and in whatever way you choose read this from the JSON data.

**Comment by BurntSushi** [comment]
I think there are too many variables, too much complexity and not enough user demand for a feature like this. I'd recommend writing your own program to do this. You can even use ripgrep's libraries to do it.

**Comment by BurntSushi** [comment]
(I'm pretty sure this is a duplicate, but I couldn't find the original issue.)

**Comment by kewisch** [comment]
Would you accept a patch to ripgrep to add the pattern to the JSON output, or are you specifically saying you would not want this feature in ripgrep?

**Comment by BurntSushi** [comment]
I do not think this feature belongs in ripgrep at the current time.

Also, it is possible for multiple patterns to match the same text, so you'd need to include all of them. In general, this feature is more difficult to implement than you might imagine, particularly if performance is a concern.

**Comment by TheTechromancer** [comment]
@kewisch out of curiosity, did you ever find a solution to your problem of correlating regex patterns to their matches? I am looking at a similar problem.

**Comment by kewisch** [comment]
It has been quite a while and for a past job. I don't believe we created something substantial based on ripgrep that solved this issue, looking back over the code we had for this I think we managed to work around by not relying on the pattern at all.

**Comment by TheTechromancer** [comment]
Thanks. Right now it's looking like the answer to our problem is [yara](https://github.com/VirusTotal/yara).
