### ISSUE TITLE
--vimgrep is not an option

### ISSUE THREAD

**Issue by davidosomething** [BurntSushi/ripgrep#13]

**Comment by BurntSushi** [comment]
Could you please show the exact command you're running? And also, the output of `rg --version`?

**Comment by davidosomething** [comment]
```
david@elitedavid:~projects/elitedaily/ed-videoplayer                                                                                                                                                                                                [node:v6.6.0][py:3.5.2][rb:2.3.1]
11:31:57I(vast*)% rg --version
0.1.15
```

Just for testing:
```
11:32:09I(vast*)% rg --vimgrep video
Unknown flag: '--vimgrep'

Usage: rg [options] -e PATTERN ... [<path> ...]
       rg [options] <pattern> [<path> ...]
       rg [options] --files [<path> ...]
       rg [options] --type-list
       rg --help
       rg --version
```

expected output in format `filename:LINENUMBER:grep-result`

**Comment by BurntSushi** [comment]
Oh, the `--vimgrep` option was added in `0.1.16`. How did you install `rg`? (It looks like something is out of date.)

**Comment by davidosomething** [comment]
oh the brew package is referencing 0.1.15 still
https://github.com/BurntSushi/ripgrep/blob/master/pkg/brew/ripgrep.rb

**Comment by BurntSushi** [comment]
I've updated the brew package to `0.1.17`, so you should get the `--vimgrep` option now.
