### ISSUE TITLE
Add a way to ignore files only for ripgrep?

### ISSUE THREAD

**Issue by Elronnd** [BurntSushi/ripgrep#1312]
Is there any possibility of adding a `.rgignore` (or similar)?  I have certain files that I want to be ignored by ripgrep but acknowledged by git, so this would be really convenient.

**Comment by alexeyten** [comment]
#1284

**Comment by Elronnd** [comment]
Perfect; closing this in favour of that.  The docs should be better, but obviously that issue is tracking that already.

**Comment by BurntSushi** [comment]
@Elronnd #1284 is just about making the feature better advertised. `.ignore` and `.rgignore` are documented in the guide: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering
