### ISSUE TITLE
doesn't understand plus (+) sign

### ISSUE THREAD

**Issue by kaldown** [BurntSushi/ripgrep#1314]
#### What version of ripgrep are you using?

ripgrep 11.0.1 (rev d1389db2e3)

#### How did you install ripgrep?

https://aur.archlinux.org/ripgrep-git.git

#### What operating system are you using ripgrep on?

arch

#### If this is a bug, what is the actual behavior?

```
> rg +
regex parse error:
    +
    ^
error: repetition operator missing expression
```

#### If this is a bug, what is the expected behavior?

to solve a problem I'm piping output to an original grep
`rg - | grep +`

My proposal to add something like need of operations a.k.a `--`, like
`rg -- +`, for rg understand this is not an option or weird stuff

**Comment by svanburen** [comment]
you need to escape the `+`:

```shell
rg "\+"
```

**Comment by kaldown** [comment]
true, thanks
