### ISSUE TITLE
Return only filenames of matches

### ISSUE THREAD

**Issue by Kyle-Thompson** [BurntSushi/ripgrep#1325]
It would be useful to have an option that when set will cause rg to print only the names of the files that contain matches. I've run into situations before where it would be useful to say `vim -O $(rg --match-filenames-only keyword)`.

**Comment by BurntSushi** [comment]
Try the `-l/--files-with-matches` is standard and has been available in ripgrep probably since its first release. Why can't you use that?

**Comment by Kyle-Thompson** [comment]
Don't mind me, I'm just an idiot. Somehow missed that.
