### ISSUE TITLE
hang when greping /sys/kernel/security/apparmor/{policy,revision}

### ISSUE THREAD

**Issue by HongxuChen** [BurntSushi/ripgrep#1331]
#### What version of ripgrep are you using?

```
ripgrep 11.0.1 (rev 08ae4da2b7)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?
`cargo build --release` against github repo, HEAD version

#### What operating system are you using ripgrep on?
`Linux H5 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`, Ubuntu 19.04

#### If this is a bug, what are the steps to reproduce the behavior?

run `rg power /sys/kernel/security/apparmor/policy` or `rg power /sys/kernel/security/apparmor/revision` (or explicitly with `--no-follow`), it hangs there.

#### If this is a bug, what is the actual behavior?

```
$ rg --no-follow power /sys/kernel/security/apparmor/revision --debug
DEBUG|grep_regex::literal|grep-regex/src/literal.rs:59: literal prefixes detected: Literals { lits: [Complete(power)], limit_size: 250, limit_class: 10 }
DEBUG|globset|globset/src/lib.rs:435: built glob set; 0 literals, 0 basenames, 11 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
DEBUG|grep_searcher::searcher::mmap|grep-searcher/src/searcher/mmap.rs:86: /sys/kernel/security/apparmor/revision: failed to open memory map: memory map must have a non-zero length
# hang there
```

#### If this is a bug, what is the expected behavior?

I expect that `rg` would exit soon (especially for `/sys/kernel/security/apparmor/revision`; but `grep` would also hang on this zero-length file) or at least behave like `grep` for `/sys/kernel/security/apparmor/policy`:
```
$ grep power -r /sys/kernel/security/apparmor/policy
# exit soon

$ grep power -R /sys/kernel/security/apparmor/policy
# hang
```

Other information:

```
$ ls -l /sys/kernel/security/apparmor/
total 0
drwxr-xr-x  2 root root 0 Jul 27 19:54 attr/
drwxr-xr-x 15 root root 0 Jul 27 19:54 features/
lr--r--r--  1 root root 0 Jul 27 19:54 policy -> 'apparmorfs:[12192]'
-r--r--r--  1 root root 0 Jul 27 19:54 profiles
-r--r--r--  1 root root 0 Jul 27 19:54 revision
```

#### What do you think ripgrep should have done?

This seems to be specific to `apparmor` and I've no idea what is going on.

**Comment by BurntSushi** [comment]
`grep` hangs when running

```
$ grep power /sys/kernel/security/apparmor/revision
```

Indeed, `cat` hangs too:

```
$ cat /sys/kernel/security/apparmor/revision
```

As such, this isn't a problem with ripgrep. `strace` (in all instances) indicates that the process hangs in the `read` call.

A little googling [demystifies this](https://gitlab.com/apparmor/apparmor/wikis/AppArmorInterfaces#syskernelsecurityapparmorrevision):

> The revisions file behaves like a pipe with the current revision
> available to read when the file is opened. Subsequent reads will
> sleep the reading task until the next revision is available.

So this seems like intended behavior. In general, you shouldn't be arbitrarily searching the `/sys`, `/proc` and `/dev` directories. Other issues have come up on this, since folks seem to assume that these directories are normal file hierarchies. But they aren't.

**Comment by HongxuChen** [comment]
Yes, I noticed that `grep` (as well as `cat`) hangs on the revision file. Is there any way to avoid hangs when greping recursively, such as what `grep -r` does? I met several scenarios to search inside special directories in Linux.

**Comment by BurntSushi** [comment]
I don't know. Someone will need to dig into what `grep` does and figure out what its case analysis looks like. I don't have any plans to do that myself. If someone wants to do that research and post it back here, then I can consider re-opening this.
