### ISSUE TITLE
regression: 11.0.2 is not (fully) statically linked

### ISSUE THREAD

**Issue by rlaager** [BurntSushi/ripgrep#1343]
#### What version of ripgrep are you using?

11.0.2

#### How did you install ripgrep?

The GitHub binary release:
https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb

#### What operating system are you using ripgrep on?

Ubuntu 18.04

#### Describe your question, feature request, or bug.

The ripgrep 11.0.2 release is _not_ (fully) statically linked like the 11.0.1 release was. It is linked with libpcre2-8.so.0. When I upgraded, ripgrep broke, because I didn't have libpcre2-8-0 installed.

#### If this is a bug, what are the steps to reproduce the behavior?

Download and install:
https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb

#### If this is a bug, what is the actual behavior?

```
$ ldd `which rg`
	linux-vdso.so.1 (0x00007fff364fc000)
	libpcre2-8.so.0 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9855fd7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9855dcf000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9855bb0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9855998000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f98555a7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9856662000)
```

#### If this is a bug, what is the expected behavior?

Compare to the ripgrep 11.0.1 binary package:
```
$ ldd `which rg`
	linux-vdso.so.1 (0x00007ffeb65c1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcb3edd4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcb3ebcc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcb3e9ad000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcb3e795000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcb3e3a4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcb3f4d4000)
```

If linking with libpcre is intentional, then the ripgrep package needs to `Depend` on the appropriate libpcre binary package (in this case libpcre2-8-0). You shouldn't hard-code that, but should get it via `${shlibs:Depends}`.

**Comment by BurntSushi** [comment]
My bad! I goofed when I uploaded the deb artifact, which is manually generated by me. If you re-download the deb, this should be fixed. (PCRE2 is statically linked.)

**Comment by rlaager** [comment]
Thanks!
