### ISSUE TITLE
--hidden doesn't work with --type all

### ISSUE THREAD

**Issue by kurnevsky** [BurntSushi/ripgrep#1344]
#### What version of ripgrep are you using?

ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

Linux package.

#### What operating system are you using ripgrep on?

Arch Linux

#### Describe your question, feature request, or bug.

`--hidden` doesn't work with `--type all`

#### If this is a bug, what are the steps to reproduce the behavior?

Search something contained in project's hidden files (starting with dot) with both `--hidden` and `--type all` flags.

#### If this is a bug, what is the actual behavior?

It won't be found.

#### If this is a bug, what is the expected behavior?

It should be found.

**Comment by BurntSushi** [comment]
Please provide a reproduction. As the issue template requests:

> If possible, please include both your search patterns and the corpus on which
you are searching.

**Comment by kurnevsky** [comment]
```sh
mkdir /tmp/1
cd /tmp/1
echo qwerty > .env
rg --hidden qwerty
rg --hidden --type all qwerty
```

**Comment by kurnevsky** [comment]
Hm... Just realized that it's filtered by extension `.env`. So even file `name.env` won't be shown. Is it expected to happen?

**Comment by kurnevsky** [comment]
It seems `--type all` means all supported extensions - couldn't find it in the docs so was confused about it. Sorry for bothering.

**Comment by BurntSushi** [comment]
Indeed, the special `all` type does not appear in the man page. That should be fixed, so I'm re-opening this. Thanks!

**Comment by telotortium** [comment]
Hi, could you add this to the documentation? I was confused about `--type all` wasn't searching all of my non-ignored files and couldn't find anything about it until now.

**Comment by BurntSushi** [comment]
@telotortium Yes. This ticket is marked as `doc` bug.

**Comment by BurntSushi** [comment]
@telotortium It would be helpful if you could write out the blurb in the docs that would have helped you! Thanks.

**Comment by telotortium** [comment]
Hi @BurntSushi I gave it a shot in  PR #1472 - thanks for getting back to me!
