### ISSUE TITLE
ignore: include files below previously excluded path / (nested) whitelist

### ISSUE THREAD

**Issue by blueyed** [BurntSushi/ripgrep#1349]
I want to include files from a previously ignored directory ("build", via
"/build/" in `.gitignore`).

It would be great if the following pattern worked in an `.ignore` file then:

```
!/build/src/nvim/auto/**
```

But what is necessary currently is:

```
!/build
/build/**
!/build/src
!/build/src/nvim
!/build/src/nvim/auto
!/build/src/nvim/auto/**
```

Or:

```
!/build
/build/*
!/build/src
/build/src/*
!/build/src/nvim
/build/src/nvim/*
!/build/src/nvim/auto
```

I.e. first do not include the directory as-is, and then ignore subentries in
all of them, but whitelist the subpaths down to the subdirectory.

It would be nice if ripgrep could transform the entry
`!/build/src/nvim/auto/**`automatically into these (internal) patterns.

While the use case here is "overriding something from a .gitignore" file, it is a useful pattern by itself: ignore everything except for some files from (a nested subdirectory of) a directory.

(As a single regular expressions `'build/(?!src/nvim/auto/)'` could be used here.)

The main problem probably is that subdirectories are not descended into in the first place, but here any whitelists could/should be considered then maybe?

#### What version of ripgrep are you using?

    ripgrep 11.0.2
    -SIMD -AVX (compiled)
    +SIMD +AVX (runtime)

**Comment by BurntSushi** [comment]
> The main problem probably is that subdirectories are not descended into in the first place

Yes, that is indeed the problem. I unfortunately do not see this getting fixed, although I do agree it is unfortunate behavior.

**Comment by blueyed** [comment]
Wouldn't it be an option then to check whitelists when traversing directories?

**Comment by BurntSushi** [comment]
I'm not adding code that automatically determines whitelists like this, sorry.
