### ISSUE TITLE
[FEATURE REQUEST] Export matches' metadata to text file

### ISSUE THREAD

**Issue by NightMachinary** [BurntSushi/ripgrep#1350]
I love https://github.com/aykamko/tag, but it's hacky, buggy and unmaintained. If rg adds a `--export-matches somefile.txt` option, so that all matches are numbered like this:
![image](https://user-images.githubusercontent.com/36224762/62473849-d95a1080-b7b6-11e9-8084-9d1e97930a0e.png)
And their metadata is stored in `somefile.txt`:
```
Match i: FILE_PATH LINE_NUMBER COLUMN_NUMBER
```

This way we can write a shell function to use `somefile.txt` to easily open our editor of choice on the desired match.
I know there are editor-specific plugins that use `--vimgrep` to accomplish this, but this is a different use case. With this, I can search any collection of files (The editors usually like to just search project directories) from the shell, using options like context and whatnot, and open any application for the results.

**Comment by BurntSushi** [comment]
Could you please explain why the `--json` flag is insufficient for your use case?

**Comment by NightMachinary** [comment]
Is there a way to ask `rg` to store the json output in a file, and output
otherwise normally? Since my use case is an interactive one, where `rg`
works as it always does, but there is an added functionality of jumping to
matches.
The other problem is that I need to see the matches numbered in the
interactive output, so I can invoke the function that reads the json file
with the index of the match I want to jump to.
I know I can rewrite a whole new frontend using `--json` to do all these,
but that's obviously way overkill and arduous.
(Have you taken a look at the project I linked?)

**Comment by BurntSushi** [comment]
It sounds like you can build your tool as a wrapper around the JSON output of ripgrep.
