### ISSUE TITLE
Feature request: invert highlighting of leading/trailing whitespace

### ISSUE THREAD

**Issue by Elronnd** [BurntSushi/ripgrep#1351]
Currently, if I say `rg 'foo'`, and `rg ' foo'`, the entries that show up will have only the text 'foo' highlighted; this makes it difficult to see, if I do run `rg ' foo'`, that the leading space is part of the match.  I propose to detect leading and trailing whitespace (also EOF), and colour its background instead of its foreground.

**Comment by BurntSushi** [comment]
You can set the background color. Please see the FAQ: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#colors

**Comment by Elronnd** [comment]
I want for the background colour to be set *only* on trailing or leading whitespace.

**Comment by BurntSushi** [comment]
I see. I'm going to have to pass on that, sorry.

**Comment by Elronnd** [comment]
OK.
