### ISSUE TITLE
output file path have garbled if file coding is not utf-8

### ISSUE THREAD

**Issue by pengpengxp** [BurntSushi/ripgrep#1364]
I run ripgrep 11.0.2 (rev 3de31f7527) on windows.

If I run rg with -H --heading. My output file path have garbled if the file path have chinese path.

I find it is because the output file path encoding is always utf-8.

I known I can use -E/--encoding the set the encoding. But it not work on the output file path.

Is there any argument to specify output file path encoding？

**Comment by BurntSushi** [comment]
This issue is not actionable. Please re-open another issue and follow the template. It's there for a reason.

(File paths in Windows are not UTF-8. They are UCS-2. ripgrep passes them through as-is.)
