### ISSUE TITLE
Unexpected interaction with symlinks

### ISSUE THREAD

**Issue by boblehest** [BurntSushi/ripgrep#137]
I noticed that `rg` ignores symlinks by default, even when I invoke it solely to search a single symlinked file. For me, that's very surprising behavior. The `-debug` flag also said nothing about why it was skipping my file.

So I'm suggestion to either change that behavior (unless maybe it's made this way for a good reason?), or inform the user that his symlinks are being ignored.

**Comment by BurntSushi** [comment]
Agreed, `rg` should search a symlinked file if it's explicitly specified. This is good enough reason for me:

```
[andrew@Cheetah tmp] echo test > foo
[andrew@Cheetah tmp] rg test foo
1:test
[andrew@Cheetah tmp] ln -s foo bar
[andrew@Cheetah tmp] rg test bar
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.
[andrew@Cheetah tmp] grep test bar
test
```

Otherwise, you can use the `-L` flag with `rg` to follow symlinks.
