### ISSUE TITLE
Whitelisting via .gitignore does not handle dot prefix ("!./fname")

### ISSUE THREAD

**Issue by blueyed** [BurntSushi/ripgrep#1374]
Given a `.gitignore` file:
```
*
!./PKGBUILD
```

`rg` will skip the `PKGBUILD` file:

> DEBUG|ignore::walk|ignore/src/walk.rs:1639: ignoring ./PKGBUILD: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("./.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))

This appears to be due to the leading dot there.
Git handles this as expected.

Removing the dot (using `!/PKGBUILD`) whitelists it then:

> DEBUG|ignore::walk|ignore/src/walk.rs:1642: whitelisting ./PKGBUILD: Whitelist(IgnoreMatch(Gitignore(Glob { from: Some("./.gitignore"), original: "!/PKGBUILD", actual: "PKGBUILD", is_whitelist: true, is_only_dir: false })))

#### What version of ripgrep are you using?

ripgrep 11.0.2

**Comment by goto-engineering** [comment]
I just tried this, and my `git` (2.25.1) seems to show the same behavior:
```
*
!./test
```
does not show the `test` file under `git status`, whereas
```
*
!test
```
does show it.

`ripgrep` has the exact same behavior.

Even when my .gitignore simply contains:
```
./test
```
the test file is NOT being git-ignored. Are we sure that the `./` syntax is supported by gitignore?

**Comment by BurntSushi** [comment]
@blueyed Can you clarify what you meant by "git handles this as expected" in your initial bug report here?

**Comment by BurntSushi** [comment]
Closing as not a bug. Happy to revisit with more compelling data.
