### ISSUE TITLE
Feature request: --files-without-matches

### ISSUE THREAD

**Issue by mernen** [BurntSushi/ripgrep#138]
One flag that occasionally comes useful is to identify files that _don't_ match a certain expression. Both `ag` and `ack` have `-L`/`--files-without-matches` (effectively the opposite of `-l`/`--files-with-matches`).

One minor problem here is that `rg -L` is already taken for following symlinks.

Curiously, `ag -lv` appears to be a synonym of `-L`. I'm not sure whether this is intentional or not, but it seems like a perfectly reasonable approach to me — in fact, years ago, before I knew of `-L`, this is actually what I first tried with `ack`, and got bogus results (it interprets this combo as "list all files that have at least one line that does not match the given expression", like ripgrep does today). Personally, I don't think I've ever had a use case for this.

**Comment by BurntSushi** [comment]
I'm not opposed to adding `--files-without-matches`, but I don't think we need to add a short alias for it. I'd at least like to keep `-L` for following symlinks.

I'm also not opposed to making `-v` a bit smarter with respect to whether `-l` is given or not, but I worry that it will make "find files with a line that doesn't match" impossible to do.

**Comment by andschwa** [comment]
Ha, I almost added this earlier @mernen but ran into exactly the problem you described 😄

**Comment by BurntSushi** [comment]
OK, so I did some more thinking about this and I think the *current* behavior of `-lv` is probably the right one. I totally get that it can be confusing, but `-v` pretty solidly refers to matching at the line level and isn't a generic "do the opposite" flag. In particular, `grep -lv` behaves the same as `rg -lv`.

Here is a proposed specification.

Add a new flag `--files-without-matches`. Only show the path of each file that contains zero matches.

**Comment by hauntsaninja** [comment]
(If, like me, you're coming here from Google, the flag that made it into ripgrep is `--files-without-match`)

**Comment by sankalp-khare** [comment]
I keep coming back here to re-check what the flag is 😢

**Comment by jeremyfiel** [comment]
how can we use this flag in vs code search?

**Comment by BurntSushi** [comment]
This is the issue tracker for ripgrep. Your question is about VS Code UX. You are in the wrong place.
