### ISSUE TITLE
Alternate filename for the ignore file

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [BurntSushi/ripgrep#1383]
I am looking for a recursive directory walker that uses a .gitignore compatible ignore format, but it's own filename - not .gitignore - that would live alongside .gitinore in many cases.

Do you contemplate this crate being extended to allow users to specify the name of the ignore file to be used, replacing ".gitignore".

**Comment by BurntSushi** [comment]
You already can: https://docs.rs/ignore/0.4.10/ignore/struct.WalkBuilder.html#method.add_custom_ignore_filename
