### ISSUE TITLE
Limit the characters included in the search result

### ISSUE THREAD

**Issue by thatreguy** [BurntSushi/ripgrep#1386]
#### What version of ripgrep are you using?

ripgrep 11.0.2 (rev 8cb7271b64)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

snap

#### What operating system are you using ripgrep on?

Ubuntu 18.04.3 LTS

#### Describe your question, feature request, or bug.

Limit the output from a single line. A base64 encoded line outputs a huge text exhausting the terminal scrollback buffer.

**Comment by okdana** [comment]
That is what `-M` (optionally combined with `--max-results-preview`) does
