### ISSUE TITLE
Allow .ignore to override .gitignore

### ISSUE THREAD

**Issue by tbodt** [BurntSushi/ripgrep#1413]
#### What version of ripgrep are you using?

ripgrep 11.0.1 (rev 1f1cd9b467)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### What operating system are you using ripgrep on?

Debian

#### Describe your question, feature request, or bug.

I have some files in .gitignore that I want to search anyway. (In this case they're git repositories inside a main git repository that are managed by a script rather than as submodules.) --no-ignore-vcs excludes the entire gitignore, which I don't want because that includes things like build directories. I just want to whitelist some directories, which I was thinking I could do with a .ignore pattern like `!/third_party`.

**Comment by BurntSushi** [comment]
`.rgignore` overrides `.ignore` and `.ignore` overrides `.gitignore`. So this is already possible.

**Comment by tbodt** [comment]
Aha, my .gitignore had `/third_party/*` instead of `/third_party`. Works now.
