### ISSUE TITLE
Add file type "patch"

### ISSUE THREAD

**Issue by svenstaro** [BurntSushi/ripgrep#1418]
#### What version of ripgrep are you using?

ripgrep 11.0.2

#### How did you install ripgrep?

Arch repo

#### What operating system are you using ripgrep on?

Arch Linux

#### Describe your question, feature request, or bug.

I'd like a new file type for "patch". These are usually `.diff` or `.patch` files generated by `git diff`, `svn diff` or just plain old `diff`. Nothing fancy.

**Comment by BurntSushi** [comment]
For file types, please just submit PRs. No need for tracking tickets.
