### ISSUE TITLE
Please bump the dependency on thread_local to v1.0.0

### ISSUE THREAD

**Issue by paride** [BurntSushi/ripgrep#1438]
Please bump the dependency on thread_local to version 1.0.0. The dependency is pulled in at least in grep_regex, ignore, pcre2, regex, but a ripgrep run on the project directory will help to find all its occurrences :)

This will help the packaging in Debian/Ubuntu and other distros.

Thanks!

**Comment by BurntSushi** [comment]
This appears to have been done in cb2f6ddc61b79b7acf59bb00a6be9f1740aa55b8.
