### ISSUE TITLE
ripgrep man page differs from CPU

### ISSUE THREAD

**Issue by bmwiedemann** [BurntSushi/ripgrep#1441]
#### What version of ripgrep are you using?

11.0.2

#### What operating system are you using ripgrep on?

openSUSE Tumbleweed

#### Describe your question, feature request, or bug.

While working on reproducible builds for openSUSE, I found that
ripgrep man page content differs on different CPUs

```diff
--- /usr/share/man/man1/rg.1.gz
-11\&.0\&.2 \-SIMD \-AVX (compiled) +SIMD +AVX (runtime)
+11\&.0\&.2 \-SIMD \-AVX (compiled) \-SIMD \-AVX (runtime)
```

The strings come from `ripgrep-11.0.2/src/app.rs  fn runtime_cpu_features()`

#### If this is a bug, what are the steps to reproduce the behavior?

use my "rbk" script from the reproducibleopensuse repo (needs some setup and an openSUSE account) or do a distribution/release build on different CPUs (e.g. I use `kvm -cpu qemu64` and `-cpu host` )

#### If this is a bug, what is the actual behavior?

The man page differs depending on build machine CPU.

#### If this is a bug, what is the expected behavior?

The man page should be the same on every build (everytime, everywhere)

See https://reproducible-builds.org/ for why this matters.

**Comment by BurntSushi** [comment]
It's likely that the `SIMD` and `AVX` designations should be removed entirely from the man page, as they don't really make sense there. They are there probably because they are derived from the same template that drives the output of `rg --version` (which _should_ show the `SIMD` and `AVX` designations).

**Comment by bmwiedemann** [comment]
I tested your fix. Build is now reproducible.
Thanks.
