### ISSUE TITLE
I'm getting "invalid argument" with trying to add new types

### ISSUE THREAD

**Issue by samuelcolvin** [BurntSushi/ripgrep#145]
Best described with terminal output

```shell
> rg --type-add 'jinja:*.{jinja,jinja2}'
Invalid arguments.

Usage: rg [options] -e PATTERN ... [<path> ...]
       rg [options] <pattern> [<path> ...]
       rg [options] --files [<path> ...]
       rg [options] --type-list
       rg [options] --help
       rg [options] --version
> echo $?
1
> rg --version
0.2.1
```

However `--type-add` works fine with combined with a search, eg. `rg --type-add 'jinja:*.{jinja,jinja2}'  -tjinja foobar`, but that doesn't add the type to the global list and has to be used on every search.

OS: ubuntu 16.04, kernel `4.4.0-36-generic`.

**Comment by BurntSushi** [comment]
> but that doesn't add the type to the global list and has to be used on every search.

There is no global list or persistent configuration that `ripgrep` writes. I would very much appreciate it if you could tell me where the docs have led you astray. :-( How can I fix them?

**Comment by samuelcolvin** [comment]
Docs are clear now I look more properly, just me being dumb.

Would you accept a pull request to add jinja files to the types?

**Comment by BurntSushi** [comment]
@samuelcolvin Absolutely. Thanks. :-)
