### ISSUE TITLE
suggestion: simplify options

### ISSUE THREAD

**Issue by dicktyr** [BurntSushi/ripgrep#1450]
it would be useful if options `-l` and `-v` worked together
to be effectively identical to `--files-without-match`
and so redefining `-l`: print file name(s) instead of file content(s)

there's one example
but there may be further opportunity to abstract/simplify/reduce options
hence the generic title

in any case
thank you for sharing your software! :}

**Comment by BurntSushi** [comment]
Thanks for the thoughts, but this isn't quite right and I would rather not leave non-actionable tickets open. `-lv` in particular is _not_ the same as `--files-without-match`. The former shows any file that contains at least one non-matching line, where as the latter shows any file that contains zero matching lines.
