### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by mark-i-m** [BurntSushi/ripgrep#1464]
I hope you don't mind that this is a duplicate issue, but I wanted to say Thank you for this project.

I use rg with the fzf.vim plugin pretty much every day as a code search tool to look for identifiers in the Linux kernel. Its impresive that this is notably faster than the venerable grep. This well-built tool has significantly improved my productivity.

**Comment by BurntSushi** [comment]
@mark-i-m Thanks for the kind words. :-) Much appreciated!
