### ISSUE TITLE
ignores config file on Mac

### ISSUE THREAD

**Issue by jadamsvac** [BurntSushi/ripgrep#1468]
#### What version of ripgrep are you using?

Replace this text with the output of `rg --version`.

#### How did you install ripgrep?

brew, but the same error is there when installed through cargo.

#### What operating system are you using ripgrep on?

Macos Catalina 10.16.2

#### Describe your question, feature request, or bug.

It does not read the config file, as shown by the following two commands.
❯ cat $RIPGREP_CONFIG_PATH                                                                                                                 
--type-add web:*.{html,css,js}*
❯ rg --debug -tweb blah                                                                                                                    
DEBUG|grep_regex::literal|grep-regex/src/literal.rs:59: literal prefixes detected: Literals { lits: [Complete(blah)], limit_size: 250, limit_class: 10 }
unrecognized file type: web

**Comment by BurntSushi** [comment]
This behavior is correct as far as I can tell. Please consult the [guide's section on config file syntax](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file). Namely, you have `--type-add web:.{html,css,js}`, but every line in the config file is a _single_ shell argument. You either need

```
--type-add=web:*.{html,css,js}
```

or

```
--type-add
web:*.{html,css,js}
```

In the future, please also consider using code blocks when showing commands in GitHub issues.
