### ISSUE TITLE
cargo install ripgrep   no longer works

### ISSUE THREAD

**Issue by flip111** [BurntSushi/ripgrep#1471]
In the readme it mentions `cargo install ripgrep` i believe when i ran that command ripgrep was installed in `$HOME/.local` (`bin` directory in there) EDIT: might have been mistaken and it was `$HOME/.cargo/bin`. However now i get this error:

```
error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.
```

How can i compile from source and then install ?

**Comment by flip111** [comment]
My bad, i was just using `cargo install` seems to work when specifying `ripgrep`

**Comment by BurntSushi** [comment]
`cargo install ripgrep` installs ripgrep from crates.io. Running the command shown to you in your error message in a checkout of the ripgrep repo will compile and install from source.
