### ISSUE TITLE
Dead link in Readme

### ISSUE THREAD

**Issue by atouchet** [BurntSushi/ripgrep#1474]
#### Describe your question, feature request, or bug.

In the Readme the link to http://opus.lingfil.uu.se/OpenSubtitles2016/mono/OpenSubtitles2016.raw.en.gz no longer works. I am not sure if the file was moved to a new URL or is no longer available.

**Comment by BurntSushi** [comment]
Drats, okay. I'll either upload my copy of it somewhere or redo the benchmarks with the 2018 data set.

If you want to test on the 2018 English subtitles, then the link for that is: http://opus.nlpl.eu/download.php?f=OpenSubtitles/v2018/mono/OpenSubtitles.raw.en.gz

**Comment by rdp** [comment]
I also noticed the link to "ack has a [bug]"  says it has been fixed or some odd, FWIW... :)

**Comment by BurntSushi** [comment]
That doesn't seem related to this issue. And the link is correct. The bug is wontfix for ack2. The right thing to do here is to update the benchmarks to use ack3.
