### ISSUE TITLE
ripgrep hangs infinitely when ran in Elixir with System.cmd

### ISSUE THREAD

**Issue by zapateo** [BurntSushi/ripgrep#1495]
I have a problem running `rg` from the Elixir programming language.
I cannot understand if the problems is related to Elixir or to ripgrep; I decided to post the issue here because if I change the arguments passed to the `rg` command everything works fine.

#### What version of ripgrep are you using?

```
ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

```
sudo dnf install ripgrep
```

#### What operating system are you using ripgrep on?

Fedora 31 Workstation

#### Describe your question, feature request, or bug.

If I run `rg` using the function [System.cmd](https://hexdocs.pm/elixir/System.html#cmd/3) in the Elixir programming language, the execution of `rg` never ends.

#### If this is a bug, what are the steps to reproduce the behavior?

1. Open the Elixir shell with `iex`
2. Execute `System.cmd("rg", ["mypattern"])`
3. The process never ends.

The problem seems to solve if the PATH is passed as argument to `rg`:

1. Open the Elixir shell with `iex`
2. Execute `System.cmd("rg", ["mypattern", "."])`
3. Elixir prints the output of the command.

#### If this is a bug, what is the actual behavior?

```
$ iex
iex> System.cmd("rg", ["mypattern", "--debug"])
DEBUG|grep_regex::literal|/usr/share/cargo/registry/grep-regex-0.1.4/src/literal.rs:59: literal prefixes detected: Literals { lits: [Complete(mypattern)], limit_size: 250, limit_class: 10 }
                   DEBUG|globset|/usr/share/cargo/registry/globset-0.4.4/src/lib.rs:435: built glob set; 0 literals, 0 basenames, 11 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
```
And then it hangs forever.

#### If this is a bug, what is the expected behavior?

I expected `rg` to show the same result I would get if I have explicitly passed the PATH, as it does with the shell, not to hang infinitely.

**Comment by BurntSushi** [comment]
ripgrep attempts to read stdin if no path arguments are given and it cannot detect if it's on a tty. So yes, please provide a path to ripgrep to eliminate the need for ripgrep to guess.

**Comment by zapateo** [comment]
Perfect, thanks for your reply.
