### ISSUE TITLE
"(Yes, ack has a bug.)" appears to be outdated

### ISSUE THREAD

**Issue by matkoniecz** [BurntSushi/ripgrep#1506]
https://github.com/BurntSushi/ripgrep#quick-examples-comparing-tools has "(Yes, ack has a bug.)" linking to https://github.com/beyondgrep/ack2/issues/445 and https://github.com/beyondgrep/ack2/issues/14

Both are closed. So either ack fixed this bug or wontfixed it. It probably should be rerun and updated to either to not list ack as buggy or to mention that ack is buggy and it was kept as "feature"

**Comment by matkoniecz** [comment]
I now found https://github.com/BurntSushi/ripgrep/issues/1474#issuecomment-582532579 so "has a bug" is true and will be true forever.

Though maybe it is worth clarifying.

**Comment by BurntSushi** [comment]
I think my stance is still the same here. At some point, I will redo the benchmarks and upgrade to ack3.
