### ISSUE TITLE
Enroll in GitHub Sponsors

### ISSUE THREAD

**Issue by bbkane** [BurntSushi/ripgrep#1507]
I use `ripgrep` a lot- I'd like to do the little dollar a month sponsor thingie and I bet other people do too. Consider enrolling in https://github.com/sponsors .

**Comment by BurntSushi** [comment]
I'm appreciative that you would want to donate, but it's not a good fit for me. This is addressed in the FAQ: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#donations
