### ISSUE TITLE
globset: Access violation when built with lto = "thin" on Windows

### ISSUE THREAD

**Issue by forbjok** [BurntSushi/ripgrep#1508]
Version: globset v0.4.4
OS: Windows 10 Pro x64 v1909

Calling globset.is_match(...) causes the program to crash with an access violation if built with `lto = "thin"` under certain circumstances.

The circumstances being (as far as I can tell):
* OS = Windows (tested on Arch Linux and could not reproduce it there)
* Target = x86_64-pc-windows-msvc (I haven't tested every other target, but it does not happen with i686-pc-windows-msvc)

I don't know if this is actually an error in globset, or if it's some obscure compiler error that just happens to be triggered by globset.

It happens both with stable and nightly Rust.

Error message:
![ConEmu64_WJEnWXAnNJ](https://user-images.githubusercontent.com/4687674/75930152-4f6c4600-5e72-11ea-92ec-4750f271240d.png)

Minimal reproduction project:
[lto-thin-repro.zip](https://github.com/BurntSushi/ripgrep/files/4289999/lto-thin-repro.zip)

**Comment by BurntSushi** [comment]
Thanks for the bug report, but yeah, this doesn't look like it belongs here. This looks more like a compiler bug I guess? You might want to file it on rust-lang/rust, although this might be hard to diagnose without a smaller reproduction (i.e., that doesn't use a fairly big crate like globset).

**Comment by lespea** [comment]
Do you have ryzen by chance?  https://github.com/rust-lang/rust/issues/63959

Should be fixed on stable soon.

**Comment by forbjok** [comment]
> Do you have ryzen by chance? [rust-lang/rust#63959](https://github.com/rust-lang/rust/issues/63959)
> 
> Should be fixed on stable soon.

Nope, it's an Intel Core i9-9900K CPU on Intel Z390 chipset.

**Comment by lespea** [comment]
Interesting.  Does it panic on nightly as well?

**Comment by forbjok** [comment]
Yep, same error in both stable and nightly. I also tested on an older machine (Intel Core i7-6700, Intel Z170 chipset), and I get it there as well.

**Comment by forbjok** [comment]
I remembered I had configured cargo to use the LLVM linker, because it's faster. Turns out the problem is also restricted to the LLVM linker, but still only the 64-bit target.
Seems pretty likely that it's actually an LLVM linker bug.
