### ISSUE TITLE
Adding file types in Windows

### ISSUE THREAD

**Issue by theamazingfedex** [BurntSushi/ripgrep#151]
I'm running ripgrep v0.1.17, on Windows 7 in Cmder console emulator, and every time that I try to add a custom file type, i get the error `Invalid arguments.` despite precisely following the example.

What i'm calling: `rg --type-add spark:*.spark`
I even tried doing exactly as the example showed: `rg --type-add html:*.html` but still get the same error.

Is there something I'm doing wrong somewhere?

On a separate note, great job on the tool; I've been making co-worker's jaw's drop at how fast it rips through our company repos and finds what I need. :+1: (plus it's rust, so I get to show people an awesome practical use of rust) :+1: :+1: :+1:

**Comment by BurntSushi** [comment]
@theamazingfedex Thanks for the kind words. :-)

> I even tried doing exactly as the example showed

Could you show me where you saw this example? I ask because it's wrong. I thought I fixed all of them, but I must have left one lingering somewhere.

In any case, you can't just run `rg --type-add'html:*.html'`. `rg` doesn't persist your type settings anywhere. You need to pass `--type-add` to every call to `rg`. While this seems like a pain, my intention was for folks to configure their types using aliases. (Is that even a thing on Windows? In bash I can do, `alias rg="rg --type-add 'foo:*.foo'` and then `rg -tfoo PAT` does the right thing.

**Comment by kaushalmodi** [comment]
@BurntSushi This confusion that `--type-add` stores the type association in some file has come up multiple times in these issues. I thought the same when I used `ripgrep` the first time too. 

But that `alias` example for `--type-add` is perfect. May be you can add that to the `--help` and man page?

**Comment by BurntSushi** [comment]
@kaushalmodi Right, believe me, I realize this has been a pain point. :-) I will do another pass through everything that mentions `--type-add` and try to be extra clear about it.

**Comment by theamazingfedex** [comment]
I'm using Cmder, which uses clink around cmd.exe in a ConEmu window, so I do have a way of doing aliased commands. Here's some pictures:

**results of trying `--type-add html:*.html`:**
![Results of using the command](https://cloud.githubusercontent.com/assets/6488706/19197055/317b2a62-8c75-11e6-99b0-c665fffaf86f.png)

**`rg --help` (where I saw the example)**
![rg --help](https://cloud.githubusercontent.com/assets/6488706/19197117/7d97f510-8c75-11e6-9a94-762e973f24db.png)

**And if I try to do it as a one-off:**
![image](https://cloud.githubusercontent.com/assets/6488706/19197346/93cc01c2-8c76-11e6-9f8e-3e6112ecd5bf.png)

Also, I created an alias for `rg=rg --type-add 'spark:*.spark'` then tried `rg -tspark foo` and get the message: `unrecognized file type: spark`

**Comment by BurntSushi** [comment]
Could you please provide a reproduction that doesn't use an alias? I can run `rg --type-add 'spark:*.spark' -tspark foo` just fine, which to me suggests that your alias isn't working.

**Comment by theamazingfedex** [comment]
I just tried running the command `rg --type-add spark:*.spark -tspark foo` in git bash, and it worked, but running it in cmd does not, as displayed in the third screenshot of my previous comment.

**Comment by theamazingfedex** [comment]
Well well, I just updated to v0.2.1, and ran `rg --type-add spark:*.spark -tspark foo` and it worked wonderfully. Not sure what changed, but it works now, thanks!

**Comment by theamazingfedex** [comment]
Is there a blog post somewhere detailing the reasoning behind choosing to push for an alias approach vs a config-based approach for adding file types?

**Comment by BurntSushi** [comment]
No. Config files are extra complexity that I would like to avoid if
possible. I am open to adding one in the future, but I would like to hold
off for now.

I would also encourage anyone to upstream their file types if they are
types that others might use.

**Comment by theamazingfedex** [comment]
Alright, that's fair. Forgive my ignorance, but how would I upstream a file type?

**Comment by BurntSushi** [comment]
Submit a PR. There are lots of previously merged PRs that do just that, and
they would be good examples.

Sorry for the short response. On mobile. If you need more help, let me know
and I'll try to give more of an explanation when i get a chance.

**Comment by theamazingfedex** [comment]
Oh okay, I had a suspicion that was what you were implying, but I had not personally heard that terminology used for PR's, and wanted to be sure ^_^. I've got a couple types that would be widely useful; I'll make individual PR's for each one.

**Comment by theamazingfedex** [comment]
#153 #154 and #155 have been opened against master

**Comment by BurntSushi** [comment]
@theamazingfedex Thank you!
