### ISSUE TITLE
Ripgrep among mixed encoded files

### ISSUE THREAD

**Issue by yk-Du** [BurntSushi/ripgrep#1515]
It seems that rigprep can handle files with the same encoding system only, e.g., `-E gb18030` only grep files encoded with gb18030.

My question is how can I grep the content that I want among files encoding with gb18030 and UTF-8 under one certain directory.

**Comment by BurntSushi** [comment]
You can't. Or at least, I don't see any simple UX to enable such behavior. Sorry.
