### ISSUE TITLE
Missing some assets on release page

### ISSUE THREAD

**Issue by dikiaap** [BurntSushi/ripgrep#1519]
Hello, I'm using the binary of rg from ripgrep-v$-i686-unknown-linux-musl.tar.gz. In the [v12.0 release page](https://github.com/BurntSushi/ripgrep/releases/tag/12.0.0), the assets isn't complete as in [v11](https://github.com/BurntSushi/ripgrep/releases/tag/11.0.2).
It doesn't have ripgrep-12.0.0-i686-pc-windows-gnu.zip and ripgrep-12.0.0-i686-unknown-linux-musl.tar.gz.

**Comment by BurntSushi** [comment]
Yup, I'm not providing those any more. Please compile them yourself.
