### ISSUE TITLE
Can't escape '$' in --replace text

### ISSUE THREAD

**Issue by linuskr** [BurntSushi/ripgrep#1524]
#### What version of ripgrep are you using?
ripgrep 12.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### What operating system are you using ripgrep on?

Windows 10

#### Describe your question, feature request, or bug.

When using ripgrep's --replace option, '$' can't be used in the replacement text, because it is interpreted as the name of a capture group and cannot be escaped:  
`rg -iIN 'test([^:_$])' -r '$replacement_text$$1'` outputs `$1` instead of e.g. `$replacement_text$!`

Trying to escape the '$' does not work either:  
`rg -iIN 'test([^:_$])' -r '\$replacement_text\$$1'` yields `\\$1` instead.

**Comment by BurntSushi** [comment]
It can be escaped. Use `$$` to write a literal `$`. It's documented here: https://docs.rs/regex/1.3.5/regex/struct.Captures.html#method.expand

It should be documented in the help text for the `--replace` flag though, so I'll mark this as a doc bug.

**Comment by linuskr** [comment]
Didn't think about that, thank you for the quick response and ripgrep itself.
