### ISSUE TITLE
[Question] Search for a file that contains a string

### ISSUE THREAD

**Issue by msclp** [BurntSushi/ripgrep#1526]
#### What version of ripgrep are you using?

12.0.0

#### How did you install ripgrep?

with brew

#### What operating system are you using ripgrep on?

macOS 10.15.3

#### Describe your question, feature request, or bug.

How to use `vim`picker` with `ripgrep` to  search a file that contains a specified string

This does not work well
```
nmap <leader>a :call picker#File("rg --column --line-number --no-heading --color=never --smart-case ''", 'edit')<cr>
```

It would be awesome if it would work same as `<Plug>(PickerEdit)`

**Comment by BurntSushi** [comment]
This doesn't look like a ripgrep question to me, sorry. If you have a ripgrep question, then please ask it without respect to other tools. Otherwise, it sounds like you need a support forum for vim or whatever plugin you're using.

**Comment by msclp** [comment]
Sorry, I just noticed I asked here, not in `vim-picker`
