### ISSUE TITLE
show error message ' No such file or directory (os error 2) '

### ISSUE THREAD

**Issue by ryoppippi** [BurntSushi/ripgrep#1527]
#### What version of ripgrep are you using?

ripgrep 12.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

installed with homebrew

#### What operating system are you using ripgrep on?

macOS 10.5
#### Describe your question, feature request, or bug.

When I search files like
```
rg --files --hidden --follow  --glob "!.git/*"        
```
It shows some unknown files like
```
 ./Library/ApplicationSupport/Microsoft Edge/SingletonCookie: No such file or directory (os error 2)  
```
I reinstalled ripgrep but it doesn't solve it
How can I solve this?
Is there any cache on my mac?

**Comment by okdana** [comment]
It's reporting a broken symlink because you used `--follow`. If you just want to disable the error message you can use

```
--no-messages
    Suppress all error messages related to opening and reading files.
    Error messages related to the syntax of the pattern given are still
    shown.
```

**Comment by ryoppippi** [comment]
Great! Thanks, it works!!

P.S.
I'll fix symbolic link...
