### ISSUE TITLE
Installing ripgrep in local directory

### ISSUE THREAD

**Issue by shahid31091** [BurntSushi/ripgrep#1532]
Hi,

I do not have sudo access but I would like to install ripgrep.

Is there a way to install this in the ~/.local directory?

**Comment by BurntSushi** [comment]
```
$ git clone https://github.com/BurntSushi/ripgrep
$ cd ripgrep
$ cargo build --release
$ cp target/release/rg ~/.local/
```

**Comment by shahid31091** [comment]
This does not work for me :(
cargo build --release
zsh: command not found: cargo

**Comment by BurntSushi** [comment]
Please consider [reading the README](https://github.com/BurntSushi/ripgrep#building) before asking questions.
