### ISSUE TITLE
Clarify --ignore-file option short description

### ISSUE THREAD

**Issue by runapp** [BurntSushi/ripgrep#1541]
I've trapped into the same confusion with #684 . Glad to see that the document was enriched, but to me "Specify additional ignore files." and even "Process ignore files case insensitively." for `--ignore-file-case-insensitive` are both not so clear.
I wonder if it'd be better to refer to the file as "ignore rule files"?

**Comment by BurntSushi** [comment]
I'd prefer if these sort of tickets were just submitted as PRs with the desired wording, then we can hash it out from there. Thanks!
