### ISSUE TITLE
Replacing matches inside the originating file

### ISSUE THREAD

**Issue by djc** [BurntSushi/ripgrep#1558]
I semi-regularly use command-line tools to do mass substitutions in my code (whether with Rust or with Python). Perhaps I ought to learn to make better use of the IDE here, but even for non-code things this has been a useful feature.

Currently I usually use something like `find . -name "*.rs" | xargs sed -i '' 's!foo!bar!g'`. However, `sed` seems like a pretty old-school tool and I sometimes find that it's hard to make it do modern regex features.

It would be nice if ripgrep could do --replace -i '' (the argument is used to as a suffix for backed up files, but I almost never use it because stuff is usually under version control anyway).

I realize this might be out of scope a bit since it involves actually rewriting the files rather than just searching through them. Wanted to mention this as a desirable feature (to me) anyway.

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#search-and-replace
