### ISSUE TITLE
The `--ignore-file` flag requires a space instead of equals with `~`

### ISSUE THREAD

**Issue by texastoland** [BurntSushi/ripgrep#1563]
#### What version of ripgrep are you using?

12.0.1

#### How did you install ripgrep?

Homebrew

#### What operating system are you using ripgrep on?

macOS 10.15.4

#### Describe your bug.

`--ignore-file ~/.config/rg/ignore` works but `--ignore-file=~/.config/rg/ignore` produces the error:

`file: No such file or directory (os error 2)`

`fd` which is a dependent produces an identical error CC @sharkdp.

**Comment by sharkdp** [comment]
I can not reproduce this, neither with `rg`, nor with `fd`.

What are the exact commands that you are running? Have you aliases `rg`/`fd` to something else?
```
❯ echo foo > a
❯ echo foo > b
❯ rg foo
b
1:foo

a
1:foo
❯ echo b > file
❯ rg foo --ignore-file=file
a
1:foo
❯ rg foo --ignore-file file
a
1:foo
```

**Comment by texastoland** [comment]
Oh you're right! I'm using `--ignore-file=~/.config/ignore`. It must be `~`? I'll fix my report.

**Comment by sharkdp** [comment]
That is the expected shell behavior:
```
$ echo --ignore-file ~/.something
--ignore-file /home/shark/.something
$ echo --ignore-file=~/.something
--ignore-file=~/.something
```
You would get a similar error if you (single- or double-) quote the `~`.

To my knowledge, it is uncommon for programs to do an additional expansion of `~`.

I tend to avoid `~`, especially in scripts. Use `$HOME` instead.

**Comment by texastoland** [comment]
Thanks for the help! Makes sense to me. I'll close unless @BurntSushi reopens it.

**Comment by okdana** [comment]
If you're using zsh (the default on macOS now), you can enable the `MAGIC_EQUAL_SUBST` option to make it work the way you expected:

```
% echo --ignore-file=~/.config/rg/ignore
--ignore-file=~/.config/rg/ignore
% setopt magic_equal_subst
% echo --ignore-file=~/.config/rg/ignore
--ignore-file=/Users/dana/.config/rg/ignore
```

Obviously you'll need to quote/escape when you don't want it to expand, same as with parameter assignments. The effect is explained in the [manual](http://zsh.sourceforge.net/Doc/Release/Options.html)
