### ISSUE TITLE
Request: Add type for meson

### ISSUE THREAD

**Issue by gerion0** [BurntSushi/ripgrep#1586]
Programs build with [Meson](https://mesonbuild.com/) rely on specific build files that are always called `meson.build`. Maybe you also want to include `meson_options.txt` for [meson specific options](https://mesonbuild.com/Build-options.html). Please add a type to only search this files.

**Comment by BurntSushi** [comment]
For file type additions, please just submit PRs. I otherwise don't track them as independent requests.
