### ISSUE TITLE
SIGINT handling doesn't reset tty color

### ISSUE THREAD

**Issue by rorytm** [BurntSushi/ripgrep#1597]
#### What version of ripgrep are you using?

ripgrep 12.1.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

pacman

#### What operating system are you using ripgrep on?

Linux / Arch / 5.6.14-1-ck-skylake

#### Describe your bug.
When the process closes via sigint (ctrl + c), ripgrep doesn't revert the tty color before exiting.

#### What are the steps to reproduce the behavior?

Interrupt the process while it's printing a colored character.
```
rg . /
```
`ctrl + c`

#### What is the actual behavior?
tty continues printing in the most recent color that ripgrep was using

#### What is the expected behavior?
tty should go back to the primary color

What do you think ripgrep should have done?
ripgrep should go back to the primary color before exiting after receiving sigint

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#stop-ripgrep
