### ISSUE TITLE
rg "-1"

### ISSUE THREAD

**Issue by GopherJ** [BurntSushi/ripgrep#1604]
#### What version of ripgrep are you using?

Replace this text with the output of `rg --version`.

#### How did you install ripgrep?

If you installed ripgrep with snap and are getting strange file permission or
file not found errors, then please do not file a bug. Instead, use one of the
Github binary releases.

#### What operating system are you using ripgrep on?

Replace this text with your operating system and version.

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

If possible, please include both your search patterns and the corpus on which
you are searching. Unless the bug is very obvious, then it is unlikely that it
will be fixed if the ripgrep maintainers cannot reproduce it.

If the corpus is too big and you cannot decrease its size, file the bug anyway
and the ripgrep maintainers will help figure out next steps.

#### What is the actual behavior?

Show the command you ran and the actual output. Include the `--debug` flag in
your invocation of ripgrep.

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

What do you think ripgrep should have done?

**Comment by GopherJ** [comment]
ripgrep seems don't handle `""` correctly like other tools. Things inside `""` shouldn't be treat as command arguments

**Comment by GopherJ** [comment]
```
➜  client git:(master) ✗ rg "-1"
error: Found argument '-1' which wasn't expected, or isn't valid in this context

USAGE:
    
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN

For more information try --help

```

**Comment by GopherJ** [comment]
```
➜  client git:(master) ✗ rg --version
ripgrep 11.0.1 (rev 1f1cd9b467)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

```

**Comment by BurntSushi** [comment]
From the man page:

> A regular expression used for searching. To match a pattern beginning with a dash, use the -e/--regexp option.

In the future, please be more careful and fill out the issue template.
