### ISSUE TITLE
AIX support

### ISSUE THREAD

**Issue by scottismyname** [BurntSushi/ripgrep#1631]
I know this is probably a long shot, but my work uses AIX. I don't have permission to install code on our machine, but was wondering if I could somehow get a binary I could run directly.

**Comment by BurntSushi** [comment]
Unfortunately, I don't know anything about AIX and I'm not inclined to add more targets to the CI matrix unless it's really well motivated.

Your best bet would be to use [cross](https://github.com/rust-embedded/cross), although I [don't see AIX on its list of supported targets](https://github.com/rust-embedded/cross#supported-targets).

I don't see it on [rustc's supported target list either](https://forge.rust-lang.org/release/platform-support.html).

Googling for "llvm AIX support" yields this: https://lists.llvm.org/pipermail/llvm-dev/2019-February/130175.html

So I'd say you're out of luck for now.
