### ISSUE TITLE
Line number is not printed when output is piped to GNU sort

### ISSUE THREAD

**Issue by anishmittal2020** [BurntSushi/ripgrep#1632]
#### What version of ripgrep are you using?

```
$ rg --version
ripgrep 12.0.1
```

```
$ sort --version
sort (GNU coreutils) 8.30
```

#### How did you install ripgrep?
linuxbrew

#### What operating system are you using ripgrep on?

Ubuntu 20.04

#### Describe your bug.

Line number is not printed when output is piped to GNU sort.  Thus GNU Sort is not able to sort as per line number!

> Note: I am not using `--sort-file` inbuilt option of ripgrep.

#### What are the steps to reproduce the behavior?

```
$ grep --with-filename --line-number 'ripgrep' *.md | sort
ImprovedAlternateUtilities.md:21:| grep             | [BurntSushi/ripgrep][], [beyondgrep/ack3][]                   
ImprovedAlternateUtilities.md:55:  [BurntSushi/ripgrep]: https://github.com/BurntSushi/ripgrep
```

```
$ rg -t md 'ripgrep' | sort
ImprovedAlternateUtilities.md:  [BurntSushi/ripgrep]: https://github.com/BurntSushi/ripgrep
ImprovedAlternateUtilities.md:| grep             | [BurntSushi/ripgrep][], [beyondgrep/ack3][]        
```

```
$ rg -t md 'ripgrep' 
ImprovedAlternateUtilities.md
21:| grep             | [BurntSushi/ripgrep][], [beyondgrep/ack3][]          
55:  [BurntSushi/ripgrep]: https://github.com/BurntSushi/ripgrep
```

#### What is the expected behavior?

```
$ rg -t md 'ripgrep' | sort
ImprovedAlternateUtilities.md:21:| grep             | [BurntSushi/ripgrep][], [beyondgrep/ack3][]        
ImprovedAlternateUtilities.md:55:  [BurntSushi/ripgrep]: https://github.com/BurntSushi/ripgrep
```

Note that the sorting order is correct as it is sorted by line number!

**Comment by BurntSushi** [comment]
Yes, this is correct. Pass `-n/--line-number` just like you would with grep. Aa you can see in your examples, ripgrep changes its output format depending on whether it's printing to a tty or not.
