### ISSUE TITLE
High memory consumption on MacOS from Visual Studio

### ISSUE THREAD

**Issue by madhavajay** [BurntSushi/ripgrep#1640]
#### What version of ripgrep are you using?
```
./rg --version
ripgrep 11.0.1 (rev 973de50c9e)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

This is part of a plugin in vscode im not sure if its bundled with the main app or a plugin.

#### What operating system are you using ripgrep on?
macOS Catalina 10.15.4 (19E266)

#### Describe your bug.
See images:
https://imgur.com/a/5nHcyoe

System ground to a halt when vscode was doing something.

#### What are the steps to reproduce the behavior?

I dont know, I was checking my installed extensions and looking at my settings.json as I am migrating to a new macbook.
I don't remember doing anything except maybe typing a search term in the Extensions input box.

#### What is the actual behavior?

All I can see is that the process was using 30gb of memory and my system nearly froze, its a 6-core 2018 MBP with 16gb of ram.

#### What is the expected behavior?

Is it possible to throttle / prevent ripgrep from consuming too much memory by limiting how much it takes in at a time?

**Comment by BurntSushi** [comment]
This isn't actionable without a command line reproduction on a particular corpus that I can access. Sorry.

**Comment by madhavajay** [comment]
I have linked this from the vscode-ripgrep repo:
https://github.com/microsoft/vscode-ripgrep/issues/11
