### ISSUE TITLE
Incorrect line numbering when using multiline and replacing by noncontiguous capture groups

### ISSUE THREAD

**Issue by afsmi** [BurntSushi/ripgrep#1655]
#### What version of ripgrep are you using?
ripgrep 12.1.1
-SIMD -AVX (compiled)
+SIMD -AVX (runtime)

#### How did you install ripgrep?

`pacman -S ripgrep`
(package version 12.1.1-1 from [community] repo)

#### What operating system are you using ripgrep on?

Arch Linux x86-64 5.7.4

#### Describe your bug.

When using -r with noncontiguous capture groups together with --multiline and -n, the output line numbers are reported incorrectly.

#### What are the steps to reproduce the behavior?

run the following command:
`seq 5 | rg -n --multiline -r '$1$3' '^(2)$(\n^.$)+(\n^5)'`

#### What is the actual behavior?

`seq 5 | rg -n --multiline -r '$1$3' '^(2)$(\n^.$)+(\n^5)'`

gives

```
2:2
3:5
```

#### What is the expected behavior?

output should be one of

```
2:2
4:5
```
```
2:2
5:5
```
```
2:2
4:
5:5
```
depending on the desired semantics (which line should each character in the capture group `(\n^5)` be associated with?)

**Comment by BurntSushi** [comment]
This looks correct to me. Or at least, as correct as one might expect. Line numbers and multi-line replacements don't really make a whole lot of sense. The replacement could insert an arbitrary number of new lines or remove an arbitrary number of new lines, and so creating a "correct" mapping seems impossible to me because it's not clear what "correct" would be. Here is perhaps a simpler example:

```
$ seq 8 | rg -n --multiline '(?s)(2).+(\n5)' -r '$1$2'
2:2
3:5
```

Or even:

```
$ seq 8 | rg -n --multiline '(?s)(2).+(\n5)|(7)' -r '$1$2$3'
2:2
3:5
7:7
```

And things get even whackier when the replacement string contains new lines itself:

```
$ seq 8 | rg -n --multiline '(?s)(2).+(\n5)|(7)' -r '$1$2





$3'
2:2
3:5
4:
5:
6:
7:
8:
9:
7:
8:
9:
10:
11:
12:
13:7
```

What exactly should the correct output be here? I don't know. If you count the new lines in the original text as I think you want, then that falls over in the above example because the replacement will throw off the count. (You'd wind up with a non-increasing sequence of line numbers.) ripgrep counts new lines in this sort of case by simply starting from the number of the line in which the match starts and then incrementing the line number for each subsequent line that is _written_ for that particular match.

I'm pretty sure this is probably a `wontfix` bug. I could potentially be swayed to some other sort of behavior if a compelling use case were presented though.

**Comment by afsmi** [comment]
### Use case
My goal is to inline a range of lines that follow a marker into mentions of that marker, across an entire file hierarchy, using a unix command pipeline.

In my approach, I want to use `rg` and some other commands to generate a list of identifier -> line range associations.

I need the start and end line numbers of the range

### Further details
I'm using this on files containing an uncommon serialization format that represents GUI objects hierarchically, but I'll use some toy examples to illustrate.

My approach using `rg`,`cut`,`paste`, and `join`  might generate lines like
```
FileA.txt:34:MMM:FileB.txt:1000:1005:2200
FileA.txt:35:NNN:FileB.txt:302:400:440
```

where the fields are
`<inline-destination-file>:<common match>:<inline-source-file>:<source-match-line>:<range-start-line>:<range-end-line>`

and where FileA.txt and FileB.txt might look like
```
  FileA.txt   line#     |   FileB.txt           line#
  ---------   -----     |   ---------           -----
  ...                   |   SectionNNN{           302
  var MMM;       34     |   ...     
  var NNN;       35     |     start_match         400
  ...                   |   ...
                        |     end_match           440
                        |   ...
                        |   }
                        |   ...
                        |   SectionMMM{          1000
                        |   ...
                        |     start_match        1005
                        |   ...
                        |     end_match          2200
                        |   ...
                        |   }
                        |   ...
```

I think this illustrates that this could be quite useful for summarizing salient portions of hierarchical data, giving both line ranges and nesting information from one command while using fancy pcre2 lookaround criteria to include/exclude ranges in delimited contexts

### A more concrete  (but still contrived) example
`seq -f "%04g" 0 9999 | sed 'y/0123456789/abcdefghij/' > data.txt`
This fills `data.txt` with the sequence of all strings of length 4 over the characters `{abcdefghij}` in lexicographic ordering.

Now to each match of the form `XYaa` (here X and Y match any word character), I want to associate the first range of lines starting/ending at `XYXY`/ `XYYX`, which is encountered after `XYaa`
```
  rg -e '(?sxx: ((\w)([^a])aa\n) .*? (\2\3\2\3\n) .*? (\2\3\3\2\n) )'\
  -r '@@$1$2' --pcre2 -I -n --multiline\
| tail -n 15

output:
6801:@@giaa
6802:gigi
6803:giig
6901:@@gjaa
6902:gjgj
6903:gjjg
7801:@@hiaa
7802:hihi
7803:hiih
7901:@@hjaa
7902:hjhj
7903:hjjh
8901:@@ijaa
8902:ijij
8903:ijji
```
The original line numbers are lost here.

an easy way to get the correct line numbers (but ostensibly slower when working on many large files with many matches) is to use two passes, where the first does the numbering
```
  rg -e '.*' -I -n \
| rg -r '@@$1$4$5' -e '(?sxx: (^\N+?(\w)([^a])aa\n) .*? (^\N+?\2\3\2\3\n) .*? (^\N+?\2\3\3\2\n) )' --pcre2 --multiline\
| tail -n 15

output:
@@6801:giaa
6869:gigi
6887:giig
@@6901:gjaa
6970:gjgj
6997:gjjg
@@7801:hiaa
7879:hihi
7888:hiih
@@7901:hjaa
7980:hjhj
7998:hjjh
@@8901:ijaa
8990:ijij
8999:ijji

```

### Alternative solution: a separate feature
I can imagine different features that would fit my use case.
Of those, the one I personally find most pleasing would be to provide the user a means to print only the line number of the first character that a given capture group captures.

Then I could do something like `rg ... -r ':$@2:$2'`, without `-n`, where `$@2` gives the first line number for the first character of capture group 2.

Regarding earlier comments' examples, it would then be very clear what the output is supposed to be

**Comment by BurntSushi** [comment]
Thank you for elaborating. I really appreciate it. Unfortunately, I'm not convinced that your use case is really compelling enough to convince me to change how line numbers are handled in cases like this. To be honest, I think you would be better served by writing a dedicated tool to do what you want. That's probably what I would do anyway.

ripgrep provides just the barest replacement support, and I will continue to resist adding features that enhance the replacement syntax. There are other tools more suited to that task.
