### ISSUE TITLE
Default for -j is not clear

### ISSUE THREAD

**Issue by durka** [BurntSushi/ripgrep#167]
`rg --help` says this:

```
    -j, --threads ARG
        The number of threads to use. Defaults to the number of logical CPUs
        (capped at 6). [default: 0]
```

I have four cores here. Given this documentation I have no idea what the default parallelishness is :)

**Comment by BurntSushi** [comment]
I guess it's confusing because of `[default: 0]`?

I guess it should say, "`0` means use the number of logical CPUs, capped at 6."

**Comment by durka** [comment]
That would be much more clear!

**Comment by durka** [comment]
I can make a PR. Are the man pages auto generated somehow or should I make the same edits there?

**Comment by BurntSushi** [comment]
@durka Thanks! They aren't auto-generated unfortunately. You'll need to edit both `src/args.rs` and `docs/rg.1.md`, and then run `cd doc && ./convert-to-man`.
