### ISSUE TITLE
[FR] Have `--read0` that reads the input records separated by null

### ISSUE THREAD

**Issue by NightMachinary** [BurntSushi/ripgrep#1689]
Sometimes, the records we want to filter have newlines in them, so we can't use the newline as input record separator. Having `--read0` would solve this problem:

```
echo 123$'\0'456$'\0'789 | rg --read0 56
# => 456
```

**Comment by BurntSushi** [comment]
Why doesn't `--null-data` work for you?

**Comment by NightMachinary** [comment]
[**@BurntSushi**](https://github.com/BurntSushi) commented on [Sep 26, 2020, 5:11 PM GMT+3:30](https://github.com/BurntSushi/ripgrep/issues/1689#issuecomment-699497163 "2020-09-26T13:41:14Z - Replied by Github Reply Comments"):
> Why doesn't `--null-data` work for you?

Sorry, I mistakenly read that as being equivalent to `--print0`. Thanks!

**Comment by BurntSushi** [comment]
Aye, and note that `--null-data` can also be found in GNU grep.
