### ISSUE TITLE
Short Alias for --no-ignore

### ISSUE THREAD

**Issue by sproxet** [BurntSushi/ripgrep#1703]
`--no-ignore` is, in my experience, one of the most common flags one would want to pass to ripgrep, but unfortunately it doesn't have a single character alias for its option. Obviously you can just add it by creating an alias under a different name, but it's annoying to do that on every system. It would be great if ripgrep supported such an option out of the box.

**Comment by okdana** [comment]
`-u` is basically the short option for `--no-ignore`. It's documented separately because it behaves differently when used more than once, but `-u` by itself is the same as `--no-ignore`

**Comment by BurntSushi** [comment]
Aye, yeah, the short flag for `--no-ignore` is `-u`. And in particular, `-u` can be used repeatedly to progressively disabled smart filtering. `-u` disables ignore file filtering. `-uu` disables hidden file filtering. And `-uuu` disables binary file filtering.

The docs for `--no-ignore` should definitely mention the `-u` flag here.
