### ISSUE TITLE
Support Handlebars files

### ISSUE THREAD

**Issue by alexlafroscia** [BurntSushi/ripgrep#171]
[Handlebars](http://handlebarsjs.com/) (also used in Ember.js for templating) files end in `hbs`, which is something not currently supported.  I'll try to make a PR for this myself, but figured I would make an issue first!

**Comment by BurntSushi** [comment]
Sounds good to me! Since "handlebars" is quite long, I'd probably make the
type name "hbs" (unless there is some other better suited initialism).

**Comment by alexlafroscia** [comment]
@BurntSushi Sounds good; PR made, with `hbs` as the name
