### ISSUE TITLE
idea: mark matches with tags

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [BurntSushi/ripgrep#1725]
#### Describe your feature request

Right now ripgrep has a `--colors=COLORS, --colours=COLORS` parameter to let the user mark different parts of the matches with different colors. However, this is only useful in a console environment. When the result of ripgrep was redirected to a file, all colors will disappear. If there are options like `--tag-start` and `--tag-end` to let the user mark the matches, it will improve the usability of the program. If we have `--tag-start` and `--tag-end` options, we can use `rg --tag-start "<div>" --tag-end "</div>" example test.txt` to get results like `<div>example</div>`.

**Comment by BurntSushi** [comment]
Use the `-r/--replace` flag.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks! I missed this option and it work well.
