### ISSUE TITLE
allow specifying files to search from via stdin, eg: `find / | rg pattern --stdin`

### ISSUE THREAD

**Issue by timotheecour** [BurntSushi/ripgrep#1727]
#### Describe your feature request

I'd like to allow searching for a pattern in files specified via stdin, eg: `find / | rg pattern --stdin`
note that `find / | rg pattern -` is different, as it treats stdin as a file and searches for a pattern there.

The motivation is it allows separation of concerns, eg using some program to specify which files you're interested in searching from, and then asking ripgrep to search for content among those.

**Comment by BurntSushi** [comment]
You can do this with xargs: `find / -print0 | xargs -0 rg pattern`.

See also #273. Which I've just re-opened.
