### ISSUE TITLE
Parallel Command Execution (as in fd)

### ISSUE THREAD

**Issue by dharrigan** [BurntSushi/ripgrep#1731]
Hi,

A feature I personally find incredibly useful in [fd](https://github.com/sharkdp/fd), is the ability for it to pass the results of the run individually, or in batch, to an external program using parallel command execution, using these switches:

```
    -x, --exec <cmd>                   Execute a command for each search result
    -X, --exec-batch <cmd>             Execute a command with all search results at once
```

More details can be found here about fd's [parallel command execution](https://github.com/sharkdp/fd#parallel-command-execution).

Whilst a similar thing can be achieved by doing this already in rg (for example): 

```
vim `rg -l text`
```

It's a bit cumbersome and is only working in batch. It would be great if rg had a similar mechanism as in fd, i.e.,

`rg text -X vim {}` (for batch)

Thank you.

-=david=-

**Comment by BurntSushi** [comment]
I'd rather folks relied on their shell to do this. And if you don't want batch mode, you can use `xargs -n1` to execute a command for each argument.
