### ISSUE TITLE
Dead AppVeyor links in crate Readmes

### ISSUE THREAD

**Issue by atouchet** [BurntSushi/ripgrep#1732]
#### Describe your bug.

The Readmes for various crates in this repo contain links to AppVeyor that no longer work.

Ex: https://github.com/BurntSushi/ripgrep/blob/master/crates/cli/README.md

links to https://ci.appveyor.com/project/BurntSushi/ripgrep which says "Project not found or access denied."

Should these be edited or removed?

**Comment by BurntSushi** [comment]
I switched to GitHub Actions a while ago. It replaces both AppVeyor and Travis CI.

It should just link to the same CI pages as the main ripgrep README. I've updated them. Thanks for the report!
