### ISSUE TITLE
subrepository search

### ISSUE THREAD

**Issue by androm3da** [BurntSushi/ripgrep#174]
AFAICT `rg` stops recursing at subrepo boundaries.  I don't prefer this behavior by default -- besides, `rg` is so fast that I can afford searching in potentially unrelated repos :)

If it makes sense as a default, it'd be nice if I could add a command line arg or `.rgconfig` option to change this behavior.

**Comment by BurntSushi** [comment]
What is a "subrepo boundary"? Could you provide a small reproducible example with `mkdir` and `git init` calls?

You may want to check whether your subrepos are in your `.gitignore` file. If they are, `rg` will respect them and ignore them. If this behavior is undesirable, you can drop a `.ignore` file in the same directory and whitelist the paths you want to search, e.g., `!subrepo`.

**Comment by androm3da** [comment]
tsk, sorry, indeed the project is configured with `ignore` for those subrepos.  Whoops!  Carry on.
