### ISSUE TITLE
Support searching through git history

### ISSUE THREAD

**Issue by Jab2870** [BurntSushi/ripgrep#1745]
Currently, to search through the history of a git repository, you need to do something like

```
git log -S 'search term'
```

This technically searches through diffs. However, it would be very nice to be able to use rg with its speed and pretty output to accomplish the same.

Is this something you'd consider implementing?

Obviously this feature request could be extended to support other version control systems although I am only familier with git.

**Comment by krobelus** [comment]
You can already do that by piping Git commands into `rg`. A tighter integration seems out of scope.

**Comment by BurntSushi** [comment]
Definitely way out of scope. Use shell pipelines.

This is also the kind of feature that begets more features. Which makes it very unlikely that I'll change my mind.

**Comment by Jab2870** [comment]
No worries, thanks for replying anyway. :+1:

**Comment by venkatd** [comment]
Is there a recommended series of pipelines that would allow me to use ripgrep to search all the contents of the git history? If so, I would be happy to submit a PR to the user guide.
