### ISSUE TITLE
Support fixed string search (-F) for pattern files (-f)

### ISSUE THREAD

**Issue by jonashaag** [BurntSushi/ripgrep#1750]
#### Describe your feature request

I want to search for lots of patterns from a pattern file in another file with lots of lines. Here, lots = 50k.

So, what I want is a faster version of `grep -f needles haystack`.

I think currently `-F` is ignored when using `-f`, causing ripgrep to crash because it tries to create a giant regex from 50k patterns.

**Comment by BurntSushi** [comment]
> causing ripgrep to crash

This sounds like a bug report to me. Please file a new issue and fill out the bug report template.
