### ISSUE TITLE
Shader file extensions for --type-list

### ISSUE THREAD

**Issue by gheshu** [BurntSushi/ripgrep#1752]
Hi,

It would be great to have some shader languages added to the --type-list:
hlsl: *.hlsl, *.fx, *.fxh
glsl: *.glsl, *.vert, *.frag, *.comp, *.geom

Thank you

**Comment by BurntSushi** [comment]
Please submit a PR. I don't track file types in issues. They are too numerous. It's easier to just propose them via a patch.
