### ISSUE TITLE
type asp seems to have an error

### ISSUE THREAD

**Issue by NetMage** [BurntSushi/ripgrep#1768]
#### What version of ripgrep are you using?

ripgrep 12.1.1 (rev 7cb211378a)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

Using Scoop

#### What operating system are you using ripgrep on?

Windows 10 v1909

#### Describe your bug.

In the output of  rg --type-list, the file listing for asp has a duplicate *.aspx.cs - was the second one intended to be *.aspx.vb?

#### What are the steps to reproduce the behavior?

rg --type-list

#### What is the actual behavior?
...
```
asp: *.ascx, *.ascx.cs, *.ascx.vb, *.aspx, *.aspx.cs, *.aspx.cs
```
...

#### What is the expected behavior?

```
asp: *.ascx, *.ascx.cs, *.ascx.vb, *.aspx, *.aspx.cs, *.aspx.vb
```

**Comment by BurntSushi** [comment]
I don't use ASP. I rely on contributors to maintain the file type list. If there's an error, please submit a PR with links to any relevant supporting material. Thanks.

**Comment by NetMage** [comment]
Really, two duplicate entries aren't enough indication there is an error?

**Comment by BurntSushi** [comment]
Please file a PR.
