### ISSUE TITLE
--vimgrep reports incorrect column number

### ISSUE THREAD

**Issue by latortuga** [BurntSushi/ripgrep#18]
The column reported is off-by-one. You can see this here:

https://github.com/BurntSushi/ripgrep/blob/master/tests/tests.rs#L577

The W in "Watsons" is column 16, vim starts column counting with 1.

**Comment by BurntSushi** [comment]
And also, rg claims they are 1-based indexed:

```
    --column
        Show column numbers (1 based) in output. This only shows the column
        numbers for the first match on each line. Note that this doesn't try
        to account for Unicode. One byte is equal to one column.
```

**Comment by BurntSushi** [comment]
All set. It should be fixed in the next release. I'm going to try to knock off a few bugs before cutting one.

**Comment by latortuga** [comment]
Cool, thanks! Any chance of getting a linux build on the next release too? I noticed there isn't one for 0.1.17...

**Comment by BurntSushi** [comment]
@latortuga Absolutely! It's supposed to happen automatically, but either Travis or rustup.rs hiccuped last time: https://travis-ci.org/BurntSushi/ripgrep/jobs/162231880
