### ISSUE TITLE
Allow to set custom directory configuration

### ISSUE THREAD

**Issue by fidalgo** [BurntSushi/ripgrep#1834]
#### Describe your feature request
My request is about to add support for ripgrep to lookup for a `.ripgreprc` file in the current directory and then look up in the user folder.

Software projects are very different by nature, and having a global configuration of ripgrep, is not always suitable for different projects. If I'm doing a `C` project, I would like to exclude the `build` directory, but if I'm using a ruby project that build could contain some scripts that will help me, let's say create an artefact for deploy.

Having the same configuration and especially use it for the backend of a search system in the editor (my case) will lead in unsatisfactory results.

**Comment by BurntSushi** [comment]
Not happening, sorry. I elaborated more here: https://github.com/BurntSushi/ripgrep/issues/1373#issuecomment-753659388
