### ISSUE TITLE
warning is output to stdout

### ISSUE THREAD

**Issue by Yggdroot** [BurntSushi/ripgrep#1835]
#### What operating system are you using ripgrep on?

Linux

#### Describe your bug.

`WARNING: stopped searching binary file src/security-scanner-frontend/dist/fonts/ionicons.a558ac78.eot after match (found "\u{0}" byte around offset 3)` is output to stdout rather than stderr.

#### What are the steps to reproduce the behavior?

`rg "" 2> /dev/null  | grep WARNING`, the warning is displayed.

#### What is the expected behavior?
Warning is output to stderr.

What do you think ripgrep should have done?

**Comment by skuzzymiglet** [comment]
@Yggdroot Can you help us reproduce your bug by providing some files in your directory that caused the warning?

**Comment by BurntSushi** [comment]
ripgrep's test suite reproduces this behavior as it is intended: https://github.com/BurntSushi/ripgrep/blob/92286ad4d2a9c8b054de8aaea05c23a7220d20b3/tests/binary.rs#L37-L46

I think the question here is whether we should change this. IIRC, GNU grep recently changed its behavior to emit these messages to stderr as well. (But I could be mis-remembering.) I can see arguments in favor of both ways personally. I currently tend to lean towards retaining existing behavior personally.

**Comment by BurntSushi** [comment]
Going to stick with existing behavior for now.
