### ISSUE TITLE
rg should skip holes in files

### ISSUE THREAD

**Issue by umanwizard** [BurntSushi/ripgrep#1836]
Some files on some filesystems (e.g. ext4) can be sparse - they contain holes which are read as all zero bytes and occupy no space on disk.

```
$ truncate -s 1000G fake_big_file
$ du fake_big_file
0       fake_big_file
$ rg foo fake_big_file # this takes a long time, but could be made to take a short time
```

See e.g. this (never landed) PR to `ag` from 2015: https://github.com/ggreer/the_silver_searcher/pull/579

**Comment by BurntSushi** [comment]
Unfortunately, I don't think this is a good fit for ripgrep. I note also that GNU grep doesn't appear to implement any hole-oriented optimizations either.

For the most part, I just don't see how to robustly implement something like this. Your implementation in `ag`, for example, seems tightly coupled to the memory map method of searching. Memory maps don't work for all files. Moreover, when the "skip holes" flag is enabled, there is a non-trivial additional amount of overhead for every file searched.

With that said, I don't think you're stuck. I suspect that you would be able to write a preprocessor program that did this handling for you. See the section in the guide on the `--pre` flag: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#preprocessor
