### ISSUE TITLE
rg creating an overzealous .gitignore filter when used in a sub-directory

### ISSUE THREAD

**Issue by tarka** [BurntSushi/ripgrep#184]
To reproduce:

    $ cd linux
    $ rg TURKS
    <SNIP>

    drivers/gpu/drm/radeon/radeon_uvd.c
    111:	case CHIP_TURKS:

    <SNIP>

    $ cd drivers/gpu/drm/radeon/
    $ rg TURKS
    $

The relevant debug output is:

    DEBUG:rg::ignore: linux-drm-intel/drivers/gpu/drm/./radeon_uvd.c ignored by Pattern { from: "/home/ssmith/software/linux-drm-intel/.gitignore", original: ".*", pat: "**/.*", whitelist: false, only_dir: false }

Full debug log attached.
[rg.txt](https://github.com/BurntSushi/ripgrep/files/531817/rg.txt)

**Comment by BurntSushi** [comment]
What version of rg are you using? The latest is 0.2.3.

**Comment by tarka** [comment]
0.2.3 from cargo install, and also tested against master.

**Comment by BurntSushi** [comment]
Good find. This was indeed a bug. Should be fixed in the next release!
