### ISSUE TITLE
Add option to customize the separator character betwen paths, lines, columns and matches

### ISSUE THREAD

**Issue by noib3** [BurntSushi/ripgrep#1842]
As of version 12.1.1, if the `--no-heading` option is used then a `:` will be used to separate paths, lines, columns (if the `--column` option is used) and matches. Is it possible to customize those characters individually?

For example I'd like to use a `@` between paths and lines, the default `:` between lines and columns and a space between columns and matches.

I'm new to ripgrep, I've read the manual but I haven't found anything about it so I assume this behaviour is not currently supported?

**Comment by BurntSushi** [comment]
There is no way to customize it. But the underlying library does support customizing it: https://github.com/BurntSushi/ripgrep/blob/7923d252285d78b023a237d669d741dfa210ff86/crates/core/args.rs#L789-L790

I think I would be OK with a PR that adds two flags, one each for customizing the match and context separators for fields emitted in each case.

As a hint, you'll want to use [`cli::unescape_os`](https://github.com/BurntSushi/ripgrep/blob/7923d252285d78b023a237d669d741dfa210ff86/crates/core/args.rs#L1025) to extract out the separator from the CLI argument.

**Comment by samwho** [comment]
I'm also keen to have this feature, and my use-case is to make sure that the file path and line number are presented in the terminal in a way that can be ctrl+left clicked such that they will open to that line in VSCode.

I use the following settings:

```
--max-columns=150
--max-columns-preview
--smart-case
--search-zip
--color=auto
--no-heading
--no-messages
--trim
```

And the output looks like this:

```
$ rg use
src/entries.rs:186:use super::*;
src/entries.rs:187:use std::io::Cursor;
src/entries.rs:188:use test_case::test_case;
```

Sometimes, the fact that there is no space after the 2nd colon on each line makes it such that VSCode won't open the file at that line, instead it will initiate a search that yields nothing. Having a space there makes this work 100% of the time.

Removing `--trim` isn't a solution.

**Comment by samwho** [comment]
I've forked the repo and started taking a preliminary look. If I manually change line 789 of `ripgrep/crates/core/args.rs` to be a space instead of a colon, it doesn't quite do what I'd like. I'd like to be able to keep the colon between the path and the line number, but have a space between the line number and the match.

Would you be open to accepting a PR that changes the `printer` crate to allow this?

**Comment by BurntSushi** [comment]
@samwho Possibly. It depends on if there are any performance problems created by accepting multiple bytes vs one byte. It's been a while since I've touched that code, but my instinct is that there shouldn't be.

**Comment by fallaciousreasoning** [comment]
@samwho did you come up with a solution? I have the same problem with VSCode link detection, and `--field-match-separator " "` doesn't quite do what I want, as I lose the line number when clicking a link.

**Comment by samwho** [comment]
I'm afraid I didn't.
