### ISSUE TITLE
[feature request] file type filters for only headers / only source files

### ISSUE THREAD

**Issue by durka** [BurntSushi/ripgrep#186]
Use case: my question is "what do I include to get this function?", so I want to look through `*.h` but not `*.c`/`*.cpp`.

**Comment by BurntSushi** [comment]
What is the type name? Of the popular languages, I think only C/C++ have this kind of split, so I imagine it would be specific to them and not a general rule.

Note that you can also search header files by specifying a glob, e.g., `-g '*.h'`, which I kind of think might be good enough.

**Comment by durka** [comment]
Yeah, I guess globbing is fine for niche things.

**Comment by gvansickle** [comment]
`ack`, `ag`, and `ucg` (and maybe others) have a `--hh` file type for this for C/C++, which only includes '\*.h' files.  Which now that I type that, probably should be expanded to include '\*.hpp' etc. forms.

**Comment by BurntSushi** [comment]
I added a new `h` file type that matches `*.h` and `*.hpp`.
