### ISSUE TITLE
Optionally suppress decompression errors

### ISSUE THREAD

**Issue by raxod502** [BurntSushi/ripgrep#1861]
#### Describe your feature request

When I use the `-z, --search-zip` flag on my filesystem, I am typically met with a deluge of error messages like this, typically from the sample files in various open-source repos' test suites:

```
python/distlib/tests/fake_archives/coverage-3.5.2.tar.gz: 
-------------------------------------------------------------------------------
gzip: python/distlib/tests/fake_archives/coverage-3.5.2.tar.gz: unexpected end of file
-------------------------------------------------------------------------------
python/distlib/tests/fake_archives/coverage-3.4b2.tar.gz: 
-------------------------------------------------------------------------------
gzip: python/distlib/tests/fake_archives/coverage-3.4b2.tar.gz: unexpected end of file
-------------------------------------------------------------------------------
python/distlib/tests/fake_archives/coverage-3.3.1.tar.gz: 
-------------------------------------------------------------------------------
gzip: python/distlib/tests/fake_archives/coverage-3.3.1.tar.gz: unexpected end of file
-------------------------------------------------------------------------------
```

I would like to optionally be able to suppress the reporting of decompression errors. One way to implement this feature would be a new long option `--suppress-zip-errors`, or something along those lines. The option could be added to one's `RIPGREP_CONFIG_PATH` file, if one so desires.

The precise behavior would be that if ripgrep cannot decompress a file, then it will silently ignore that file, will not output to stderr, and will exit with a zero return code if no other errors occur.

The usage of ripgrep with this option would be `rg -z --suppress-zip-errors`.

**Comment by BurntSushi** [comment]
@raxod502 Have you tried using `--no-messages`?

**Comment by raxod502** [comment]
Ah, thank you, that does exactly what I wanted.
