### ISSUE TITLE
Automatically recognize compressed files

### ISSUE THREAD

**Issue by smprather** [BurntSushi/ripgrep#1870]
I regularly scan directories recursively. Some of those files may be gzipped, some not. Not to mention it is a minor pain in the neck to remember to add -z if grepping a compressed file. I can't just write a wrapper because I rely on rg's directory recursion a lot. Sure, I could wrap for that too, but then it starts getting hairy.

It would be really helpful if rg could automatically recognize compressed files and do The Right Thing. Initial support could just look at the file extension and not attempt recognition by internal file scanning. Thanks!

**Comment by BurntSushi** [comment]
Sorry, but what is the problem with `alias rg="rg -z"`?

**Comment by smprather** [comment]
Nothing wrong with that, except that I didn't know the flag would still search uncompressed files :). I though -z was used specifically for compressed file searches, but not for others. Thanks @BurntSushi .
