### ISSUE TITLE
Consider showing less output for `rg -h`

### ISSUE THREAD

**Issue by djc** [BurntSushi/ripgrep#189]
This might be a bit subjective, but for me the result of `rg -h` was somewhat suboptimal in giving me much more output than expected, thus quickly scrolling the most useful stuff off the screen.

I think I would like it better if `rg -h` did not show the `Less common options` and `File management options` by default, instead showing a line at the bottom that refers to some extra switch to make `-h/--help` more verbose.

**Comment by BurntSushi** [comment]
FWIW, `rg --help | less` should help, and it's what I normally do when the output of `--help` is large.

I'm not opposed to doing this, but I'm not 100% sure we should because I'm not a fan of making flags harder to discover.

**Comment by kballard** [comment]
`ag --help` shows a one-line (or sometimes two-line) description of all flags. Maybe `rg --help` should do the same, and then something like `rg --help-options` to show the more verbose output? That would make it easier to skim the options to find what you want.

**Comment by djc** [comment]
Yeah, that's another option that would maybe help discovery without making flags harder to discover.

**Comment by BurntSushi** [comment]
I do like that idea better.

**Comment by devsnek** [comment]
I'm not sure if something has happened since this, but the help output is once again enormous, and usually end up doing `rg --help | rg "thing i'm looking for"`.

**Comment by BurntSushi** [comment]
`rg --help` has been basically "the man page" for years. Nothing has changed recently. If you want a denser view, then use `rg -h`.

**Comment by devsnek** [comment]
Oh interesting. I'm not used to `-h` and `--help` doing different things. Perhaps they should be merged and manpages can be generated separately?

**Comment by BurntSushi** [comment]
No. man pages aren't available everywhere. The behavior is staying as is.

**Comment by lilyball** [comment]
`rg -h` still has a large header block that looks identical to the one from `rg --help`. Perhaps we could slim down the `rg -h` header block for just a couple of lines? It seems odd that even the USAGE section isn't immediately visible in `rg -h | less` on a 80x24 terminal.

**Comment by BurntSushi** [comment]
Indeed, I'd be open to that. The initial header block has indeed slowly grown larger over the years.
