### ISSUE TITLE
The version and SHA256 hash in ripgrep-bin doesn't match.

### ISSUE THREAD

**Issue by arzoriac** [BurntSushi/ripgrep#1896]
The version is still 12.1.1 instead of 13.0.0:
https://github.com/BurntSushi/ripgrep/blob/7ce66f73cf7e76e9f2557922ac8e650eb02cf4ed/pkg/brew/ripgrep-bin.rb#L2

**Comment by BurntSushi** [comment]
@arzoriac Out of curiosity, is there a reason why you're still using the tap instead of upstream homebrew? (I have idly considered removing the tap.)

**Comment by arzoriac** [comment]
Just because I remember it having SIMD optimizations so I always had that it was a "better" version of it.

**Comment by BurntSushi** [comment]
@arzoriac Ah. That was true a few years ago. You can switch to the Homebrew now then if that's the only reason. ripgrep's SIMD is now baked into the binary portably. Previously, you had to enable a compile time switch to get it to work on nightly Rust, but that stuff stabilized a while back and now everything "just works." :-)

**Comment by arzoriac** [comment]
Goof to know! I'll use it from Homebrew from now on.
