### ISSUE TITLE
How can I execute it with other commands at the same time?

### ISSUE THREAD

**Issue by ghost** [BurntSushi/ripgrep#1925]
When i execute
**apt list | rg 'apk'**
Its execution result is the direct output result of rg
How should I use *|rg ？
thank you ！

**Comment by BurntSushi** [comment]
I don't understand the question. Why not include the actual output and the expected output? Please also consider using standard commands. I don't have `apt` on my system.

**Comment by GitHubNeko** [comment]
> 我不明白这个问题。为什么不包括实际输出和预期输出？还请考虑使用标准命令。`apt`我的系统上没有。

Why can't **rg** and **|** be used at the same time?

https://user-images.githubusercontent.com/83487691/124404922-8c4e9280-dd6f-11eb-8057-d4f70bcfbd40.mp4

**Comment by BurntSushi** [comment]
Please provide a reproduction. I don't want a video. I want commands I can run. Of course ripgrep works with `|`.

What version of ripgrep are you using?

Why did you delete the issue template that requested this basic information? I didn't put it there for fun.

**Comment by jplatte** [comment]
The account of the user who asked this question has since been deleted, time to close this?
