### ISSUE TITLE
[Question] how to search by filenames only?

### ISSUE THREAD

**Issue by hh9527** [BurntSushi/ripgrep#193]
`--files` will list all files which respect ignore files. Is there a flag to list filenames which match the given filename pattern?

**Comment by BurntSushi** [comment]
From `rg --help`:

```
    -g, --glob GLOB ...        Include or exclude files for searching that
                               match the given glob. This always overrides any
                               other ignore logic. Multiple glob flags may be
                               used. Globbing rules match .gitignore globs.
                               Precede a glob with a '!' to exclude it.
```

**Comment by YPCrumble** [comment]
@BurntSushi this is related to the issue I just raised, #284. The I believe the question here is "How can I search for a pattern in the filename, and return the filenames that include that pattern in the path/filename?"

It appears that the -g flag limits my search _for text within the file_ to the filenames matching the -g pattern. Does that explain the nuance? 

Example: 

If there is a file relative to my directory, `./stories/story.txt` that contains the text "Once upon a time", I want to be able to run `rg -g story` and return `./stories/story.txt`. It appears that the -g flag would return nothing in this query, but it would return "Once upon a time" if I try `rg Once -g story.*`.

**Comment by hraban** [comment]
I have the following alias to shim this in my ~/.bashrc:

```sh
alias rgf='rg --files | rg'
```

This allows you to do:

```sh
$ rgf 2018
lib/lib.es2018.full.d.ts
lib/lib.es2018.promise.d.ts
lib/lib.es2018.intl.d.ts
lib/lib.es2018.regexp.d.ts
lib/lib.es2018.asynciterable.d.ts
lib/lib.es2018.d.ts
```

**Comment by johnyradio** [comment]
> ```shell
> --files
> ```

how would you do that without the alias?

**Comment by hraban** [comment]
@johnyradio just type the command directly:

    rg --files | rg 2018

A Bash alias just substitutes the command for whatever the contents of the alias is, then continues evaluating as usual. That's all an alias is:

    alias rgf="rg --files | rg"
    rgf 2018

=

    rg --files | rg 2018

**Comment by johnyradio** [comment]
Many thanks! Super helpful.

**Comment by dzhang-b** [comment]
`rg --files | rg <pattern> <directory>`  or `rgf <pattern> <directory>`won't work. It will search all contents in the directory, not the filename in that directory.

**Comment by Piping** [comment]
@hraban Thanks for the tip, I updated the logic a bit for future newcomer.
```sh
rf() {
  if [ -z "$2" ]
  then
      rg --files | rg "$1"
  else
      rg --files "$2" | rg "$1"
  fi
}
```

**Comment by anishmittal2020** [comment]
> > `rg --files | rg <pattern> <directory>` or `rgf <pattern> <directory>`won't work. It will search all contents in the directory, not the filename in that directory.
> > It is best if we can add an actual flag to do this.
> 
> ```
> $ rg --files [directory] | rg <pattern>
> ```
> 
> if you want to do this as a "rgf" style alias, use a function instead:
> 
> ```shell
> function rgf {
>     rg --files $2 | rg $1
> }
> ```

What you suggested searches in the entire path and not just in the filename (what the OP had asked)!

**Comment by anishmittal2020** [comment]
Use (to search Python):

```
Regex="Python"
rg --files-with-matches --type md --files "${PWD}" | rg --regexp "${Regex}[^/]*$" | sort | nl
```

**Comment by anishmittal2020** [comment]
To search Python in filenames:

```
Search=Python
rg --files-with-matches --type md --files "${PWD}" | rg --regexp "${Search}[^/]*$" | sort | nl
```

**Comment by ssbarnea** [comment]
I still hope to see native support for it. There is a huge UX benefit on having it as a default feature and the number of user upthumbs explains it.

**Comment by BurntSushi** [comment]
Use `fd` instead.

**Comment by AtomicNess123** [comment]
> ```
> rg --files | rg 2018
> ```

Thanks, very useful. What does the | mean?

**Comment by BurntSushi** [comment]
@AtomicNess123 `rg --files | rg 2018` will only print file names that contain `2018`.

The `|` is a shell pipeline. It redirects the output of `rg --files` into the input of `rg 2018`.

**Comment by AtomicNess123** [comment]
Mmm... I have to digest that. Could you give a more illustrative example? No rush, though...

**Comment by BurntSushi** [comment]
```
$ touch foo2018 foo bar2018 bar
$ rg --files
foo
foo2018
bar2018
bar
$ rg --files | rg 2018
foo2018
bar2018
```

**Comment by AtomicNess123** [comment]
Thanks. What is the difference then between `rg --files | rg 2018` and `rg --files -g '*2018*' ` ?
Thanks for your time!

**Comment by BurntSushi** [comment]
The former will print all paths in the current tree that contain 2018. The latter will only print paths containing 2018 where all of its parent directories also contain 2018. The `-g` flag influences which directories ripgrep descends into.

**Comment by AtomicNess123** [comment]
Thanks, very insightful!

**Comment by AtomicNess123** [comment]
Actually, it won't work like that in my case:

```bash
rg --files -g '*helm*'                                                                                                       
xxx-helm-xxx.el
helm/xxx-helm-xxx.el
helm/sub2/xxx-helm-xxx.el
helm/sub2/xxxhelmxxx.el
helm/xxxhelmxxx.el
a/xxx-helm-xxx.el
a/sub2/xxx-helm-xxx.el
a/sub2/xxxhelmxxx.el
a/xxxhelmxxx.el
xxxhelmxxx.el

rg --files | rg helm               
xxx-helm-xxx.el
helm/xxx-helm-xxx.el
helm/sub2/xxx-helm-xxx.el
helm/sub2/xxxhelmxxx.el
helm/xxxhelmxxx.el
a/xxx-helm-xxx.el
a/sub2/xxx-helm-xxx.el
a/sub2/xxxhelmxxx.el
a/xxxhelmxxx.el
xxxhelmxxx.el
```

As you can see, the -g flag makes no difference.

**Comment by theicfire** [comment]
> Use `fd` instead.

Probably referencing https://github.com/sharkdp/fd. TIL.

**Comment by hangyu-feng** [comment]
maybe `rg -l` is what you are looking for?

**Comment by JosephTLyons** [comment]
Any way to search for all file nams with a given pattern without having to specify a search pattern?

```bash
〉rg -g *.json                                                                                                             
ripgrep requires at least one pattern to execute a search
```

**Comment by BurntSushi** [comment]
Yes. Use the `--files` flag.
