### ISSUE TITLE
rg glob file order diffrent to ls

### ISSUE THREAD

**Issue by redaready** [BurntSushi/ripgrep#1937]
#### What version of ripgrep are you using?

12.1.1

#### How did you install ripgrep?

Github binary releases.

#### What operating system are you using ripgrep on?

Amazon Linux 2

#### Describe your bug.

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?
 rg *.log --files
20210716-000000.log
20210715-000000.log
20210714-000000.log
20210713-000000.log
20210712-000000.log
20210711-000000.log
20210710-000000.log
20210709-000000.log
20210708-000000.log
20210707-000000.log
20210706-000000.log

but with ls or grep we have 
ls -alh *.log
20210706-000000.log
20210707-000000.log
20210708-000000.log
20210709-000000.log
20210710-000000.log
20210711-000000.log
20210712-000000.log
20210713-000000.log
20210714-000000.log
20210715-000000.log
20210716-000000.log

What do you think ripgrep should have done?

rg should have some parameter to config the order of files

**Comment by redaready** [comment]
rg *.log --files --sortr path

**Comment by BurntSushi** [comment]
Yes, you want `--sort path` if you want to sort files in ascending order lexicographically. And `--sortr path` to do it in reverse. See the docs for other values you can pass to `--sort`.

Note that using `--sort` disables parallelism.
