### ISSUE TITLE
Documentation for '--quiet' is misleading

### ISSUE THREAD

**Issue by zachriggle** [BurntSushi/ripgrep#1962]
The documentation for the `--quiet` flag is misleading with the `--files` flag.

The current documentation states:

```
       -q, --quiet
           Do not print anything to stdout. If a match is found in a file,
           then ripgrep will stop searching. This is useful when ripgrep is
           used only for its exit code (which will be an error if no matches
           are found).

           When --files is used, then ripgrep will stop finding files after
           finding the first file that matches all ignore rules.
```

The very last part, "the first file that matches all ignore rules" seems like it's worded backwards.  I get what it means, it's just oddly worded.  It might be better to state instead "the first file that does not match any ignore rules".

Just an opinion, feel free to close if you disagree.

#### What version of ripgrep are you using?

```
rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

**Comment by BurntSushi** [comment]
Feel free to file a PR! (For very small wording tweaks like this, I'd prefer just filing a PR.)

**Comment by zachriggle** [comment]
I would absolutely love to, especially since it's small and easy, but my employer has VERY strict rules against FOSS contributions (even for permissive, MIT-licensed code, even for non-"code" changes).

**Comment by ryanwhitehouse** [comment]
PR to fix this here https://github.com/BurntSushi/ripgrep/pull/2462 :)
