### ISSUE TITLE
--smart-case doesn't work with --regexp/-w

### ISSUE THREAD

**Issue by alejandro5042** [BurntSushi/ripgrep#199]
Smart casing works great if you use --fixed-strings. However, once you use --regexp or -w, it falls apart:

For example, this code does not match "ToCsvFile" in any file.

```
rg --smart-case --regexp "\btocsvfile"
```

Same with -w. Doesn't work:

```
rg --smart-case -w "tocsvfile"
```

But begins matching with --ignore-case.

**Comment by alejandro5042** [comment]
Version 0.2.3.

**Comment by BurntSushi** [comment]
This is indeed a bug. It's probably related to literal optimizations that are ignoring the smart case flag. For example, this works even though it's using a regex:

```
[andrew@Cheetah tmp] cat foo
ToCSVFile
tocsvfile
[andrew@Cheetah tmp] rg '^\p{Ll}+$' foo
2:tocsvfile
[andrew@Cheetah tmp] rg -S '^\p{Ll}+$' foo
1:ToCSVFile
2:tocsvfile
```

(Although, I wonder if making pure regexes case insensitive even when smart case is enabled is desirable. Maybe it should only activate if there's at least one literal byte? Not sure, but that's a separate issue I guess.)
