### ISSUE TITLE
Parse errors in .gitignore do not sanitize some terminal escape sequences before printing to stderr

### ISSUE THREAD

**Issue by Kimundi** [BurntSushi/ripgrep#1992]
#### What version of ripgrep are you using?

```
ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

`apt install ripgrep` in a Ubuntu 20.04 WSL2 install.

#### What operating system are you using ripgrep on?

Ubuntu 20.04 in a WSL2

#### Describe your bug.

The line printed from a .gitignore in case of an parse errors might contain terminal escape sequences that mess up the terminal state.

#### What are the steps to reproduce the behavior?

I'm not sure which kind of terminal escape sequences these are, so in case this is terminal emulator specific:

- Be on windows
- Use the new "Windows Terminal"
- Be logged into a WSL2 instance with it (bash or fish)
- Have a `.gitignore` containing the following bytes: `\x5b\x5d\xc2\x96\xc2\x97\xc2\x98\xc2\x99\xc2\x9a\x0a`
- run `rg foo` or any other command that causes it to parse `.gitignore` files.
- You should now be able to observe that some terminal control sequences got send to the terminal

#### What is the actual behavior?

```
> hexdump -C .gitignore
00000000  5b 5d c2 96 c2 97 c2 98  c2 99 c2 9a 0a           |[]...........|
0000000d
> rg foo
./.gitignore: line 1: error parsing glob '[]': unclosed character class; missing ']'
^[[?1;0c
> [?1;0c
```

![grafik](https://user-images.githubusercontent.com/2903206/133650874-39677ecb-4a7f-43cc-81e8-9910e3e90aca.png)

#### What is the expected behavior?

Any terminal escape sequences should get sanitized out from the line, at least if printed to an interactive terminal.

**Comment by BurntSushi** [comment]
I can't seem to reproduce this:

![no-color-mangling](https://user-images.githubusercontent.com/456674/134041804-0a6ef063-a8d5-44b6-8722-79120668ba4c.png)

Either way, I appreciate the bug report, but I think I'm going to mark this as `wontfix`. ripgrep passes through content it reads, as-is, pretty much everywhere. The same would happen if you were searching a file and ripgrep printed a match with ANSI escape codes, for example. Similarly for file names and probably other stuff. I'm not really sure it's ripgrep's place to get super paranoid about this and start cleansing everything it prints. It certainly doesn't seem like other tools do it.
