### ISSUE TITLE
Needs to have command line option opposite of --with-filename

### ISSUE THREAD

**Issue by jikamens** [BurntSushi/ripgrep#20]
There needs to be a way to disable the file name prefix even when multiple files are being searched.

**Comment by BurntSushi** [comment]
Could you help motivate this by describing a use case? Thanks!

**Comment by jikamens** [comment]
I sort of thought the use case was obvious: I want to see matches for a given pattern in a bunch of files but I don't care what files the matches are in. For example, if I want to search for log entries matching a pattern in a bunch of compressed log files which are split up only so they don't get too big, then each matching log line fully identifies everything I need to know about it in the log line itself; I don't care about the file name when looking at the results.

**Comment by BurntSushi** [comment]
That's perfect, thank you. :-)

**Comment by BurntSushi** [comment]
This is done. I added the `--no-filename` flag.
