### ISSUE TITLE
[Feature] Ask for tab width in spaces when calculating the search result column position

### ISSUE THREAD

**Issue by pidgeon777** [BurntSushi/ripgrep#2006]
Actually, given a searched string, `ripgrep` can return:

- line position
- column position (in bytes, 1 character = 1 byte)

Please add an argument so that the column position is returned keeping into account the eventual presence of tabs, for example by asking the user how many spaces (bytes) should be associated with the tab character(s).

**Comment by BurntSushi** [comment]
I don't think this is a good fit for ripgrep. I'd suggest post-processing the output somehow.
