### ISSUE TITLE
Print header line

### ISSUE THREAD

**Issue by ljufa** [BurntSushi/ripgrep#2017]
Add option to print header line of tabular inputs 
i.e. for the input:

| Command | Description |
| --- | --- |
| git status | List all new or modified files |
| git diff | Show file differences that haven't been staged |

`ripgrep --header 1 staged`

Should print:

| Command | Description |
| --- | --- |
| git diff | Show file differences that haven't been staged |

Optionally, the header line number could be provided by the user (default to 1).
Let me know if this is an interesting feature. I will be happy to contribute.

**Comment by BurntSushi** [comment]
I'm going to pass on this one. I think it's out of scope for ripgrep.
