### ISSUE TITLE
Combining -z and -l works but prints error messages

### ISSUE THREAD

**Issue by golimarrrr** [BurntSushi/ripgrep#2019]
#### What version of ripgrep are you using?

ripgrep 13.0.0 (rev af6b6c543b)

#### How did you install ripgrep?

Downloaded the zip file for Windows

#### What operating system are you using ripgrep on?

Win10 1809

#### Describe your bug.

Combining -z and -l works but there is a seemingly unrelated error in the output

#### What are the steps to reproduce the behavior?

`rg -zl pattern` having gz files that contain "pattern" in the current directory

#### What is the actual behavior?

```
>c:\temp\rg -zl "Connection reset"
MyLogFile-56.log.gz:
-------------------------------------------------------------------------------
stdout: Invalid argument

gzip:
-------------------------------------------------------------------------------
MyLogFile-54.log.gz:
-------------------------------------------------------------------------------
stdout: Invalid argument

gzip:

```

#### What is the expected behavior?

```
>c:\temp\rg -zl "Connection reset"
MyLogFile-56.log.gz
MyLogFile-54.log.gz
```

**Comment by golimarrrr** [comment]
I'm attaching a file where it happens; about the questions you asked:
- `gzip -d -c < file.gz` does not produce any error, just outputs the content
- if I search something that doesn't exist there are no errors and also no output (as expected)
- it doesn't occur when not using `-l` , it outputs the matching filenames, line numbers and lines as expected

[aqui.txt.gz](https://github.com/BurntSushi/ripgrep/files/7494946/aqui.txt.gz)

**Comment by BurntSushi** [comment]
I can't reproduce the problem:

```
$ tree /tmp/rg2019/
/tmp/rg2019/
└── aqui.txt.gz

1 directory, 1 file

$ rg -zl . /tmp/rg2019/
/tmp/rg2019/aqui.txt.gz
```
