### ISSUE TITLE
Cannot add newlines using \n in the replacement string

### ISSUE THREAD

**Issue by dasebasto** [BurntSushi/ripgrep#2025]
#### What version of ripgrep are you using?

ripgrep 13.0.0 (rev 7ec2fd51ba)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

sudo apt-get install ripgrep
#### What operating system are you using ripgrep on?
WSL2 (under Windows 10)
kernel 4.19.104-microsoft-standard

#### Describe your bug.
Newlines \n are not processed as expected in the replace pattern.

#### What are the steps to reproduce the behavior?
`echo "fox" | rg -r '${1}\n${1}es' "(fox)"`
Expected output:
```
fox
foxes
```

Actual output:
```
fox\nfoxes
```

**Comment by dasebasto** [comment]
My bad, I didn't check I was up to date as I installed ripgrep today through apt-get.

I just updated to ripgrep_13.0.0_amd64.deb, and the behavior is still the same.

**Comment by BurntSushi** [comment]
Looking more closely, this doesn't look like a ripgrep problem. This is a shell input problem. You telling ripgrep to insert `\n` verbatim, not an actual newline.
