### ISSUE TITLE
[globset] Create an escaped pattern from a literal string

### ISSUE THREAD

**Issue by piegamesde** [BurntSushi/ripgrep#2060]
Basically I'm migrating some code from `glob` and looking for a functional equivalent of https://docs.rs/glob/0.3.0/glob/struct.Pattern.html#method.escape. Maybe put is as `GlobBuilder::new_escaped` or something.

**Comment by BurntSushi** [comment]
`GlobBuilder::new_escaped` seems pretty weird to me. I suspect it should either be `Glob::escape` (like `Pattern::escape`), or perhaps just a free function, like in the [regex crate](https://docs.rs/regex/1.5.4/regex/fn.escape.html). I think I have a preference toward the latter.

**Comment by piegamesde** [comment]
You are right, I didn't think this through. Since there is no globbing, we also don't need the options and thus don't need to use the `GlobBuilder`.

**Comment by BurntSushi** [comment]
A PR would be welcome. Otherwise, it's unlikely I'll work on this any time soon myself.
