### ISSUE TITLE
Named Capture Groups

### ISSUE THREAD

**Issue by balupton** [BurntSushi/ripgrep#2068]
#### Describe your feature request

It would be nice if ripgrep supported ECMAScript's Named Capture Groups:

``` javascript
let personList = `First_Name: John, Last_Name: Doe
First_Name: Jane, Last_Name: Smith`;

let regexpNames =  /First_Name: (?<firstname>\w+), Last_Name: (?<lastname>\w+)/mg;
let match = regexpNames.exec(personList);
do {
  console.log(`Hello ${match.groups.firstname} ${match.groups.lastname}`);
} while((match = regexpNames.exec(personList)) !== null);
```

**Comment by balupton** [comment]
Nevermind, I'm an idiot. I didn't realise that this supports the rust regex format, of which named capture groups are supported, just a different syntax: https://docs.rs/regex/1.5.4/regex/#syntax

**Comment by balupton** [comment]
Actually, seems it doesn't work:

``` bash
# echo "2012-03-14, 2013-01-01 and 2014-07-05" | rg '(?P<y>\d{4})-(?P<m>\d{2})-(?P<d>\d{2})' --replace "$m/$d/$y"
//, // and //
```

**Comment by balupton** [comment]
nevermind, still an idiot, needed single quotes around the replacement:

``` bash
echo "2012-03-14, 2013-01-01 and 2014-07-05" | rg '(?P<y>\d{4})-(?P<m>\d{2})-(?P<d>\d{2})' --replace '$m/$d/$y'
```

**Comment by BurntSushi** [comment]
No it does work. Use single quotes. Otherwise your shell interpolates your variables.
