### ISSUE TITLE
Is "rg -l | xargs" vulnerable to files with leading dashes?

### ISSUE THREAD

**Issue by jzinn** [BurntSushi/ripgrep#2078]
Should `rg -l` prepend `./` to relative paths when outputting to a non-interactive tty to protect against files named with leading dashes being unintentionally interpreted as flags by xargs commands?

`fd` is looking at this: https://github.com/sharkdp/fd/issues/760.  `rg -l` seems similar.

### Edit:

If it's a problem, it's bigger than `rg -l`:

Actual:
```
% echo there > hi
```

```
% rg ere
hi
1:there
```

```
% rg ere | cat
hi:there
```

Expected?:

```
% rg ere | cat
./hi:there
```

**Comment by BurntSushi** [comment]
No, I don't think this is necessary. Not even GNU grep does this. But in either case, if you want to have `./` preprended to each path, then you just need to specify it:

```
$ rg -l 'fn is_empty'
GUIDE.md
crates/globset/src/lib.rs
crates/ignore/src/overrides.rs
crates/ignore/src/gitignore.rs
crates/ignore/src/types.rs
crates/matcher/src/lib.rs
crates/cli/src/process.rs

$ rg -l 'fn is_empty' ./
./GUIDE.md
./crates/globset/src/lib.rs
./crates/ignore/src/types.rs
./crates/ignore/src/gitignore.rs
./crates/ignore/src/overrides.rs
./crates/matcher/src/lib.rs
./crates/cli/src/process.rs

$ grep -rl 'fn is_empty'
crates/matcher/src/lib.rs
crates/cli/src/process.rs
crates/ignore/src/types.rs
crates/ignore/src/gitignore.rs
crates/ignore/src/overrides.rs
crates/globset/src/lib.rs
GUIDE.md

$ grep -rl 'fn is_empty' ./
./crates/matcher/src/lib.rs
./crates/cli/src/process.rs
./crates/ignore/src/types.rs
./crates/ignore/src/gitignore.rs
./crates/ignore/src/overrides.rs
./crates/globset/src/lib.rs
./GUIDE.md
```

**Comment by jzinn** [comment]
Grep and posix are old, and this would be a breaking change.  Maybe it's a good idea to prefix, but the weight of compatibility prevents it?  Maybe it's not necessary.

**Comment by BurntSushi** [comment]
I don't see this as necessary. File paths starting with a `-` are not something I've ever seen personally, _and_ there's a way to work-around it.
