### ISSUE TITLE
`--file` output includes './'

### ISSUE THREAD

**Issue by cloudhead** [BurntSushi/ripgrep#21]
Hey, I'm playing around with `rg` as a replacement for `ag` in my [fuzzy file finder](https://github.com/cloudhead/neovim-fuzzy) and I noticed the output of `rg --files` includes a './' in the output, ex:

```
./src/file.c
./src/file2.c
```

In comparison to `ag -g ''` or `ack -g ''` which looks like this:

```
src/file.c
src/file2.c
```

Would you consider adding an option for this or changing it to match ack/ag? I'm aware I can use sed, but it would be nice if it was built-in.

Thanks

**Comment by BurntSushi** [comment]
I think the current behavior matches `find` right?

I'm not opposed to adding a flag. What about changing the default output instead?

**Comment by cloudhead** [comment]
Yes, the current behaviour does match `find`. It has an option though (`-print`?) to change the output, but I'd say that's probably not worth implementing at this point. I'd be happy if the default didn't include `./`, I think in general it might be a better default.
