### ISSUE TITLE
Provide a `--stats-only` option

### ISSUE THREAD

**Issue by fpdotmonkey** [BurntSushi/ripgrep#2121]
This is a feature that exists in SilverSearcher.  From its man page,

```
--stats-only
        Print stats (files scanned, time taken, etc) and nothing else.
```

This would do exactly what `--stats` does now, but it would also disable output of matches, headers, files, etc.  Anything that isn't the stats block.

**Comment by BurntSushi** [comment]
Could you say why `--stats -q` is insufficient for your use case?

**Comment by fpdotmonkey** [comment]
Well largely because I didn't catch that in the man page.  Thank you!

**Comment by fpdotmonkey** [comment]
Although actually the man page is a little misleading for `--quiet`.  It reads "Do not print anything to stdout", however `--stats` prints to stdout
