### ISSUE TITLE
Please state more clearly whether the tool searches file names or file content

### ISSUE THREAD

**Issue by tempelmann** [BurntSushi/ripgrep#2135]
The initial readme says: "… searches the current directory for a regex pattern."

It is not clear to me _what_ it searches. The file names in the directory, or the text file content in the files in the directory.

It should be easy to fix that by editing that part of the sentence, thank you.

**Comment by BurntSushi** [comment]
You left out the initial part of the sentence, which I think clarifies things:

> ripgrep is a *line-oriented* search tool

It also has "grep" in the name, which has a fairly ubiquitous meaning.
