### ISSUE TITLE
search-zip: include .jar files

### ISSUE THREAD

**Issue by simon04** [BurntSushi/ripgrep#2136]
#### Describe your feature request

I would like to `rg --search-zip` to search in .jar files

```
$ file *jar
foo.jar: Zip archive data, at least v1.0 to extract, compression method=deflate
bar.jar: Zip archive data, at least v2.0 to extract, compression method=deflate
```

Plenty of test files can be obtained from https://repo1.maven.org/maven2/, for instance https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.35/slf4j-api-1.7.35.jar

**Comment by BurntSushi** [comment]
I'm not sure this is exactly expected behavior to be honest. You can work around it with the `--pre` and `--pre-glob` flags.

**Comment by garoto** [comment]
`--search-zip` is searching inside actual zip files currently?

**Comment by BurntSushi** [comment]
No, it isn't. Because zips are archives. Good point. So this is an easy "no."

**Comment by jumarko** [comment]
@BurntSushi can you elaborate more on why this isn't supported.
I thought using `rg -z pattern my.zip` (or `my.jar`) would work 
If `-z` doesn't search inside compressed files what it is for?

**Comment by BurntSushi** [comment]
I'm not sure what else there is to elaborate on. Zips and tar files are archives. Gzip and xz and what not are compression formats. ripgrep searches the latter with this flag, not the former.

**Comment by BurntSushi** [comment]
See: #1112, #974, #1479, #1060, #918.
