### ISSUE TITLE
glob has different behaviours on window and linux.

### ISSUE THREAD

**Issue by xaljer** [BurntSushi/ripgrep#2137]
#### What version of ripgrep are you using?

ripgrep 13.0.0 (rev af6b6c543b)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?
Github binary releases.

#### What operating system are you using ripgrep on?

Windows 10 and Ubuntu 20.04 on WSL

#### Describe your bug.

--glob has different behaviours on window and linux.

#### What is the actual behavior?
On Windows:
```
PS C:\Users\Ryan\test_rg> echo a > my_00.log
PS C:\Users\Ryan\test_rg> echo b > my_01.log
PS C:\Users\Ryan\test_rg> rg --files -g my_*.log
my_01.log
my_00.log
```

On Linux：
``` bash
> ryan test_rg$ rg --files -g my_*.log
my_01.log
> ryan test_rg$ rg --files -g my_0*.log
my_01.log
> ryan test_rg$ rg --files -g my_*0.log
my_00.log
```

#### What is the expected behavior?
behaviour on Windows make sense.

**Comment by BurntSushi** [comment]
This is correct. Since you aren't quoting the argument to the `-g` flag, at least on Linux, your shell is expanding the glob. Not ripgrep.

**Comment by xaljer** [comment]
Thanks.
