### ISSUE TITLE
Makefile type list is missing "*.mak"

### ISSUE THREAD

**Issue by MiguelLatorre** [BurntSushi/ripgrep#217]
Comparing several _greppers_:

rg --type-list:
`make: *.mk, Gnumakefile, Makefile, gnumakefile, makefile`

ack --help-types
`--[no]make         .mk; .mak; makefile; Makefile; Makefile.Debug; Makefile.Release`

sift --list-types
`make           :Makefile *.mak`

I am missing the ***.mak** pattern.

By the way, this tool is awesome.
Good work. Keep it up!

**Comment by BurntSushi** [comment]
If you open a PR and modify [this line](https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/types.rs#L126) then I'd be happy to merge it.

If not, that's OK, and I'll do it next time I think of it!

**Comment by theamazingfedex** [comment]
I was making PRs for filetypes, and saw this issue, so I went ahead and made a PR for this change: #220

**Comment by BurntSushi** [comment]
@theamazingfedex Thanks!

**Comment by MiguelLatorre** [comment]
Wow. Perfect timming. Big thanks to both of you!
