### ISSUE TITLE
Recursive search fails in GitHub Actions

### ISSUE THREAD

**Issue by AndrewSouthpaw** [BurntSushi/ripgrep#2181]
#### What version of ripgrep are you using?

```
# local
$ rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

# github action
ripgrep 13.0.0 (rev 7ec2fd51ba)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

Followed these instructions:

```
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
          sudo dpkg -i ripgrep_13.0.0_amd64.deb
```

#### Describe your bug.

I'm running v13.0.0, and it works fine locally, but not in CI with GitHub Actions:

Local

```
$ rg '<<<<<< HEAD'
modules/mypkg/package.json
1:<<<<<< HEAD

modules/mypkg/package-lock.json
3:  <<<<<< HEAD
```

When I run it in CI with these commands:

```
          echo 'checking merge conflicts with explicit path'
          rg '<<<<<< HEAD' modules/mypkg/package-lock.json
          echo 'checking merge conflicts recursively'
          rg '<<<<<< HEAD'
```

It works fine for the explicit path but not for the recursive search.

```
(output)
checking merge conflicts with explicit path
  <<<<<< HEAD
checking merge conflicts recursively
Error: Process completed with exit code 1.
```

Any ideas what's going on?

**Comment by BurntSushi** [comment]
Probably something related to Actions attaching something to stdin when it shouldn't, thus ripgrep tries to search stdin.

The work around is easy: don't rely on auto detection. Use `rg foo ./`.

**Comment by AndrewSouthpaw** [comment]
Yep that did the trick, I never would've guessed to do that. Thanks for the quick response!

**Comment by casey** [comment]
I just hit this, and it was pretty hard to debug. This is definitely not ripgrep's fault, but documenting this somewhere might be helpful for users who hit it.

**Comment by casey** [comment]
Created a discussion [here](https://github.com/orgs/community/discussions/29721), hopefully they revert this.
