### ISSUE TITLE
shell completion '-t' for extensions prompt

### ISSUE THREAD

**Issue by Freed-Wu** [BurntSushi/ripgrep#2195]
Now, the shell completion `-t`(e.g. zsh) is as following:

```
❯ rg -t<Tab>
file type
agda          cabal         csv           fidl          hbs           license       minified      po            robot         sv            typoscript    z
...
```

In the code, it truncate `:*` of the output of `rg --type-list`

```
❯ rg --type-list|head -n1
agda: *.agda, *.lagda
```

How about adding the extension information? Like this:

```
❯ rg -t<Tab>
file type
agda     *.agda,*.lagda
aidl     *.aidl
...
```

It should can be realized, because zsh use `(agda aidl)` to provide the completion without prompt information, and use `(agda\:*.agda,*.lagda aidl\:*.aidl)` to provide the completion with prompt information.

**Comment by Freed-Wu** [comment]
Just like `fd -t<Tab>`

**Comment by BurntSushi** [comment]
I think the current behavior is ideal. Otherwise it becomes way too noisy. If you want to see the extensions for each type, then I think needing to run `rg --type-list` separate is fine.

**Comment by okdana** [comment]
zsh has a [standard style](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Standard-Styles) called `extra-verbose` that can be used for stuff like this. `_rg_types` could support it with a small modification, and then users who want the more elaborate completion results can turn them on in their shell profile with `zstyle`.

Maybe the visual/maintenance burden still isn't worth it, idk, but i could put a PR together if you did want to provide the option

**Comment by BurntSushi** [comment]
Oh I would be okay with that! Good call.
