### ISSUE TITLE
-g flag in Windows doesn't work as expected when following the user guide

### ISSUE THREAD

**Issue by BertanAygun** [BurntSushi/ripgrep#2207]
#### What version of ripgrep are you using?

ripgrep 13.0.0 (rev af6b6c543b)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?
choco
#### What operating system are you using ripgrep on?
Windows

#### Describe your bug.
The user guides show example usage as: 
rg someText -g '*.ext'

But this fails on Windows and --debug shows that .ext files were not being matched.

However the command:
rg someText -g *.ext

works correctly.

Not sure if this is a bug or documentation issue though.

**Comment by BurntSushi** [comment]
This is almost certainly a Windows shell thing. You probably need to use double quotes.

**Comment by garoto** [comment]
No quotes or double-quotes is the proper way to do it on a `cmd.exe` prompt. The user-guide is written from a *nix shell pov.

**Comment by salsifis** [comment]
Quoting with single quotes will work in Powershell or bash, not in CMD.

CMD does not interpret single quotes and will include them in the subprocess command-line.

**Comment by BurntSushi** [comment]
I don't think there is anything actionable on my end here.

I've always found cmd.exe quite difficult and very unwieldy to use, especially around quoting. It's unclear why one would use on modern Windows. And in particular, I'm not sure it's worth cluttering up the user guide just to address `cmd.exe`.
