### ISSUE TITLE
Ripgrep does not use parent-directory, same-repo .gitignore files

### ISSUE THREAD

**Issue by srcreigh** [BurntSushi/ripgrep#221]
Consider the following Git repo:

```
.gitignore
foo/
foo/message  # contains "hey"
foo/bar/
foo/bar/message  # contains "hey"
```

where `.gitignore` contains:

```
/foo/bar/
```

The issue is that when I run `rg hey` while in the `foo` directory, it returns 2 files (both `foo/message` and `foo/bar/message`). This is a bug because `foo/bar/message` is ignored by git, yet it's returned by `rg`, and the whole point of using `rg` over `grep` (imo) is that it doesn't include files that are ignored by Git.

## Reproduction steps

Run these commands:
```
mkdir -p rg-test rg-test/foo rg-test/foo/bar
echo "hey" > rg-test/foo/message
echo "hey" > rg-test/foo/bar/message
echo "/foo/bar/" > rg-test/.gitignore
cd rg-test/foo
rg hey
```

Ex:
```
λ /tmp/ mkdir -p rg-test rg-test/foo rg-test/foo/bar
λ /tmp/ echo "hey" > rg-test/foo/message
λ /tmp/ echo "hey" > rg-test/foo/bar/message
λ /tmp/ echo "/foo/bar/" > rg-test/.gitignore
λ /tmp/ cd rg-test
λ /tmp/rg-test/ cd foo
λ /tmp/rg-test/foo/ rg hey
bar/message
1:hey

message
1:hey
λ /tmp/rg-test/foo/ 
```

Expected output (from the `rg` command):
```
message
1:hey
```

Actual output:
```
bar/message
1:hey

message
1:hey
```

## Screenshot
<img width="446" alt="screen shot 2016-11-03 at 11 21 04 pm" src="https://cloud.githubusercontent.com/assets/2747249/19993466/5128b6c4-a21c-11e6-84f2-b5dafe2853d9.png">

**Comment by BurntSushi** [comment]
What version of ripgrep are you using?

**Comment by srcreigh** [comment]
```
λ ~/ rg --version
0.2.3
λ ~/
```

Installed via `brew install ripgrep` earlier today.

**Comment by BurntSushi** [comment]
Ah okay. 0.2.6 is out, but not on brew yet (there is a binary download here
on github though). I'm on mobile, but I'll check this out on the latest
version tomorrow. Thanks for the detailed report!

**Comment by BurntSushi** [comment]
Yay, looks like this has already been fixed. :-)

```
[andrew@Cheetah ripgrep] mkdir 221
[andrew@Cheetah ripgrep] cd 221/
[andrew@Cheetah 221] mkdir -p foo/bar
[andrew@Cheetah 221] echo "hey" > foo/message
[andrew@Cheetah 221] echo "hey" > foo/bar/message
[andrew@Cheetah 221] echo /foo/bar/ > .gitignore
[andrew@Cheetah 221] rg hey
foo/message
1:hey
[andrew@Cheetah 221] cd foo/
[andrew@Cheetah foo] rg hey
message
1:hey
```

The gitignore logic recently went through a major overhaul, and I may have accidentally fixed a few bugs along the way.

I'll see about submitting a PR to homebrew to update.

**Comment by lyuha** [comment]
I submitted PR to https://github.com/Homebrew/homebrew-core/pull/6590, and accepted. So, latest rg is 0.2.6 at homebrew.

**Comment by BurntSushi** [comment]
@lyuha Thanks! ^_^

**Comment by srcreigh** [comment]
Thanks everyone. :smile:
