### ISSUE TITLE
Ripgrep doesn't read configuration

### ISSUE THREAD

**Issue by Pound-Hash** [BurntSushi/ripgrep#2212]
#### What version of ripgrep are you using?

ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

From Arch community repo

#### What operating system are you using ripgrep on?

Arch

#### Describe your bug.

`rg` doesn't read from my config.

#### What are the steps to reproduce the behavior?

Run a search. Matches are printed in red instead of blue, as defined in my `rc`.

The config is located at `/home/USER/.config/ripgrep/rc`.

The config's content is this single line: `--colors=match:fg:blue`

Running `echo $RIPGREP_CONFIG_PATH` produces: `/home/USER/.config/ripgrep/rc`

Running `echo 'this is a test' | rg --debug is` produces:

![image](https://user-images.githubusercontent.com/51193876/168396895-0aac0327-661e-4d41-a971-0efd5ba5ddae.png)

**Comment by BurntSushi** [comment]
Please show the output with `--trace`.

Please also try `echo ... | RIPGREP_CONFIG_PATH=... rg --trace ...` and show the output, with the dots replaced with your stuff.

This is almost certainly not a ripgrep bug, but a setup problem on your end. These types of issues have been filed in the past, and they usually boil down to the environment variable not being set or being set to the wrong value. Please debug your environment.

**Comment by Pound-Hash** [comment]
Here you are:

![image](https://user-images.githubusercontent.com/51193876/168399967-4e492712-2384-44e0-afa0-1ab6d8813174.png)

**Comment by BurntSushi** [comment]
So... Your config file is working then... It read the color setting from it and seems to have applied it. What's the problem?

**Comment by BurntSushi** [comment]
You're doing `export RIPGREP_CONFIG_PATH=/home/...`, right?

**Comment by Pound-Hash** [comment]
Good grief, you're right
