### ISSUE TITLE
type-add: Support for regexpes

### ISSUE THREAD

**Issue by warpspin** [BurntSushi/ripgrep#2233]
I wished --type-add would also support regexpes in addition to globs.

In my current use case, I'd usually like to filter all SQL dumps (*.sql) but still include SQL migration files (*.sql file but starting with a number, so basically [^0-9].*\.sql as a regexp, so I'd love to redefine the sql type to something excluding migrations. But I'm pretty sure more use cases come up once regexpes would be supported.

**Comment by BurntSushi** [comment]
Sorry, but the file filtering and type matching logic is staying with globs for the foreseeable future.

It sounds like you can achieve what you want by adding multiple file types and filtering that way.
