### ISSUE TITLE
max-depth doesn't seem to have an effect

### ISSUE THREAD

**Issue by torqu3e** [BurntSushi/ripgrep#2237]
Per the man page, max-depth is the count of directories deeper than the search path. I have come across a situation where that does not seem to be the case

No results 
```
08:12:31 ✖1 $ rg -i "Offline maintenance of the DB instance is taking place" ~/dev_wip/repo-name/
08:12:43 ✖1 $ rg -i "Offline maintenance of the DB instance is taking place" ~/dev_wip/repo-name/aws/terraform/modules/
08:12:59 $ rg --max-depth 99 -i "Offline maintenance of the DB instance is taking place" ~/dev_wip/repo-name/aws/terraform/modules/
```

Going one level deeper on the search path parameter returns results
```
08:12:57 ✖1 $ rg -i "Offline maintenance of the DB instance is taking place" ~/dev_wip/repo-name/aws/terraform/modules/aws/
/Users/username/dev_wip/repo-name/aws/terraform/modules/aws/rds/instance/monitoring.tf
10:  query = "events('priority:all sources:rds Offline maintenance of the DB instance is taking place. The DB instance is currently unavailable').rollup('count').last('5m') > 0"

08:13:08 ✖1 $ rg --max-depth 99 -i "Offline maintenance of the DB instance is taking place" ~/dev_wip/repo-name/aws/terraform/modules/aws/
/Users/username/dev_wip/repo-name/aws/terraform/modules/aws/rds/instance/monitoring.tf
10:  query = "events('priority:all sources:rds Offline maintenance of the DB instance is taking place. The DB instance is currently unavailable').rollup('count').last('5m') > 0"
```

My first thought was that ripgrep only searches 9 levels deeper than root but based on above it seems to go 3 (default??) deeper than the path given and the `--max-depth` parameter does not change that.

```
$ rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
```

**Comment by torqu3e** [comment]
Apologies re the template, one did not popup when I tried creating an issue (which did seem odd to me).

It most certainly was a `.gitignore` entry of `aws/`. Completely user error/lack of coffee etc. Thank you for pointing that out, where do I send you a beverage for the troubles?

**Comment by BurntSushi** [comment]
No problem. I just see a lot of gitignore related errors, so it's easier for me to sniff'em out.

As for sending beverages, I'm happy to see donations done instead. :-) See: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#donations
