### ISSUE TITLE
--field-context-separator does not work

### ISSUE THREAD

**Issue by 95440b97d** [BurntSushi/ripgrep#2239]
#### What version of ripgrep are you using?
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?
pacman -S ripgrep

#### What operating system are you using ripgrep on?
Arch Linux

#### Describe your bug.
seq 3 | rg -n --field-context-separator=% 2
2:2

Option --field-context-separator is ignored.  The expected output of the above program is '2%2'.

**Comment by BurntSushi** [comment]
From the man page, emphasis mine:

> Set the field context separator, which is used to delimit file paths, line numbers, columns and the context itself, **when printing contextual lines.**

There are zero contextual lines in your example, so it's unclear to me how you're concluding that `--field-context-separator` does not work.

Here's an example that demonstrates it working as intended:

```
$ seq 3 | rg -n --field-context-separator=% 2 -C1
1%1
2:2
3%3
```

I suspect this example may also be useful to you:

```
$ seq 3 | rg -n --field-context-separator=% --field-match-separator=# 2 -C1
1%1
2#2
3%3
```

**Comment by 95440b97d** [comment]
Yes I see. The mistake was on my side. Sorry for the noise we can close this.
