### ISSUE TITLE
.ignore / .rgignore files are not being respected

### ISSUE THREAD

**Issue by ye** [BurntSushi/ripgrep#224]
Not sure if this is a misunderstanding on my part, but I can't seem to get `rg` to respect `.ignore` or `.rgignore` files.

In this example, I can't get `rg` to search the keyword string in the `.hidden-file` with ignore files. But `--hidden` flag does seem to work correctly as expected. Did I miss something with ignore files? 

```bash
$ cat .hidden-file
docker pull python:3.4-wheezy
$ echo \!.hidden-file > .ignore
$ cat .ignore
!.hidden-file
$ rg python:3.4-wheezy
$
$ rg --debug python:3.4-wheezy
DEBUG:grep::search: regex ast:
Concat(
    [
        Literal {
            chars: [
                'p',
                'y',
                't',
                'h',
                'o',
                'n',
                ':',
                '3'
            ],
            casei: false
        },
        AnyCharNoNL,
        Literal {
            chars: [
                '4',
                '-',
                'w',
                'h',
                'e',
                'e',
                'z',
                'y'
            ],
            casei: false
        }
    ]
)
...
DEBUG:rg::ignore: ./.hidden-file ignored because it is hidden
...
$ mv .ignore .rgignore
$
$ rg python:3.4-wheezy
$ 
$ rg --hidden python:3.4-wheezy
.hidden-file
1:docker pull python:3.4-wheezy
```

This is opened as per request by @BurntSushi in #90

**Comment by BurntSushi** [comment]
What version of ripgrep are you using?

**Comment by ye** [comment]
@BurntSushi right on! I was having `0.1.15` and after `brew upgrade ripgrep` to `0.2.8`, it worked like a charm! 

Sorry about it, I had a feeling this is human error from the start ...

**Comment by BurntSushi** [comment]
No problem! I love bugs that fix themselves. :-)
