### ISSUE TITLE
Glob for `-g '**'`  ignores the `.gitignore` whereas `-g '*.*'`  uses `.gitignore`

### ISSUE THREAD

**Issue by mangelozzi** [BurntSushi/ripgrep#2252]
Firstly, maybe this is not a bug but the desired behaviour, if so, then apologies, and sorry for wasting your time. I found the behaviour unexpected.

#### What version of ripgrep are you using?

Replace this text with the output of `ripgrep 11.0.2`.

#### How did you install ripgrep? 

`sudo apt install ripgrep` (I think)

#### What operating system are you using ripgrep on? 

`Ubuntu 20.04`

#### Describe your bug.

A search using `-g '**'` will not use the ignore files. A search using `-g '*.*'` will not use the ignore files

#### What are the steps to reproduce the behavior?

1. Download the attached zip. 
2. `cd` into it. In it are two files:
    - `foo.html` where we want to find a match
    - `htmlcov/bar.html` where we want to ignore matches (there are "autogenerated" test reports)
4.  Run the following search, you will see one match, the .gitignore file is used to ignore the match in `htmlcov`
    ```
    $ rg -g '*.*' pattern
    foo.html
    1:<p>pattern</p>
    ```
3.  Run the following search, you will see the .gitignore file is **NOT** used, it finds additional entries:
    ```
    $ rg -g '**' pattern
    foo.html
    1:<p>pattern</p>

    htmlcov/bar.html
    1:<p>pattern</p>

    .git/info/exclude
    4:# exclude patterns (uncomment them if you want to use them):
    ```

#### What is the actual behavior?

It fails to use the `.gitignore` file when using the glob pattern `**`, however if one uses the glob pattern `*.*` then it uses the `.gitignore` file.

#### What is the expected behavior?

Always apply the `.gitignore` rules unless one uses `--no--ignore`

[testrg.zip](https://github.com/BurntSushi/ripgrep/files/9037865/testrg.zip)

**Comment by BurntSushi** [comment]
Yeah this is intended behavior. The `-g` flag is specifically overriding your gitignore. That's how it's intended to work. It's just like how a `.ignore` file will override a `.gitignore`. Since `**` matches everything, it effectively whitelists everything and thus overrides every rule in your gitignore. This is not only correct, but to do it any other way would likely lead to madness. :)
