### ISSUE TITLE
only matching -o<number> option

### ISSUE THREAD

**Issue by mikez** [BurntSushi/ripgrep#2281]
#### Describe your feature request

[pcre2grep](https://github.com/PCRE2Project/pcre2) has a handy option `-o<number>`.

From the [documentation](https://pcre2project.github.io/pcre2/doc/html/pcre2grep.html):
```
-onumber, --only-matching=number
    Show only the part of the line that matched the capturing parentheses of the given number.
```

If `rg` had this, it would allow you to do things like

```sh
$ echo https://github.com/BurntSushi/ripgrep/issues/2281 | rg -o1 'github.com/(\w+)/'
BurntSushi
``` 

Currently, this can be achieved by the more verbose:

```sh
... | rg -or '$1' 'github.com/(\w+)/'
``` 
or
```sh
... | rg -o --pcre2 '(?<=github.com/)\w+(?=/)'
```

**Comment by BurntSushi** [comment]
`-or '$1'` is just barely more verbose and I'm fine with it. It is not even close to being verbose enough to introduce another way to do the same thing. Sorry.

**Comment by mikez** [comment]
Thanks for the fast reply.
