### ISSUE TITLE
Add support for Solidity/*.sol file type

### ISSUE THREAD

**Issue by johnsaigle** [BurntSushi/ripgrep#2283]
#### Describe your feature request

Add Solidity file type to the list of supported files and extensions for the --type flag. Should match *.sol extensions

Not supported as of this rg version:
ripgrep 13.0.0
-SIMD -AVX (compiled)

**Comment by BurntSushi** [comment]
I don't track requests to add things to the default type definitions. Instead, just submit a PR please. Thanks.

For more obscure file types (I've never heard of Solidity), please include some link explaining what it is.

Thanks!
