### ISSUE TITLE
Option to ignore git submodules

### ISSUE THREAD

**Issue by Mmdixon** [BurntSushi/ripgrep#23]
`git grep` by default does not search for files within a git submodule, even though they appear like normal directories.
`rg` on the other hand will by default recurse into these directories.

Since `.gitignore` is supported, it would be convenient to support how git searches when there are submodules. (Either by default and turn off with one of the `-u` flags, or provide some other flag besides explicitly black listing the submodule folders.)

**Comment by BurntSushi** [comment]
How can `rg` detect whether a directory is a submodule or not?

(Running a `git` command is not something I want to do.)

**Comment by BurntSushi** [comment]
I'd like to close this. If there's a simple way to detect submodules that doesn't sacrifice performance, I might be willing to support that. One thing I'm worried about is that I personally don't have much experience with submodules, so I don't know whether it's the Right Thing to ignore them or not. My suspicion is yes, it is right, because I tend to see them used as a way to vendor dependencies.

**Comment by mgee** [comment]
If it is going to be implemented please make it optional. Internal libraries shared between multiple projects can also be included as submodules. In that case I want to search them too e.g. when performing a global refactoring.

**Comment by Mmdixon** [comment]
@BurntSushi there will be a `.gitmodules` file with a list of the following format:
```
[submodule "myName"]
	path = src/myName
	url = someUrl
# repeat
```
Here, the `path` has the folder `src/myName` the start of the submodule (which is another git repository).

**Comment by Kha** [comment]
More importantly, there should be a `.git` _file_ in the submodule workdir. So a general option to ignore nested repositories should cover submodules.

**Comment by Mmdixon** [comment]
ah that is true too,  a `.git` file instead of folder in the submodule directory.

**Comment by BurntSushi** [comment]
I think the `.git` file thing is a newer feature of `git` though?

I think I'd like to ask that you use `.ignore` files to explicitly skip searching submodule directories.

With that said, if someone submitted a PR to the `ignore` crate that added support for ignoring submodules (which was disabled by default), then I'd be OK adding a new flag to ripgrep to enable that.

**Comment by BurntSushi** [comment]
I'm going to close this as part of a process of culling the issue tracker to things that are likely to be implemented. I think my previous comment still stands, but I would still rather not add a new flag and instead just insist that this be part of using ripgrep's `.ignore` file functionality.

**Comment by BatmanAoD** [comment]
Would you still be open to a PR on the `ignore` crate to support ignoring nested git directories?

> I think the `.git` file thing is a newer feature of `git` though?

If I understand correctly, the idea is just to check for the existence of the standard `.git/` directory containing `git` metadata, so not a new feature of `git` at all. I.e., the check would be something like:

* when searching in a git repository rooted at `/repo/root`,
* if `/repo/root/foo/bar/.git/` exists,
* ignore all of `/repo/root/foo/bar`.
