### ISSUE TITLE
execute shell command on all files which are matched

### ISSUE THREAD

**Issue by makarono** [BurntSushi/ripgrep#2305]
#### Execute arbitrary shell command

It would be nice feature if when using -l option could execute command on those files

example:

```
rg -l test -X sed -i 's:test:foo:g' {}
```

same thing as fd find does with -X option and gnu-find with --exec option

**Comment by BurntSushi** [comment]
I think this is beyond the scope of ripgrep. I'd encourage you to use `xargs` or some other mechanism.
