### ISSUE TITLE
`-c` (`--count`) does not count multiple times in same line

### ISSUE THREAD

**Issue by nopeless** [BurntSushi/ripgrep#2333]
I am sure that this is intended behavior

However, I would like an option to count multiple times in a single line. If there is already a way to do this (thats not written in the docs) let me know

**Comment by BurntSushi** [comment]
This is correct, documented, intended and consistent with grep. Moreover, the documentation for `--count` answers your question: https://github.com/BurntSushi/ripgrep/blob/4386b8e805e273a9795ad4e256c455c74407c949/crates/core/app.rs#L1057

Use `--count-matches` or `-oc`.
