### ISSUE TITLE
limit search to specific namespaces and classes

### ISSUE THREAD

**Issue by phipse** [BurntSushi/ripgrep#236]
Hi,
I'd like to be able to focus the search in a C++ code base to classes/functions in specific namespaces;
Meaning, I'd like to do something like this:
```sh
rg ns::Foo ./path/
```

and get a result 'class Foo' defined in namespace 'ns' ; and no results of 'class Foo'  defined in other namespaces.

Or if I am looking for a function 'fn' in class 'Bar', I'd like to do:
```sh
rg Bar::fn ./path/
```
and get not only a result for a member function definition outside the class declaration, which already contains the string "Bar::fn", e.g.:

```c++
void Bar::fn(int a, int b) { ... }
```

but also results for a function definition 'fn' inside a class declaration e.g.:
```c++
class Bar {
void fn(int a, int b) { ... }
};
```
Is something like this already possible?

**Comment by BurntSushi** [comment]
This requires language aware search. As of right now, ripgrep is a *general purpose line oriented search tool*. Language aware search is not something ripgrep currently supports, and it's not really on the horizon either. Language aware search would require *significant effort*.

The closest thing to your request (and it's admittedly not *that* close*) is #95, which is about adding fulltext search to ripgrep. It doesn't have to be strictly language aware, but having language aware tokenizers could potentially improve the quality of results. However, language aware tokenizers is a totally different story than actually understand language level concepts like classes or namespaces.

Maybe something like this will appear in ripgrep (or a related tool) some day, but I'd expect that time scale to be measured in *years*. So I'm just going to close this for now.

**Comment by BurntSushi** [comment]
@phipse Out of curiosity, is there another tool you use that has this feature? (Other than something like a specific C++ IDE plugin or something.)

**Comment by phipse** [comment]
No, there isn't, unfortunately. Is there a way to match the corresponding closing brace using ripgrep,  such that I can search for "namespace Foo \{.*\}" ?

In my head it's basically this:
```
for each file in `rg -l "namespace Foo"`:
do
rg "class Bar" file
done;
```
and in between count the opening and closing braces to limit the content of `file` to the namespace.
A language aware tokenizer would be nice to have, but I think for my use case this might also be a little bit over the top.

**Comment by BurntSushi** [comment]
> Is there a way to match the corresponding closing brace using ripgrep, such that I can search for "namespace Foo {.*}" ?

ripgrep is line-oriented. It doesn't support multi-line search. Stated more clearly: no part of a regex can ever match a `\n`.

> and in between count the opening and closing braces to limit the content of file to the namespace.

In normal operation, ripgrep never actually holds the contents of an entire file in memory (unless it happens to be small enough to fit into ripgrep's buffer).

> A language aware tokenizer would be nice to have, but I think for my use case this might also be a little bit over the top.

But the specification you've described *is* language aware. (I only mentioned a language aware *tokenizer* in the context of *fulltext search*. I agree that it is both insufficient and overkill at the same time for your problem.) More to the point, the implementation path you've described is also insufficient. You can't just count braces because they can appear inside of strings or comments where they have no significance.

---

I will say this: I do continue to noodle on the possibility of multi-line search, because it is occasionally useful, and it could possibly bail you out too in a problem like this. There are unfortunately significant performance trade offs that come with multi-line search though (both time *and* memory), so it needs careful thought and probably won't happen soon.

**Comment by phipse** [comment]
Alright, thanks a lot for your thoughts.

**Comment by forgottenswitch** [comment]
> for each file in `rg -l "namespace Foo"`:
do
rg "class Bar" file
done;
`rg Func $(rg -l Namespace)` ?

**Comment by forgottenswitch** [comment]
> for each file in `rg -l "namespace Foo"`:
do
rg "class Bar" file
done;

Shorter: `rg Func $(rg -l namespace.\*Namespace)`
(assumes that file paths do not contain spaces).

Or: `cg -l namespace.\*Namespace Func`

Perhaps it's worth adding an `-ll` option.

**Comment by forgottenswitch** [comment]
> for each file in `rg -l "namespace Foo"`:
do
rg "class Bar" file
done;

Shorter: `rg Func $(rg -l namespace\*Namespace)`
Or: `cg -l namespace\*Namespace Func`

`-ll` would probably make sense, but ...
```
   Compiling ripgrep v0.3.0 (file:///home/user/repo/text/ripgrep)
error: failed to run custom build command for `ripgrep v0.3.0 (file:///home/user/repo/text/ripgrep)`
process didn't exit successfully: `/home/user/repo/text/ripgrep/target/debug/build/ripgrep-581e9751039aff66/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Argument short must be unique

        -l is already in use', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.18.0/src/app/parser.rs:148
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by forgottenswitch** [comment]
A quick and partial solution would probably be `--replace` for args, i.e. `rg_struct foo bar` => `rg --replace-args 'struct ($|) {' foo bar` => `rg 'struct (foo|bar) {'`.
