### ISSUE TITLE
sorting results by path properties

### ISSUE THREAD

**Issue by nguyenvukhang** [BurntSushi/ripgrep#2365]
As outlined in https://github.com/BurntSushi/ripgrep/issues/2243, results are incorrectly sorted by file stats (modified/created/accessed time).

One approach is to make the recursive directory traversal smarter. For example, when sorting by latest modified, the parent directory will be assigned the latest modified time of all its children, rather than the direct result of calling `stat` on it.

Another approach will be to sort the results after all search results have been matched and collected. This will likely collecting all results into memory, tagging each result with a key based on the sorting criteria, and sorting the results by this key.

**Comment by BurntSushi** [comment]
Let's try to keep this in one issue instead of creating many for the same problem. I moved this comment to [here](https://github.com/BurntSushi/ripgrep/issues/2243#issuecomment-1331166864).
