### ISSUE TITLE
Add an option to open matching files in $EDITOR

### ISSUE THREAD

**Issue by jkramer** [BurntSushi/ripgrep#237]
Add an option (maybe -E) that, when set, makes rg go silent (no console output) and instead after finishing the search run `$EDITOR <file1> [file2] ...` with the matching files, as a convenient shortcut to `vim $(rg ...)`.

**Comment by BurntSushi** [comment]
Have you tried `vim $(rg -l foo)`? If not, does that work for you? If so, why doesn't it work for you?

**Comment by jkramer** [comment]
That's what I'm currently doing. As I said in the original comment, it's about having a convenient shortcut to doing exactly that. I (and I guess many others) often search something, look at the result and then decide that I have to edit the file(s). Just going one up in the shell history and adding -E is really convenient and saves a lot of time. I've added this in [rst](https://github.com/jkramer/rst/blob/master/rst) (slimmer faster version of ack I made long ago) and don't wanna miss it. :)

**Comment by BurntSushi** [comment]
I still don't quite buy it. Put this in `~/bin/rge`:

```
#!/bin/sh
exec vim $(rg -l "$@")
```

Now you can do:

```
$ rg foo
# i want to see in vim
$ rge foo
```

... which seems about roughly equivalent to adding `rg -E`.

Note that I've resisted a similar feature that causes the results of ripgrep to open in a pager by suggesting this alternative in `~/bin`:

```
#!/bin/sh
exec rg -p "$@" | less -RFX
```

**Comment by BurntSushi** [comment]
OK, I'm going to close this because I think it's relatively easy to make this work in a low effort way without adding support to ripgrep proper.

**Comment by mlippert** [comment]
I agree no need to add support in ripgrep proper, but your comment above, pretty much verbatim would make a good FAQ entry.

**Comment by bradleybossard** [comment]
FWIW, I'm kind of a fan of this tool

https://github.com/aykamko/tag

which augments the `ripgrep` output with a numbering system, then allows you to type `e<number>` to jump straight to that result in VIM.

**Comment by matkoniecz** [comment]
It seems that following works well when you use `.bashrc` file:

```
rgopen() {
    #do things with parameters like $1 such as
    echo "$@"
    echo $(rg -l "$@")
    codium $(rg -l "$@")
}
```
https://github.com/matkoniecz/dotfiles_public/commit/1a4313efac57d373136394dd2a960ea0c1180f11

**Comment by matkoniecz** [comment]
@BurntSushi 

> Have you tried vim $(rg -l foo)? If not, does that work for you? If you have tried it, why doesn't it work for you?

is seems that it will fail for files with spaces in them
