### ISSUE TITLE
rename the `-r` option

### ISSUE THREAD

**Issue by ChrisJefferson** [BurntSushi/ripgrep#24]
I just got very confused for quite a while, as my fingers tend to just naturally type `-r` which wanting a recursive search sometimes. The current `-r` does something (to me) really confusing (I'm not really sure what it would be useful for, but I'm sure it was added for a reason). However, it is (in my opinion) worth considering leaving `-r` unused, as it's such a common option people give to `grep` (then at least they get an error message).

**Comment by BurntSushi** [comment]
The `-r` flag is short for `--replace`, which pretty much does what it says on the tin: it replaces each match with the value given to the flag, expanding capturing groups if necessary.

Can you suggest an alternative shorthand for `--replace`?

**Comment by durka** [comment]
You could use `-s` (like `sed s/.../.../`). But unfortunately `s` isn't one of the letters in `replace` :/

**Comment by BurntSushi** [comment]
I'm sympathetic to this request. Muscle memory is tricky. But I really like `-r` as a short hand for `--replace`.

I'd prefer we try to fix this by making it clearer that `rg` will do recursive search. I added some clarification to the output of `--help`.

**Comment by cmgsplk** [comment]
@BurntSushi Maybe at least include this warning in the README.md?.   I found ripgrep a year or two ago (grep->ack->silversearcher).... 

grep -r (recursive) memory  getting confused  -> ends up nuking lots of files.  Fortunately, it was a fresh repo checkout but even figuring out what the glob actually replaced would have been a painful day in another directory :)

**Comment by BurntSushi** [comment]
> Maybe at least include this warning in the README.md?

It is: "ripgrep is a line-oriented search tool that recursively searches your current directory for a regex pattern."

> grep -r (recursive) memory getting confused -> ends up nuking lots of files.

What? ripgrep doesn't nuke anything. I don't know what you're talking about. When complaining, please be **specific.**

**Comment by cmgsplk** [comment]
Ack @BurntSushi;   You're correct and it's my bad.   I only saw it on the OUTPUT side and was bewildered :)

**Comment by nullbio** [comment]
This has been causing problems in many different AI models for a while now. @BurntSushi 

I get that this isn't your problem, but I've resorted to blocking Claude's access to rg as a result of this, which is... Unfortunate :<
