### ISSUE TITLE
Slight documentation clarification

### ISSUE THREAD

**Issue by nyurik** [BurntSushi/ripgrep#2401]
I think the first documentation line should clarify that `ripgrep` searches the **content** of the files, as oppose to the filenames that match regex (like `fd`).

Current description:

> `ripgrep` is a line-oriented search tool that recursively searches the current
directory for a regex pattern.

Some ideas (not sure about the wording yet):

> `ripgrep` recursively searches for text files whose content matches a regular expression pattern.

**Comment by BurntSushi** [comment]
I settled on this:

```
ripgrep (rg) recursively searches the current directory for lines matching
a regex pattern. By default, ripgrep will respect gitignore rules and
automatically skip hidden files/directories and binary files.
```

**Comment by nyurik** [comment]
Do you think `the current directory` is needed in the description?  Seems like `recursively searches for lines ...` is descriptive enough.

**Comment by nyurik** [comment]
P.S. tbh `lines` is also a bit of a minor confusion - usually novice users think of files in terms of content or text.  The fact that its a line search tool is more of an implementation detail (that might even be overridable with various multiline regexes?). So perhaps something like this? (sorry for bikeshading):

```
ripgrep (rg) recursively searches file content matching a regex pattern.
By default, ripgrep will respect gitignore rules and automatically skip
hidden files/directories and binary files.
```
