### ISSUE TITLE
Issue when run in a subprocess

### ISSUE THREAD

**Issue by lyrixx** [BurntSushi/ripgrep#2434]
#### What version of ripgrep are you using?

```
rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

with cargo

#### What operating system are you using ripgrep on?

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

#### Describe your bug.

RG return the list of the file, instead of what it matches in the document

#### What are the steps to reproduce the behavior?

Use the following code to reproduce:

```
mkdir ripgrep
cd ripgrep

touch a b c d e
cat > CHANGELOG.md <<'EOF'
CHANGELOG
=========

6.3
---

 * foo bar baz

6.2
---

 * something else

EOF
```

I have a more complex regex, but I have simplified it to show the bug

Not in a sub-shell, no trailing space ✅ 
```
rg '6.3\n---\n\n' -U --multiline-dotall  CHANGELOG.md 
4:6.3
5:---
6:
```

Not in a sub-shell, with trailing space ✅ 
```
>/tmp/foobar/ripgrep rg '6.3\n---\n\n ' -U --multiline-dotall  CHANGELOG.md 
4:6.3
5:---
6:
7: * foo bar baz
```

In a subshell, no trailing space ✅ 
```
echo `rg '6.3\n---\n\n' -U --multiline-dotall  CHANGELOG.md` 
6.3 ---
```

In a subshell, with trailing space ❌ 

```
                                          #⬇ There is a trailing space here
>/tmp/foobar/ripgrep echo `rg '6.3\n---\n\n ' -U --multiline-dotall  CHANGELOG.md` 
6.3 --- a b c CHANGELOG.md d e foo bar baz
```

---

As you can see, there is something super strange. As soon as I put a trailing space, rg print in the middle of the output the files in the current directly!

**Comment by lyrixx** [comment]
Ohhhh. Just understood the bug ! Sorry for the noise !

**Comment by BurntSushi** [comment]
If you fix your own problem, it is good practice to include the answer so that if others have the same problem, it will be more helpful. In this case, I actually get different output than you for the last example:

```
$ echo `rg '6.3\n---\n\n ' -U --multiline-dotall  CHANGELOG.md`
6.3 --- * foo bar baz
```

Which looks correct to me. That trailing space matches something on the next line, and thus ripgrep prints the whole thing.

I don't think this has anything with running ripgrep as a sub-process. The output is just a little weird because you're passing it to `echo`.

**Comment by lyrixx** [comment]
Sorry for not putting my answer here :( 

the problem was indeed about echoing something that containes `*` and so it globs...

I fixed the issue by surrounding it with `"`:


```
>/tmp/foobar/ripgrep echo `rg '6.3\n---\n\n ' -U --multiline-dotall  CHANGELOG.md` 
6.3 --- a b c CHANGELOG.md d e foo bar baz
>/tmp/foobar/ripgrep echo "`rg '6.3\n---\n\n ' -U --multiline-dotall  CHANGELOG.md`"
6.3
---

 * foo bar baz
```
