### ISSUE TITLE
an 'execute' option like in find/fd (--exec/-x)

### ISSUE THREAD

**Issue by marcotrosi** [BurntSushi/ripgrep#2442]
#### Describe your feature request

I would like to have an 'execute' option like in find/fd (--exec/-x) to run a command for every file that contains a matching or non-matching pattern.
I know this can be solved in the shell but it's annoying.

Just to be clear, the pattern shall very normally match the content, and not the filename. For that we have find/fd.
But the execution of a command shall be on the files that contain that pattern.
e.g.
`rg 'some.*pattern' --exec mv {} subfolder/`

**Comment by BurntSushi** [comment]
I think this is beyond the scope of what I want to be in ripgrep. I myself avoid using things like `--exec` in tools that have them today, because it's basically another little DSL you have to understand that is embedded inside your shell. So I actually find it far _more_ annoying than just using the shell or something like `xargs`.

**Comment by BurntSushi** [comment]
> Why is this in particular any different?

There are an unbounded number of ways that ripgrep can reduce or eliminate boiler plate. I can't accept and maintain all of them. Therefore, I must draw a line somewhere between "we do some things that reduce boiler plate" and "we avoid doing other things that reduce boiler plate." Where that line is drawn is not informed by some rigorous formal process that consistently follows a sequence of objective criteria. Loosely speaking, it is informed by, in no particular order:

1. My perception of how broad the utility of the feature is.
2. What work-arounds look like.
3. Implementation complexity.
4. How likely it is to beget more feature requests.

This just doesn't clear the bar for me. Sorry.

**Comment by marcotrosi** [comment]
fair. It's your project and I'm happy you responded to the proposal. I can work with xargs too. Thanks, and thanks for ripgrep. Have a great day :-)
