### ISSUE TITLE
[BUG REPORT] RHEL/Rocky Linux 9.1 install fails / SHA1 deprecated

### ISSUE THREAD

**Issue by cocoonkid** [BurntSushi/ripgrep#2459]
#### What version of ripgrep are you using?

latest

#### How did you install ripgrep?

```
yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
dnf install ripgrep
```

#### What operating system are you using ripgrep on?

Rocky Linux 9 which is 100% compatible with RHEL/CentOS

#### Describe your bug.

warning: Signature not supported. Hash algorithm SHA1 not available.

#### What are the steps to reproduce the behavior?

try it out as I did

additonal information '>

RHEL 9 deprecating and no longer enabling SHA1 out of the box

Please upgrade your key :)

**Comment by BurntSushi** [comment]
I don't know why you're reporting problems with your distro's package manager install here. You need to go ask them for help. Not me. I don't have anything to do with how RHEL/Rocky packages their stuff.

**Comment by cocoonkid** [comment]
Apology. I thought you maintain the package and it's your key.!
