### ISSUE TITLE
Check for special case option error `-heading` and `-hidden` and print a warning in addition to displaying help.

### ISSUE THREAD

**Issue by rljacobson** [BurntSushi/ripgrep#2461]
#### Describe your feature request

Suppose some bonehead were to accidentally leave off a dash from either the `heading` or the `hidden` options:

```bash
$ rg -heading myneedle .
```

ripgrep correctly interprets the `-h` and dutifully prints the help message. This probably wouldn't throw a normal person, but imagine a bonehead getting this result. Since ripgrep usually prints an error in the case of invalid invocation, that bonehead might even think there is a bug in ripgrep! 

Obviously ripgrep *should* continue to behave correctly, but maybe it could also print a warning in the special cases of the two options that start with an `"h"`? This is a somewhat obscure error case, but it's also presumably trivial to implement. 🤷

**Comment by rljacobson** [comment]
Yeah, that actually makes a lot of sense. Argument parsing is a huge pain in the ass. I use a library for anything that isn't completely trivial. 

In the presence of `-h` (or equivalent), other options are ignored. If you could detect the presence of *any* other options, you could warn the user under the assumption that the user expected the other option(s) to do something. Given the subtleties you point out, I don't know if Clap makes this possible or easy, nor am I confident that it's the right thing to do. 😄

What is interesting to me is how there is a category of things that we teach students to do that are actually *bad* practices. Almost every book and tutorial I've seen does argument parsing by hand. Granted the arguments being parsed are usually simple, but as you point out even simple cases can require complicated implementations if one wants to follow standard conventions. So books and tutorials just don't follow standard conventions!

**Comment by BurntSushi** [comment]
> In the presence of `-h` (or equivalent), other options are ignored. If you could detect the presence of _any_ other options, you could warn the user under the assumption that the user expected the other option(s) to do something. Given the subtleties you point out, I don't know if Clap makes this possible or easy, nor am I confident that it's the right thing to do. smile

I actually wouldn't want to do this anyway, because I consider it valid to tack on a `-h` or `--help` at the end of a command and reliably get the `--help` output. A warning could in theory be okay there, but it's a valid use case to me and so not something I want to warn about I don't think.
