### ISSUE TITLE
Filter out files by last modified age. 

### ISSUE THREAD

**Issue by nickolay-kondratyev** [BurntSushi/ripgrep#2475]
#### Describe your feature request

Provide an option along the lines of `find -mtime` to only look at files that were modified in the last X minutes.

```
    -mtime n[smhdw]
             If no units are specified, this primary evaluates to true if the difference between the file last modification time and the time find was started, rounded up to the next full
             24-hour period, is n 24-hour periods.

             If units are specified, this primary evaluates to true if the difference between the file last modification time and the time find was started is exactly n units.  Please
             refer to the -atime primary description for information on supported time units.
```
Doesn't have to have units, can be simplified to just accept `--modified-in-last-minutes X`

The idea is to be able to look within code files that were modified in the last hour, in the last day etc...

The main use case is to be able to do something along the lines of `rg --modified-in-last-minutes X --glob '*.your-extension' | fzf` which doesnt seem to work if we try to use `find` before using `rg`

**Comment by BurntSushi** [comment]
I think this is too much scope creep. And it is a feature that will beget more features. If we allow filtering by mtime, then what about creation time? And various other attributes?

I think it would be better to just use `find` and build a pipeline with ripgrep.

**Comment by BurntSushi** [comment]
> The main use case is to be able to do something along the lines of rg --modified-in-last-minutes X --glob '*.your-extension' | fzf which doesnt seem to work if we try to use find before using rg

I don't see any reason why using `find` wouldn't work here.
