### ISSUE TITLE
Release for fedora 25 in copr

### ISSUE THREAD

**Issue by SanketDG** [BurntSushi/ripgrep#249]
The [copr](https://copr.fedorainfracloud.org/coprs/carlgeorge/ripgrep/) is not enabled for the newly released fedora 25!

**Comment by BurntSushi** [comment]
I don't know what the copr is and I am sure there is nothing I can do to fix it. I think you need to get in touch with the maintainer of the package. I think that might be @carlwgeorge.

**Comment by carlwgeorge** [comment]
Yes, that's my copr.  Copr is a build service provided by the Fedora project.  It is similar to Ubuntu PPA's.  It is just a temporary repo until I can get ripgrep into the main Fedora/EPEL repos.  The [cargo release](https://bodhi.fedoraproject.org/updates/FEDORA-2016-2ca07f1b54) for F25 has not yet been pushed to stable.  Once it is I can enable F25 in the ripgrep copr.

**Comment by carlwgeorge** [comment]
I figured out how to temporarily enable the Fedora updates-testing repository in the copr, so it can now be used with Fedora 25.  This ticket can be closed.

**Comment by SanketDG** [comment]
Thanks, I just installed `ripgrep` on my Fedora 25. :fire: :boom:
