### ISSUE TITLE
Surprising application of .gitignore in rust-lang/rust repo

### ISSUE THREAD

**Issue by brson** [BurntSushi/ripgrep#25]
This may be working as designed but it was quite surprising. If I run `rg LLVM_BINDINGS` from the top level of the rust repo I get results. If I do the same from `src/` I get no results. The reason is that rust's .gitignore file contains `/llvm/`.

Perhaps this is how .gitignore is defined to work, but it's not what I expected. I might expect that .gitignore would by applied relative to the directory in which it is defined.

**Comment by foophoof** [comment]
According to `gitignore(5)` on my system (OS X running Git 2.9.0) (emphasis mine):

> - Patterns read from a .gitignore file in the same directory as the path, or in any parent directory, with patterns in the higher level files (up to the toplevel of the work tree) being overridden by those in lower level files down to the directory containing the file. **These patterns match relative to the location of the .gitignore file.** A project normally includes such .gitignore files in its repository, containing patterns for files generated as part of the project build.

So I think your expectation is correct, that it _should_ match relative to the location of the file, not the current directory.

**Comment by BurntSushi** [comment]
It is indeed a plain ol' bug.
