### ISSUE TITLE
Gcc 8.4 ```-mno-outline-atomics```

### ISSUE THREAD

**Issue by predators46** [BurntSushi/ripgrep#2527]
Openwrt
Gcc 8.4
Rust 1.70.0

i found an error while compiling in openwrt using gcc 8.4

```cargo:warning=aarch64-openwrt-linux-musl-gcc: error: unrecognized command line option '-mno-outline-atomics'; did you mean '-fno-inline-atomics'?```

**Comment by BurntSushi** [comment]
Dunno. This isn't really a question I can answer. A C compiler shouldn't be needed at all for the default build. I believe it's only needed if you include PCRE2. Which means this is probably more of a PCRE2 question? But I'm just guessing. This is probably something you'll have to dig into on your own.

It might help others help you if you provide a way to reproduce your error. For example, you haven'y provided any build commands that you're using.

**Comment by predators46** [comment]
https://github.com/openwrt/packages/blob/master/utils/ripgrep/Makefile

**Comment by predators46** [comment]
if i use gcc 11 i can make it work. i want to use gcc 8

**Comment by BurntSushi** [comment]
Try work PCRE2. Otherwise it is a non-goal of this project to support arbitrarily old compiler toolchains. Sorry.

**Comment by predators46** [comment]
Thanks
