### ISSUE TITLE
Install documentation request

### ISSUE THREAD

**Issue by briskt** [BurntSushi/ripgrep#2531]
#### Describe your feature request

Being my first day learning about ripgrep, I am very excited to know that it exists. Thank you for creating and maintaining it!!!

I just about installed it using the .deb download, but thankfully I read on and found that it is officially maintained by Debian. That, of course, means that it is available in Debian/Ubuntu derivatives like PopOS. Since Buster is now double-superseded, the whole Debian section of the install docs could probably be replaced by a simple `sudo apt install ripgrep` with the appropriate note about derivative distributions. Just my two cents.

Thanks again!

**Comment by BurntSushi** [comment]
Thanks. I made a small tweak to the wording, but the rest of it really should stay. The `deb` package installation steps, for example, are important because Debian usually has very old versions of software. The `deb` package provides an easy way for users to opt into something newer.
