### ISSUE TITLE
Default preprocessor configuration by file type

### ISSUE THREAD

**Issue by rosejn** [BurntSushi/ripgrep#2542]
#### Describe your feature request

Since ripgrep already has support for preprocessor scripts, it would be great if we could specify a set of preprocessor scripts and/or commands by filetype in the config file.  For example we could use pdftotext for pdfs like you show in the documentation, but also nbdime for ipython notebooks, even OCR for images, etc.

Thanks for a great tool!

**Comment by BurntSushi** [comment]
You should do this in the preprocessor script itself. I don't see any reason why it needs to be baked into ripgrep.
