### ISSUE TITLE
/n is not include in the "." in multiline mode 

### ISSUE THREAD

**Issue by hawktang** [BurntSushi/ripgrep#2548]
#### What version of ripgrep are you using?

ripgrep 13.0.0
-SIMD -AVX (compiled)
#### How did you install ripgrep?
brew

#### What operating system are you using ripgrep on?

MacOS 13.3

#### Describe your bug.

/n is not include in the "." in multiline mode 

#### What are the steps to reproduce the behavior?

success\t.*?dept:ssq(.|\n)*?(?=\n\d{4}-\d{2}-\d{2})

need to be used instead of 

success\t.*?dept:ssq.*?(?=\n\d{4}-\d{2}-\d{2})

#### What is the actual behavior?

\n was ignored when use . pattern  in multiline mode

```
rg -U --pcre2 "success\t.*?dept:proc(.|\n)*?(?=\n\d{4}-\d{2}-\d{2})" logs > proc.log

```

#### What is the expected behavior?

\n should include when use . pattern  in multiline mode

```
rg -U --pcre2 "success\t.*?dept:proc.*?(?=\n\d{4}-\d{2}-\d{2})" logs > proc.log
```

**Comment by hawktang** [comment]
Sorry, we have --multiline-dotall

and maybe always enable this is not a good idea.

**Comment by BurntSushi** [comment]
You can also use `(?s:.)`. This is indeed intended behavior.
