### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by aakarshan-raj** [BurntSushi/ripgrep#2551]
#### What version of ripgrep are you using?

not applicable 

#### How did you install ripgrep?

i am compiling

#### What operating system are you using ripgrep on?
linux

#### Describe your bug.

compilers issuse error code[E0658] at 4 instance while compiling and aborts.sighting "use of unstanble feature 'is_terminal'" 

#### What are the steps to reproduce the behavior?
 clone the repo
 cd in to it
 `cargo build --release`

**Comment by BurntSushi** [comment]
You're probably using a version of Rust that is too old. I believe you need Rust 1.70.

(The README is unfortunately out of date and so is the `rust-version` in `Cargo.toml`. Once that's updated, you'll get a better error message here.)

If upgrading your Rust toolchain isn't feasible or isn't something you want to do, then you'll need to build an older version of ripgrep. Try `git checkout 13.0.0`.
