### ISSUE TITLE
Is there a new release in 2023 or very soon?

### ISSUE THREAD

**Issue by Coresi7** [BurntSushi/ripgrep#2558]
Dear contributors and owners:
I know ripgrep is not a kind of some application which is keen on release new versions, but it's been a while that ripgrep has no new version for almost two years.
Hope it has a new version released which make your recent efforts meaningfull!
Thanks!

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#release
