### ISSUE TITLE
Suggestion: add strip = true to [profile.release] in Cargo.toml instead of calling `strip` in .github/workflows/release.yml

### ISSUE THREAD

**Issue by jennydaman** [BurntSushi/ripgrep#2564]
Cargo can strip binaries for you, simplifying your CI yamls just a bit.

See https://github.com/johnthagen/min-sized-rust#strip-symbols-from-binary

https://github.com/BurntSushi/ripgrep/blob/304a60e8e9d4b2a42dc3dfb1ba4cef6d7bf92515/.github/workflows/release.yml#L128-L140

**Comment by BurntSushi** [comment]
Yes I'm aware. But I don't want stripping happening automatically for every build. Just CI release builds. Probably the answer to that is a new named profile, which is somewhat newer at the time scales that I move at.

Thanks for the suggestion.
