### ISSUE TITLE
Detect filetype by head of file content instead of extension name

### ISSUE THREAD

**Issue by spin6lock** [BurntSushi/ripgrep#2579]
#### auto detect filetype by head of the file

ripgrep detect compress file type by extension name. It would be nice that support filetype detection by head of file. Then we can search zst file by not only naming *.zst, but also *.zst.1, *.zst.2 etc. Such as this in [zgrep test_format function](https://fossies.org/linux/zutils/zutils.cc).

The usage is the same as old one, no changes in manpage

**Comment by BurntSushi** [comment]
I don't have any plans to implement this, sorry. There is a big difference between detecting file type by looking at the name and actually opening the file and reading its contents. The latter requires a lot more work.

**Comment by spin6lock** [comment]
ok, thanks for sharing your thought
