### ISSUE TITLE
add -l / --files-with-matches option?

### ISSUE THREAD

**Issue by Roguelazer** [BurntSushi/ripgrep#26]
I use the `-l` option to grep / ack / ag / etc quite a lot to list files containing matches for further processing in a shell pipeline. Does it seem reasonable as a thing to add to ripgrep?

**Comment by BurntSushi** [comment]
Does `-c`/`--count` satisfy your use case?

**Comment by andschwa** [comment]
@BurntSushi at least my use case is generally `ag -l something | xargs ...`, so `-c` doesn't work without an intermediate `awk` or something to strip the count.

**Comment by BurntSushi** [comment]
That's reasonable. `grep` also has these options, so it seems fine for `rg` to grow them as well.

**Comment by andschwa** [comment]
I was looking at adding it to `ucg` yesterday... now I'm looking at doing it here (I do like Rust more!) (but no promises; recovering from a cold and might give up to play some video games).

**Comment by BurntSushi** [comment]
@andschwa No worries! I might actually bang this out tonight.

**Comment by andschwa** [comment]
@BurntSushi Hey I just got it working! Let me get some tests and docs written and cleaned up, and I'll open a PR.

**Comment by BurntSushi** [comment]
@andschwa Oh you're quick, awesome, thank you!

**Comment by andschwa** [comment]
@BurntSushi Working, but not finished. Right now it operates almost exactly the same as `count` but calls `printer.path` instead of `printer.path_count`, but doing this *right* I think includes terminating the search after the first match.

It also should be just as easy to add `-L/--files-without-match` that just sets `files_with_matches` and `invert_match`.

I also think I could share a bit more logic with `count`... I might open a review to ask for some refactor help.

**Comment by andschwa** [comment]
Tada:

```sh
$ ./target/debug/rg -l files_with_matches
src/search_buffer.rs
src/search_stream.rs
src/args.rs
```

**Comment by BurntSushi** [comment]
Nice!

>  but doing this right I think includes terminating the search after the first match.

Absolutely, yes. This will probably need to go in both of the searchers, which means making them aware of this parameter as well.

**Comment by BurntSushi** [comment]
I'd be happy to do a review. The printer is due for a bit of refactoring, so don't feel too bad about it.

**Comment by andschwa** [comment]
Aye yai yai... figured out with `-L` wasn't working (but my quick addition of `--files-without-match` was); it's already used for `--follow`, but grep uses `-L` for this. What do you do in this case?

**Comment by BurntSushi** [comment]
Bah. How about we prefer compatibility with `grep` (although I got `-L` from `find`)... Hmm...

Maybe we can just drop the short hand for `--files-without-match` altogether?
