### ISSUE TITLE
Release using current regex crates.

### ISSUE THREAD

**Issue by plugwash** [BurntSushi/ripgrep#2619]
Hi.

We are currently in the process of upgrading the regex crates (regex, regex-syntax, regex-automata, aho-corasick etc). However the current release of grep-regex depends on an old version of regex-syntax.

I've looked at the commit history to investigate the possibility of cherry-picking the changes, but the number of patches involved seems significant and it's not clear to me if things are in a release-worthy state. 

Is there any chance of a release of the grep crates that uses the latest version of the regex crates in the not too distant future?

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#when-is-the-next-release

I am actually working on the ripgrep 14 release. Things are still shifting quite a bit, so pulling patches probably isn't the greatest idea but is doable if necessary.
