### ISSUE TITLE
document how to install the completion files

### ISSUE THREAD

**Issue by daxim** [BurntSushi/ripgrep#262]
The release archive `ripgrep-0.3.1-x86_64-unknown-linux-musl.tar.gz` contains a number of completion files, but no instructions how to use them AFAICS.

**Comment by BurntSushi** [comment]
I would love to provide documentation, but I don't know how to use them myself. I could figure out bash, but I'm unlikely to figure out the others.

**Comment by kbknapp** [comment]
[`rustup` has some simple documentation](https://github.com/rust-lang-nursery/rustup.rs/blob/f6cd385fc58008fd78a4514329d5207c4ff42d57/src/rustup-cli/help.rs#L135-L223).

**Comment by daxim** [comment]
Thank you, I used that info in order to write the following documentation patch.

    Shell completions
    =================

    Bash
    ----

    Move `rg.bash-completion` to [`$XDG_CONFIG_HOME/bash_completion`](https://github.com/scop/bash-completion/blob/master/doc/bash_completion.txt#L4) or `/etc/bash_completion.d/`.

    Fish
    ----

    Move `rg.fish` to `$HOME/.config/fish/completions`.

Apply it where you see fit.
