### ISSUE TITLE
Add a ´-C all´ option or similar

### ISSUE THREAD

**Issue by eadf** [BurntSushi/ripgrep#2641]
#### Describe your feature request:
Use case: I occasionally use fgrep or rg for text coloring (to easily see why yanked crates are in the tree, etc): 

```
cargo tree | rg -C 12345 "crossbeam-utils v0.8.5" 
```

Here i use a "large number" to not lose any context in the text, and this works, but it's a bit hackish to provide a "large enough" number like 12345.

So something like this would be cleaner:

```
cargo tree | rg -C all "crossbeam-utils v0.8.5" 
```

What i suggest is a dual mode for the -C option, so that is can be parsed as `[number]` or `all`

**Comment by BurntSushi** [comment]
Can you say why the `--passthru` flag doesn't work for your use case?

**Comment by eadf** [comment]
That works just fine, thanks
