### ISSUE TITLE
-N for bytes

### ISSUE THREAD

**Issue by chadbrewbaker** [BurntSushi/ripgrep#2661]
#### Describe your feature request

I need something that does -N but instead of lines I want N bytes before and after the matched string.

Something like "-N_bytes" ? Represent bytes as base64?

```bash
N bytes before
My matched string
N bytes after
```

This would be a good integration test benchmark. It enumerates all sections that do parameterized SQLite queries.
```bash
ripgrep -N_bytes 128 "VALUES" /System/Applications/*.app/Contents/MacOS/*
```
On second thought, it might be better to have PREFIX+string+SUFFIX as one base64 per line? Even better if it does:

```bash
 FILE_NAME OFFSET_BYTES  PREFIX+string+SUFFIX 
 ```

Apparently -Hb already gives filenames and offsets?

**Comment by BurntSushi** [comment]
You can use `.{N}<pattern>.{N}`. The `-r` and `-o` may also be useful, perhaps in combination with capture groups.

I don't know what base64 has to do with this.
