### ISSUE TITLE
darcs boringfiles

### ISSUE THREAD

**Issue by toastal** [BurntSushi/ripgrep#2689]
#### Describe your feature request

Like Git + gitignore files, darcs supports boringfiles that users would like to skip over. There is a default set, but also can be overridden by users on a global + per-project bases using `darcs setpref boringfile` which saves the setting in the `_darcs/prefs/prefs` file (typically by convention this file is `$PROJ_ROOT/.boring`, but doesn’t have to be).

**Comment by BurntSushi** [comment]
Sorry, but darcs isn't widely used enough to justify the work to add this IMO. ripgrep doesn't even have Mercurial support.

Darcs users will likely need to find some way to duplicate their ignore files. One for Darcs and another, i.e., `.rgignore`, for ripgrep.
