### ISSUE TITLE
Inconsistent behavior on windows when path not specified

### ISSUE THREAD

**Issue by brson** [BurntSushi/ripgrep#27]
This is again possibly by design since ag does the same thing, but I don't understand why.

On linux I can write `rg foo` and rg will search for "foo". On windows if I write `rg foo` rg hands indefinitely, but I can write `rg foo .` to search.

**Comment by brson** [comment]
This is in a mingw mintty console.

**Comment by BurntSushi** [comment]
In a standard Windows command prompt, I can run `rg` with no problems.

It sounds like `rg` thinks something is being sent to `stdin`, and thus sits there waiting for input.

**Comment by BurntSushi** [comment]
I think this was a dupe of #19 and has been fixed. But note that I ended up (purposefully) creating a new bug #94.
