### ISSUE TITLE
`-e` flag doesn't work

### ISSUE THREAD

**Issue by CamJN** [BurntSushi/ripgrep#270]
The command `rg -F -e '-lselinux'` doesn't do the same thing as `rg -F -- '-lselinux'` despite the man page saying that `-e` should deal with the leading hyphen. `rg -F -e '-lselinux' --pretty` also doesn't work to override the `-l` that ripgrep thinks is there.

**Comment by BurntSushi** [comment]
See the changelog. We had a regression here recently. Hopefully should be
fixed soon when I update clap. (On mobile.)
