### ISSUE TITLE
Typo in help description for --vimgrep option: "im" instead of "in"

### ISSUE THREAD

**Issue by kcollett** [BurntSushi/ripgrep#2757]
### Please tick this box to confirm you have reviewed the above.

- [X] I have a different issue.

### What version of ripgrep are you using?

ripgrep 14.1.0

### How did you install ripgrep?

Homebrew

### What operating system are you using ripgrep on?

macOS 14.4

### Describe your bug.

In the output of rg -h, there is a typo in the description of the --vimgrep option: "Print results im a vim compatible format." ("im" should be "in".)

### What are the steps to reproduce the behavior?

rg -h

### What is the actual behavior?

See above

### What is the expected behavior?

See above

**Comment by BurntSushi** [comment]
Thanks for the issue, but I don't track bugs for typos because they aren't a priority for me to fix unless they obscure meaning. I might get around to fixing this, or just a PR is sufficient.
