### ISSUE TITLE
Double quotes?

### ISSUE THREAD

**Issue by joeparkerz** [BurntSushi/ripgrep#276]
This seems to fail in Windows?

`rg "(?<=\/url\?q=)[^"]*" --mmap c:\test.txt`
Error parsing regex near '(?<=\/u' at character offset 2: Unrecognized flag: '<'. (Allowed flags: i, m, s, U, u, x.)

**Comment by BurntSushi** [comment]
ripgrep doesn't support lookaround.

Otherwise, you need to figure out how to escape quotes in your shell. I don't know how to do it on Windows (and I don't know which shell you're using).

**Comment by joeparkerz** [comment]
Okay that sucks a lot.

**Comment by joeparkerz** [comment]
CLEARLY not the best grep replacement out there.

**Comment by BurntSushi** [comment]
It is mentioned: https://doc.rust-lang.org/regex/regex/index.html

It could be mentioned more prominently. It is discussed at length in my blog post about ripgrep: http://blog.burntsushi.net/ripgrep/#regex-engine

Please try to keep unstructured criticism to a minimum.

**Comment by leeoniya** [comment]
@BurntSushi is it possible to use unicode escapes? I'm trying to work around this issue in windows' `cmd` via `\u0022` and getting:

```
Error parsing regex near '[ \?\u0022' at character offset 21: Unrecognized escape sequence: '\u'.
```

**Comment by BurntSushi** [comment]
@leeoniya Please open new issues for different questions.

[Unicode escapes are possible.](https://doc.rust-lang.org/regex/regex/index.html#escape-sequences) Use `rg '\x{0022}'` for example.
