### ISSUE TITLE
ignore: WalkBuilder::build_parallel() example does not compile

### ISSUE THREAD

**Issue by cgzones** [BurntSushi/ripgrep#2767]
The example given in the documentation for `ignore::WalkBuildeer::build_parallel()`
https://github.com/BurntSushi/ripgrep/blob/eca13f08a2a0ece89a423565891e48a90a8aedef/crates/ignore/src/walk.rs#L594
does not compile, since the returned closure is expected to return a `WalkState`, not `()`.

**Comment by BurntSushi** [comment]
PRs are welcome to fix this sort of thing.
