### ISSUE TITLE
ripgrep never terminates when passing `-q` or `--quiet` flags

### ISSUE THREAD

**Issue by lilianmoraru** [BurntSushi/ripgrep#279]
`rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)`
`ripgrep 0.3.2`

ripgrep never terminates when passing `-q` or `--quiet` flags.
Here is an example run(I added `--debug` later):
```
rg --debug --quiet "GCC"
DEBUG:grep::search: regex ast:
Literal {
    chars: [
        'G',
        'C',
        'C'
    ],
    casei: false
}
DEBUG:grep::literals: literal prefixes detected: Literals { lits: [Complete(GCC)], limit_size: 250, limit_class: 10 }
```

**Comment by BurntSushi** [comment]
Wow. Can't believe this one slipped through. This required there to be at least one match. There were tests for `-q`, but none of them involved finding matches. Thanks for reporting!
