### ISSUE TITLE
 ARMv8 release binary for RPI 5

### ISSUE THREAD

**Issue by p1r473** [BurntSushi/ripgrep#2799]
Hey!
Can we get the  ARMv8 release binary for RPI 5
Thanks!

**Comment by p1r473** [comment]
Nevermind, I was able to run the v7 binary on it.

**Comment by BurntSushi** [comment]
If you want this, please do the following:

1. Submit a PR adding the target you want.
2. Provide a link to a fork where the release pipeline has executed in full successfully.

I otherwise do not have any plans to work on this.

**Comment by p1r473** [comment]
No problem, was able to compile it myself
