### ISSUE TITLE
Release the mmap heuristics as a crate

### ISSUE THREAD

**Issue by dev-ardi** [BurntSushi/ripgrep#2851]
#### Describe your feature request

There is a lot of effort in heuristics of when mmapping will be a bit faster than normal reads.
I would like to use it for my programs so what I did is mostly copypasting the code which is not ideal. Do you think you could release that part as a crate for the ecosystem?

**Comment by BurntSushi** [comment]
It's in the grep-searcher crate.

If you're talking about splitting it out from there into an even smaller crate, then I don't really support micro crates like that. I would suggest starting your own crate if you are of that philosophy.
