### ISSUE TITLE
[ignore] Unexpected behaviour when ignoring directories without a slash

### ISSUE THREAD

**Issue by lbirkert** [BurntSushi/ripgrep#2857]
### Please tick this box to confirm you have reviewed the above.

- [X] I have a different issue.

### What version of ripgrep are you using?

using the library ignore = "0.4.22"

### How did you install ripgrep?

using the library ignore = "0.4.22"

### What operating system are you using ripgrep on?

Linux

### Describe your bug.

Ripgreps ignore matching does not behave equally to gits ignore matching.

### What are the steps to reproduce the behavior?

-

### What is the actual behavior?

.gitignore: `my_dir` or `my_dir/`
matches `my_dir` itself but does not match `my_dir/**`

### What is the expected behavior?

.gitignore: `my_dir` or `my_dir/`
should match `my_dir` and `my_dir/**`

This however is not how git handles gitignore matches and should be resolved.

**Comment by BurntSushi** [comment]
Please provide an MRE.

**Comment by lbirkert** [comment]
made this repo https://github.com/lbirkert/ripgrep-issue-2857

```
git clone https://github.com/lbirkert/ripgrep-issue-2857
cd ripgrep-issue-2857
cargo run
```

**Comment by lbirkert** [comment]
it seems like I have used the wrong method here ups.
Should've used "matched_path_or_any_parents" instead.
