### ISSUE TITLE
pause on showing results

### ISSUE THREAD

**Issue by ruizander** [BurntSushi/ripgrep#289]
it would be good to have a option to pause the search maintaining the colors and format... if we use "| more" the colors are gone....

**Comment by BurntSushi** [comment]
Use the -p flag.

**Comment by BurntSushi** [comment]
I was on mobile before. Here's a more useful workaround:

```
$ cat $HOME/bin/rgp
#!/bin/sh

exec rg -p "$@" | less -RFX
```

Then you can just use `rgp` whenever you want to have a pager pause results for you.

**Comment by ibotty** [comment]
Can there be a flag to (more intelligently) do that with ripgrep alone? Akin to what `git grep` does: forking `$PAGER` and connecting stdout to `$PAGER`'s stdin, but only with interactive sessions. Would you accept a patch that does that?

**Comment by BurntSushi** [comment]
@ibotty I think that has already been requested. I'm on mobile, but could you please find that issue, read it, and respond to the arguments given against doing that? I would in particular like to hear what a wrapper script is insufficient.

**Comment by ibotty** [comment]
That is the issue I am responding to.

A wrapper script is not as comfortable as command line flags. I do use such a wrapper script (as `rg`), but whenever I want to pipe rg's output I have to remember using `\rg`. It's no big deal, but not as nice as a built-in mechanism.

**Comment by BurntSushi** [comment]
@ibotty Sorry, this was the issue I was referring to: https://github.com/BurntSushi/ripgrep/issues/86 --- It would help if you addressed the concerns in that issue (is this a cross platform feature?) and why specifically you can't pipe when using `less -RFX`.

**Comment by ibotty** [comment]
Oh, I can and do pipe to `less -RFX`. I'll comment on #86.
