### ISSUE TITLE
use colorscheme

### ISSUE THREAD

**Issue by Masber** [BurntSushi/ripgrep#2908]
#### Describe your feature request

many terminal applications like vim, alacritty, bat allows the user to set a specific colorscheme to print commands output. Could ripgrep take the same approach using the `--colors` argument?
something like:

Some examples:

set ripgrep to use gruvbox-dark colorscheme

```
rg --colors=colorscheme=gruvbox --colors=bg:dark
```

set ripgrep to use gruvbox-light colorscheme

```
rg --colors=colorscheme=gruvbox --colors=bg:light
```

or directly (without specifying background)

```
rg --colors=colorscheme=gruvbox-dark
```

thank you

**Comment by BurntSushi** [comment]
I appreciate the suggestion, but this isn't something I want to maintain. ripgrep's use of colors are also way simpler than vim, alacritty or bat.
