### ISSUE TITLE
Is there any Debian installation option for ripgrep?

### ISSUE THREAD

**Issue by sami10007** [BurntSushi/ripgrep#291]
Hi, 

I previewed the installation options and did not find any option for Debian and Ubuntu. 

How can you install ripgrep (rg) in Debian 8.5?

**Comment by BurntSushi** [comment]
For now, you can download binary executables: https://github.com/BurntSushi/ripgrep/releases

Debian packages are being worked on. 

cc @JoshTriplett

**Comment by BurntSushi** [comment]
We should just track this in #10 to avoid having an issue for every package repo.

**Comment by mcandre** [comment]
I see a PPA for ripgrep at https://launchpad.net/~x4121/+archive/ubuntu/ripgrep

However, when I try to use this PPA, apt-get update complains that this PPA is missing a "Release" file.

**Comment by shark0der** [comment]
@mcandre it's because the ppa provides the package only for ubuntu zesty (17.04).

**Comment by trusktr** [comment]
Cool, that PPA worked with 17.10

**Comment by Piping** [comment]
Hi I wonder what is the current status of debian package in general for rust program? does every rust crate make it own package in debian?

**Comment by Piping** [comment]
Link the relevant source: https://www.reddit.com/r/rust/comments/8w9mfy/debian_is_starting_to_package_rust_crates/

**Comment by BurntSushi** [comment]
I don't know. This issue tracker isn't really a good place for general Debian questions. If I had to guess, I'd say, "Rust crates that a Debian packager wants to package get packaged."
