### ISSUE TITLE
Error description erratum: reptition

### ISSUE THREAD

**Issue by MiguelLatorre** [BurntSushi/ripgrep#294]
I think there is an erratum in the following error message (I am not a native english speaker though):

$> rg '*'
Error parsing regex near '*' at character offset 0: Missing expression for **reptition** operator.

By the way, thanks so much for this tool. It is awesome.

**Comment by BurntSushi** [comment]
Thanks for the report! This was actually a bug in the `regex-syntax` crate (i.e., the regex parser), but was [fixed about a month ago](https://github.com/rust-lang-nursery/regex/commit/45ad9237b65adbfe5d66b8ebf76f7f83ae9b5054). The fix will make its way into ripgrep eventually. :-)
