### ISSUE TITLE
----

### ISSUE THREAD

**Issue by pinguicula** [BurntSushi/ripgrep#2947]
---

**Comment by BurntSushi** [comment]
[Help me help you.](https://www.youtube.com/watch?v=l1B1_jQnlFk) Don't tell, [_show_](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Here's [how to do it](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by pinguicula** [comment]
Mistaken, the files were not being searched because they were symlinks.

**Comment by pinguicula** [comment]
Mistaken, the files were not being searched because they were symlinks.

**Comment by BurntSushi** [comment]
Thanks for following up. But I'll never understand why people scrub their issues like this. Like what if someone else had the same problem as you? Now this issue is much less likely to appear in a web search.

**Comment by pinguicula** [comment]
The reason for removing it is that is confusing: It was a faulty question. The real question should be:
Why does rg follow symlinks when you type `rg search-pattern .*`  but not `rg search-pattern .`.

**Comment by BurntSushi** [comment]
I understand. But that fault question came _from a perspective_ and that perspective is valid and may be shared by others.

It's not a big deal, but personally I would just suggest not scrubbing issues in the future.
