### ISSUE TITLE
Add swig type

### ISSUE THREAD

**Issue by mcepl** [BurntSushi/ripgrep#296]
That’s [swig](http://swig.org/) which uses `*.i` and `*.def` files. Equivalent of
```
--type-add 'swig:*.i' --type-add 'swig:*.def'
```

**Comment by BurntSushi** [comment]
A PR adding it would be most welcome. It should be a simple change to this list: https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/types.rs#L82
