### ISSUE TITLE
Option flag to automatically escape regex

### ISSUE THREAD

**Issue by AnthIste** [BurntSushi/ripgrep#299]
I mainly use ripgrep to search for stuff in a C# project. By default the search string is a regex which means that namespace separators, method calls and strings must all be escaped with `\`. These are my primary searches and all of them need copious backslashes:

- `Project.Namespace.Whatever` -> `rg "Project\.Namespace\.Whatever"`
- `object.Method()` -> `rg "object\.Method\(\)"`
- `"string"` -> `rg "\"string\""`

Would it make sense to add an argument that treats the search query as a "raw" string and automatically convert it to a "dumb" escaped regex?

**Comment by BurntSushi** [comment]
It already exists. It is the -F flag, which is identical to the same flag
in grep.

How could the documentation be improved such that this would have been
clearer to you?

**Comment by AnthIste** [comment]
> How could the documentation be improved such that this would have been
clearer to you?

No really, it can't be more obvious. I just looked through `ripgrep --help` again and didn't see it. When I copy-pasted the output it jumped out on me.

```
    -F, --fixed-strings        Treat the pattern as a literal string instead of
                               a regular expression.
```

Yup, that looks like what I need. I honestly have no idea how I missed that - I even started scratching through the source code before opening an issue.

Thanks for the help!

**Comment by BurntSushi** [comment]
No problem!

**Comment by AnthIste** [comment]
Just another question not directly related to this issue:

Is there an option to specify file extensions to search without using the `--type-add` system? I find myself wanting to do ad-hoc searches on specific combinations of filetypes without necessarily designating a category for them.

**Comment by BurntSushi** [comment]
@AnthIste Why not just use the `-g/--glob` flag? e.g., `rg -g '*.{foo,bar,baz}' pattern'` will only search files with an extension `foo`, `bar` or `baz`.

**Comment by AnthIste** [comment]
That makes sense :+1: I'll try that in future

**Comment by partounian** [comment]
I tried to use `-F` but it didn't work when searched for `rg '->price'`

**Comment by okdana** [comment]
You need to use `--` to tell `rg` that a pattern beginning with a hyphen isn't supposed to be a command-line option:

```
rg -- '->price'
```
