### ISSUE TITLE
trailing recursive globs shouldn't ignore the directory itself, only its contents

### ISSUE THREAD

**Issue by foophoof** [BurntSushi/ripgrep#30]
I have a .gitignore file that contains something like this:

```
vendor/**
!vendor/manifest
```

I'd expect `vendor/manifest` to be searched, but nothing else in the `vendor` directory, but instead it seems like `vendor/manifest` is ignored too. If I remove the `vendor/**` line, the search does what I expect it to.

**Comment by BurntSushi** [comment]
This is an interesting case, because `rg` will avoid descending into the `vendor`, which appears wrong, since `vendor` itself shouldn't be ignored. From `man gitignore`:

```
       ·   A trailing "/**" matches everything inside. For example, "abc/**" matches all files inside directory "abc",
           relative to the location of the .gitignore file, with infinite depth.
```

(Running `rg` with the `--debug` flag told me that `vendor` itself was ignored. `rg` never even sees `vendor/manifest`.)
