### ISSUE TITLE
Symantec Endpoint Protection complains about rg.exe under Windows

### ISSUE THREAD

**Issue by mathiasdahl** [BurntSushi/ripgrep#300]
Hi,

I just downloaded the latest binaries of ripgrep for Windows (the msvc version) and unpacked it. A minute later Symantec Endpoint Protection complains about it being infected by "SONAR.Heur.RGC!g201".

http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2016-061612-2956-99

Should I be afraid?

Thanks!

/Mathias

**Comment by BurntSushi** [comment]
I don't know. I'm not a Windows user, so I I don't understand the error message you've reported or how such an error is reported. Every piece of code that goes into producing the binary is open source. My guess is that it's a false positive. 

cc @retep998

**Comment by retep998** [comment]
Notice the `Heur` part of the signature. Basically it has a heuristic that searches for certain code behavior and flags binaries as being infected as a result. If you're worried you can try building ripgrep from source and seeing whether the same AV complaint occurs. If it does, that AV simply has a false positive that needs to be reported to the AV. There is nothing @BurntSushi or I can do about false positives unfortunately.

**Comment by BurntSushi** [comment]
Thanks for chiming in @retep998! :-)

**Comment by mathiasdahl** [comment]
Thanks for your comments/answers!
