### ISSUE TITLE
Broken .toml file

### ISSUE THREAD

**Issue by mcepl** [BurntSushi/ripgrep#302]
```
matej@xerus:~/Build/ripgrep$ cargo build --release
failed to parse manifest at `/home/matej/Build/ripgrep/Cargo.toml`

Caused by:
  could not parse input as TOML
Cargo.toml:42:9 expected a key but found an empty string
Cargo.toml:42:9-42:10 expected `.`, but found `'`

matej@xerus:~/Build/ripgrep$ 
```

**Comment by BurntSushi** [comment]
What version of rust/cargo do you have installed?

**Comment by mcepl** [comment]
What's in Ubuntu 16.04, rustc 1.7.0 and cargo 0.8.0.

**Comment by mcepl** [comment]
OK, so rust is still too unstable for normal use. I'll get the staticly build file.

**Comment by BurntSushi** [comment]
That's wrong. Rust is quite stable. ripgrep simply requires a newer version of Rust than what you have installed.

**Comment by mcepl** [comment]
Sorry, I didn't mean to be rude. However, then probably it would be good to reconsider the required compatibility. I am not personally invested in Ubuntu (being the Red Hat employee, I use Fedora/RHEL for all my needs, and we have the latest rust even for RHEL-7/EPEL), but 16.04 is LTS, so I guess it could be wise to have it supported.

**Comment by BurntSushi** [comment]
No, it's not happening, sorry. I can't afford to do that kind of maintenance. We need to move forward.
