### ISSUE TITLE
git: explicitly added files are ignored

### ISSUE THREAD

**Issue by Istvan91** [BurntSushi/ripgrep#31]
I'm not sure if this is in scope of ripgrep, but explicitly added files in git repositories are ignored.

The script
```
#!/bin/bash
mkdir testfolder
pushd testfolder
    git init
    echo "some text" > testfile
    echo "*" > .gitignore
    git add -f testfile .gitignore
    git commit -m "Initial commit"
    echo "ripgrep:"
    rg some
    echo "git grep:"
    git --no-pager grep some
popd

```
yields following output:
```
Initialized empty Git repository in /full/path/testfolder/.git/
[master (root-commit) 350428e] Initial commit
 2 files changed, 2 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 testfile
ripgrep:
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.
git grep:
testfile:some text
```

**Comment by BurntSushi** [comment]
I don't think there's a way to fix this without digging deeping into `git`. We might have to live with it.

Note that you can add files to your `.rgignore` (soon to be `.gitignore`) that will override this. You can also whitelist them in your `.gitignore`, which honestly kind of seems like the right thing to do anyway.

**Comment by Istvan91** [comment]
Have you actually evaluated to (optionally) call git and ask for all files? I guess this would also fix all other gitignore related problems.

Though I partially disagree, I leave it like this since ag, silver_searcher and co. can't do this as well. (In the future you could mention this limitation in the README.)

**Comment by BurntSushi** [comment]
It just seems like bad juju for `rg` to have a runtime dependency on another command line tool. Moreover, implementing *optional* support for it is a recipe for monstrous code complexity and innumerable bugs.

If we really wanted to get serious about this, I'd probably insist researching something like `libgit2` or something to see if we could use that to implement this stuff. Depending on a C library doesn't sound great to me either, but slightly more palatable than another command line tool.

**Comment by BurntSushi** [comment]
I am going to close this because I don't see an answer to this problem that I'm comfortable with. If anything new comes to light, we can revisit it.
