### ISSUE TITLE
Support for custom configurations

### ISSUE THREAD

**Issue by kenny1847** [BurntSushi/ripgrep#314]
This relates to https://github.com/BurntSushi/ripgrep/issues/196.
There is going thread about persistent global config, but, on the other hand, as for me, in many cases I need custom .rgrc for custom project. And it will be great pros, because anyone invited to project won't has to write own aliases or anything what he/she likes.

**Comment by BurntSushi** [comment]
I don't think we need two tickets tracking this. If directory specific configs are desirable, then that should probably be part of the initial design, since I expect it will add an extra layer of complexity.
