### ISSUE TITLE
Cannot install via cargo, possibly corruped TOML

### ISSUE THREAD

**Issue by deathbeam** [BurntSushi/ripgrep#315]
So I was trying to install ripgrep via cargo on Ubuntu 16.04 (since it is not in repos), and this is error that I am facing:

```
 Updating registry `https://github.com/rust-lang/crates.io-index`
failed to parse manifest at `/home/deathbeam/.cargo/registry/src/github.com-88ac128001ac3a9a/ripgrep-0.3.2/Cargo.toml`

Caused by:
  could not parse input as TOML
/home/deathbeam/.cargo/registry/src/github.com-88ac128001ac3a9a/ripgrep-0.3.2/Cargo.toml:43:9 expected a key but found an empty string
/home/deathbeam/.cargo/registry/src/github.com-88ac128001ac3a9a/ripgrep-0.3.2/Cargo.toml:43:9-43:10 expected `.`, but found `'`
```

I am not sure what is causing it, I installed cargo from repo (`apt install cargo`) and when I opened mentioned TOML file, it seemed okay.

**Comment by BurntSushi** [comment]
What version of Rust? You need at least 1.11.

**Comment by deathbeam** [comment]
Thank you for fast reply. I am not really sure, because I installed cargo solely to install ripgrep, and it seems that I do not even have rustc in PATH, but `cargo -V` outputs `cargo 0.8.0 (built 2016-03-22)`, so I guess it is outdated then.

**Comment by BurntSushi** [comment]
Yup. Definitely too old. You can download a binary release though (which i
realize is not ideal).

**Comment by deathbeam** [comment]
I installed up-to-date version of cargo, so now it is working. And yeah, downloading binary release is not ideal, but at least there is a binary release, many popular projects do not even bother with them. Anyway, my problem is solved, so closing this issue.
