### ISSUE TITLE
Switch to avoid crossing filesystem boundaries

### ISSUE THREAD

**Issue by wavexx** [BurntSushi/ripgrep#321]
It's often useful to search only files that reside on the same filesystem as the search paths, same as ``find -xdev`` or ``ag --one-device``. I find ag's "one-device" switch to be misleading, as it's more correctly described by find as "do not cross filesystem boundaries", since the restriction applies to each search path in turn (which can span more than *one* device).

**Comment by BurntSushi** [comment]
This needs to be implemented in `walkdir` (see: https://github.com/BurntSushi/walkdir/issues/8) and `ignore`'s parallel iterator, and then exposed up through ripgrep as a command line flag.

I agree with the naming choice. Using `find`'s flag name seems fine. It looks like GNU grep doesn't have a similar flag?

**Comment by wavexx** [comment]
On Wed, Jan 18 2017, Andrew Gallant wrote:
> I agree with the naming choice. Using find's flag name seems fine. It looks like GNU grep doesn't have
> a similar flag?

Indeed it doesn't, which is a shame.

If you're working with FUSE and/or remote filesystems, -xdev is very
useful (either to avoid crossing, and/or to escape the local fs).

**Comment by BurntSushi** [comment]
I think I'm liking the name `--mount` for this. It's supported by `find`, is relatively short, and feels a bit more generic than `--xdev`.

Does anyone know the provenance of the name `--xdev`? I guess "dev" means "device" (which seems consistent with the `dev` attribute in the `stat` structure) and I guess `x` means "cross" or "don't cross" in this case.

**Comment by ssokolow** [comment]
> Does anyone know the provenance of the name --xdev? I guess "dev" means "device" (which seems consistent with the dev attribute in the stat structure) and I guess x means "cross" or "don't cross" in this case.

I suspect you're correct there, given that tools like `ncdu` use the short option `-x` and describe it as follows:

> `-x`  Do not cross filesystem boundaries, i.e. only count files and directories on the same filesystem as the directory being scanned.

**Comment by BurntSushi** [comment]
@okdana Ah nice, thanks! The prevalence of `--one-file-system` makes a compelling argument for that name. I guess we should probably go with that? It's also seemingly the most accurate. The only downside is that it's kind of long.

**Comment by ssokolow** [comment]
Another thing which just occurred to me is that I like the `x`-based names (`-x`, `-xdev`, etc.) because, in addition to "crossing device boundaries", they also associate it with options like `--exclude` in my mind, which is technically accurate. (You're eXcluding stuff outside the current filesystem.)
