### ISSUE TITLE
Order of conflicting arguments

### ISSUE THREAD

**Issue by chneukirchen** [BurntSushi/ripgrep#327]
I generally prefer the `--no-heading` output, but there is no shortcut to enable it.  After adding an alias for `rg --no-heading`, I discovered `rg --no-heading --heading` behaves just like `rg --no-heading`.
It would be nice if the "last argument wins", so defaults can be defined yet changed easily.

**Comment by BurntSushi** [comment]
I'm not sure if we can.

@kbknapp Is there any way to make this type of thing happen with existing clap?

**Comment by chneukirchen** [comment]
The clap README mentions `POSIX Compatible Conflicts/Overrides`

**Comment by kbknapp** [comment]
In either `heading` or `no-heading` use `Arg:: overrides_with(other)` it's meant for exactly that purpose (allowing alias overrides).

I'm on mobile but when I get to a computer I can link to the docs page.

**Comment by BurntSushi** [comment]
Oh excellent! That sounds familiar. I'll try it out soon.
