### ISSUE TITLE
Account for case-insensitivity in file matching

### ISSUE THREAD

**Issue by thijsvandien** [BurntSushi/ripgrep#336]
I'm on a Mac that has a case-insensitive file system (and so does Windows). When I have a folder containing `a.txt` and `b.TXT`, both `rg --ttxt --files` and `rg -g '*.txt' --files` list only `a.txt`. 

A user on such system would expect both filenames to be matched, so that's what I would vouch for. Perhaps, in addition there could be a flag to either force case-sensitive or case-insensitive filename matching. 

If detecting case-sensitivity of the filesystem is terribly inconvenient to do—a search may span multiple volumes with different case-sensitivity!—I suppose case-sensitive should remain the default always, and case-insensitivity could optionally be enabled with a flag (to become a very popular one on those platforms then).

For a point or reference, Python 3's `glob` module respects the filesystem. It's possible that this is an issue to address in the library used for globbing rather than this consuming project.

**Comment by thijsvandien** [comment]
Excuse me, I missed https://github.com/BurntSushi/ripgrep/issues/163.

**Comment by BurntSushi** [comment]
Yup, this is a dupe. Thanks for contributing to the discussion. :-)

(In case it isn't clear, I'm fully supportive of taking action on this issue. The UX just isn't quite clear to me...)
