### ISSUE TITLE
Add an option similar to -o, --only-matching

### ISSUE THREAD

**Issue by dzamlo** [BurntSushi/ripgrep#34]
With grep you can print only the matched parts of the files. The option is described like this in the grep manpage:

```
-o, --only-matching
       Print only the matched (non-empty) parts of a matching line, with each such part on a separate output line.
```

A more powerful option, would something similar to `--replace`, but that doesn't print the non matched part of the text.

**Comment by cwillu** [comment]
Note that surrounding the search regex with .*(  ).* and then using --replace $1 will do this; pretty verbose though, especially when using it in a pipeline.

**Comment by BurntSushi** [comment]
`--replace` already exists (and I agree it's kind of verbose for this case).

`-o`/`--only-matching` is an option on `grep`, so I'm OK adding this.

**Comment by sergeevabc** [comment]
Input
```
host -t A wikipedia.org | rhash --sha256 - | rg [A-Fa-f0-9]{64}
```
Output
```
1:0d00409623da8ae039de83200af7f6fa9211bb13e1b3e10ea45142cd08b3e50b  (stdin)
```
Hash is coloured red, but I need hash only.
Would option ```--only-matching``` be of help?

**Comment by BurntSushi** [comment]
@sergeevabc Yes, it would solve your problem. But there is a work-around for now:

```
$ host -t A wikipedia.org | openssl dgst -sha256 | rg -N '^.*([A-Fa-f0-9]{64}).*$' --replace '$1'
```

**Comment by sergeevabc** [comment]
@BurntSushi, thanks, but when ```--only-matching`` will be implemented?

**Comment by BurntSushi** [comment]
@sergeevabc I don't know. It happens when it happens. I do this in my free time and I don't typically schedule my free time in advance. Sorry.

**Comment by sergeevabc** [comment]
> It happens when it happens.
Reminds of “[when it’s done][1]” promise of Duke Nukem Forever developers. It tooks them ~15 years.

> I don't typically schedule my free time in advance
Schedule could make you more effective, [details][2].

[1]: https://en.wikipedia.org/wiki/Development_of_Duke_Nukem_Forever
[2]: http://calnewport.com/blog/2016/12/07/from-deep-tallies-to-deep-schedules-a-recent-change-to-my-deep-work-habits/

**Comment by gavinfoley** [comment]
To counterbalance the above comment, I wanted to say that I use and enjoy this excellent tool you've created every day, and I appreciate whatever improvements are made whenever they are made. Thanks for using some of your limited free time to make my life and others' easier.

**Comment by BurntSushi** [comment]
@sergeevabc This issue tracker isn't place to give me advice on how to schedule my free time or to shame anyone into doing work on their free time. Future comments in that vain won't be tolerated.

**Comment by sergeevabc** [comment]
[TED][1] shames nobody while spreading worthy ideas, so do I. Yet you interpret it in a mean way. Since you’re so touchy and servile gratitude is the only kind of feedback you favour, consider garnishing boastful paragraphs of [README.md][4] with a disclaimer like “[Abandon all hope, ye who enter here][2]” to strangle public illusionary hopes for improvement at birth.

[1]: https://www.ted.com/
[2]: http://idioms.thefreedictionary.com/Abandon+hope,+all+ye+who+enter+here
[4]: https://github.com/BurntSushi/ripgrep/blob/master/README.md

**Comment by 22a** [comment]
Wonderful, thank you for the great work @kpp + @BurntSushi 🎉
