### ISSUE TITLE
document that keyboard interrupt doesn't restore the termcolor on Windows

### ISSUE THREAD

**Issue by jmcomets** [BurntSushi/ripgrep#347]
Hi everyone,

First of all, great job on this. :+1: 

Now on to my issue: I'm using stable Rust (stable-x86_64-pc-windows-msvc + rustc 1.14.0) and installed ripgrep using `cargo install`.
When running a basic `rg --type cpp <pattern>` and pressing Ctrl-C in the middle, cmd's foreground stays red/purple/whatever color was last printed. I haven't tried on Linux to see if this is really platform specific.

**Comment by BurntSushi** [comment]
PR #187 actually added this functionality.

I later removed it to fix #281. My reasoning is here: https://github.com/BurntSushi/ripgrep/issues/281#issuecomment-269093893

TL;DR - There are significant trade offs for doing `^C` handling, and IMO, screwing up the colors in the terminal (which is easy to fix by running `echo -ne "\033[0m"` or `color` on Windows I believe) is the least worst choice.

**Comment by jmcomets** [comment]
I 100% understand the decision. Would you be open to adding this issue to a "faq" or "issues" section in the readme?

**Comment by BurntSushi** [comment]
@jmcomets Great idea.
