### ISSUE TITLE
rg pattern dir -g '!'"$path/to/exclude" fails if $path ends with /

### ISSUE THREAD

**Issue by timotheecour** [BurntSushi/ripgrep#354]
could consecutive // be treated as a single / ? that would simplify usage: $path/foo is simpler to use than ${path}foo and works regardless whether $path has a trailing slash or not, unlike ${path}foo

**Comment by BurntSushi** [comment]
Do other tools do this? Is there ever a difference between file paths `foo/bar` and `foo//bar`?

Note that `gitignore` semantics matches current behavior.

**Comment by timotheecour** [comment]
> Is there ever a difference between file paths foo/bar and foo//bar?
no

`//` can never occur in a path so there's no downside to treating consecutive `/` as one

**Comment by BurntSushi** [comment]
Why doesn't git do it? Why don't other tools do it? I would want to know that before jumping on this.

**Comment by timotheecour** [comment]
@BurntSushi  it makes less sense in a .gitignore file because IIRC we can't have environment variables there, so having a `//` in there would be silly and trivial to avoid.
But it does make sense when using shell commands (where environment variables can be used), as is the case for `-g`.

my workaround is not pretty (it should handle cases with spaces in paths, otherwise it'd be simpler)

```
rg_sanitized(){
    # could also be passed as argument
    local g_pattern=(-g '!'"$dir1/foo/" -g '!'"$dir2/bar/" )

    local g_pattern2=()
    for f in "${g_pattern[@]}" ; do
      local temp=$(echo "$f" | sed -E 's@/+@/@g')
      g_pattern2=($g_pattern2 $temp) ;
    done

    #NOTE:this wouldn't work with spaces in $dir1 for example:
    #local g_pattern2=($(echo $g_pattern |  sed -E 's@/+@/@g' ))

   (
      # cd to / assuming $dir1, $dir2 are absolute paths
      cd / && rg "$@" $g_pattern2
   )
}


rg_sanitized foo $dir3
```

(and happy to receive any suggestions on how to improve this, bash isn't my favorite thing)

**Comment by BurntSushi** [comment]
To be honest, I don't really understand what you're working around. Why do
you have paths with multiple consecutive slashes in them?

**Comment by timotheecour** [comment]
eg use case: with this change,
```
rg -g "$package_dir/lib"
```
would work regardless of whether $package_dir ends with a `/` or not, eg:
* would work with `package_dir=/usr/local/`
* would work with `package_dir=/usr/local`
=> both cases treated as meaning `rg -g /usr/local/lib`

without this change: I have to know whether `$package_dir` ends with a `/` or not:
* ends with a `/` => use `rg -g "${package_dir}lib"`
* ends without a `/` => use `rg -g "$package_dir/lib"`

It's a small thing. If no-one has time, would u accept a PR or would that be rejected?

**Comment by BurntSushi** [comment]
I've just never seen this as a problem that people have faced, and I would like to know what other tools do before we act. It seems like you could just define your env vars without a trailing slash, and all your problems would go away.

**Comment by BurntSushi** [comment]
After thinking about this, I don't think this is a problem that ripgrep should solve. If you have an env var and you're not sure if it has a trailing slash, then you can use `${package_dir%/}` to remove it.
