### ISSUE TITLE
Respect .gitexcludes settings

### ISSUE THREAD

**Issue by avindra** [BurntSushi/ripgrep#358]
Hi,

`.gitexcludes` allows you to specify global options to ignore:

https://coderwall.com/p/ithnoq/gitexcludes

It would be neat if ripgrep respected those options!

**Comment by BurntSushi** [comment]
It's already supported. Note that `.gitexcludes` isn't something recognized by git automatically. The key line in your link is:

```
$ git config --global core.excludesfile ~/.gitexcludes
```

ripgrep should read your git config to find the right file path.

If something isn't working, please open a new issue with a small reproducible example. :-)

**Comment by avindra** [comment]
@BurntSushi Incredible, that did the trick :+1: thanks for this awesome project
