### ISSUE TITLE
The color option should be aliased to colour

### ISSUE THREAD

**Issue by filterfish** [BurntSushi/ripgrep#367]
This is predominantly to match `grep` but also in my version of English `color` is not the correct spelling.

**Comment by BurntSushi** [comment]
I get it. But I don't really like having aliases unless there's a strong motivation and IMO this doesn't qualify. Sorry.

**Comment by filterfish** [comment]
> But I don't really like having aliases ...
It's already aliased to --`pretty` to so why not `--colour` as well?

**Comment by BurntSushi** [comment]
`--pretty` is an alias for multiple flags.

If I could go back in time, I probably wouldn't have added the --pretty flag. But some aliases are actually useful. The -u flags for example.

I'm not interested in adding alternative spellings. Sorry.
