### ISSUE TITLE
images being searched?

### ISSUE THREAD

**Issue by ryanong** [BurntSushi/ripgrep#368]
I was reading in the documentation binary files are skipped. Are images considered binary or not?

Other filetypes being search which I would consider binary:
font files
xls files

**Comment by BurntSushi** [comment]
Binary detection is, at best, a heuristic. The heuristic is similar to what GNU grep does. If the file contains a `NUL` byte, then the file is treated as a "binary" file. There is however a bug associated with detection that causes it to be too conservative. See #52.

Could you please provide more details on the problem you're having? In particular, can you provide a small reproducible example?

**Comment by ryanong** [comment]
yea sure
download https://upload.wikimedia.org/wikipedia/commons/8/85/Capybara_portrait.jpg into a temp folder and run `rg --files` and it comes up as a valid searchable file.

I'm on `ripgrep 0.4.0`

**Comment by BurntSushi** [comment]
> and it comes up as a valid searchable file

That's because it is. The only way to know whether a file is binary or not is... to search it.

**Comment by ryanong** [comment]
fair point. I guess I was just expecting functionality similar to AG
`https://github.com/ggreer/the_silver_searcher/blob/b5e750a42c28d0ac1f5acd6ac82cfdd8518c732e/src/util.c#L351`

**Comment by BurntSushi** [comment]
> I guess I was just expecting functionality similar to ag

It is similar. In fact, with your example file, the behavior is nearly identical. You're using the `--files` flag which say "print all files that ripgrep **will search**." Watch:

```
$ mkdir ripgrep-368
$ cd ripgrep-368
$ curl -sO 'https://upload.wikimedia.org/wikipedia/commons/8/85/Capybara_portrait.jpg'
$ rg purl
$ rg -a purl
Capybara_portrait.jpg
24:            xmlns:dc="http://purl.org/dc/elements/1.1/">
$ ag purl
$ ag -a purl
Binary file Capybara_portrait.jpg matches.
$ rg --files
Capybara_portrait.jpg
$ ag -g .
Capybara_portrait.jpg
```

Both tools emit `Capybara_portrait.jpg` as files that will be searched, but both tools ignore that file when actually executing the search.

**Comment by ryanong** [comment]
Ah cool! thanks for making an awesome tool and taking the time to explain.

The reason I brought this up was I am trying to figure out why AG is faster searching my repo and I doubt that ag is faster than rg at individual files.

**Comment by BurntSushi** [comment]
When you say "ag is faster," do you mean "it beat ripgrep by a few milliseconds on my tiny repo"? Or do you mean "it beat ripgrep by several seconds on a very large repo"?

If the former, then that's not too interesting. At that point, we're talking about process overhead and the cost of spinning up threads.

If the latter, then it's hard to say without a more thorough analysis. If you could reproduce your results on a repo we can both access, then I could probably tell you exactly what's going on if you're curious.

**Comment by ryanong** [comment]
The later, ag does it in about a second and ripgrep takes about 5-10 seconds. I'll attempt to make a reproducible repo. I'll open a new issue with step by step replication.

**Comment by BurntSushi** [comment]
@ryanong Wow that's a big difference! Thanks for the attempt. :-)

(The first thing I'd check for is whether they are searching the same files. ag's gitignore support isn't great, so if it's accidentally ignoring some large files or something, that might explain things.)

**Comment by ryanong** [comment]
yep that is what I was thinking, which is why I thought images were being searched.
I compared `ag -l` to `ripgrep --files` and the only thing that stuck out were images

**Comment by BurntSushi** [comment]
@ryanong You probably want to compare `ag -l` with `rg -l`. :-)

**Comment by ryanong** [comment]
`ag -l` without an argument lists all files. `rg -l` requires an argument

**Comment by ryanong** [comment]
I just did `rg -l ""` and that worked. there is no difference in files :/ I'll keep poking around

**Comment by BurntSushi** [comment]
@ryanong Try `ag -l '^'` vs `rg -l '^'`.

**Comment by BurntSushi** [comment]
ah yeah, weird. best bet is to find a reproduction we can both see i guess. thanks for your patience :-)
