### ISSUE TITLE
On Windows cmd.exe with environment variable TERM=msys, --color prints escape sequences

### ISSUE THREAD

**Issue by mgr2000** [BurntSushi/ripgrep#370]
example output:
`[m[32m845[m:[m[31m[1mextern template[m struct BasicData<void>;`

coloring works fine after I do
_set TERM=_

This issue occurred after upgrading from ripgrep v 0.3.x to 0.4.0

**Comment by BurntSushi** [comment]
This sounds like correct behavior. Why do you have `TERM=msys` in the native Windows console? `cmd.exe` is certainly not a MSYS terminal as far as I know.

**Comment by mgr2000** [comment]
Thanks for the hint.
I suppose it was because TERM=NTCONSOLE leads to git complaining about "terminal is not fully functional" and some stackoverflow solution was to set TERM to msys instead...
Please consider this issue invalid.
