### ISSUE TITLE
clap 2.20.x?

### ISSUE THREAD

**Issue by ignatenkobrain** [BurntSushi/ripgrep#383]
Would be nice to update clap dependency to latest version.

Not sending PR, because there are a lot of enhancements and I'm not sure which ones you would like to implement.

**Comment by BurntSushi** [comment]
OK, I just did this quickly because it didn't require any changes in ripgrep.

Note that since ripgrep and clap (and any dependency really, not just clap) might track different minimum Rust versions, this won't always be so easy. But this time it was.

**Comment by BurntSushi** [comment]
@ignatenkobrain By the way, thank you for filing all the issues on various Rust repos. I promise I'll do my part soon. :-)
