### ISSUE TITLE
[ignore] Strange whitelist behaviour

### ISSUE THREAD

**Issue by Yamakaky** [BurntSushi/ripgrep#384]
```rust
let overrides = "
    !/*
    /tmp
";
let walker = WalkBuilder::new("/")
                         .overrides(OverrideBuilder::new("/")
                                                    .add(overrides)
                                                    .unwrap()
                                                    .build()
                                                    .unwrap())
                         .build();
for res in  walker {
    let entry = res.unwrap();
    println!("{:?}", entry);
}
```
I expect this code to list the files in `/tmp`, but it also lists the files in all `/`, like `/home`. Did I do something wrong?

**Comment by BurntSushi** [comment]
The docs for the [`add`](https://docs.rs/ignore/0.1.7/ignore/overrides/struct.OverrideBuilder.html#method.add) method say:

> Add a glob to the set of overrides.

In your code, you're adding a whole bunch of globs. You need to add them one at a time.

**Comment by Yamakaky** [comment]
Oh, OK, thanks.
