### ISSUE TITLE
add scss and ejs file types

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#393]
Does `scss` belong in the `css` file type? Does `ejs` belong in the `js` file type or a separate `ejs` type?

**Comment by keithgabryelski** [comment]
If jsx goes with js then I think scss goes with CSS 

Imho, Ejs belongs with HTML not js -- it should have more HTML in it than js

But ejs is in a group of templates -- so there could be a "tmpl" type

But I think they all belong in a super group webapp
