### ISSUE TITLE
Add svg file type

### ISSUE THREAD

**Issue by porglezomp** [BurntSushi/ripgrep#394]
I'm searching through a web codebase and keep running into hundreds/thousands of lines of results from SVG

**Comment by BurntSushi** [comment]
We could certainly just add a file type (in the meantime, `-g '!*.svg'` should do). A PR for that would be welcome.

Is there anything else we should be doing? svgs are plain text XML files, but it feels weird to try and search them.

**Comment by porglezomp** [comment]
I don't know, I hadn't seen the glob exclude but had seen the filetype exclude so I jumped straight to that as my solution. I don't really have any more specific suggestions because I don't work with SVGs enough.

**Comment by jdhorwitz** [comment]
@BurntSushi I would love to work on this, just a point in the right direction would be great.  Thanks!

**Comment by BurntSushi** [comment]
@jdhorwitz The simplest thing to do is to add an `svg` file type to ripgrep: https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/types.rs --- That way, one can ignore them by just using `-Tsvg`.

As to whether svgs should be ignored automatically or not kind of requires a UX exploration. I'm content to punt on that for now until more folks are actually having a problem with it.

**Comment by porglezomp** [comment]
Thanks @jdhorwitz!
