### ISSUE TITLE
Cannot build ripgrep

### ISSUE THREAD

**Issue by ruipacheco** [BurntSushi/ripgrep#396]
```
$ cargo install ripgrep --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading ripgrep v0.4.0
error: [60] Peer certificate cannot be authenticated with given CA certificates (SSL certificate problem: self signed certificate in certificate chain)
```

Latest OSX with:

```
$ rustc --version
rustc 1.15.1
```

```
$ cargo --version
cargo 0.13.0 (eca9e15 2016-11-01)
```

**Comment by BurntSushi** [comment]
Sorry, but this has nothing to do with ripgrep. I don't actually know what the problem is. Clearly there is some problem talking to crates.io.

Work around:

```
$ git clone git://github.com/BurntSushi/ripgrep
$ cd ripgrep
$ git checkout 0.4.0
$ cargo build --release
$ ./target/release/rg --version
```

**Comment by ruipacheco** [comment]
$ cargo build --release
 Downloading clap v2.19.3
error: unable to get packages from source

To learn more, run the command again with --verbose.

**Comment by BurntSushi** [comment]
Sorry, but i don't know how to debug your issue. I don't know why you can't contact crates.io. :-( cc @alexcrichton

**Comment by BurntSushi** [comment]
Could you please run with the --verbose flag to get more details?

**Comment by alexcrichton** [comment]
@ruipacheco are you behind a firewall or proxy of some kind? If so it may be causing problems. Do you have to configure other software for how it talks to the network?
