### ISSUE TITLE
_rg.ps1 not included in windows zips

### ISSUE THREAD

**Issue by dstcruz** [BurntSushi/ripgrep#399]
Is there a reason why we are not including `_rg.ps1` in the windows zip files for release? I can't find the file in the repo, so I assume that this is a generated file, which makes it hard to include in the [chocolatey windows package](https://chocolatey.org/packages/ripgrep), since it is not something I can easily download.

**Comment by BurntSushi** [comment]
I don't think there's any specific reason. My Windows shell skills are pretty bad, so I think it just needs to be added to the release script here: https://github.com/BurntSushi/ripgrep/blob/master/appveyor.yml#L42

**Comment by BurntSushi** [comment]
fixed in https://github.com/BurntSushi/ripgrep/pull/401
