### ISSUE TITLE
deprecate .rgingore, switch to .ignore

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#40]
As discussed between myself and @ggreer: https://news.ycombinator.com/item?id=12568822 Yay cooperation!

**Comment by tinyapps** [comment]
Might it also be possible to add a switch like ag's `--ignore PATTERN`?

> Ignore files/directories whose names match this pattern. Literal file and directory names are also allowed.

Sorry - don't mean to hijack this thread; just seemed tangentially related.

**Comment by BurntSushi** [comment]
`rg` has it with the `-g`/`--glob` flag.

**Comment by tinyapps** [comment]
Thanks for the fast response! And sorry for bothering you - I had tried the `--glob` flag, but had been erroneously placing it before the search term with the other options. After reading your response here, found your [detailed blog post](http://blog.burntsushi.net/ripgrep/) with a slew of examples, including just the one I was after:

> exclude files matching a particular glob:

`$ rg foo -g '!*.min.js'`

**Comment by BurntSushi** [comment]
Strange, the placement of `-g` (before or after pattern) shouldn't have any effect.

**Comment by tinyapps** [comment]
I must apologize again: on closer inspection, the problem was me not enclosing the glob in single quotes. I was doing this sort of thing:

`$ rg -t html -g index*` _searchterm_
`No such file or directory (os error 2)`

**Comment by BurntSushi** [comment]
Ah, yup, that'll do it. The shell takes over there. No worries! Glad you got it straightened out. :-)

**Comment by tinyapps** [comment]
Thanks again for the super-fast replies Andrew! And of course, for crafting ripgrep - it is a marvel! Do you accept donations? Or even have an Amazon wish list or the like?

**Comment by BurntSushi** [comment]
@tinyapps Thanks! If you're so inclined, please donate it to a cause you find worthy. (I'd recommend Wikipedia.)

**Comment by tinyapps** [comment]
Done! $100 sent to Wikipedia a few moments ago thanks to you and your generosity!

**Comment by BurntSushi** [comment]
Wow. That's very generous of you! Thank you so much! :-)

**Comment by tinyapps** [comment]
No, it is _you_ who is so generous with your time and expertise! And that after having been on the HN front page all day! Cannot thank you enough!
