### ISSUE TITLE
Should stop when output pipe is closed

### ISSUE THREAD

**Issue by glandium** [BurntSushi/ripgrep#409]
I was doing something like:
```
$ ssh host cat verylargearchive.zst | zstd -d | rg pattern | head
```
to check that my pattern made sense before running on the full thing. And that hang for a while, and I assume it would have waited for the whole thing to have been read.

Replace `rg` with `grep` and the program stops as soon as `head` closes its input pipe.

**Comment by BurntSushi** [comment]
Yes, this is a known bug. Dupe of #200.
