### ISSUE TITLE
What about "git grep"?

### ISSUE THREAD

**Issue by SylvainDe** [BurntSushi/ripgrep#417]
I've just discovered your awesome tool and I'm too far from a computer to perform a benchmark but from my experience, "git grep" is very fast (because it uses some git internal object iirc).
Would it be possible to include this in your benchmark.
(In any case, there is an obvious limitation because it only works on indexed files)

**Comment by BurntSushi** [comment]
`git grep` is featured in **both** the benchmarks in the README *and* extensively in the blog post linked from the README: http://blog.burntsushi.net/ripgrep/

**Comment by SylvainDe** [comment]
Oops indeed. Not sure how i managed to read the readme without spotting this. Sorry for the inconvenience.
