### ISSUE TITLE
Add -0 shortcut for --null

### ISSUE THREAD

**Issue by caedn** [BurntSushi/ripgrep#419]
I've use ag with `-0` a lot to safely pipe it into xargs. Any chance you could add the same alias so I don't have to type as much when switching to rg?

**Comment by BurntSushi** [comment]
I'd be willing to add a `-Z` short flag for `--null`, since that's what grep does. (ripgrep obviously takes a certain amount of inspiration from ag, but when there's a choice to be made with respect to flags, I've tended to side with GNU grep because of its ubiquity.)

**Comment by caedn** [comment]
That makes sense for GNU grep. Do note though that BSD grep (which ships with macOS) behaves differently:

    -Z, -z, --decompress
             Force grep to behave as zgrep.

Neither grep uses `-0`.

**Comment by BurntSushi** [comment]
Yuck. I'd like ripgrep to support decompression some day. I still lean towards `-Z`... However, `-0` also has precedent, e.g., with `xargs`.
