### ISSUE TITLE
Set default options

### ISSUE THREAD

**Issue by sgraham** [BurntSushi/ripgrep#423]
I prefer --no-heading as the default for copy-paste-ability.

On Mac/Linux I can just add a wrapper script that adds --no-heading, but on Windows a wrapper .bat to set default options causes the terrifically annoying "Terminate batch file (Y/N)?" prompt when hitting Ctrl-C so it's not optimal.

Is there any way to set some default options (environment variable, rc file, etc.)?

**Comment by BurntSushi** [comment]
> Is there any way to set some default options (environment variable, rc file, etc.)?

No. That's the subject of #196, so I'm going to close this as a duplicate.

> but on Windows a wrapper .bat to set default options causes the terrifically annoying "Terminate batch file (Y/N)?" prompt when hitting Ctrl-C so it's not optimal.

This is a critical piece of motivation for supporting config files. Could you share your experience in #196? In particular, are `bat` files the right way to write wrapper scripts in Windows? Is there a way to create aliases? (Please respond in #196, not here. :-))
