### ISSUE TITLE
How to use inside vim?

### ISSUE THREAD

**Issue by Neats29** [BurntSushi/ripgrep#425]
Thanks for building this, it's very cool. Quick question, I was wondering if you could please let me know or add to the readme how to integrate this with vim. At the very least I'm interested in 'search and replace' globally within a repository.

Thank you.

**Comment by FSMaxB** [comment]
You could ask [mileszs/ack.vim](https://github.com/mileszs/ack.vim) for integration of rg.

**Comment by Neats29** [comment]
@FSMaxB but from reading the other issues, it seems like some people are using it inside vim already, so I thought there might be a way...

**Comment by Neats29** [comment]
My bad for not searching the internet first. There is this plugin: [vim-ripgrep](https://github.com/jremmen/vim-ripgrep) and [this article](https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2) for using with `fzf` :)

**Comment by BurntSushi** [comment]
Sounds like you got your answer.

I wouldn't be opposed to putting links to editor integrations in the README. But since I don't use any of them myself, I probably won't do it.

**Comment by ericandrewlewis** [comment]
> I wouldn't be opposed to putting links to editor integrations in the README. But since I don't use any of them myself, I probably won't do it.

It took me a little to figure out how to do this. Can I open a PR with some suggested context setting for folks interested in this?

**Comment by BurntSushi** [comment]
@ericandrewlewis Yeah sure! Just put it toward the bottom of the README with the other questions. (At some point, I will split it out into a proper FAQ.)

**Comment by dyng** [comment]
If you don't mind using a plugin, It's my pleasure to recommend my plugin [ctrlsf.vim](https://github.com/dyng/ctrlsf.vim) which integrates `rg` out of the box, and supports **asynchronous searching**.

![](https://raw.githubusercontent.com/dyng/i/master/ctrlsf.vim/async-demo.gif)

**Comment by jpesce** [comment]
> For the future researchers:
> 
> ```
> set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
> ```
> 
> works great with no other configuration required.
> 
> I use this mapping to open the list of the files in location list:
> 
> ```
> nnoremap <Leader>g :silent lgrep<Space>
> ```
> 
> and further navigate it:
> 
> ```
> nnoremap <silent> [f :lprevious<CR>
> nnoremap <silent> ]f :lnext<CR>
> ```

As an addendum, since this issue comes up when searching for this in search engines.
Also set the format like so: `set grepformat=%f:%l:%c:%m,%f:%l:%m` and `:grep` will understand the format better :-)

**Comment by nyngwang** [comment]
> For the future researchers:
> 
> ```
> set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
> ```
> 
> works great with no other configuration required.

@pirj A noob question here: If this works, why do we need a plugin like vim-ripgrep?

**Comment by pirj** [comment]
> why do we need a plugin like vim-ripgrep?

At a glance, it offers match highlighting, and configuring quickfix window location.

**Comment by craigmac** [comment]
> Also set the format like so: set grepformat=%f:%l:%c:%m,%f:%l:%m
This will make the location list understand the output format better

The second value is not needed, it's there in the default 'grepformat' string, and it's better to only append to that value instead of overwriting it, in case you don't have rg installed, you'll still have a usable grepformat value, so something like:

```vim
if executable('rg') | set grepformat+=%f:%l:%c:%m grepprg=rg <options you prefer> | endif
```

**Comment by dehidehidehi** [comment]
Builing on the shoulders of what's been posted here.
This will use the `grep` command to search for a pattern, and then will prompt you for a replacement; it prefills most of the boiler plate to issue this command; I feel it's easier to search and replace everywhere if you have the visual confirmation (using the quickfix window) before proceeding to type the replacement.

```vim
" Handling search and replace boilerplate using ripgrep
if executable('rg') | set grepformat+=%f:%l:%c:%m grepprg=rg\ --vimgrep\ --no-heading\ --smart-case | endif
" We use feedkeys because we don't want to press enter at the end of this command.
command! -nargs=1 FindReplaceAll :silent grep <args> | copen | call feedkeys(":cdo %s/" . <q-args> . "/") | redraw!
" We use feedkeys because otherwise the screen isn't redrawn
nnoremap <silent> <C-r> :call feedkeys(':FindReplaceAll ')<CR>
```
