### ISSUE TITLE
Interrupting ripgrep causes to affect terminal colors. Windows

### ISSUE THREAD

**Issue by DoumanAsh** [BurntSushi/ripgrep#430]
I'm not sure how exactly coloring is made on Windows but you can `Crtl-C` ripgrep and it gets your console like that:

http://i.imgur.com/PR0wrCe.png

All non-colored fonts became red for example.
It can happen with any color that ripgrep is using just interrupt it in the moment when coloring starts...

P.s. workaround for powershell:
```
[Console]::ResetColor()
```

**Comment by DoumanAsh** [comment]
Ok, sorry i haven't looked properly and found https://github.com/BurntSushi/ripgrep/commit/de5cb7d22e00c18dfce082a68b0cf45924b56e7f

But no, it is bad. Really bad for user.
You cannot expect user to do clean-up after software.

**Comment by BurntSushi** [comment]
I reopened #281. Please use that and suggest a path forward. I don't need to be told that it is not desirable. I need help to figure out how to fix it.

**Comment by DoumanAsh** [comment]
Ok, i'm sorry i didn't mean to be rude. But i was surprised to see that issue is closed while bad fix has been reverted.
I'm planning to look into possible ways to deal with it.
