### ISSUE TITLE
rg --help outputs search results

### ISSUE THREAD

**Issue by bluss** [BurntSushi/ripgrep#439]
I don't understand this.

rg 0.5.0 installed using cargo install -f ripgrep compiled using `rustc 1.18.0-nightly (5309a3e31 2017-04-03)` platform: Linux x86-64.

`~/.cargo/bin/rg -h` outputs the help as expected, `~/.cargo/bin/rg --help` outputs..something that looks like every line of all the files?

**Comment by kbknapp** [comment]
`cargo install` doesn't use/respect the `Cargo.lock`. See #438 for details on this issue.

**Comment by BurntSushi** [comment]
Strange. I can't seem to reproduce. There's been a little bit of churn lately on handling `-h/--help`, so I wonder if compiling from `master` has the same bug. Would you be willing to try that?

**Comment by BurntSushi** [comment]
@kbknapp Oh. Derp. Thanks for that reminder. :-)

**Comment by BurntSushi** [comment]
> I can't seem to reproduce.

Of course, I didn't use the same steps as @bluss. Instead, I did this, which I thought was equivalent before @kbknapp's reminder:

```
$ git clone git://github.com/BurntSushi/ripgrep
$ cd ripgrep
$ git checkout 0.5.0
$ cargo build --release
$ ./target/release/rg --help
```

**Comment by kbknapp** [comment]
I just pushed the new version to crates.io so once the ripgrep tests pass it should be safe to merge ;-)

**Comment by BurntSushi** [comment]
OK, the PR is merged. I will close this one out once I put out a new release of ripgrep and test that `cargo install` works. Thanks again @kbknapp!

**Comment by bluss** [comment]
Cool. What does cargo install --locked do? It's not entirely clear.

**Comment by bluss** [comment]
I'm confused too, was just looking at cargo install and wondering if it were possible to ask it to respect the lock file. Then I learned it's not packaged.

**Comment by kbknapp** [comment]
>What does cargo install --locked do? It's not entirely clear.
> [..] was just looking at cargo install and wondering if it were possible to ask it to respect the lock file. Then I learned it's not packaged.

So, the `Cargo.lock` is never packaged? I'm wondering what `--locked` and `--frozen` do too, then. Seems strange to me, as it's pretty much the whole purpose for *binaries* so that things like this exact issue don't happen. I'd have thought (before just recently) that it'd be the *default* for `cargo install`

**Comment by yarko** [comment]
glad that simply following @BurntSushi 's clone/build idiom works for just copying the built command into place.

**Comment by BurntSushi** [comment]
I can confirm that `cargo install ripgrep` now works in `0.5.1`. Thanks for the report @bluss!

**Comment by bluss** [comment]
Thanks for fixing. I'm glad you continue to support cargo install, it's very convenient.. for rusties.

**Comment by bluss** [comment]
Fix confirmed on this end, by the way.
