### ISSUE TITLE
Searching with a glob pattern that matches a single file - file name is not printed

### ISSUE THREAD

**Issue by roblourens** [BurntSushi/ripgrep#440]
Have an empty directory

```
echo "foo" > a.txt
rg foo     # prints filename header
rg foo ./  # also prints filename
rg foo *   # does not print filename
rg foo ./* # does not print filename
rg foo ./a.txt  # does not print filename
```

If another file is in the directory, then the filenames are printed. I think this makes sense in the `rg a.txt` case but in the other cases, a user may be searching with a complex glob in a large directory, so doesn't it make sense to also print the filename?

**Comment by BurntSushi** [comment]
Globs are resolved by the shell on Unix, so when you use `rg foo *`, ripgrep never actually sees the `*`. Instead, it just sees the expansion, which in this case, is simply `rg foo a.txt`. In other words, in a directory with a single file `a.txt`, every single one of your commands is indistinguishable from the other from ripgrep's perspective.

If you always want to display the file path, then you can use the `-H/--with-filename` flag (which is also found in GNU grep).
