### ISSUE TITLE
How do I properly setup ripgrep?

### ISSUE THREAD

**Issue by idkvince** [BurntSushi/ripgrep#447]
Hey so I am using Atom and the package goto-defintion and it has a performance mode that depends on ripgrep. I downloaded ripgrep and have rg.exe. Ripgrep works in the command prompt but I cam't get it to work in atom. I have added the environment PATH to where rg.exe is located but I am still facing issues with using it within atom. I get "Please instsall ripgrep first" what should I do to remedy this situation? Thanks

**Comment by BurntSushi** [comment]
It seems like this is a question for the Atom or goto-definition people, isn't it? If rg works in the command prompt and you have your PATH set correctly, then that's pretty much the extent of installing rg.

**Comment by idkvince** [comment]
Okay thanks for the prompt response, I will talk with them.
