### ISSUE TITLE
Does ripgrep respect `export GREP_OPTIONS`?

### ISSUE THREAD

**Issue by peteyy** [BurntSushi/ripgrep#453]

**Comment by BurntSushi** [comment]
No.

**Comment by peteyy** [comment]
Is there any way I could add default configuration to it other than aliasing? I'd like to always search with `rg -C 3`

**Comment by BurntSushi** [comment]
Please see: https://github.com/BurntSushi/ripgrep/issues/196

Why is aliasing a problem? Why is creating a wrapper script a problem?
