### ISSUE TITLE
Allow fetching matched data in `globset`

### ISSUE THREAD

**Issue by hauleth** [BurntSushi/ripgrep#459]
I want to implement [Projectionist](https://github.com/tpope/vim-projectionist) in Rust however there is no functionality that allow me to load `*` part of `src/*.rs` glob match. It would be great addition to this library.

**Comment by BurntSushi** [comment]
I don't understand this feature request, sorry. Could you please provide more detail, examples and the specific problem you're trying to solve?

**Comment by hauleth** [comment]
Currently `globset::GlobMatcher` only have method to match against the path. However what I would also need is to have method that would return something like `Option<Match>` where I could extract the thing that was matched by `*` ONLY. That functionality is unavailabe in neither `glob` nor `globset`. I am currently on my mobile, so I will provide exact example later. 

--
Łukasz Jan Niemier

Dnia 26.04.2017 o godz. 03:58 Andrew Gallant <notifications@github.com> napisał(a):

**Comment by BurntSushi** [comment]
@hauleth Can you please describe the problem you're trying to solve? This description should not mention the `glob` or `globset` crates at all. In other words, *what is your specification*?

Can you also please provide an example of a globbing library that does what you want?

**Comment by hauleth** [comment]
I do not know any glowing library that support such feature, but basically what I need is something to match path like `a/b/c/d.rs` to glob `a/*.rs` and be able to extract part `b/c/d` which is the part matched by `*` in glob pattern. I need this to provide functionality of Projectionist that allow me to provide "alternate" files for given file which simply are path substitution based on glob.

**Comment by BurntSushi** [comment]
I don't know what Projectionist is, so mentioning it doesn't help me understand your feature request.

> I do not know any glowing library that support such feature

I also don't know of any globbing library that supports it. Probably because "capturing groups" aren't a thing in globs, so I don't see how you expect this to work at all.
