### ISSUE TITLE
zsh completions don't offer paths

### ISSUE THREAD

**Issue by spiffytech** [BurntSushi/ripgrep#465]
Tab completion under zsh only offers flags for `rg`, but doesn't complete file paths after my parameters.

**Comment by BurntSushi** [comment]
Sounds like a dupe of #375.

**Comment by spiffytech** [comment]
Hmmm, you're right, this issue is mentioned at the bottom of [this comment](https://github.com/BurntSushi/ripgrep/issues/375#issuecomment-281562815) on that issue. Apologies, there are quite a view different complaints in that issue.
