### ISSUE TITLE
Using --help with aliased rg

### ISSUE THREAD

**Issue by kaushalmodi** [BurntSushi/ripgrep#47]
I have aliased `rg` to `rg --follow`.

After that `rg --help` gives this error:

```
Invalid arguments.

Usage: rg [options] -e PATTERN ... [<path> ...]
       rg [options] <pattern> [<path> ...]
       rg [options] --files [<path> ...]
       rg [options] --type-list
       rg --help
       rg --version
```

So I need to remember to use `\rg --help` when I need to see help.

The `--help` arg probably needs to ignore all other args provided to `rg`.

**Comment by BurntSushi** [comment]
Yeah, I see, Docopt doesn't make this especially convenient. It looks like I'll need to hand-hold Docopt through this one. (Instead of letting it figure out when to show the usage message itself.)

**Comment by kaushalmodi** [comment]
Thanks for the fix. I confirm the fix.
