### ISSUE TITLE
rename repo into rg?

### ISSUE THREAD

**Issue by kindlychung** [BurntSushi/ripgrep#470]
It's counter-intuitive that we need to `cargo install ripgrep` only to use the `rg` executable.

**Comment by BurntSushi** [comment]
Sorry, but no.

If it were up to me, I would have called the executable ripgrep. But I would have been overrun by complaints that the executable name was too long. Therefore, I wanted it to be short. But if it's short, then it's hard for it to carry any significant meaning and makes it harder to search for. ripgrep is a meatier name, and by using it in as many places as I can (*except* for the executable name), it makes it much more discoverable.

The situation is lamentable, and I think your particular issue is, at best, a very minor nuisance compared to the gains.

**Comment by BurntSushi** [comment]
Also, a minor note: but the title of this issue asks to rename the repository, but the content if your issue mentions `cargo install ripgrep`. The repository name on github is distinct from the crate name on crates.io. "ripgrep" is also used in various packaging repositories, such as brew and Archlinux.
