### ISSUE TITLE
Encoding issue when piping rg output

### ISSUE THREAD

**Issue by elirnm** [BurntSushi/ripgrep#471]
There seems to be an encoding issue when piping the output of a ripgrep search. The characters `ø æ å ä` (and probably others, those are just the ones I've tested with) are converted to `??` when being piped to anything.

It seems to only be with piping; passing stdout to a file with `>` works fine (at least in cmd.exe where files are created with utf8).

![capture](https://cloud.githubusercontent.com/assets/19817004/25610476/32325c72-2ed8-11e7-8c12-443fb138567f.PNG)

This is what I used to test this.
```
mkdir rgtest
cd rgtest
echo "testøæåä" > strtest.txt
mkdir testø
echo "blahblah" > testø/testå.txt
```

Then search for various things as seen in the picture. (The `--colors` option is unrelated; that's just so you can see the filenames in Powershell).

This is on Windows 7 with ripgrep 0.5.1. I've recreated this in both powershell and cmd.exe, but I don't have a Linux install to test it there.

**Comment by BurntSushi** [comment]
Can you provide the raw bytes of strtest.txt?

**Comment by elirnm** [comment]
```
116
101
115
116
195
184
195
166
195
165
195
164
13
10
```

If that's not what you wanted you'll have to give me more specific instructions.

The file is currently UTF-8 encoded but this issue occurs with other file encodings as well (and when not reading from a file, as seen in the `--files` examples.

**Comment by elirnm** [comment]
Hmm, this might not actually be ripgrep. Piping these characters is succeeding with every native Powershell command, but failing with every call to an executable or any non-built-in program.

![cap](https://cloud.githubusercontent.com/assets/19817004/25614555/4b3a87bc-2ee7-11e7-882e-965428a56dec.PNG)

And while I seem to remember it failing in cmd.exe before, it works fine there now.
