### ISSUE TITLE
path autocompletion not supported

### ISSUE THREAD

**Issue by ronnin** [BurntSushi/ripgrep#480]
as to **grep**, when typing path, autocompletion is supported by press Tab after /
> grep 'pattern' /path/to/file

but the beloved **rg** dosn't.

env:
> zsh + oh-my-zsh
   mac os 10.12.4

**Comment by BurntSushi** [comment]
I don't maintain the auto-completions. They are auto-generated. I cannot fix this. You'll need to file a bug against clap: https://github.com/kbknapp/clap-rs
