### ISSUE TITLE
Unable to use query starting with "-"

### ISSUE THREAD

**Issue by RalfJung** [BurntSushi/ripgrep#482]
Calling `rg -e --` (to search for all occurrences of "--") fails with
```
$ rg -e "--"
error: The argument '--regexp <pattern>...' requires a value but none was supplied
```
In contrast, the same pattern works for the usual GNU-style tools:
```
$  egrep -e "--" -R .
...
```

I am aware that I can work around this issue using e.g. `[-]-` as the pattern, but that should not be necessary.

**Comment by BurntSushi** [comment]
This might be a clap bug. Note that `rg -e -` works.

cc @kbknapp

**Comment by kbknapp** [comment]
It looks like it's due to the special casing of `--` meaning "only free args follow" taking precedence over the `-e` allowing values to start with `-`. This should be a decently easy fix, I think I can knock it out later today if all goes well.

**Comment by BurntSushi** [comment]
@kbknapp If there were even an example of a low priority bug, this would be it. :-) Thank you all the same though!
