### ISSUE TITLE
--files --quiet should be quiet

### ISSUE THREAD

**Issue by alecthomas** [BurntSushi/ripgrep#483]
`rg --files` always lists files, even if `--quiet` is passed. I did not expect that.

**Comment by nateozem** [comment]
From `--help`

	   -q, --quiet
	           Do not print anything to stdout. If a match is found in a file, stop searching. This is
	           useful when ripgrep is used only for its exit code.

"anything" didn't apply, unless `--quiet` needs a redefinition.

**Comment by BurntSushi** [comment]
I suppose in order to make this useful, ripgrep should return an error exit code if `--files` would otherwise result in no output. (Otherwise, I don't know what the point of `--quiet` is.)

**Comment by BurntSushi** [comment]
@alecthomas Can you say more about why you're trying to use `--files --quiet`?

**Comment by alecthomas** [comment]
Similar to why I'd use a normal grep... I want to know if files with a certain extension exist, for the purposes of further processing. A bit like `find . -type f -name '*.h' > /dev/null && do_something`

**Comment by alecthomas** [comment]
I'm doing `if rg --files --quiet --glob '*.go'; then ... fi`

**Comment by BurntSushi** [comment]
Ah, OK, I actually didn't even know ripgrep already handled the exit code correctly here. Nice. Yes, `--quiet` should work.

**Comment by alecthomas** [comment]
👍
