### ISSUE TITLE
no output using `--color never` on Windows 

### ISSUE THREAD

**Issue by Yggdroot** [BurntSushi/ripgrep#500]
`rg --version`: ripgrep 0.5.2
Windows 10, x64
There is output using `rg . --files`, but no output using `rg . --files --color never`.

**Comment by elirnm** [comment]
Probably related to https://github.com/BurntSushi/ripgrep/issues/466

**Comment by BurntSushi** [comment]
My guess is that this is a duplicate of #466 (which I can't reproduce).
