### ISSUE TITLE
path separator on windows is not always \

### ISSUE THREAD

**Issue by albfan** [BurntSushi/ripgrep#501]
running under mingw output shows paths with \ but mingw (running bash) uses /

Were is the code related with path separator?, maybe mingw can be detected to fix that

**Comment by BurntSushi** [comment]
There is no automatic detection, but you can use the `--path-separator` flag to override the path separator in any environment. I imagine sticking it in an alias might work for you?

**Comment by albfan** [comment]
On cmd it works, but on mingw bash (the one that git for windows provides if you're curious) it outputs:

    $ rg foo --path-separator '/'
    A path separator must be exactly one byte, but the given separator is 20 bytes.

**Comment by albfan** [comment]
same without quotes

**Comment by BurntSushi** [comment]
That error message is baffling to me. Someone will need to debug it. I'll do it eventually.

**Comment by albfan** [comment]
Ok, count on me for that

Seems there's window detecting no?
https://github.com/BurntSushi/ripgrep/blob/13235b596f93f7f0e7ce76e7967996787147e96e/src/printer.rs#L412

and docs say it too:
https://github.com/BurntSushi/ripgrep/blob/master/doc/rg.1#L390

Have to check what is behind cfg!(windows)

maybe that can be a better fix. By now options would work

If you want to go for OS detection or want to detect that problem with bytes just open a bug and comment here

**Comment by BurntSushi** [comment]
@albfan Why did you close this? If `--path-separator` isn't working, then that's a bug.

**Comment by albfan** [comment]
My problem with choose a separator is resolved:

    $ rg foo --path-separator '\x2F'

There's another problem that maybe you want to solve. But feels that is a different issue

Do you want me to reopen this and work that here?

**Comment by BurntSushi** [comment]
@albfan I understand that you found a work-around, but if `rg foo --path-separator /` is giving your error messages about the path separator being 20 bytes, then that's a bug.

If there's a distinct issue, then I'd say open a new ticket...

**Comment by albfan** [comment]
Here some test:

```
$ rg foo --path-separator /
A path separator must be exactly one byte, but the given separator is 20 bytes.

#this works
$ rg foo --path-separator //

$ rg foo --path-separator aa
A path separator must be exactly one byte, but the given separator is 2 bytes.

$ rg foo --path-separator aaa
A path separator must be exactly one byte, but the given separator is 3 bytes.

$ rg foo --path-separator aaa/
A path separator must be exactly one byte, but the given separator is 4 bytes.

$ rg foo --path-separator aaa//
A path separator must be exactly one byte, but the given separator is 5 bytes.

#double do not increase faulty bytes
$ rg foo --path-separator aaa//
A path separator must be exactly one byte, but the given separator is 5 bytes.

$ rg second --path-separator /a
A path separator must be exactly one byte, but the given separator is 3 bytes.

#what???
$ rg second --path-separator /aa
A path separator must be exactly one byte, but the given separator is 23 bytes.

$ rg second --path-separator /aaa
A path separator must be exactly one byte, but the given separator is 24 bytes.
```

Have to learn how to debug rust, any hint on windows?

**Comment by BurntSushi** [comment]
@albfan Ah, I wonder if the problem here is your shell. Maybe the shell is expanding `/` to something like `/c/cygdrive/` or something similar?

**Comment by albfan** [comment]
I think so

**Comment by albfan** [comment]
http://www.mingw.org/wiki/Posix_path_conversion

Here we are. / gets translated into a absolute path on mingw. Double // prevents conversion.

That's why 20 bytes

This is solved then

**Comment by albfan** [comment]
> Definitive solution

```
$ cat ~/.bashrc
...
alias rg='rg --path-separator="//"'
...
```
