### ISSUE TITLE
Using an unparenthesized pipe with -w produces unexpected results

### ISSUE THREAD

**Issue by scottmcm** [BurntSushi/ripgrep#506]
I ran `rg -w 'min|max' src/lib*` in the rust source, and got far more results than I expected.  For example:
```
src/liblibc\src\unix\solaris\mod.rs
17:pub type minor_t = ::c_uint;
250:        pub f_namemax: ::c_ulong,
1070:    pub fn mincore(addr: *const ::c_void, len: ::size_t,
```

It seems to be matching `(\bmin)|(max\b)`, whereas I expected `\b(min|max)\b`.

repro'd in 0.4.0 and 0.5.2

**Comment by BurntSushi** [comment]
Hah. Nice. Looks like you are right: https://github.com/BurntSushi/ripgrep/blob/master/src/args.rs#L508

**Comment by BurntSushi** [comment]
This should be a relatively easy bug if anyone wants to take a crack at it. Basically, all that needs to be done is to put a non-capturing group around the inner expression here: https://github.com/BurntSushi/ripgrep/blob/13235b596f93f7f0e7ce76e7967996787147e96e/src/args.rs#L508 --- And put a regression test in `tests/tests.rs` (search for `regression` to see examples of other regression tests).
