### ISSUE TITLE
error parsing glob '!**.sha1': invalid use of **; must be one path component

### ISSUE THREAD

**Issue by Yggdroot** [BurntSushi/ripgrep#507]
There is a `.gitignore` in the source of chromium:
$ cat .gitignore
```
*/*
!**.sha1
```
If run rg as this: `rg --files`, the error `./.gitignore: line 2: error parsing glob '!**.sha1': invalid use of **; must be one path component` is printed.

**Comment by BurntSushi** [comment]
What is the expected behavior? The error message seems pretty clear. In any case, this is a duplicate of #373.

**Comment by Yggdroot** [comment]
Oh, sorry, did not notice it.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/43597746-e244b3ac-967a-11e8-8c9b-9e5f37f00ea1.png)
I'm getting this even with no uses of `**` in my gitignore. Even with no gitignore at all.

**Comment by BurntSushi** [comment]
@ChildishGiant Sorry, but your comment **is not actionable**. Please open a new issue and follow the instructions listed in the issue template. Please provide a **reproducible example** and **include output using the `--debug` flag**.

**Comment by ChildishGiant** [comment]
Turns out that an extension had generated some invalid files.exclude workspace settings. Sorry for the hassle.
