### ISSUE TITLE
Support for matching new lines in expression?

### ISSUE THREAD

**Issue by ideasman42** [BurntSushi/ripgrep#508]
I was looking to replace `pcregrep` with `ripgrep`, but found it doesn't have support for newline.

Example search for:
```
    }
    else some_text;
```
Command:
```
find . -name '*.c' | xargs pcregrep -n -M '\s}\n\s+else.*;\s*$'
```
Does ripgrep plan to support newline literals?

**Comment by BurntSushi** [comment]
How is this different than multiline support? See: #176

**Comment by ideasman42** [comment]
Sorry for duplicate, searched existing issues for `newline` `new line`.
