### ISSUE TITLE
Q&A: Should `-F` ignore all regular expression characters, including `$` and `^`?

### ISSUE THREAD

**Issue by Byron-TW** [BurntSushi/ripgrep#515]
Recently I was looking for known values in a codebase that contain all kinds of characters, including `$`.  `-F` was used for this assuming this searches for 'fixed strings' in the sense that they are just a string literal. However, `$` is definitely interpreted by the regex engine, and needs to be escaped via `\$`.

Is this intended, or is this a bug?

Thank you,
Sebastian

PS: Please apologise if this is not the right forum for questions like these.

**Comment by BurntSushi** [comment]
Could you please provide a reproducible example that demonstrates this behavior? It's pretty hard to help you otherwise. For example, things seem to be working correctly for me:

```
$ cat test
foo$bar
$ rg 'foo$' test
$ rg -F 'foo$' test
1:foo$bar
```

**Comment by Byron-TW** [comment]
I am so sorry to have wasted your time ...!
In the shell, I managed to use double-quotes instead of single-quotes.
