### ISSUE TITLE
Color replacements when using --replace

### ISSUE THREAD

**Issue by lydell** [BurntSushi/ripgrep#521]
ripgrep colors matches in red (by default). That's very useful.

When using the `--replace` option, I would find it very useful if the replacements were colored. Currently, nothing is colored (except file paths and line numbers of course).

Here's a screenshot showing what I mean:

![screenshot from 2017-06-17 14-21-23](https://user-images.githubusercontent.com/2142817/27252839-4bf37a2e-5368-11e7-9f66-5adf9f90a67e.png)

And here's a text sketch:

```
$ cat test
exponential notation: 123e4
another example: 42e-10
$ rg '(\d+)e' --replace '${1}E' test
1:exponential notation: <color>123E</color>4
2:another example: <color>42E</color>-10
```

What do you think?

(By the way, thank you very much for ripgrep. It's excellent.)

**Comment by BurntSushi** [comment]
Agreed. I like it!

**Comment by okdana** [comment]
Maybe a new colour spec? So you could do like `--colors 'replace:fg:red'` (with the default being identical to the default `match` spec)?

**Comment by BurntSushi** [comment]
@okdana I'd rather not add a new color spec. We should just use the existing `match` spec. When `-r/--replace` is used, all matches are replaced, so there's never a need to distinguish between the replacement color and the match color.

**Comment by okdana** [comment]
Fair
