### ISSUE TITLE
RFE: show enabled features in --version output

### ISSUE THREAD

**Issue by g2p** [BurntSushi/ripgrep#524]
Just to make sure that SSE and AVX are enabled.

See `systemd --version` for what the output could look like.

**Comment by g2p** [comment]
Is it okay if I tweak the output to be more like systemd produces, before this is released?

**Comment by BurntSushi** [comment]
@g2p I think I'm OK with that. Is systemd's output standard or common?

**Comment by g2p** [comment]
It's machine parseable at least; I picked it as the best looking option I'm aware of.
