### ISSUE TITLE
`rg -g foobar` ?

### ISSUE THREAD

**Issue by steckerhalter** [BurntSushi/ripgrep#54]
I'm used to this from `ag` as a more convenient `find`. Could that be supported? Thanks

**Comment by BurntSushi** [comment]
Try `rg -g foo --files`.

**Comment by steckerhalter** [comment]
Thanks, a bit more to type though :)

Noted just now that `ag` seems to use wildcards by default:

```sh
$ ag -g grandshell
etc/grandshell-theme/README.md
etc/grandshell-theme/grandshell-theme-pkg.el
etc/grandshell-theme/grandshell-theme.el
etc/grandshell-theme/grandshell-theme.png
etc/etc/emacs/grandshell-theme.el
```

and it searches the whole path:

```sh
$ rg -g grandshell --files
$ rg -g *grandshell* --files
./etc/grandshell-theme/grandshell-theme-pkg.el
./etc/grandshell-theme/grandshell-theme.el
./etc/grandshell-theme/grandshell-theme.png
./etc/etc/emacs/grandshell-theme.el
```

**Comment by BurntSushi** [comment]
The goal here isn't too do everything exactly like ag. For example, it would be nice to have one glob syntax. If you want the whole path, try `**/grandshell/**`.

**Comment by steckerhalter** [comment]
Of course, I'm just noticing and expecting `rg` to be just the same. And maybe you can use this information for some purpose...

**Comment by BurntSushi** [comment]
Gotya. Thanks for the bug report, it's useful to be aware of the difference, but I think I'm going to stick with what we have.
