### ISSUE TITLE
Errors running the benchmark suite

### ISSUE THREAD

**Issue by sivamahadevan** [BurntSushi/ripgrep#558]
What is the correct usage of the benchmark python script? I tried to run it based on the information posted here: http://blog.burntsushi.net/ripgrep/#benchmark-runner.
Specifically, running `$ ./benchsuite --dir /downloaded/data/dir --list` gives me this:
```
Traceback (most recent call last):
  File "./benchsuite", line 1322, in <module>
    main()
  File "./benchsuite", line 1242, in main
    disabled_cmds=args.disabled.split(','),
AttributeError: 'NoneType' object has no attribute 'split'
```
My python3 version is `Python 3.6.1`

**Comment by BurntSushi** [comment]
There was a bug. Should be all set now. Thanks for reporting!

**Comment by sivamahadevan** [comment]
I'm not sure if they're fully resolved, but at least I'm able to list the benchmarks available. Now, after downloading "subtitles-ru" and trying to run `$ ./benchsuite --allow-missing --dir /data/dir 'subtitles_ru_literal'`, I'm getting a similar error:
```
Traceback (most recent call last):
  File "./benchsuite", line 1323, in <module>
    main()
  File "./benchsuite", line 1270, in main
    disabled_cmds=args.disabled.split(','),
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by BurntSushi** [comment]
@sivamahadevan I pushed another commit. Sorry. Try again?

**Comment by sivamahadevan** [comment]
Yes, it seems to work, thanks for the fixes!
