### ISSUE TITLE
There may be something wrong on windows.

### ISSUE THREAD

**Issue by Yggdroot** [BurntSushi/ripgrep#561]
`rg --files -g "!.svn"` has output while `rg --files -g '!.svn'` does not have.
The only difference is quote, why? Is it a bug?

**Comment by BurntSushi** [comment]
> Is it a bug?

I don't understand Windows quoting rules and your bug report doesn't say which shell you're using, so it's impossible to say.

**Comment by Yggdroot** [comment]
I used the cmd.exe of windows.

**Comment by therockmandolinist** [comment]
@Yggdroot https://stackoverflow.com/a/24181667/4992688

**Comment by Yggdroot** [comment]
@therockmandolinist  Got it. Thank you.
