### ISSUE TITLE
Does it support 32 bit OS?

### ISSUE THREAD

**Issue by btstw** [BurntSushi/ripgrep#563]
I am using fedora_24 _i386.
When I try to install this tool, it shows error message .
"Failed to synchronize cache for repo 'carlwgeorge-ripgrep', disabling."

**Comment by okdana** [comment]
Doesn't seem like it, the only RPMs here are for `x86_64`:

https://copr-be.cloud.fedoraproject.org/results/carlwgeorge/ripgrep/

Pretty sure that repo is maintained by a third party tho so you might have to talk to whoever that is

In the mean time, though, the first-party builds on GitHub include a 32-bit version:

https://github.com/BurntSushi/ripgrep/releases/tag/0.5.2

**Comment by btstw** [comment]
I was able to use first-party builds, thanks.
