### ISSUE TITLE
Enable short-cut to open specific search result in editor

### ISSUE THREAD

**Issue by robdmc** [BurntSushi/ripgrep#567]
I constantly use the `sack` tool ( https://github.com/sampson-chen/sack ) to provide a nice wrapper around my silversearcher results.  It allows me to quickly open a file with vim at the exact location of the search result.  As you can imagine, this saves tons of time when exploring a large code base.  I would love to see this capability in ripgrep.  I recently discovered a similar project implemented in go  https://github.com/zph/go-sack.  I'm not sure how difficult it would be to add this capability to ripgrep, but it would greatly improve its usefulness.

**Comment by BurntSushi** [comment]
ripgrep is certainly not going to grow `sack` functionality on its own. It seems like it should be added as a wrapper tool like it is for the silver searcher. Adding editor specific functionality to ripgrep doesn't seem like something I'd be willing to maintain.

**Comment by robdmc** [comment]
Thanks for the quick reply.  Great work with ripgrep.
