### ISSUE TITLE
ripgrep match styling not detected by emacs

### ISSUE THREAD

**Issue by tspiteri** [BurntSushi/ripgrep#570]
Emacs seems to be matching a particular ANSI pattern in `grep.el` to be able to jump directly to the match in a line, using the pattern `"\033\\[0?1;31m\\(.*?\\)\033\\[[0-9]*m"`. This works for GNU grep which styles the match using `"\x1b[01;31m"`, but not for rg which styles the match using `"\x1b[31m\x1b[1m"`.

Note: As a workaround, I wrapped rg with a script:
```sh
#!/bin/sh
rg --color ansi -nH --no-heading "$@" | sed 's/\o033\[31m\o033\[1m/\o033[1;31m/g'
```

**Comment by okdana** [comment]
Related? https://github.com/BurntSushi/ripgrep/issues/244#issuecomment-262168037

**Comment by BurntSushi** [comment]
I don't think it's reasonable to expect that ripgrep's ANSI styling matches grep's ANSI styling byte-for-byte. Your work-around seems fine to me?
