### ISSUE TITLE
Regex feature expansion?

### ISSUE THREAD

**Issue by voider1** [BurntSushi/ripgrep#571]
I've read the part about regex in the README, is there no way you would consider adding more regex syntax to ripgrep? I really like it, and I'd love to use it, but I use a lot of regex. Things like:

```regex
rg -tpy 'def (?=[A-Z])[a-zA-Z\-_]+\(.+\):'`
```

don't even work and forces me to write things like:

```regex
rg -tpy '[a-zA-Z\-_]+\(.+\):' | ggrep -P 'def (?=[A-Z])'
```

I might as well just use (GNU) grep, which is quite a shame. I really enjoy ripgrep's sane defaults and usability.

**Comment by okdana** [comment]
The `regex` crate is based on / inspired by [RE2](https://en.wikipedia.org/wiki/RE2_(software)), which is deliberately designed to avoid back-tracking for safety and edge-case-performance reasons; as a consequence it doesn't support look-around features like this.

I can't figure out why you need look-ahead for the case you've provided, but anyway — [`ag`](https://github.com/ggreer/the_silver_searcher) uses PCRE, which does support these features, if that's something that's critically important to you.

**Comment by BurntSushi** [comment]
Thanks @dana, that covered it. :)

Another tool that supports fancier features is Universal Code Grep, which uses PCRE2: https://github.com/gvansickle/ucg

**Comment by BurntSushi** [comment]
And yes, I also can't figure out why you need look around for the given example. Your broader point is reasonably accurate though. Sometimes the lack of lookaround forces you to use a pipeline, but that should eliminate the lookaround, unlike in your example.

**Comment by voider1** [comment]
@okdana How would I otherwise know if, say, the first letter of a sequence is an uppercase? Just pipe through grep?

**Comment by okdana** [comment]
Unless i'm misunderstanding, it seems like you should just be able to do `def [A-Z][A-Za-z_-]+` or w/e

**Comment by BurntSushi** [comment]
(Looks like @voider1 deleted their comment, but yeah, @okdana that's what I was going to say too! You're quick. :P)

**Comment by voider1** [comment]
@BurntSushi I posted the comment and then realized I could do that too.
