### ISSUE TITLE
Changing definition of word character

### ISSUE THREAD

**Issue by pesterhazy** [BurntSushi/ripgrep#573]
Is it possible to change what is considered a _word character_ when using `-w`? Take the lisp/clojure definition of symbols for example, which allows `-` as part of a function name. Say I want to search for `time` but exclude `start-time`, `time-period`. That is, I want to classify `-` as a word character.

`(?:^|[^\w-])time(?:[^\w-]|$)` seems to do the job. But is there a better way?

**Comment by okdana** [comment]
The `-w` option just surrounds the pattern with `\b`s, which is hard-coded behaviour. There is some discussion of possibly changing it to more closely replicate the way `grep` works, but that wouldn't help you here either. So i can't think of a better option than the pattern you mentioned

**Comment by BurntSushi** [comment]
@okdana Has it right. The definition of `\b` is set in stone.
