### ISSUE TITLE
Please add julia type

### ISSUE THREAD

**Issue by pintergreg** [BurntSushi/ripgrep#574]
[Julia](https://julialang.org/) uses the `.jl` extension and it would be great if I could use a Julia type filter. I figured out `*.jl` is listed in lisp types, so I'm using `-tlisp` currently, but a `-tjl` would be more handy such as `-tpy` for python.
Thanks

**Comment by BurntSushi** [comment]
It already exists: https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/types.rs#L147

If you want `jl` specifically, then please submit a PR.

**Comment by pintergreg** [comment]
You're right. I did not check the master, only the latest release I'm using (0.5.2) nor specified version.
