### ISSUE TITLE
"-w" does not work if pattern contains "|"

### ISSUE THREAD

**Issue by jpetkau** [BurntSushi/ripgrep#580]
For example, the command `rg -w 'aa|ee|ii|oo|uu'` incorrectly matches `foo` and `aardvark`.

It appears that `-w` is implemented by surrounding the pattern with `\b`, so the above is equivalent to `\baa|ee|ii|oo|uu\b`, when it should be equivalent to `\baa\b|\bee\b|\bii\b|\boo\b|\buu\b` or `\b(aa|ee|ii|oo|uu)\b`.

**Comment by BurntSushi** [comment]
This is fixed in master (see #516).
