### ISSUE TITLE
_rg zsh completion refuses to work on Arch Linux

### ISSUE THREAD

**Issue by ishitatsuyuki** [BurntSushi/ripgrep#582]
```
zsh 5.4.1 (x86_64-unknown-linux-gnu)
```

```
$ rg <tab>
_rg: parse error near `)'
_rg: parse error near `)'
```

Side note: I have [zim](https://github.com/Eriner/zim) installed.

**Comment by okdana** [comment]
I don't have Arch, but i can't seem to replicate with zsh 5.4.1 on macOS. Never used ZIM before, but i tried sourcing its template files as mentioned in the `README` and i don't seem to have any troubles there either.

Do you know if you're using the completion function included with `rg` 0.6.0 (released last night), or is it the older one?

Can you do the following please?

1. `autoload -Uz +X _rg`
2. `typeset -f _rg` -> paste the output into a Gist and link here
3. `typeset -ft _rg`
4. `rg <tab>` -> paste the output into another Gist and link here

**Comment by ishitatsuyuki** [comment]
```
 ishitatsuyuki@X1Yoga  ~  autoload -Uz +X _rg
zsh: parse error near `)'
 ✘ ishitatsuyuki@X1Yoga  ~  typeset -f _rg
_rg () {
	# undefined
	builtin autoload -XUz
}
 ishitatsuyuki@X1Yoga  ~  typeset -ft _rg
 ishitatsuyuki@X1Yoga  ~  rg
(no error, silence)
```

**Comment by okdana** [comment]
Hm, i guess that makes sense if the file itself is broken.

`print -l ${^fpath}/**/_rg(#qN)` should tell you where the file is; can you paste the command's output as well as the contents of the file(s) it lists?

**Comment by ishitatsuyuki** [comment]
Yeah, you were correct. The packager missed something:
```
install -Dm644 "target/release/build/ripgrep-"*/out/_rg.ps1 "$pkgdir/usr/share/zsh/site-functions/_rg"
```

Uh, so I will overwrite with the version in the repository for the meanwhile. I cannot find the ps1 file inside repo either, is that removed or where is that generated from?

**Comment by ishitatsuyuki** [comment]
Anyway, closing.

**Comment by okdana** [comment]
Oh, i don't know what the deal with that is. The `.ps1` file is a completion function for PowerShell, it has nothing to do with zsh. It's auto-generated during the build by `clap`. 🤷‍♀️
