### ISSUE TITLE
Missing benchmark for GNU grep

### ISSUE THREAD

**Issue by vktec** [BurntSushi/ripgrep#59]
ripgrep claims to be faster than GNU grep, however I see no benchmarks for GNU grep in the README. Before I can evaluate whether ripgrep would be useful to me, I would need to see some _significant_ improvements over `grep -r` in terms of speed.

`.gitignore` support is not particularly useful to me and grep can search only specific files with the help of globs (`grep pattern {,**/}*.py`), so speed would be the only real benefit over GNU grep and, personally, I doubt that ripgrep is fast enough to make a difference.

**Comment by BurntSushi** [comment]
The README links to benchmarks: http://blog.burntsushi.net/ripgrep

**Comment by vktec** [comment]
Ah yes, I found the GNU grep benchmarks. Thanks!

Personally, I'd consider adding GNU grep to the list of benchmarks on the README, as it's mentioned frequently throughout other parts of said README.

**Comment by howaboutsynergy** [comment]
`rg`8892bf648cfec111e6e7ddd9f30e932b0371db68  is like 4.5 times faster than gnu `grep`(3.3) when first run aka not disk-cached
and
`rg` is 2.8 times faster when disk-cached.

ran on chromium repo.
test based on https://github.com/BurntSushi/ripgrep/issues/1392#issuecomment-536330689
