### ISSUE TITLE
Option to use bytes regex?

### ISSUE THREAD

**Issue by lespea** [BurntSushi/ripgrep#591]
Sorry if this already exists and I just can't find it.  I have an issue where I'm piping a large amount of data into rg and it's not always valid unicode (could be a mix of encodings in the same stream).  I tried using the encoding ascii but the regex will still complain that the input isn't valid utf8.  Is there (or could there be) a way to use the bytes::Regex instead of the normal Regex to get around this issue?

**Comment by BurntSushi** [comment]
Sorry, but the way you've described this issue doesn't make any sense to me. Please provide a way for me to reproduce your problem.

bytes::Regex is a red herring. That's what ripgrep already uses.

**Comment by lespea** [comment]
Well sorry to waste your time but I completely misread what the `-f` option did. My apologies!
