### ISSUE TITLE
`-trs` claims unrecongized file type

### ISSUE THREAD

**Issue by valarauca** [BurntSushi/ripgrep#592]
Running ripgrep to find a debug message, within the root I run `$ rg -trs 'ProcNotes'` to help locate a debug error. I was notified `unrecongized file type: .rs`.

I rebuilt the current git repo's head, and the error persisted. Am I doing something wrong?

**Comment by okdana** [comment]
The proper name of the type that includes `.rs` files is actually `rust`:

```
% rg --type-list | rg -w rs
rust: *.rs
```

So `-trust` should work.

**Comment by BurntSushi** [comment]
I think the error message pretty much says it. `rs` isn't a recognized file type. Assuming you're trying to search Rust files, I think you want `-trust`. If you want to see the available file types, you can run `rg --type-list`.

**Comment by BurntSushi** [comment]
I wouldn't be opposed to adding `rs`, although I'm trying to avoid having a bunch of aliases (but am failing).

**Comment by valarauca** [comment]
I just kind of assumed as `-ttoml` or `-tjs` seemed to imply `-trs`. 

>I'm trying to avoid having a bunch of aliases (but am failing).

Welcome to building a cli tool :P
