### ISSUE TITLE
--with-filename doesn't show filenames on each match in a tty

### ISSUE THREAD

**Issue by dfabulich** [BurntSushi/ripgrep#596]
I like having `rg` print a filename on each matched line. I use iTerm2 for macOS, where I can command-click on a line like `foo.c:123:blah` and have Sublime automatically open `foo.c` at line 123.

By default, `rg` enables `--heading` in a tty:
> This shows the file name above clusters of matches from each file instead of showing the file name for every match. This is the default mode at a tty.

That breaks my use case, so I tried using `-H` or `--with-filename`:
> Prefix each match with the file name that contains it. This is the default when more than one file is searched.

I was quite surprised to find that this did nothing. Of course it says "This is the default when more than one file is searched," but I was searching more than one file and it was still just showing the heading and not showing the file name with "each match" on each line.

In fact, to get the output I want, I have to use `--no-heading`:
> Don't group matches by each file. If -H/--with-filename is enabled, then file names will be shown for every line matched. This is the default mode when not at a tty.

I think the current behavior of `--with-filename` would be better described like this:
> Display the file name for matches. This is the default when more than one file is searched. If --heading is enabled, the file name will be shown above clusters of matches from each file; otherwise, the file name will be shown on each match.

**Comment by BurntSushi** [comment]
LGTM!

**Comment by dfabulich** [comment]
I'm not sure if my use case is particularly unusual, but I'd prefer `--no-heading` by default in a tty. Am I right in understanding that since there's no `.rgrc` #196 I'd have to `alias` `rg` to get that behavior?

**Comment by BurntSushi** [comment]
Yes. Defaults aren't changing. Sorry.

**Comment by KindDragon** [comment]
Can you add short option for `--no-heading`?

**Comment by BurntSushi** [comment]
@KindDragon Please don't post unrelated requests in closed issues. Please open a new issue and fill out the provided template.
