### ISSUE TITLE
Does WalkParallel::run need to be blocking?

### ISSUE THREAD

**Issue by sharkdp** [BurntSushi/ripgrep#601]
Currently, there is the following loop at the end of the `WalkParallel::run` method:

https://github.com/BurntSushi/ripgrep/blob/beb010d004a79eedb8baa6f4eab21532e83a0ef0/ignore/src/walk.rs#L944-L946

When generating a `WalkParallel` over a directory with many entries in [fd](https://github.com/sharkdp/fd) (see [this PR](https://github.com/sharkdp/fd/pull/41)), this loop - and therefore, the `run`-method-call - takes several *seconds* to finish.

I tried to simply remove them and it seems to work fine (for my use case :smile:). So without understanding the details, I'm just going to ask: are these calls necessary? Does `run` have to be blocking?

**Comment by BurntSushi** [comment]
Those thread join calls synchronize the completion of all worker threads. Without some synchronization step, there is no guarantee that the worker threads will terminate before the program terminates.

This sounds like an XY problem to me honestly. What problem are you trying to solve?

**Comment by sharkdp** [comment]
Thank you for the explanation!

> This sounds like an XY problem to me honestly.

You were right, I figured out a way to solve this on my side.

> What problem are you trying to solve?

I have a `sync::mpsc::channel` and each thread that is spawned by `WalkParallel::run` is sending results into the channel. I was calling `run` from the main thread and wanted to collect the results on the receiver-side of the channel in the main thread as well. Now, I'm spawning another thread for the receiver (before calling `WalkParallel::run`).
