### ISSUE TITLE
Add option to disable regex search and search only for exact matches

### ISSUE THREAD

**Issue by hauleth** [BurntSushi/ripgrep#607]
This option could also accept `--smart-case` and `--ignore-case` options with would allow to case independent searches.

**Comment by BurntSushi** [comment]
@hauleth Why doesn't the `-F/--fixed-literals` flag, which is named after the corresponding flag in `grep`, work for your use case?

**Comment by hauleth** [comment]
Oh, I've must missed that option. Sorry for this fuss.

**Comment by cedricvanrompay** [comment]
I would suggest to add this to the FAQ or to add a section for it in the user guide because it's pretty hard to find in the user guide right now when you don't know the name of the option already.

**Comment by viggy28** [comment]
I didn't find `--fixed-literals`, rather `--fixed-strings` is available.

**Comment by BurntSushi** [comment]
Yes, I misspoke. I corrected my comment.

**Comment by guanghechen** [comment]
Hi, I just wonder if there is any workaround to search strings contain `\n` with the --fixed-strings option specified like the vscode did?

**Comment by BurntSushi** [comment]
@guanghechen Please ask a question via Discussions: https://github.com/BurntSushi/ripgrep/discussions

Please show an example of what you want. Please show what you've tried and the output of what happened when you did.
