### ISSUE TITLE
Allow options before --help and --version

### ISSUE THREAD

**Issue by snorr** [BurntSushi/ripgrep#61]
Currently `rg argument --version` will work fine, but `rg -u --version` will fail with `Invalid arguments.`.

This feature would be nice, since it would make adding default options with CLI aliases easier (e.g. `alias rg='rg --no-mmap'` or `alias rg='rg -u'`). Currently these aliases break `--help` and `--version`.

(Tested with `rg --version` reporting `0.1.17`.)

**Comment by 0xmohit** [comment]
Dup of #47

**Comment by snorr** [comment]
Ah, thank you, closing. :)
