### ISSUE TITLE
hidden files to be searched by default

### ISSUE THREAD

**Issue by akostadinov** [BurntSushi/ripgrep#623]
Am I the only one that thinks hidden files should be searched by default? Especially when trying to find something related to configuration, these things are often put into hidden files in user home.

And if I'm the only one, probably #196 is what can help me.

**Comment by okdana** [comment]
Excluding hidden/dot files by default is common for this class of tool — notably, `ag` and `pt` both do it. `rg` was inspired directly by `ag`, so that's probably (?) the immediate reason for the current behaviour. But i think it makes sense even if you ignore the historical baggage, since these tools are mainly designed for searching through source code, and dot files in that context are usually just noise.

If you've read that other ticket you've probably already picked this up, but just in case, this is your best work-around for now:

```
alias rg='rg --hidden'
```

**Comment by BurntSushi** [comment]
@okdana has got it. This isn't changing.

**Comment by kriskhaira** [comment]
The following is @okdana's solution, but with the .git folder remaining ignored:
```
alias rg="rg --hidden --glob '!.git'"
```

**Comment by Nakilon** [comment]
Personally I would never complain if the Github Actions wasn't invented as being put into `.github` and that now I need to grep those often to find how I solve common issues.

**Comment by BurntSushi** [comment]
@Nakilon Sorry, what's the point of your comment? Just to complain? Why not put `!/.github/` in your `.ignore`? Boom. Problem solved.

**Comment by Nakilon** [comment]
> put `!/.github/` in your `.ignore`?

Can't figure out how this autofiltering thing works. I have `mydir/infrared/.rgignore` with content:
```none
/*.cache.yaml
```
but
```
$ rg jobs: --sortr created mydir -g*.y*l
...mydir/infrared/token.cache.yaml
204267:Now people are getting food/gas priced out of their homes and jobs:
...
```
Why doesn't it ignore the file?

**Comment by BurntSushi** [comment]
Please open a new Discussion question instead of posting in some old issue that may or may not be related.

Please also include a full reproduction that others can try.

Please also read the guide. For example, why haven't you tried using the `--debug` flag yet?

**Comment by StackOverflowExcept1on** [comment]
I also ran into the same problem today when the `rg foo` command cannot find the code that is in `.github/workflows`.It makes sense to exclude the `.gitignore` files and the `.git` folder from hidden files. The hidden files should be searched by default.
For example, if you run the command `grep foo -r --include="*.yaml"`, it will find matches in hidden files. If your utility is trying to replace `grep`, why put restrictions on hidden files?

**Comment by BurntSushi** [comment]
> If your utility is trying to replace `grep`

[It's not.](https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#posix4ever)

I guess I need to start locking issue threads now.
