### ISSUE TITLE
Support for equivalence classes

### ISSUE THREAD

**Issue by albfan** [BurntSushi/ripgrep#626]
Is there any chance to support equivalence classes?

https://www.regular-expressions.info/posixbrackets.html#eq

here is a scce test case:
```
$ cat >test <<EOF
Búsqueda global
EOF
$ grep -RiH "B[[=u=]]squeda global" *
test:Búsqueda global
$ ag -i "b[[=u=]]squeda global"
ERR: Bad regex! pcre_compile() failed at position 2: POSIX collating elements are not supported
If you meant to search for a literal string, run ag with -Q
```

**Comment by BurntSushi** [comment]
I'm not in principle against it, but this enhancement requires enhancements to the regex engine itself. If this ever happens, it will not be for a very long time.

Anywho, this issue isn't really for ripgrep but for the regex engine, so I've filed the issue there instead: https://github.com/rust-lang/regex/issues/404

**Comment by albfan** [comment]
Fair enough. Thanks for take time to do fill that. Let's see if I can provide a patch on that

**Comment by BurntSushi** [comment]
Please sketch out an implementation strategy before doing the work. It is a
*significant* task.

**Comment by albfan** [comment]
As a resume for anyone looking at this

rust tries to be agnostic about charsets, so this concept of equivalence classes is not avaliable. The only thing remotely similar is the normalization form for chars, so `ò` can be decomposed on `o` and ``` so searching for `o` equivalences could detect `ò`as an equivalence. That implies a file preprocess. That can be done with https://crates.io/crates/unicode-normalization, but presumably it will slow down all searches
