### ISSUE TITLE
equivalence option

### ISSUE THREAD

**Issue by albfan** [BurntSushi/ripgrep#627]
just if #626 is possible

Using kcharselect o gucharmap and looking for "letter with" you will find every unicode character that can have accents, like aáà,eéè etc. In spanish it works mostly for vocals, but seems there're other languages with consonants modyfied with accents. Something like --equivalents to search for:

$ echo película sobre un Camión español | grep -i "pel[[=i=]]cula sobre un cami[[=o=]]n espa[[=n=]]ol"

will rock

**Comment by BurntSushi** [comment]
I don't understand what the difference is between this issue and #626. Could you please elaborate?

**Comment by albfan** [comment]
#626 is to support the regex

    [=a=] equals to [aáàä]

this is to allow to write non accent characters in regex and match with or without it

    rg --equivalents camion matches camión and camion

For long phrases is just syntastic sugar

    Tomás pidió públicamente perdón, disculpándose después muchísimo más íntimamente

**Comment by BurntSushi** [comment]
This doesn't seem unreasonable to me, but I would rather wait until the equivalence feature exists in the regex engine before tracking additional features on top of that.

**Comment by albfan** [comment]
Sure

**Comment by albfan** [comment]
this would be another task of preprocessing, but this time for regex expression instead of files searched.

**Comment by HynDuf** [comment]
I would love this too.
