### ISSUE TITLE
Option to remove (?-u) in the glob.regex()?

### ISSUE THREAD

**Issue by iology** [BurntSushi/ripgrep#635]
While working on sharkdp/fd#96, I found this: https://github.com/BurntSushi/ripgrep/blob/12ffcb4296e0c2068797daea6ed88885b060d916/globset/src/glob.rs#L596

Is there any reason for not having an option to allow `(?u)`?

**Comment by BurntSushi** [comment]
Yes. Globs match paths, which aren't always UTF-8.

**Comment by iology** [comment]
Ah, right. Maybe I should fix the "UTF8-aware matching" downstream. Closing for now.
