### ISSUE TITLE
`rg` alias conflict with oh-my-zsh rails plugin

### ISSUE THREAD

**Issue by th11** [BurntSushi/ripgrep#637]
If you use the oh-my-zsh rails plugin, it sets the `rg` alias to `rails generate`. Installing ripgrep doesn't override this. It would be helpful to put a note somewhere in the readme letting people know about the conflict so they can quickly resolve the issue.

https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#rails

**Comment by BurntSushi** [comment]
This was fixed in #638.

@okdana If you add `Fixes #nnn` to a commit message on its own line, merging that PR will cause the corresponding ticket to be closed. :-) (I need to get better and making sure the commit messages are formatted correctly during review!)

**Comment by okdana** [comment]
Oops, thought it only needed to be in the PR title. I'll try to remember next time!
