### ISSUE TITLE
Can't search for "->" with --fixed-strings

### ISSUE THREAD

**Issue by Wilfred** [BurntSushi/ripgrep#639]
```
$ rg -F "->"
error: Found argument '->' which wasn't expected, or isn't valid in this context

USAGE:

    rg [OPTIONS] <pattern> [<path> ...]
    rg [OPTIONS] [-e PATTERN | -f FILE ]... [<path> ...]
    rg [OPTIONS] --files [<path> ...]
    rg [OPTIONS] --type-list

For more information try --help
```

I wanted to search for the literal string `->` (used in Python type annotations). I can work around this with a normal regexp search and `--`:

```
$ rg -- "->"
```

but I can't see any way of passing this argument to `-F`:

```
$ rg -F "->" --
error: Found argument '->' which wasn't expected, or isn't valid in this context
```

In this case, `->` is a valid regular expression, but if I'm searching for a more elaborate expression like `-> Optional[` I would like to be able to use `-F`.

Is this impossible, or am I missing a way of passing this?

**Comment by BurntSushi** [comment]
`-F` is a flag that does not accept any arguments, as documented. The invocation `rg -F "->" --` therefore doesn't really make sense. `rg -F -- ->` or `rg -F -e ->` should both work.

**Comment by BurntSushi** [comment]
Note that `rg --help` says:

> A regular expression used for searching. To match a pattern beginning with a dash, use
            the -e/--regexp option.

**Comment by Wilfred** [comment]
Aha, that makes sense. I'd misunderstood the flag and assumed it took an argument.

Thanks for your help! :)
