### ISSUE TITLE
Ctrl+C handling in Windows can bleed coloring

### ISSUE THREAD

**Issue by calonx** [BurntSushi/ripgrep#661]
I accidentally made my search a bit too loose and found tons of useless results scrolling by on my screen. As works with many other command-line utilities, I used Ctrl+C to abort the search -- but I got unlucky and happened to abort while in a colored sequence, so the color then bled into my whole prompt session.

![image](https://user-images.githubusercontent.com/1431773/32281594-a5acba1e-bef5-11e7-906a-32a6f7652cee.png)

(the bottom two lines should not contain red text; should be the standard off-white for cmd.exe)

**Comment by calonx** [comment]
...and I just now found this closed issue:

https://github.com/BurntSushi/ripgrep/issues/430

Does ripgrep currently do any special handling of Ctrl+C on Windows?

**Comment by BurntSushi** [comment]
This is a known issue. It's described a bit in a tangent here: https://github.com/BurntSushi/ripgrep/issues/281 TL;DR - "Add `^C` handling" is not a complete answer.

As of now, this is not something I plan on fixing.

**Comment by calonx** [comment]
Gotcha, I'll read that over -- thanks!
