### ISSUE TITLE
.gitignore handling of overlapping patterns is inconsistent with git

### ISSUE THREAD

**Issue by bennofs** [BurntSushi/ripgrep#67]
Git allows the following in a `.gitignore`:

```
/*
!/dir
```

which means: ignore every directory in the root of the repository except the `dir` directory. Git understands this, but `rg` will fail to find results in `/dir`. Note that `pt` handles this correctly.

**Comment by BurntSushi** [comment]
Thanks for the report! This wasn't actually a bug with overlapping patterns or anything. There was a bug in the gitignore parser that was triggered by the whitelist that was preventing `/dir` from being interpreted as an absolute path.
