### ISSUE TITLE
gitignore: Disregard plain wildcard

### ISSUE THREAD

**Issue by zachriggle** [BurntSushi/ripgrep#672]
It is occasionally useful to have Git ignore *all* files unless explicitly added to the index via `git add --force`.  This would appear in a gitignore file like:

```
# Ignore everything not tracked
*
```

For example, this is generally useful when an entire home directory is a git repository (for dotfiles, etc. ~/bin/, etc) without needing to add every single random directory to `.gitignore`.

In this case, `rg` will not search anything unless given the `--unrestricted` flag.  This is correct in the strict sense, but cumbersome -- and also means that it will ignore any other rules it discovers in the "global" gitignore (`git config --global core.excludesfile ~/.gitignore_global`)

I'd like to suggest that if the specific pattern `*` is discovered in a `.gitignore`, that the rule is disregarded.

**Comment by BurntSushi** [comment]
No, sorry. ripgrep isn't going to start ignoring patterns arbitrarily.

With that said, I agree it is cumbersome. The `-u` flag or specifying explicit file paths (e.g., `rg foo *`) should both work though. Another work around is to override your `.gitignore` by whitelisting everything in your `.ignore`. e.g., `echo '!*' > $HOME/.ignore` or similar.

**Comment by zachriggle** [comment]
Would you accept a pull request for a `--dont-ignore-all` flag which does this conditionally?

**Comment by BurntSushi** [comment]
No.
