### ISSUE TITLE
^$ does not work when using --no-mmap

### ISSUE THREAD

**Issue by ericbn** [BurntSushi/ripgrep#690]
I found this while running the examples described at #441 

```
$ cat scratch
a
b

c


d
$ rg 'a' scratch
1:a
$ rg 'b' scratch
2:b
$ rg 'c' scratch
4:c
$ rg 'd' scratch
7:d
$ rg --mmap '^$' scratch
3:
5:
6:
8:
$ rg --no-mmap '^$' scratch
2:
4:
6:
7:
9:
$
```

By "does not work" I mean using `--no-mmap` gives an unexpected number of results and unexpected line numbers. I get these same unexpected results by running `rg '^$' scratch`.

I'm using ripgrep 0.7.1 under macOS.

**Comment by BurntSushi** [comment]
I suspect this can be rolled up into the same bug as #441.

**Comment by dennis-benzinger-hybris** [comment]
It's similar to #441 but the interesting point here is that phantom empty lines are also found elsewhere in the file. For example between line 1 and 2 (then 3). Try with `-C1`.

**Comment by BurntSushi** [comment]
I believe this bug should be fixed in libripgrep.
