### ISSUE TITLE
Don't display context separators when only listing files

### ISSUE THREAD

**Issue by tupton** [BurntSushi/ripgrep#693]
```
❯ command rg --context=3 -l "context-separator"
complete/_rg
--
doc/rg.1.md
--
src/app.rs
--
src/args.rs
```

When listing files, even if `--context` is an option, I don't think we need the context separator. I understand that those options don't make much sense in this contrived example. However, I have an alias set up for `rg` that adds a bunch of options that I want as defaults, including `--context`. I (sometimes) use `-l` to list out files that I can pass to `vim`, e.g. `vim $(rg "context-separator" -l)`.

I tried to set `--context=0` when using `-l` – which would be an ok tradeoff for me – but it looks like multiple `--context` flags are not allowed.

`rg … | sed '/--/d'` is another potential solution, but it would break if `--context-separator` specified a different separator.

**Comment by okdana** [comment]
Yeah, also affects `--count` and `--files-without-match`.
