### ISSUE TITLE
don't skip directories

### ISSUE THREAD

**Issue by mosesn** [BurntSushi/ripgrep#695]
I recently ran into an issue where rg doesn't look in all directories.

```
$ rg 'libthrift-0.5.0' 'src/java/com/twitter/search/common'
... (didn't find it)
```

```
$ rg 'libthrift-0.5.0' 'src/java/com/twitter/search/common/images'
... (found it)
```

I thought maybe the name "images" was special, but I didn't find anything promising in the rg repository.

Sorry for the sort of crummy bug report.  I looked at the permissions for the "images" directory that it doesn't want to search recursively, and it doesn't look weird.  Happy to include any other information, but I didn't really know what to say.

**Comment by okdana** [comment]
Try it with `--debug`

**Comment by BurntSushi** [comment]
@mosesn The first sentence of the README says:

> ripgrep is a line-oriented search tool that recursively searches your current directory for a regex pattern while **respecting your gitignore rules.**

Your bug report doesn't mention anything about your gitignore rules, so I can't tell whether you've account for that or not.

**Comment by BurntSushi** [comment]
> Should I close this ticket and file a feature request to also search files that are in .gitignore, but also in the git index?

It has been requested but it's not happening. The recommended work-around is to explicitly whitelist files that are in your `.gitignore` but you still want to search. You can do that in either a `.gitignore` or a `.ignore` file.

**Comment by BurntSushi** [comment]
@mosesn See also https://github.com/BurntSushi/ripgrep/issues/645

**Comment by mosesn** [comment]
If anyone else is curious, I did some follow-up research in how other tools handle this.

git grep looks in the index directly, so it gets this for free.
```
$ git grep 'libthrift-0.5.0' 'src/java/com/twitter/search/common'
(FINDS IT)
```

if you tell it to not use the index but to use gitignore, it doesn't find it.
```
$ git grep --exclude-standard --no-index 'libthrift-0.5.0' 'src/java/com/twitter/search/common'
(DOESN'T FIND IT)
```

If you search using ag, it does find it (???)

```
$ ag 'libthrift-0.5.0' src/java/com/twitter/search/common
(FINDS IT)
```

However, if you search using ag from the root of the repository, and then grep for the directory, it's not there.

```
$ ag 'libthrift-0.5.0' | grep 'src/java/com/twitter/search/common'; echo $?
1
```

So it seems like ag only looks for .gitignore files in the directories you specify for them to search.

I think rg handles this the right way–it's quite confusing that ag sees different results depending upon which directory you search from.

**Comment by BurntSushi** [comment]
@mosesn Yeah, `git grep` has one-up on us here. With respect to `ag`, its `gitignore` support is incredibly buggy. I say that because when I was first building ripgrep, I'd often use `ag` as my standard of correctness. But I soon realized that this was folly, because it gets a lot of the `gitignore` rules wrong. (The irony is that I say that in an issue that highlights what's most reasonably considered a `wontfix` bug in ripgrep on the very same functionality! :rofl:)

There are a couple other tools that claim to respect gitignores such as `pt` and `sift`, which each have their own independent implementation.
