### ISSUE TITLE
Is there any way to not exclude .gitignore, while respecting .rgignore?

### ISSUE THREAD

**Issue by Caagr98** [BurntSushi/ripgrep#698]
I've got a project which has a large directory gitignored, since it contains copyrighted information. However, I'd like my searches to include it. Is this possible?

**Comment by BurntSushi** [comment]
Why doesn't the `--no-ignore-vcs` flag do what you want?

**Comment by Caagr98** [comment]
I just didn't see it when I looked. It does exactly what I wanted.
