### ISSUE TITLE
Add --smart-case option

### ISSUE THREAD

**Issue by Tarmean** [BurntSushi/ripgrep#70]
Description:
When smart case is enabled then ignorecase is implicitly enabled if the query doesn't contain uppercase characters .

This saves the user from thinking about case sensitivity in virtually all common cases. The option is offered by a number of other search tools like ag or vim's regex search. I'd like this as rg's default but aliasing it obviously would work just as well.

**Comment by BurntSushi** [comment]
Yeah, I actually dislike this option very much, so I'm pretty opposed to using it by default. I'm fine with a new flag.

**Comment by kastiglione** [comment]
Could this be enabled by default via an environment variable?

**Comment by BurntSushi** [comment]
@kastiglione Please see #196.

**Comment by verhovsky** [comment]
rg --smart-case <your search>

or

    rg -S <your search>
