### ISSUE TITLE
Changing formatting of search results

### ISSUE THREAD

**Issue by facingBackwards** [BurntSushi/ripgrep#700]
When using `--no-heading`, is there any way to add a space between the filename and the `:##:`?

At the moment it concatenates the file, the line number and the line with the search result meaning that double clicking to select a file selects the number as well so double-click → middle-click to type a file name isn't possible.

**Comment by BurntSushi** [comment]
No, sorry. If you want this, I'd recommend writing a script that post-processes the output.

**Comment by facingBackwards** [comment]
For anyone else having a similar issue, you can change how double-click selects words. For gnome-terminal, `edit` → `General` → `Select-by-word-characters` → remove `:` from textbox.

**Comment by sergeevabc** [comment]
Is there a native way (some switch) to concatenate, join, merge lines in the output?

Now:
Bat
Cat
Dog

Expected:
Bat Cat Dog

**Comment by BurntSushi** [comment]
No. ripgrep isn't designed to perform arbitrary output manipulations. You'll need to find some other tool.

In the future, please don't necro post on old issues unless it's directly related. If you have a question, use Discussions.
