### ISSUE TITLE
is it possible to implement -NUM (from man grep)

### ISSUE THREAD

**Issue by sitaramc** [BurntSushi/ripgrep#701]
is it possible to implement -NUM; i.e., make the "-C" optional, as it is in grep.

Please feel free to say "no".   It's mainly muscle memory that is causing me to ask, nothing more serious.

**Comment by okdana** [comment]
As far as i can tell, this is hard to achieve with `clap` (the argument-parsing library `rg` uses).

The way you would do this with a traditional `getopt()` sort of method is designate `-0` through `-9` as valid short options and then basically concatenate them together in order of appearance, resetting them whenever one appears that's not adjacent to a previous one in the same argument. Then you convert the resulting string into a number.

`clap` is designed to be a much higher-level method of argument parsing, so it abstracts away things like the order and argument index that options appear in. In other words, there is no clean way AFAIK to tell the difference between `rg -12`, `rg -21`, `rg -1 -i -2`, and so on. I'm not an expert on `clap`'s quite extensive feature set, but i'm *pretty* sure that's the case, at least.

Maybe someone else knows something that i don't, but if not, this might have to be a [`clap` feature request](https://github.com/kbknapp/clap-rs/issues/new). It does seem like something that should reasonably be within its scope.

**Comment by sitaramc** [comment]
I understand; thanks for the detailed explanation.  (I'll pass on pushing this up to the clap project, at least for now.)

**Comment by BurntSushi** [comment]
Huh. I didn't even know this was a thing in GNU grep. If clap had a way to do this, then there would probably have to be an option here to do it: https://docs.rs/clap/2.28.0/clap/struct.Arg.html I don't think such an option exists.

To be honest, I'm not sure I'd even be on board with this even if clap did support it. :)
