### ISSUE TITLE
Ripgrep not working in OneDrive folders using Files On Demand

### ISSUE THREAD

**Issue by roblourens** [BurntSushi/ripgrep#705]
Ref: https://github.com/Microsoft/vscode/issues/35433

Files On Demand is a new OneDrive feature that only downloads files to the local disk when needed. It has caused some issues in Node/Electron land - https://github.com/nodejs/node/issues/12737, https://github.com/Microsoft/vscode/issues/27285.

When running ripgrep in a folder with this feature enabled, I just get `Access is denied. (os error 5)` immediately. Running with `--debug` doesn't produce any clues. I will investigate if you can point me in the right place to start looking?

**Comment by BurntSushi** [comment]
I'm on mobile and headed to bed at the moment, but the first thing that
springs to mind is memory maps. If you run rg with --no-mmap (--mmap does
the opposite) then it will avoid using memory maps and instead use standard
file APIs. Linux, for example, has an issue where virtual files can't be
memory mapped. ripgrep detects this by looking at file size. If the size is
zero (which is what virtual files like /proc/cpuinfo report), then it
forcefully disables use of memory maps and everything works.

If memory maps are indeed the problem, and if there is a way to tell that
memory maps won't work with a stat call or similar then we can change
ripgrep's heuristics on Windows.

If this isn't the problem, then I personally would probably try to
reproduce the problem using a minimal Rust program, and then start
diagnosing from there. If it comes to that, how easy would it be for me to
reproduce the bug on my own Windows machine?

**Comment by roblourens** [comment]
I get the same error with `--no-mmap`. Here is a fix in libuv for this onedrive feature: https://github.com/libuv/libuv/pull/1522/files, if this is a similar problem, it's probably in Rust's `fs`.

Repro steps are basically 

- Install the latest updates for Windows and OneDrive
- Open OneDrive settings, enable "Files On-Demand"
- Wait a couple minutes for OneDrive to do it's thing
- Invoke ripgrep in a OneDrive folder

**Comment by roblourens** [comment]
Filed https://github.com/rust-lang/rust/issues/46484

**Comment by roblourens** [comment]
Since there isn't much progress on the upstream issue, I'm trying to work around it in the ripgrep build for vscode. Would you be interested in a PR? The workaround is fairly simple, just need to check the `file_attributes` of a directory for the reparse point and directory flags: https://msdn.microsoft.com/en-us/library/windows/desktop/gg258117.aspx. And it needs to be done in a few places in the walkdir and ripgrep repos.

**Comment by BurntSushi** [comment]
@roblourens Sorry for the late response, but yes, I would definitely be interested in a patch to ripgrep proper. If I had more Windows expertise, then I'd be happy to push this through upstream too, but I just don't have the bandwidth at the moment, so I'm happy to work around it.

**Comment by BurntSushi** [comment]
@roblourens I am working on a fix to this in `walkdir` and `ignore`. I may have convinced someone to fix it in `std` as well, but even if the latter were fixed and merged tonight, ripgrep wouldn't see it for months.

**Comment by roblourens** [comment]
Awesome! Sorry I never delivered on my drive-by PR offer, it's been on my list but I was too busy in January.

**Comment by BurntSushi** [comment]
@roblourens No worries! The Windows side of things is pretty straight-forward, but fixing the code itself is a little gnarly!

**Comment by BurntSushi** [comment]
Got it! I manually tested the fix. I can search directories on OneDrive using ripgrep master.

**Comment by roblourens** [comment]
This works great. Thanks!
