### ISSUE TITLE
Output matching pathname even when only one file is searched

### ISSUE THREAD

**Issue by rswgnu** [BurntSushi/ripgrep#710]
Please make 'rg' output a filename by default if matches are found when searching only one file.  This is important because if an IDE tool uses the output to jump to the associated source line, it will need the filename to do so, just as it does when multiple files are searched and matched.

**Comment by BurntSushi** [comment]
This default isn't changing. This matches `grep` behavior, which is the intended behavior in this case. If you want the filename to always be emitted, then you need to pass the `--with-filename` flag (which also exists for grep).

**Comment by BurntSushi** [comment]
(Note that the `--vimgrep` option will also achieve this effect, which also includes line numbers.)

**Comment by rswgnu** [comment]
On Thu, Dec 7, 2017 at 1:03 PM, Andrew Gallant <notifications@github.com>
wrote:

> This default isn't changing. This matches grep behavior, which is the
> intended behavior in this case. If you want the filename to always be
> emitted, then you need to pass the --with-filename flag (which also
> exists for grep).
>
​Thanks, that will work well.  I'll close the issue.
