### ISSUE TITLE
Directory separators not normalised on Windows

### ISSUE THREAD

**Issue by mrmonday** [BurntSushi/ripgrep#711]
Using either cmd or git bash on windows:
```
$ rg --version
ripgrep 0.6.0
-AVX -SIMD

$ find .
.
./a
./a/c
./a/c/b
$ cat a/c/b
aaaa
bbbb
cccc

$ rg aa a/
a/c\b
1:aaaa

```

Here the output mixed `/` and `\` as directory separators - they should be normalised for consistency.

**Comment by BurntSushi** [comment]
This looks like a duplicate of #275. In particular, what should the paths be normalized to? Does `--path-separator` fix this issue for you?

**Comment by mrmonday** [comment]
That works, I'll set up an alias.

I thought it might be good to normalise by default, so I did a little investigation:

 * `grep` in git bash (find does similarly):
    ```
    $ grep -r aa 'a\'
    a\/c/b:aaaa
    $ grep -r aa 'a/'
    a/c/b:aaaa
    ```
 * `findstr` in cmd: I couldn't find a way to make it recurse, but it prints exactly as passed
 * `dir` in cmd: This always normalises to `\`
 * `Get-ChildItem a/ -Recurse` in powershell normalises to `\`

I'm no expert in Window's command line utilities, but my minor investigation reveals quite a mixed bag of results - there's no definitive "ripgrep should do this because it's what everything else does".

I'll close this, since `--path-separator` is a sufficient workaround. Thanks.
