### ISSUE TITLE
Where is _rg.ps1 file?

### ISSUE THREAD

**Issue by vors** [BurntSushi/ripgrep#716]
Hello!

The powershell completion instructions been added in
https://github.com/BurntSushi/ripgrep/commit/d2c7a76a3c0f6c264ec0b1f04e1dcaeba3862a51

>For PowerShell, add . _rg.ps1 to your PowerShell profile (note the leading period). If the _rg.ps1 file is not on your PATH, do . /path/to/_rg.ps1 instead.

I could not find the `_rg.ps1` file in the final package or source code...
Is it in another repo?
cc @elirnm

**Comment by okdana** [comment]
It's auto-generated during the build by [clap](https://github.com/kbknapp/clap-rs/)

**Comment by vors** [comment]
Cool, so where where it is in the package? I'm trying to find it on mac (powershell is cross-platform) ripgrep v0.7.1, installed thru `brew`. Is it included only in the windows build?

**Comment by okdana** [comment]
AFAIK it's included in all of the [official release archives](https://github.com/BurntSushi/ripgrep/releases)

The [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ripgrep.rb) just ignores it though

The formula code has standardised install locations for bash/fish/zsh completions; i don't think PowerShell is a core formula (?), but if there's a similar location for it that would play nicely with Homebrew you might consider [submitting a request](https://github.com/Homebrew/brew/issues) to have them add it

**Comment by vors** [comment]
On a side note (I don't know much about rust ecosystem), wow - the clap project looks awesome!

**Comment by vors** [comment]
@okdana thank you for the quick reply!
