### ISSUE TITLE
Can someone provides a FreeBSD precompiled binaries for ripgrep

### ISSUE THREAD

**Issue by dreamingo** [BurntSushi/ripgrep#720]
Archives of pre-compiled binaries for `ripgrep` are only available on Windows,  Linux and MacOS, Can someone provides a FreeBSD pre-compiled binaries for `ripgrep`?

**Comment by strangelittlemonkey** [comment]
I think you'd do better to try to get someone to make it into ports so you can install it via pkgng.

**Comment by BurntSushi** [comment]
No, sorry, I don't have the bandwidth to do it. Compiling ripgrep yourself shouldn't be too hard.
