### ISSUE TITLE
Suggest: change the directory separate char '\\' to '/' on windows

### ISSUE THREAD

**Issue by cn00** [BurntSushi/ripgrep#721]
The windows directory separate char '\\'  always case some problems, maybe use the Unix directory separate char '/' is more convenient.
I love ripgrep, thanks for your jobs.

**Comment by BurntSushi** [comment]
This is a duplicate. Please search issue tracker.

**Comment by BurntSushi** [comment]
I was on mobile before. This is a dupe of #711. Use the `--path-separator` flag to get what you want.
