### ISSUE TITLE
Glob does not respect --no-ignore

### ISSUE THREAD

**Issue by CrashyBang** [BurntSushi/ripgrep#73]
Hey I am trying to set this up with [fzf](https://github.com/junegunn/fzf) and replace [ag](https://github.com/ggreer/the_silver_searcher), this was my original `FZF_DEFAULT_COMMAND`:  

`set -g -x FZF_DEFAULT_COMMAND 'ag --ignore-case --skip-vcs-ignores --depth -1 -g ""'`

And here is my new `rg` one:  

`set -g -x FZF_DEFAULT_COMMAND 'rg --no-ignore --hidden --follow ""'`

Now this almost works but it is not listing things like `.gitignore`.

Any ideas?

**Comment by BurntSushi** [comment]
Can you please try to reproduce the problem on the command line?

**Comment by CrashyBang** [comment]
Okay on the command line I have to use this:  

`rg --no-ignore --hidden --files --follow ''`  

So this shows all my dotfiles however I have now realised I would like to hide everything in the `.git/` folder so I tried this:  

`rg --no-ignore --hidden --files --follow '' --glob '!.git/*'`  

However the `--glob` argument seems to be being overridden by `--no-ignore` as for the dotfiles not showing in `fzf` I can create an issue on that project's repo.

Cheers.

**Comment by BurntSushi** [comment]
This is fixed in current master. I'll get a new release out today.
