### ISSUE TITLE
show examples in the README

### ISSUE THREAD

**Issue by StefanoD** [BurntSushi/ripgrep#76]
I couldn't find an example like a preview of search and replace. That is what it _would_ do if rg would really replace the string. This would be really helpful in order to prevent unexpected behaviour.

**Comment by BurntSushi** [comment]
I agree. `ripgrep`'s docs could, in general, be improved a great deal. Adding examples that not only show the command but the output as well would be very beneficial.

**Comment by BurntSushi** [comment]
ripgrep's documentation was overhauled in #785. There is now a user guide and a FAQ, both of which contains examples, including an entire section dedicated to replacements.
