### ISSUE TITLE
types: add proto (*.proto)

### ISSUE THREAD

**Issue by vbauerster** [BurntSushi/ripgrep#770]
First of, thanks for rg!
Can you please add `*.proto` files support? I know there is a `--type-add` flag available, but it is overkill to invoke this flag every time.

I wouldn't ask, if there were some sort of config for custom type-list. Maybe it is worth to add such a feature? For example look up for `.rg-types` file at same directory where `.git` resides, or look up global one at `~/.rg-types`.

**Comment by BurntSushi** [comment]
Thanks for the request! There's no need to file an issue for adding built-in types to ripgrep. So long as they are somewhat widely known, then I'm happy to just add them. Just submit a PR! You should also say what `*.proto` files are.

Also, there is already a ticket for persistent config. Search the issue tracker please.
