### ISSUE TITLE
rg --files does not ignore ELF/ARM binaries

### ISSUE THREAD

**Issue by syedelec** [BurntSushi/ripgrep#784]
#### What version of ripgrep are you using?

ripgrep 0.7.1
-AVX -SIMD

#### What operating system are you using ripgrep on?

Ubuntu 16.04.3 LTS

#### Describe your question, feature request, or bug.

I found that rg --files output ARM/ELF files even if it is supposed to ignore binaries. I work a lot with cross-compilation binaries (buildroot and yocto) and in my case, ignoring ARM/ELF files is useful.

Do you have this feature planned ?

Thanks !

**Comment by BurntSushi** [comment]
Binary files can only be detected by searching them (a file is treated as binary if it contains a `NUL` byte), and the `--files` flag specifically does not search files. Therefore, it cannot rule out binary files.

If you need this and can't get it any other way, then you might consider using `-l/--files-with-matches` instead along with a trivial pattern.
