### ISSUE TITLE
version string is malformed when using `cargo install`

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#789]
When running `cargo install ripgrep`, the git hash in the version string is improperly formatted. In this case, we should just omit the revision identifier altogether.

Example:

```
ripgrep 0.8.0 (rev )
```

We should probably improve how we use `git` to get the hash. e.g., What happens if you compile ripgrep from its git source, but outside the git repo itself?

**Comment by okdana** [comment]
FYI, the official Homebrew version of `rg` has this problem too, presumably because they build from the source tarball. I agree that just omitting the revision when it's not available would be nicer / less confusing.
