### ISSUE TITLE
man page isn't included in the ARM tarball

### ISSUE THREAD

**Issue by anowlcalledjosh** [BurntSushi/ripgrep#791]
The ARM tarball (many many thanks for providing this btw!) doesn't appear to include ripgrep's man page. Not a big deal, since it can just be grabbed from another Linux tarball instead, but would be nice if it was included :)

**Comment by BurntSushi** [comment]
I think this is just my inexperience with dealing with ARM builds. As long as asciidoc can be installed, then this should be an easyish fix.
