### ISSUE TITLE
termcolor does not support underlining text

### ISSUE THREAD

**Issue by gnzlbg** [BurntSushi/ripgrep#798]
#### What version of ripgrep are you using?

Does not apply.

#### Describe your question, feature request, or bug.

termcolor does not support underlining text. Would be great if it could.

**Comment by BurntSushi** [comment]
This seems like a simple enough addition. If anyone wants to work on this, it should be relatively easy: just do what `bold` does, but implement underlining.

**Comment by PramodBisht** [comment]
@BurntSushi I am picking this one.

**Comment by okdana** [comment]
@PramodBisht if you mean you intend to work on this, PR #805 has already been submitted

**Comment by gnzlbg** [comment]
@okdana thanks! that looks nice! 

---

FWIW this is why PRs that close issues should reference the issues either in the PR or the commit messages :D

**Comment by PramodBisht** [comment]
@gnzlbg  @okdana Great!  my was almost done  :‑(
