### ISSUE TITLE
Support curly brace glob syntax

### ISSUE THREAD

**Issue by SevereOverfl0w** [BurntSushi/ripgrep#80]
Supporting globbing like `{a,b}` would be extremely useful for "or" based usage: `*.min.{css,js}`, I imagine this would also be significantly more performant, particularly when using 7/8 separate globs instead of one big or glob.

**Comment by BurntSushi** [comment]
It actually won't be more performant. Globs are already compiled down to a single finite state machine.

In any case, yes, we should support this syntax.

**Comment by BurntSushi** [comment]
This was fun. All done!
