### ISSUE TITLE
Using -l with -v gives bogus results

### ISSUE THREAD

**Issue by ohjames** [BurntSushi/ripgrep#808]
#### What version of ripgrep are you using?

ripgrep 0.7.1
-AVX -SIMD

#### What operating system are you using ripgrep on?

Archlinux

#### Describe your question, feature request, or bug.

bug

#### If this is a bug, what are the steps to reproduce the behavior?

Run this in a git repo containing a bunch of files, some of which contain the string `match` and some of which don't.

```
rg -l -v match
```

#### If this is a bug, what is the actual behavior?

I get a bunch of files listed that contain the string `match`.

#### If this is a bug, what is the expected behavior?

The listed files should not contain the string `match` (this is how `grep -l -v match **/*` works).

**Comment by ohjames** [comment]
Hm I was wrong about grep, I guess it makes sense what with it being line based, but it's kinda useless ah well.

**Comment by BurntSushi** [comment]
Indeed. I suspect the flag you're looking for is `--files-without-match`.
