### ISSUE TITLE
Port to fancy-regex for look-around

### ISSUE THREAD

**Issue by dbkaplun** [BurntSushi/ripgrep#810]
It would be great if ripgrep supported look-around. [fancy-regex](https://github.com/google/fancy-regex) does look-around. It is fairly new so let's investigate the possibility of replacing the NFA-based regex in ripgrep.

**Comment by BurntSushi** [comment]
I'm well aware of `fancy-regex`. I think it's a great project. It needs to mature first before I would consider using it in ripgrep. It would also be behind an opt-in flag. See [the FAQ](https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#fancy).

> NFA-based regex in ripgrep

This is wrong. ripgrep's regex engine uses both DFAs and NFAs, where DFAs are the work horse.
