### ISSUE TITLE
0.8.0 always follows symlinks

### ISSUE THREAD

**Issue by chrmarti** [BurntSushi/ripgrep#824]
#### What version of ripgrep are you using?

0.8.0

#### What operating system are you using ripgrep on?

Windows 10 64bit

#### If this is a bug, what are the steps to reproduce the behavior?

0.8.0 always follows symlinks, also without `--follow`:
- create two sibling folders `cwd` and `linktarget`
- create one file in each folder `cwd\\one.txt` and `linktarget\\two.txt`
- create a link in the `cwd` folder targeting the `linktarget` folder:
  - `mklink /d link ..\\linktarget`
- run ripgrep in `cwd`: `rg --files`

Also reproduces without `--files`.

#### If this is a bug, what is the actual behavior?

```
DEBUG/grep::search/grep\src\search.rs:195: regex ast:
Repeat {
    e: Literal {
        chars: [
            'z'
        ],
        casei: false
    },
    r: Range {
        min: 0,
        max: Some(
            0
        )
    },
    greedy: true
}
one.txt
link\two.txt
```

#### If this is a bug, what is the expected behavior?

```
one.txt
```

/cc @roblourens

**Comment by BurntSushi** [comment]
@chrmarti Thanks for the great bug report! This was fallout as a result of fixing #705.

**Comment by BurntSushi** [comment]
@chrmarti @roblourens [ripgrep 0.8.1](https://github.com/BurntSushi/ripgrep/releases/tag/0.8.1) is out with this fix.

**Comment by chrmarti** [comment]
Great, thanks @BurntSushi!
