### ISSUE TITLE
Include info on how to get the man page

### ISSUE THREAD

**Issue by ferhtgoldaraz** [BurntSushi/ripgrep#841]
Info on how to build the man page would be a good improvement over the already very complete readme. Maybe also mention the install methods that include it (for example the .deb doesn't seem to install it).

I use this command in mac (installed through brew) and the man page is a godsend.

Once I figure that out maybe I'll make a pull request :)

**Comment by BurntSushi** [comment]
I think this [FAQ item](https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#manpage) might answer most of your question?

The deb really *should* include the man page. In fact, *every* distro package should include the man page. The deb is under my control, but truthfully, I generate it via the `cargo deb` tool, and I'm not sure anyone has taught it about man pages yet. I don't have the bandwidth to wade into Debian packaging territory, so it's basically up to someone else at this point.

**Comment by BurntSushi** [comment]
(Also, `rg --help` is very nearly the same as the contents of the man page. `rg -h` shows a much more condensed view.)

**Comment by ferhtgoldaraz** [comment]
Perfect, I'm in the process of building from source now. I imagine we can close this.

**Comment by ferhtgoldaraz** [comment]
(maybe open some issue for the deb and a help wanted tag or somehtin, I'm not even a newbie regarding deb packaging)

**Comment by BurntSushi** [comment]
@ferhtgoldaraz Great! Good idea. Done: https://github.com/BurntSushi/ripgrep/issues/842
