### ISSUE TITLE
deb package lacks a man page

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#842]
#### What version of ripgrep are you using?

0.8.1

#### What operating system are you using ripgrep on?

Linux

#### Describe your question, feature request, or bug.

The deb package in ripgrep's release artifacts does not install the man page. This deb package is generated using the helpful [`cargo-deb`](https://github.com/mmstick/cargo-deb) tool. This tool basically "just works": I run it in the root of the ripgrep repo and out pops a deb package that can be installed in any Debian or Ubuntu system. This approach isn't idiomatic in the sense that every dependency of ripgrep is individually packaged, but the idiomatic approach is **extremely costly**. So costly, in fact, that I could never personally do it. But I can run `cargo deb`.

There is a small problem: the deb package doesn't contain a man page. I suspect the right answer here is to somehow teach `cargo deb` how to bundle a man page with the package it produces.

**Comment by infinity0** [comment]
https://anonscm.debian.org/cgit/pkg-rust/debcargo.git/ is the "idiomatic approach".

The right approach is to adopt a standard path for cargo crates to put man pages, then both debcargo and cargo-deb can put man pages from this standard path into the .debs it generates. `man/` is perfectly fine for this, and I hear other crates have done this on an ad-hoc basis.

**Comment by tmccombs** [comment]
Somewhat related to this, the deb is also missing shell completion functions (bash completion, zsh, etc.)

**Comment by kamalmarhubi** [comment]
@BurntSushi would you accept a short term fix to "manually" add the files to the deb package?

**Comment by BurntSushi** [comment]
@kamalmarhubi Potentially. Today, I run `cargo deb` and upload the resulting package manually. If there's another command or two I can run to include the man page, that I'd be willing to do that.
