### ISSUE TITLE
Port grep to new regex-syntax

### ISSUE THREAD

**Issue by ignatenkobrain** [BurntSushi/ripgrep#853]
https://github.com/BurntSushi/ripgrep/blob/00520b30f5f38e543e17b1a4cc5e8417bc488ea4/grep/Cargo.toml#L19

We can't update regex-syntax in Fedora to 0.5 because of grep holding 0.4. Would be nice if you could fix it. Thanks!

**Comment by BurntSushi** [comment]
Umm. It's on my list of things to do, but I don't understand why this is blocking an update. It sounds like a pretty serious issue, because it means you're blocked on a single programmer's capacity to migrate crates. This isn't just a trivial update either.

**Comment by ignatenkobrain** [comment]
@BurntSushi we try to keep only latest version of crates. So we could add second (0.4) and update primary to 0.5, but we try to not do this as hard as possible ;)

**Comment by BurntSushi** [comment]
All righty. I mean, I definitely want to move to the new regex-syntax as quickly as possible since it fixes a few bugs and also lets ripgrep use the new regex features. So it's a priority, at least. :-)
