### ISSUE TITLE
[fish] Flags are not completed after first flag has been completed

### ISSUE THREAD

**Issue by zx8** [BurntSushi/ripgrep#862]
#### What version of ripgrep are you using?

`ripgrep 0.8.1`

#### Expected Behavior Summary
```
$ rg --<TAB>
# list of completions
$ rg --no-follow --<TAB>
# list of completions
```

#### Actual Behavior Summary
```
$ rg --<TAB>
# works - list of completions
$ rg --no-follow --<TAB>
# broken - no completions
```
---

Cross-post of https://github.com/kbknapp/clap-rs/issues/1212 – fixed in clap v2.31.2.

Would it be possible to bump ripgrep's clap dependency to pick up the fix (or manually generate the fish completions again using the fixed version of clap)?

**Comment by BurntSushi** [comment]
This was fixed in https://github.com/BurntSushi/ripgrep/commit/34abed597fd119fbe6ca4fe0a820808d980f46c9
