### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by shmup** [BurntSushi/ripgrep#863]
#### What version of ripgrep are you using?
0.8.1

#### What operating system are you using ripgrep on?
Ubuntu 17.10

#### Describe your question, feature request, or bug.

Receiving a permission denied error in a particular directory with fine permissions. I used to be able to ripgrep it fine. Perhaps I'll discover why I was stupid before anyone reads this and I'll close this myself. :)

#### If this is a bug, what are the steps to reproduce the behavior?

```
[~/.vim (master *+)]$ rg shit
./: Permission denied (os error 13)
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.
[~/.vim (master *+)]$ ll
total 128
drwxr-xr-x 12 jared jared  4096 Mar 16 10:00 ./
drwx------ 59 jared jared 20480 Mar 19 20:07 ../
drwxr-xr-x  3 jared jared  4096 Mar 14 15:54 after/
drwxr-xr-x  2 jared jared  4096 Mar 13 21:12 colors/
drwxr-xr-x  2 jared jared  4096 Mar 14 19:48 docs/
... and more ...
```

**Comment by BurntSushi** [comment]
Please show the output of running `strace rg shit` and also `strace rg shit ./`.

**Comment by shmup** [comment]
Oh cool, I figured it out ^ sorry haven't done that yet, but I just decide to `mv .vim vim` and then step inside and do a `rg` and the output works fine.

I'll do a strace now.

**Comment by BurntSushi** [comment]
You used snap to install ripgrep? I think snap has permission issues. You might want to google it.

**Comment by shmup** [comment]
Interesting, I will absolutely google it, thanks. I have no marriage to snap. I will say, though (before I've googled), that I pointed out the permissions on `.vim/` before because I've compared permissions other areas I heavily `rg` and I can't determine why it'd work there. 

I'll report back.

**Comment by shmup** [comment]
Eh screw it, you're at least correct, and doing `snap install rg --classic` fixes the problem.

Possibly it'd be nice to know _why_ it happened specifically there and not in other directories, and the answer is probably right in front of me. But, closing this -- thanks.

**Comment by BurntSushi** [comment]
Yeah I don't know why. It seems to be a common problem with snap.
