### ISSUE TITLE
Recursive directory search behavior change with glob

### ISSUE THREAD

**Issue by cmaughan** [BurntSushi/ripgrep#866]
#### What version of ripgrep are you using?

0.8.1

#### What operating system are you using ripgrep on?

Win10

#### Describe your question, feature request, or bug.
I have a standard setup for Rg, which I used until I updated to the latest.  It goes like this:
%2 is the search term to find in a list of files.
```
rg --no-ignore --hidden --follow --glob "{^.git/*,^.*/Built/*,^.*/Built-Projects/*,*.cpp,*.js,*.config,*.html,*.h,*.txt,*.md,*.cmake}" "%2"
```

This _used_ to search recursively in the file types I provide here, and ignore .git, etc.
The behavior has changed; it now only searches the top level directory. 

How do I modify it to again recurse into all folders?

**Comment by BurntSushi** [comment]
Please provide a corpus that I can test on. Please show expected output and actual output.

**Comment by cmaughan** [comment]
[test.zip](https://github.com/BurntSushi/ripgrep/files/1834494/test.zip)
Here is a test.  If you run the command in the .bat file, it should find 'Hello' in 3 places.  It does not; it only finds it at the root.  This worked on whatever previous version I had; but when I refreshed my binary today, the exclude glob is effectively stopping recursive folder searches.  I don't know if this is a bug fix or a regression!  Either way, I'd like to know how to make it work as before ;)

Actual Output:
```
contents.txt
1:Hello at root
```
Expected:
```
contents.txt
1:Hello at root

1\contents.txt
1:Hello In 1

2\contents.txt
1:Hello in 2
```

**Comment by cmaughan** [comment]
Thanks for the response; just got back from a trip, but this looks great; will try it!
