### ISSUE TITLE
Better terminal colors

### ISSUE THREAD

**Issue by kishaningithub** [BurntSushi/ripgrep#868]
#### What version of ripgrep are you using?

Replace this text with the output of `rg --version`.

#### What operating system are you using ripgrep on?

Mac OS X El Captain

#### Describe your question, feature request, or bug.

I personally like silver searcher's color scheme better so requesting
a color scheme change

<img width="652" alt="screen shot 2018-03-26 at 3 52 42 pm" src="https://user-images.githubusercontent.com/763760/37910422-c3c8ba68-310d-11e8-9234-3af1c062838e.png">

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#silver-searcher-output
