### ISSUE TITLE
Support !directory to exclude a dir from consideration?

### ISSUE THREAD

**Issue by mqudsi** [BurntSushi/ripgrep#871]
@BurntSushi Would you be open to having `rg PATTERN !DIR [!DIR2 ..]` be used to exclude a directory from consideration at the command line?

**Comment by mqudsi** [comment]
Thanks for the quick reply. What about an option to exclude a path, then (without `-g !`)?

**Comment by BurntSushi** [comment]
@mqudsi Well, yes, I never would have used `!` if it were simple to add a `-G` (negation of `-g`) flag. :-) That work is tracked in #809, and I believe it's now possible to implement given improvements in the latest release of `clap` (argv parser). I'll _probably_ get around to it in the next release.

**Comment by mqudsi** [comment]
Thanks :)
