### ISSUE TITLE
Fall back to extension when file type pattern not defined?

### ISSUE THREAD

**Issue by mqudsi** [BurntSushi/ripgrep#877]
I know that it is possible to "define" a (non-persistent) file type for use with `-t`, but what about falling back (with a possible warning message, if you would so prefer) to interpreting `-t EXT` as `-g '\.EXT$'` where EXT is not understood by `rg`?

**Comment by BurntSushi** [comment]
No. I'd rather explicit failure modes rather than implicit guess-what-the-user-meant modes.
