### ISSUE TITLE
add --no-column flag to override --column (and --vimgrep)

### ISSUE THREAD

**Issue by kenorb** [BurntSushi/ripgrep#880]
ripgrep should have a `--no-column` flag as a way to toggle the `--column` flag. Like `--no-line-number`, this should also override `--vimgrep`.

**Comment by kenorb** [comment]
I just need the plain output without any extras. Basically "a line with more than one match will be printed more than once", so I can count the duplicates.

**Comment by BurntSushi** [comment]
Your sentences are in conflict with each other. "Plain output" to me is "print every line that matches. `rg pattern file -N` will do that.

If you want each match to be on its own line, then `rg pattern file -N -o` will do that. The `-o/--only-matching` flag is the same one found in GNU grep.

**Comment by kenorb** [comment]
It's basically for the workaround to do AND grepping which I haven't found, so:

    rg --vimgrep --no-filename --no-line-number "foo|bar|buzz" file.txt | sort | uniq -c | sort -nr | grep -w 3

should show me the lines with all 3 patterns present, but because of extra column names, it doesn't work. As for workaround, I'll have to filter out the output using `awk` and/or `cut`.

**Comment by BurntSushi** [comment]
@kenorb You're overthinking it. Look at the output of `rg 'foo|bar|buzz' file.txt | cat`. ripgrep toggles slightly different options depending on whether you're piping or printing to a tty.

**Comment by BurntSushi** [comment]
See also: `rg 'foo|bar|buzz' file.txt -o | cat`.

**Comment by kenorb** [comment]
I need basically 'foo&bar&buzz' pattern, so I need line with all patterns present at the same time.

**Comment by BurntSushi** [comment]
@kenorb Then I have no idea what you're doing. `rg foo | rg bar | rg buzz` prints only the lines that contain `foo`, `bar` and `buzz`.

**Comment by kenorb** [comment]
I know, but I was looking for some method to run `rg` only once for simplicity.

**Comment by BurntSushi** [comment]
Then why in the world did you file a bug report about `--vimgrep`? I am very confused.

**Comment by BurntSushi** [comment]
If that's what your after, then I guess you probably want #875. (It's not clear whether it will ever happen.)

**Comment by kenorb** [comment]
I would expect that `--no-line-number` would suppress numbers completely. Otherwise I'd expect another param like `--no-column-number` which is not there.

**Comment by BurntSushi** [comment]
`--no-line-number` does suppress line numbers, even when paired with `--vimgrep`. So your expectation is satisfied.

A request for a `--no-column` flag (to match the existing `--column` flag) is reasonable, but merely for consistency sake.

**Comment by kenorb** [comment]
So I would expect this:

```
$ rg --vimgrep --no-filename --no-line-number "foo|bar|buzz" file.txt  | cut -d: -f2-
foo
foo bar
foo bar
foo bar buzz
foo bar buzz
foo bar buzz
```

but without `cut` which won't work anyway when there are multiple-digits. So if `--no-line-number` can't support suppressing column numbers, then I'd expect `--no-column-number`.

**Comment by BurntSushi** [comment]
I've updated this issue to reflect the actual request.

**Comment by BurntSushi** [comment]
@kenorb OK, I'm finding this conversation to be frustrating. It's going in circles. I don't know where, how or why you're confused. If this is just a request for something as simple as `--no-column`, then fine. Let's leave it at that. But your examples with `--vimgrep` and your questions about "and" grepping combined with all this talk about `cut`, `awk` and showing patterns that actually do "or" grepping has made this issue way harder to understand than it needs to be.

**Comment by okdana** [comment]
Seems like the reason @kenorb is interested in `--vimgrep` is just that it causes `rg` to print one copy of a line for each time it matches the pattern. I don't think (?) that functionality is exposed through any other option. So his request could be fulfilled either by adding an option to disable column numbers, which could be combined with `--vimgrep`, or adding a new option that just enables that duplicate-printing behaviour. I think that's it, anyway?

**Comment by BurntSushi** [comment]
@okdana Thanks for lending some clarity to this issue! I forgot that `--vimgrep` emitted the entire line, which is of course different than what `-o` does.
