### ISSUE TITLE
Warn about conflict --files-with-matches with --files-without-match

### ISSUE THREAD

**Issue by kenorb** [BurntSushi/ripgrep#885]
#### What version of ripgrep are you using?

`ripgrep 0.8.1`

#### What operating system are you using ripgrep on?

macOS High Sierra

#### Feature

Currently this command works fine:

    rg --files-with-matches --files-without-match string1

but I think it will never produce any output, since both params are contradictory.

**Comment by BurntSushi** [comment]
This is working as intended, and is consistent with the documentation for these flags:

```
    -l, --files-with-matches
            Only print the paths with at least one match.
            This overrides --files-without-match.
        --files-without-match
            Only print the paths that contain zero matches. This inverts/negates the
            --files-with-matches flag.
            This overrides --files-with-matches.
```
