### ISSUE TITLE
Cannot grep special devices such as /dev/urandom

### ISSUE THREAD

**Issue by kenorb** [BurntSushi/ripgrep#887]
#### What version of ripgrep are you using?

`ripgrep 0.8.1`

#### What operating system are you using ripgrep on?

macOS High Sierra

#### Bug

This works:

```
$ rg . </etc/hosts
##
# Host Database
```

----

This doesn't:

`$ rg . < /dev/urandom`

or more practical example:

`$ rg -uuu -o abc < /dev/urandom`

It seems it fallback into searching the current folder.

However this syntax work:

```
$ cat /dev/urandom | rg -uuu -o abc
```

----

I believe it should work similar as other tools, e.g.

```
$ strings </dev/urandom | head
Q)CD
h`m3
+xRF:?
```

```
$ grep . </dev/urandom # GNU grep
Binary file (standard input) matches
```

**Comment by BurntSushi** [comment]
This is a bug, but I do not believe it can be fixed in a way that doesn't produce more serious bugs. The simplest work-around is to create a pipe: `cat /dev/urandom | rg .`.

See also:

* https://github.com/BurntSushi/ripgrep/commit/ab0d1c1c797c0464ad4fcdfc641bcf88f9ade304
* #35 
* #81
