### ISSUE TITLE
[QUESTION] How do I exclude a filetype from a search?

### ISSUE THREAD

**Issue by andradei** [BurntSushi/ripgrep#889]
This isn't an issue as far as I'm concerned, but I don't know where else to ask this.

I'm trying to make search that excludes XML files without success: Here's what I tried:

`rg -i someword --iglob \!.xml .`

I use the exclamation mark to exclude `.xml` files from the search. Also, I escape it because my shell tries to expand it (or do some stuff with it that I don't understand).

But the `.xml` files are still included in the search result.

**Comment by andradei** [comment]
Looks like I was missing a `*`. This worked: `rg -i someword --iglob \!*.xml .`

**Comment by BurntSushi** [comment]
Also, you might find that single quotes will help. Please see the [guide](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs)'s treatment on manual filtering.
