### ISSUE TITLE
ignore crate: DirEntry is not Clone

### ISSUE THREAD

**Issue by stevedonovan** [BurntSushi/ripgrep#891]
Not a ripgrep issue, so excuse me _ignoring_ the standard boilerplate.

`ignore::walk::DirEntry` cannot be cloned, which is an issue if I want to use it in [findr](https://github.com/stevedonovan/findr).  `findr` uses the most excellent embedded mini-scripting language Rhai, and Rust structs must be clonable to inter-operate with it.

I've been using a combination of `walkdir` (which does provide a clonable `DirEntry`) and the `gitignore` crate.  In effect, I have to reproduce a (subset) of `ignore` functionality in `findr` - it would be rather nice to offload that to a crate that already knows about directory iteration that can ignore non-essential files. 

Edit: Had a look - not so trivial, since `Error` must be `Clone` and `std::io::Error` is not....

**Comment by BurntSushi** [comment]
This is now on crates.io in `ignore 0.4.2`.

**Comment by stevedonovan** [comment]
Cool, thanks!
