### ISSUE TITLE
support global gitignore config

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#9]
e.g., `$HOME/.config/git/ignore` or `$XDG_CONFIG_HOME/git/ignore` or whatever file is specified by the configuration variable `core.excludesFile`. Another source might be `$GIT_DIR/info/exclude`.

**Comment by BurntSushi** [comment]
While supporting `core.excludesFile` or a global `.gitignore` seems easy enough, support `$GIT_DIR/info/exclude` is actually a little tricky. There are two issues:

1. Firstly, it's an additional file to stat for in *every* directory we descend. That list of files is currently at two (`.rgignore` and `.gitignore`), and I know we'd like to bump it to three so we can include `.hgignore` too. Adding `$GIT_DIR/info/exclude` would bring this list to 4 entries. Owch.
2. A `$GIT_DIR/info/exclude` file seems to have precedence strictly lower than *all* .gitignore files in the current directory all the way up to the parent directory. (See `man gitignore`). This means we need to: 1) Check all `.gitignore` files, 2) then check all `$GIT_DIR/info/exclude` files and finally 3) check the global gitignore config.

We should at least support `core.excludesFile`. Supporting `$GIT_DIR/info/exclude` seems like it might cost us too much for little gain. (My impression is that it isn't widely used.)

**Comment by Deewiant** [comment]
My 2¢: I've used `$GIT_DIR/info/exclude` in practically every repo I've worked on for a significant period of time, whereas I've never used `core.excludesFile`, so for me the priorities there would be exactly reversed.

One alternative solution might be to have a parameter or separate tool to auto-generate one or more `.ignore` files based on these sources that are otherwise trickier to handle. The usefulness of this is predicated on people not committing their `.ignore` files. I'm not sure how likely that is...

**Comment by vi** [comment]
Maybe there should be an option for specifying additional (or replacement) ignore files manually?

**Comment by BurntSushi** [comment]
@vi That's always an option, but it's not particularly satisfying.

**Comment by rjayatilleka** [comment]
I also think `$GIT_DIR/info/exclude` would be more useful than `core.excludesFile`. But if there is a worry about performance, I think the flag for specifying extra ignore files is best. It can always be aliased or put in a short function.

**Comment by Julian** [comment]
(Just for some counterbalance -- I'm certainly in the bucket of people you originally mentioned. `$XDG_CONFIG_HOME/git/ignore` is way way way more important for me.)

**Comment by john-kurkowski** [comment]
`core.excludesFile` for me

**Comment by rjayatilleka** [comment]
Actually, changed my mind. `core.excludesFile` for me too. How high on the priority list is this feature btw?

**Comment by BurntSushi** [comment]
It's being worked on.

**Comment by BurntSushi** [comment]
Fixed in #202.
