### ISSUE TITLE
--file with empty file differs in behavior from grep

### ISSUE THREAD

**Issue by mqudsi** [BurntSushi/ripgrep#900]
#### What version of ripgrep are you using?

0.8.1

#### What operating system are you using ripgrep on?

Linux/WSL

#### Describe your question, feature request, or bug.

From `man grep`:

> `-f FILE`, `--file=FILE`
> Obtain patterns from FILE, one per line.  If this option is used multiple times or is  combined  with  the  -e  (--regexp) option, search for all patterns given.  **The empty file contains zero patterns, and therefore matches nothing.**

rg's behavior here is to treat an empty file as matching everything instead:

```
touch empty.txt
rg -l -f empty.txt
# prints all files
```

See also #783

**Comment by BurntSushi** [comment]
I don't understand what your goal is here. ripgrep differs from grep in many ways. Are you asking for better docs? A change in behavior?

**Comment by mqudsi** [comment]
Sorry, I should have been clearer. I was requesting that the same handling of an empty file passed to `-f` be used. The logic is that rg may be programmatically invoked against a generated `matches.txt`, in which case there is value in treating an empty file as not matching anything.

**Comment by BurntSushi** [comment]
OK, I agree. I had a chance to review #783 as well, and I agree that ripgrep should probably be consistent with grep here.

**Comment by mqudsi** [comment]
Thanks, much appreciated!

**Comment by mqudsi** [comment]
Thanks!
