### ISSUE TITLE
Ignore Crate Case Insensitive

### ISSUE THREAD

**Issue by gsquire** [BurntSushi/ripgrep#910]
This is not directly related to ripgrep, hence the template is missing.

When using the `ignore` crate, I wanted to add a set of overrides using the `OverrideBuilder` type. When testing case-insensitivity, I noticed that it only worked when I called `case_insensitive(true)` before adding any overrides. I don't know if this is an issue or just something that should be documented in `OverrideBuilder`.

If this is a simple doc fix, I would be happy to submit a patch. Thanks!

**Comment by BurntSushi** [comment]
Yeah, that is the intended behavior. A doc fix would be most welcome. :-)
