### ISSUE TITLE
*.jsp for Java

### ISSUE THREAD

**Issue by TheCycoONE** [BurntSushi/ripgrep#914]
#### What version of ripgrep are you using?

ripgrep 0.8.1
-SIMD -AVX

#### How did you install ripgrep?

`brew install rg`

#### What operating system are you using ripgrep on?

MacOS 10.13.4

#### Describe your question, feature request, or bug.

The java type should include the jsp extension (or a new jsp type added). jsp is common enough to warrant inclusion.

**Comment by BurntSushi** [comment]
This doesn't need a ticket. Anyone is welcome to improve the existing the type definitions via a PR: https://github.com/BurntSushi/ripgrep/blob/49f36c7dcdc0f26ecbd956b4ed0ffe7a256b64f5/ignore/src/types.rs#L149

**Comment by TheCycoONE** [comment]
Sorry, I didn't know your policy. WIll do.

**Comment by BurntSushi** [comment]
Ah yup, good point. I'll update the issue template at some point to add that bit. Thanks!
