### ISSUE TITLE
.ripgreprc & glob patterns

### ISSUE THREAD

**Issue by ahmedelgabri** [BurntSushi/ripgrep#927]
#### What version of ripgrep are you using?

```
ripgrep 0.8.1
-SIMD -AVX
```

#### How did you install ripgrep?

Homebrew

#### What operating system are you using ripgrep on?

macOS 10.13.4

#### Describe your question, feature request, or bug.

I'm trying to add a global `.ripgreprc` file with the following but I can't seem to make it work with `--glob`

```
--hidden
--smart-case
--follow
--glob "!.git/*"
--glob "!node_modules/*"
```

This returns

```
error: Found argument '--glob "!.git/*"' which wasn't expected, or isn't valid in this context
        Did you mean --glob?

USAGE:
    
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f FILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list

For more information try --help
```

I also tried 

```
--hidden
--smart-case
--follow
--glob 
"!.git/*"
--glob 
"!node_modules/*"
```

this returns 

```
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.
```

So how can I do this?

**Comment by okdana** [comment]
Each line in the `ripgreprc` is an individual argument, and there is no special handling of quoting or escaping or anything else. (If you're familiar with C, each line is basically an element of the `argv` array to `execve()` or similar.) The only special cases are (1) leading and trailing white space is trimmed from each line, and (2) lines with a leading `#` are ignored as comments.

So you'd want to write your glob lines either like

```
--glob=!node_modules/*
```
or
```
--glob 
!node_modules/*
```

**Comment by BurntSushi** [comment]
Thanks @okdana!

@ahmedelgabri Note that the format is document in both the [man page](https://github.com/BurntSushi/ripgrep/blob/c21b9b20cf0d4d25bd2765f39a2d19a782c4b254/doc/rg.1.txt.tpl#L73-L116) and in the [guide](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file).

**Comment by ahmedelgabri** [comment]
@BurntSushi I did read the help but I didn't see any examples besides simple flags

> Every line is a shell argument, after trimming ASCII whitespace.

When I read this I interpreted it as `--glob "!git/*"` not as `--glob=!git/*`

**Comment by BurntSushi** [comment]
@ahmedelgabri Does the `--type-add` example in the guide clarify things? If you think an explicit example with globs would help, then that sounds like a nice addition too.

**Comment by ahmedelgabri** [comment]
It’s useful indeed but I honestly I only checked the `manpage` & searched for anything related to `RIPGREP_CONFIG_PATH`

But I’d add an example for glob too & have the same examples in the manpage & the guide. I can open a PR tomorrow for this if you want.

Sent from my iPhone
________________________________

**Comment by BurntSushi** [comment]
@ahmedelgabri SGTM! Much appreciated.
