### ISSUE TITLE
Possible bad literal extraction

### ISSUE THREAD

**Issue by brookst** [BurntSushi/ripgrep#93]
I was trying to search for IP addresses and ran into an odd problem. I tried the expression `'(\d{1,3}\.){3}\d{1,3}'` and found no matches. I changed from a fixed repetition of the subgroup to one or more - `'(\d{1,3}\.)+\d{1,3}'` - and got matches. Using the `--debug` flag I see that the first case looks for the wrong literal:

    DEBUG:grep::literals: required literal found: "..."

The second case only looks for a single `.` as expected.

Is this a bug in the regex parsing or am I doing something wrong?

**Comment by BurntSushi** [comment]
It's a pretty sweet bug. This is indeed a bug in `ripgrep`'s inner literal extraction. (Over aggressive literal extraction is one of the largest sources of bugs in the regex engine too.)
