### ISSUE TITLE
Bash script for updating Rust nightly and ripgrep

### ISSUE THREAD

**Issue by Slaiyer** [BurntSushi/ripgrep#935]
I just wrote a Bash utility [rip_up](https://github.com/Slaiyer/rip_up):
- Calls rustup
- Pulls changes from [ripgrep](https://github.com/BurntSushi/ripgrep) upstream
- Rebuilds ripgrep (but only if required) with SIMD and AVX extensions
- Runs built-in tests

**Comment by BurntSushi** [comment]
Sounds cool! What are you requesting here?

**Comment by Slaiyer** [comment]
Just leaving this here in case anyone comes looking (like I originally came looking for a PPA).
If you like it, please feel free to link to it in your README.

A token of my appreciation for a wonderful tool; thanks :)

**Comment by BurntSushi** [comment]
Okay, thanks. Note that I distribute pre-compiled executables here on GitHub, so you don't have to install Rust.
