### ISSUE TITLE
pattern with quotes interpreted as flag

### ISSUE THREAD

**Issue by flip111** [BurntSushi/ripgrep#936]
#### What version of ripgrep are you using?

ripgrep 0.8.0 (rev 361698b90a)

#### How did you install ripgrep?

build from source

#### What operating system are you using ripgrep on?

ubuntu 16.04

#### Describe your question, feature request, or bug.

I wanted to grep for `--no-suggest` so i gave the command `rg "--no-suggest"` i get this

```
error: Found argument '--no-suggest' which wasn't expected, or isn't valid in this context
	Did you mean --no-sort-files?

USAGE:
    
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f FILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list

For more information try --help
```

This should be interpreted as pattern because it's surrounded with quotes and not as flag.

**Comment by okdana** [comment]
`rg` doesn't know anything about the way you quote arguments on the command line; that's all interpreted by the shell. There are two ways to search for a pattern that begins with a hyphen:

1\. Use `--` to tell `rg` that you're done giving it options: `rg -- --no-suggest`

2\. Give the pattern as an argument to `-e`: `rg -e --no-suggest`

The latter is mentioned in the man page.

**Comment by flip111** [comment]
Would be a good idea when an "invalid" flag is passed to add to the error message "if you meant to use this as a pattern, do this .. or look here in the manual" .. unfortunately i couldn't find the location where this message in generated in the source code of ripgrep.

Also what is interesting that it seems on windows it's possible to get the unescaped raw arguments with [GetCommandLine](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683156(v=vs.85).aspx)

**Comment by BurntSushi** [comment]
This is standard behavior for command line tools, and I'm not inclined to change it. The error message you see is generated by the argv parser.

I'm open to documentation improvements in this space, but I suspect it will suffer from discoverability issues.

**Comment by flip111** [comment]
@BurntSushi is [this](https://github.com/BurntSushi/ripgrep/blob/ae6f8714912d522e8042701c30da43c6c667dfd3/src/args.rs) the argv parser? I can't find the message in there.

**Comment by BurntSushi** [comment]
No. The argv parser is clap, which is a dependency.
