### ISSUE TITLE
Attempting to install with --features unstable

### ISSUE THREAD

**Issue by ianks** [BurntSushi/ripgrep#942]
Based on the README, I am trying to install ripgrep through cargo to get simd accelleration, but am met with this error:
```
cargo install ripgrep --features unstable
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading ripgrep v0.8.1                                                     
  Installing ripgrep v0.8.1                                                     
error: failed to compile `ripgrep v0.8.1`, intermediate artifacts can be found at `/tmp/cargo-installhiwOF5`

Caused by:
  Package `ripgrep v0.8.1` does not have these features: `unstable`
```

Not sure if I am doing something wrong, or if the readme needs to be updated.

```
rustc --version
rustc 1.28.0-nightly (1d4dbf488 2018-06-11)

cargo --version
cargo 1.28.0-nightly (e2348c2db 2018-06-07)
```

**Comment by BurntSushi** [comment]
The README is correct, but it refers to current master, which isn't released. If you want installation instructions for `0.8.1` (including how to enable SIMD), then see the [README for 0.8.1](https://github.com/BurntSushi/ripgrep/tree/0.8.1).

**Comment by BurntSushi** [comment]
(You could also do `cargo install --git https://github.com/BurntSushi/ripgrep` I think, and the current README will work.)
