### ISSUE TITLE
Please add spec file type (for creating RPM packages)

### ISSUE THREAD

**Issue by mcepl** [BurntSushi/ripgrep#946]
#### What version of ripgrep are you using?

ripgrep 0.8.1
-SIMD -AVX

#### How did you install ripgrep?

(openSUSE Tumbleweed) sudo zypper in ripgrep

#### What operating system are you using ripgrep on?
Linux/openSUSE Tumbleweed

#### Describe your question, feature request, or bug.

Please add ``spec`` file type (specification files for creating RPM packages on some Linux distributions), i.e. add to the ripgrep configuration file

```
--type-add
spec:*.spec
```

**Comment by BurntSushi** [comment]
I don't keep issues tracking file type additions. Folks are invited to just submit a PR: https://github.com/BurntSushi/ripgrep/blob/15fa77cdb384e013165687f361073defa02d9d98/ignore/src/types.rs
