### ISSUE TITLE
Can you add a new tag after v0.8.1 (2/21 release)?  So we can get the -b (byte offset) flag?

### ISSUE THREAD

**Issue by ahungry** [BurntSushi/ripgrep#947]
Currently one must clone the repo and compile it (and produce a binary labelled as v0.8.1 as a result) to get the byte offset flag - however a cargo install of v0.8.1 or Arch Linux install are both missing this option.

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#release

There is intentionally no release schedule. It happens when it happens.

> Currently one must clone the repo and compile it

`cargo install --git https://github.com/BurntSushi/ripgrep` will build and install from master.
