### ISSUE TITLE
"Cannot find path" on Windows

### ISSUE THREAD

**Issue by akavel** [BurntSushi/ripgrep#950]
#### What version of ripgrep are you using?

ripgrep 0.8.1 (rev c8e9f25b85)
-SIMD -AVX

#### How did you install ripgrep?

https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep-0.8.1-x86_64-pc-windows-msvc.zip

#### What operating system are you using ripgrep on?

Windows 10

#### If this is a bug, what is the actual behavior?

Show the command you ran and the actual output. Include the `--debug` flag in
your invocation of ripgrep.

```
[...some successful matches...]
node_modules\lottie-react-native\src\android\build\tmp\expandedArchives\classes.jar_9x65my2kdi5p9awbep9cbvzwk\android\support\v4\media\session\MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver.class: System nie może odnaleźć określonej ścieżki. (os error 3)
```

(the message "System nie może odnaleźć [...]" corresponds to English "The system cannot find the path specified.")

#### If this is a bug, what is the expected behavior?

Searched the file successfully; or at least continued searching subsequent files after printing the error, instead of stopping.

**Comment by BurntSushi** [comment]
This is most definitely the long file name bug.
