### ISSUE TITLE
add a --no-fixed-strings flag

### ISSUE THREAD

**Issue by jsatk** [BurntSushi/ripgrep#964]
#### What version of ripgrep are you using?

ripgrep 0.8.1
-SIMD -AVX

#### How did you install ripgrep?

Homebrew

#### What operating system are you using ripgrep on?

macOS 10.13.5

#### Describe your question, feature request, or bug.

I rarely ever search using regular expressions. Normally I'm wanting to find some usage of a function or string. I was hoping there was a way to set `rg --fixed-strings` as the default behavior. Perhaps with a `.rgrc` or an environment variable?

Here's what I had in mind.

```sh
$ cat ~/.rgrc 
{
  "defaultSearchBehavior": "fixed-strings"
}
$ rg ".i8n(" # Would not explode
```

**Comment by okdana** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

**Comment by BurntSushi** [comment]
@okdana I agree that a `--no-fixed-strings` flag would be useful.

**Comment by jsatk** [comment]
Oops! I dug around and didn't see this info.
