### ISSUE TITLE
Feature request: -I (--no-ignore) argument

### ISSUE THREAD

**Issue by kbd** [BurntSushi/ripgrep#966]
From [fd](https://github.com/sharkdp/fd) I'm used to typing `-H` to search hidden files or `-I` to not respect `.gitignore`. They also form a convenient mnemonic, `-HI`, to search everything.

Unfortunately `-H` is already in-use, but since `-I` isn't currently used by ripgrep I thought I'd ask if you'd want to add it as an alias for `--no-ignore`. Thanks.

**Comment by BurntSushi** [comment]
Have you read [the guide's section on automatic filtering](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering)?

Namely, ripgrep already has an alias. `-u` stops respecting `.gitignore`. Specifying it again, `-uu`, will cause ripgrep to search hidden files. Specifying it a third time, `-uuu`, will cause ripgrep to search binary files.

**Comment by kbd** [comment]
I did notice in the manpage that `-u` is equivalent to `-I` and `-uu` is equivalent to `-HI` as described above. I thought it could still be worth adding, but I understand if you don't want two single-letter aliases that do the same thing.

**Comment by BurntSushi** [comment]
You got it. Single letter aliases are precious, and `-u` is good enough.

**Comment by sharkdp** [comment]
@kbd It's a hidden feature, but (for consistency/symmetry reasons) you can use ripgrep's `-u` and `-uu` in `fd` as well.
