### ISSUE TITLE
Add option '-l' to only print out the file names from the matched result

### ISSUE THREAD

**Issue by windware** [BurntSushi/ripgrep#97]
For grep and the likes including ack, they have an option that only prints the file names from the matched results.

> grep
          -l, --files-with-matches
              Suppress  normal  output;  instead  print  the  name  of each input file from which output would normally have been
              printed.  The scanning will stop on the first match.

> ack
       -l, --files-with-matches
           Only print the filenames of matching files, instead of the matching text.

This is useful for example when opening the target files in vim directly from the result, as in;
> vim -p \`grep -l foo *\`

**Comment by BurntSushi** [comment]
This is done and should be in `0.2.0`. Please update. :-)
