### ISSUE TITLE
Use `-t .foo` as alias for `-g '*.foo'`

### ISSUE THREAD

**Issue by stepancheg** [BurntSushi/ripgrep#976]
I often use ripgrep is search by various file suffixes, e. g. `rg -g '*.inl'`, when there's no defined type name (e. g. for Idris) or I don't remember what's the type name (e. g. for Python).

A small issue here is too many characters to type:
* `*` sign
* quotes for the shell

I think it would be convenient if `rg` had a quick way to search simply by file suffix.

Currently `-t` option supports a file type for a predefined set.

I think it could be convenient to have an option to execute `rg -t .foo` as an alias for `rg -g '*.foo'`.

This is easy to implement, and sound like bikeshedding, so feel free to close the request.

Using `ripgrep 0.8.1`.

**Comment by BurntSushi** [comment]
Thanks for the detailed request! I think I'm going to have to pass on this. I don't think it's a good fit, but reasonable people can disagree. Here are my reasons:

* I like that the `--type` flag accepts exactly one kind of argument: a file type name.
* I think that writing globs is a pretty standard thing to do when running commands, and I do not believe it to be onerous enough to justify changing the semantics of `--type`.
* If you are using a file extension frequently enough, then you might consider adding it to the list of available types, which ripgrep makes extensible. See [the guide](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-file-types) for instructions on how to do that.
