### ISSUE TITLE
Support --type-add in config file

### ISSUE THREAD

**Issue by vbauerster** [BurntSushi/ripgrep#977]
My `RIPGREP_CONFIG_PATH` consist of:

`--type-add foo:*.foo`

Why `rg` doesn't support this flag in config file?
```
error: Found argument '--type-add foo:*.foo' which wasn't expected, or isn't valid in this context
        Did you mean --type-add?
```

**Comment by BurntSushi** [comment]
Please read the [documentation](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) on the config file format:

> When we use a flag that has a value, we either put the flag and the value on the same line but delimited by an = sign (e.g., --max-columns=150), or we put the flag and the value on two different lines. This is because ripgrep's argument parser knows to treat the single argument --max-columns=150 as a flag with a value, but if we had written --max-columns 150 in our configuration file, then ripgrep's argument parser wouldn't know what to do with it.
