### ISSUE TITLE
Flag for ignoring a specific ignore file

### ISSUE THREAD

**Issue by sauyon** [BurntSushi/ripgrep#982]
#### What version of ripgrep are you using?

ripgrep 0.8.1 -SIMD -AVX

#### How did you install ripgrep?

Nix

#### What operating system are you using ripgrep on?

Mac OS 10.13.5

#### Describe your question, feature request, or bug.

I have a dotfiles git repository that I clone to machines to share config which has a gitignore that excludes everything. This is a bit annoying in terms of `rg` because if I want to search for things in my home directory I have to either give up the gitignore feature or temporarily move my .gitignore.

I would like a flag to ignore a specific .gitignore (or .ignore) file.

**Comment by sauyon** [comment]
Sorry, accidentally hit the enter key while looking stuff up, give me a bit to fill this out.

**Comment by BurntSushi** [comment]
> I have to either give up the gitignore feature or temporarily move my .gitignore.

I'm not convinced these are your only two options. For example, you can add a `.ignore` right along side your `.gitignore` that overrides any rules you might have in the `.gitignore`.

For what it's worth, I have the same setup (dot files in a git repo), and I just set that repo's `status.showUntrackedFiles` to `no`, and then I don't need a `.gitignore` at all.

**Comment by sauyon** [comment]
The showUntrackedFiles is probably the way to go :P.

FWIW putting a .ignore file with `!*` doesn't quite solve my problem though because it unignores things (like .git) that I would prefer to be kept ignored.

**Comment by BurntSushi** [comment]
@sauyon Yes, you need to get fancier than that perhaps, e.g., `![!.]*`.

Either way, I don't think this feature is a good fit for ripgrep. I'd rather see people solve the problem of "what to ignore" using established mechanisms.
