### ISSUE TITLE
Regex::new() panicks when given output of Glob::regex()

### ISSUE THREAD

**Issue by vadimcn** [BurntSushi/ripgrep#985]
This code
```
    let glob = globset::Glob::new("/foo/bar/*").unwrap();
    regex::Regex::new(glob.regex()).unwrap();
```
panicks with the following message:
```
thread 'test::test' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (?-u)^/foo/bar/.*$
                   ^
error: pattern can match invalid UTF-8
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', libcore/result.rs:945:5
```
I am not entirely sure what is it trying to tell me...

Versions: globset = 0.4.0;  regex = 1.0.2

**Comment by BurntSushi** [comment]
Regex::new isn't panicking. It is returning an error, and you are calling unwrap, which turns the error into a panic.

Globs match on arbitrary bytes, and therefore may catch invalid utf-8. This is intentional. Therefore, you can't use the str based API. You need to use bytes::Regex instead. The documentation for this crate should explain this.

**Comment by vadimcn** [comment]
Makes sense, sorry for the noise.   

Though, you might consider the fact that I honestly RTFM'ed and googled that error, for like an hour, before submitting this bug report.  Maybe worth considering adding a note to the description of [`Glob::regex()`](https://docs.rs/globset/0.4.0/globset/struct.Glob.html#method.regex) method?  
In fact, I did find the [paragraph](https://docs.rs/regex/1.0.2/regex/index.html#unicode) related to `(?-u)` option, but still failed to make connection to the error, because it reads as if `(?-u)` merely modifies matching behavior.
