### ISSUE TITLE
Package ripgrep not found or ambiguous name - Cygwin/babun

### ISSUE THREAD

**Issue by SalahuddinAsh** [BurntSushi/ripgrep#994]
#### What operating system are you using ripgrep on?
Windows 7 Cygwin/babun

#### Describe your question, feature request, or bug.
I'm trying to install ripgrep to use it with vim in babun terminal (pre-configured Cygwin)

When I run `pact install ripgrep`
The output is 

```
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing ripgrep
Package ripgrep not found or ambiguous name, exiting
```

How can I install ripgrep in bubun?

**Comment by BurntSushi** [comment]
I don't know and this isn't a problem with ripgrep. Go to talk to the people that maintain bubun or install ripgrep in a different way (e.g., by reading the instructions in ripgrep's readme).
